"use client";
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {ptWallClockToUtc} from '@/lib/recurring';
import {PACIFIC,pacificDate} from '@/lib/time/pacific';
import {bookingWallClock,calendarHref,calendarDate} from '@/lib/schedule/booking-context';
import {recurringPreview,type SeriesFields} from '@/lib/schedule/commands';
import {RecurrenceFields} from '@/components/schedule/recurrence-fields';
import {useBookingCommand} from '@/components/schedule/use-booking-command';
import {useSessionCreate} from '@/components/schedule/use-session-create';
interface ActivePlan{kind:'subscription'|'package';tier:string;service_type:string|null;custom_label:string|null;current_session_number:number|null;monthly_rate_cents:number|null}
interface Client{id:string;full_name:string;email:string;active_plans:ActivePlan[]}
interface Trainer{id:string;full_name:string}
interface Props{initialMode:'schedule'|'log';initialClientId?:string;initialTrainerId?:string;initialDate?:string;initialTime?:string;initialRepeat?:boolean;asOf:string;clients:Client[];trainers:Trainer[];currentUserId:string;showModeToggle?:boolean}
const field='mt-1 min-h-12 w-full rounded-xl border border-divider bg-white px-3 py-2 text-base';
const button='inline-flex min-h-12 items-center justify-center rounded-xl border border-divider bg-white px-4 text-sm font-semibold disabled:opacity-40';
const panel='space-y-4 rounded-2xl border border-divider bg-white p-5';
const SERVICE_TYPES=[{value: "training",label:'Training'},{value: "assessment",label:'Assessment'}] as const;
export function NewSessionForm({initialMode,initialClientId,initialTrainerId,initialDate,initialTime,initialRepeat=false,asOf,clients,trainers,currentUserId,showModeToggle=true}:Props){
 const pastClock=()=>{const past=new Date(Date.parse(asOf)-3600000);return `${pacificDate(past)}T${past.toLocaleTimeString('en-GB',{timeZone:PACIFIC,hour:'2-digit',minute:'2-digit',hourCycle:'h23'})}`;};
 const initial=()=>{try{return bookingWallClock(initialDate,initialTime,new Date(asOf));}catch{return bookingWallClock(undefined,undefined,new Date(asOf));}};
 const [mode,setMode]=useState(initialMode),[clientId,setClientId]=useState(clients.some(c=>c.id===initialClientId)?initialClientId!:''),[trainerId,setTrainerId]=useState(trainers.some(t=>t.id===initialTrainerId)?initialTrainerId!:trainers.some(t=>t.id===currentUserId)?currentUserId:trainers[0]?.id??'');
 const [when,setWhen]=useState(()=>initialMode==='log'?pastClock():initial()),[query,setQuery]=useState(''),[duration,setDuration]=useState(60),[serviceType,setServiceType]=useState<'training'|'assessment'>('training'),[notes,setNotes]=useState(''),[repeat,setRepeat]=useState(initialRepeat),[confirmed,setConfirmed]=useState(false),[error,setError]=useState<string|null>(null);
 const [pattern,setPattern]=useState(()=>{const when=initial();return{start_date:when.slice(0,10),end_date:null as string|null,interval_weeks:1,slots:[{weekday:new Date(when.slice(0,10)+'T12:00:00Z').getUTCDay(),time:when.slice(11,16)}]};});
 const booking=useBookingCommand(),session=useSessionCreate(),locked=booking.locked||session.locked,weekly=mode==='schedule'&&repeat&&serviceType==='training';
 const selected=clients.find(c=>c.id===clientId),matches=clients.filter(c=>`${c.full_name} ${c.email}`.toLowerCase().includes(query.toLowerCase().trim())).slice(0,30);
 const series:SeriesFields={...pattern,client_id:clientId,trainer_id:trainerId,duration_minutes:duration,location:'IMS Studio',notes};
 const back=calendarHref(weekly?pattern.start_date:when.slice(0,10),trainerId);
 useEffect(()=>{if(!booking.uncertain&&!session.uncertain)return;const warn=(event:BeforeUnloadEvent)=>{event.preventDefault();event.returnValue='';};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[booking.uncertain,session.uncertain]);
 function switchMode(next:'schedule'|'log'){setMode(next);setConfirmed(false);if(next==='schedule')setWhen(initial());else setWhen(pastClock());}
 async function submit(event:React.FormEvent){event.preventDefault();if(locked)return;setError(null);
  if(!confirmed||!selected||!trainers.some(t=>t.id===trainerId)){setError('Choose a client and trainer, then confirm the booking.');return;}
  if(!Number.isInteger(duration)||duration<1||duration>480){setError('Choose a valid whole-minute duration.');return;}
  try{
   if(weekly){if(duration<15||duration>180)throw Error('Standing sessions must be 15–180 minutes.');if(!recurringPreview(series,new Date(asOf)).occurrences.length)throw Error('No future dates in this pattern. Review the start/end range.');await booking.submit({action:'create_series',...series},'Coach confirmed recurring booking from calendar.');}
   else{const scheduled=ptWallClockToUtc(when.slice(0,10),when.slice(11,16));await session.submit({mode,client_id:clientId,trainer_id:trainerId,scheduled_at:scheduled.toISOString(),duration_minutes:duration,session_type:serviceType,service_type:serviceType==='training'?'training':null,notes_pre:mode==='schedule'?notes||null:null,notes_post:mode==='log'?notes||null:null});}
  }catch(cause){setError(cause instanceof Error?cause.message:'Review the booking details.');}
 }
 if(booking.result||session.id)return <section className={panel} role="status"><h2 className="text-xl font-semibold">{booking.result?'Standing booking confirmed':'Session saved'}</h2><p className="text-sm">{booking.result?`${booking.result.created} sessions created in the first window. ${pattern.end_date?`Stops on ${pattern.end_date}.`:'Later windows depend on the configured recurring scheduler.'}`:mode==='log'?'Completed-session transaction confirmed.':'Scheduled only. No package use or payment was recorded.'}</p><div className="flex flex-wrap gap-3"><Link className={button} href={back}>Back to selected calendar →</Link>{session.id&&<Link className={button} href={`/sessions/${session.id}`}>Open session →</Link>}{booking.result&&<Link className={button} href={`/schedule/standing?series=${booking.result.series_id}`}>Manage recurring series →</Link>}</div></section>;
 return <form onSubmit={submit} className="space-y-5"><fieldset disabled={locked} className="space-y-5"><legend className="sr-only">Session booking details</legend>
 {showModeToggle&&<div className="grid grid-cols-2 gap-2">{(['schedule','log'] as const).map(value=><button key={value} className={`${button} ${mode===value?'border-sky bg-sky/5 text-sky':''}`} aria-pressed={mode===value} type="button" onClick={()=>switchMode(value)}>{value==='schedule'?'Schedule a session':'Log completed work'}</button>)}</div>}
 <section className={panel}><h2 className="text-xl font-semibold">Client</h2>{selected?<div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{selected.full_name}</p><p className="text-sm text-cream-dim">{selected.email||'Email can be added later'}</p><p className="mt-2 text-xs text-cream-faint">Membership/package association is not selected here. Scheduling does not consume sessions.</p></div><button className={button} type="button" onClick={()=>{setClientId('');setConfirmed(false);}}>Change</button></div>:<><label className="text-sm font-semibold">Search clients<input className={field} type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name or email"/></label><div className="divide-y divide-divider">{matches.map(client=><button type="button" key={client.id} className="block min-h-12 w-full px-2 py-3 text-left text-sm hover:bg-sky/5 focus-visible:outline-sky" onClick={()=>{setClientId(client.id);setConfirmed(false);}}><span className="block font-semibold">{client.full_name}</span><span className="text-xs text-cream-dim">{client.email||'Contact-only profile'}</span></button>)}</div>{!matches.length&&<p className="text-sm">No clients match.</p>}<p className="text-xs text-cream-faint">Showing up to 30 matches. Refine the search to find another client.</p></>}</section>
 <section className={panel}><h2 className="text-xl font-semibold">Session details · Pacific time</h2><div className="grid gap-3 sm:grid-cols-3"><label className="text-sm font-semibold">Trainer<select className={field} value={trainerId} onChange={e=>{setTrainerId(e.target.value);setConfirmed(false);}}>{trainers.map(t=><option value={t.id} key={t.id}>{t.full_name}</option>)}</select></label><label className="text-sm font-semibold">Service<select className={field} value={serviceType} onChange={e=>{setServiceType(e.target.value as 'training'|'assessment');setRepeat(false);setConfirmed(false);}}>{SERVICE_TYPES.map(s=><option key={s.value} value={s.value}>{s.label}</option>)}</select></label><label className="text-sm font-semibold">Duration · minutes<input className={field} required type="number" min={weekly?15:1} max={weekly?180:480} value={Number.isNaN(duration)?'':duration} onChange={e=>{setDuration(e.target.value===''?NaN:Number(e.target.value));setConfirmed(false);}}/></label></div>
 {mode==='schedule'&&serviceType==='training'&&<div className="grid grid-cols-2 gap-2">{[false,true].map(value=><button key={String(value)} type="button" aria-pressed={repeat===value} className={`${button} ${repeat===value?'border-sky bg-sky/5 text-sky':''}`} onClick={()=>{setRepeat(value);setConfirmed(false);if(value&&calendarDate(when.slice(0,10)))setPattern(p=>({...p,start_date:when.slice(0,10),slots:[{weekday:new Date(when.slice(0,10)+'T12:00:00Z').getUTCDay(),time:when.slice(11,16)}]}));}}>{value?'Recurring':'One-time'}</button>)}</div>}
 {weekly?<RecurrenceFields value={series} asOf={asOf} onChange={patch=>{setPattern(p=>({...p,...patch}));setConfirmed(false);}}/>:<label className="block text-sm font-semibold">{mode==='log'?'When did it happen?':'Selected date and time'} · Pacific<input className={field} type="datetime-local" required value={when} onChange={e=>{setWhen(e.target.value);setConfirmed(false);}}/></label>}
 <label className="block text-sm font-semibold">{mode==='log'?'Post-session note':'Pre-session note'} · optional<textarea className={field} rows={3} maxLength={4000} value={notes} onChange={e=>{setNotes(e.target.value);setConfirmed(false);}}/></label>
 <label className="flex min-h-12 items-start gap-3 text-sm leading-6"><input className="mt-1 h-5 w-5 shrink-0" type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>{mode==='log'?'I confirm this session occurred. Saving completed work may update the linked package through the audited completion command.':weekly?'I reviewed this client, trainer, date range and all recurring slots. Create only these proposed bookings; do not send messages or change package balances.':'I reviewed this client, trainer and time. Create one scheduled session only; do not mark it completed or charge anything.'}</label></section>
 <div className="flex flex-wrap gap-3"><button type="submit" disabled={!confirmed||!clientId} className="min-h-12 rounded-xl bg-sky px-5 text-sm font-semibold text-white disabled:opacity-40">{booking.busy||session.busy?'Saving…':weekly?'Create reviewed recurring booking':mode==='log'?'Save completed session':'Book this session'}</button>{!locked&&<Link className={button} href={back}>Back to calendar</Link>}</div></fieldset>
 {(error||booking.error||session.error)&&<p role="alert" className="rounded-xl border border-status-limited/30 p-4 text-sm text-status-limited">{error||booking.error||session.error}</p>}{booking.uncertain&&<button type="button" className={button} disabled={booking.busy} onClick={()=>void booking.retry()}>Retry exact recurring request</button>}{session.uncertain&&<button type="button" className={button} disabled={session.busy} onClick={()=>void session.retry()}>Retry exact session request</button>}
 </form>;
}
