import {z} from 'zod';
import {validDate} from '@/lib/fuel/model';
const uuid=z.string().uuid(),stamp=z.string().datetime({offset:true}),reason=z.string().trim().min(10).max(2000),short=z.string().trim().max(500);
const date=z.string().refine(validDate).nullable();
const phone=z.string().trim().max(80).nullable(),email=z.string().trim().email().max(254).transform(v=>v.toLowerCase()).nullable();
const base={request_id:uuid};
export const relationshipCommandSchema=z.discriminatedUnion('action',[
 z.object({...base,action:z.literal('create_record'),kind:z.enum(['contact','inquiry']),full_name:z.string().trim().min(2).max(160),email,phone,interest:short.nullable(),note:z.string().trim().max(4000),confirmed:z.literal(true)}).strict(),
 z.object({...base,action:z.literal('save_contact'),record_id:uuid,expected_updated_at:stamp,full_name:z.string().trim().min(2).max(160),email,phone,interest:short.nullable(),reason}).strict(),
 z.object({...base,action:z.literal('save_workflow'),record_id:uuid,expected_revision:z.number().int().min(0),assigned_to:uuid.nullable(),priority:z.enum(['low','normal','high']),due_on:date,next_action:short,goal:z.string().trim().max(1200),availability:z.string().trim().max(800),permission:z.enum(['unknown','allowed','do_not_contact']),permission_evidence:z.string().trim().max(1000),tags:z.array(z.string().trim().min(1).max(40)).max(8),outreach_draft:z.string().max(4000),archived:z.boolean(),reason}).strict(),
 z.object({...base,action:z.literal('record_activity'),record_id:uuid,kind:z.enum(['note','outbound_contact','inbound_reply','consultation_booked','consultation_attended','no_show']),channel:z.enum(['email','phone','sms','in_person','other']),occurred_at:stamp,note:reason,confirmed:z.literal(true)}).strict(),
 z.object({...base,action:z.literal('set_stage'),record_id:uuid,expected_updated_at:stamp,stage:z.enum(['new','contacted','nurturing','booked','converted','not_interested']),evidence:reason}).strict(),
 z.object({...base,action:z.literal('open_inquiry'),record_id:uuid,expected_updated_at:stamp,evidence:reason,confirmed:z.literal(true)}).strict(),
 z.object({...base,action:z.literal('assign_coach'),client_id:uuid,expected_updated_at:stamp,trainer_id:uuid.nullable(),reason,access_change_confirmed:z.literal(true)}).strict(),
 z.object({...base,action:z.literal('save_staff'),staff_id:uuid,expected_updated_at:stamp,full_name:z.string().trim().min(2).max(120),phone,reason}).strict(),
 z.object({...base,action:z.literal('save_operations'),staff_id:uuid,expected_updated_at:stamp.nullable(),staff_status:z.enum(['active','onboarding','leave','inactive']),operational_owner:z.string().trim().max(120).nullable(),responsibilities:z.array(z.string().trim().min(1).max(100)).max(12),notes:z.string().max(2000),reason}).strict(),
]);
export type RelationshipCommand=z.infer<typeof relationshipCommandSchema>;
export function parseRelationshipCommand(value:unknown,now=new Date()):RelationshipCommand{const c=relationshipCommandSchema.parse(value);if(c.action==='create_record'&&c.kind==='inquiry'&&c.note.trim().length<10)throw Error('Describe the current inquiry or documented referral.');if(c.action==='record_activity'&&Date.parse(c.occurred_at)>now.getTime())throw Error('An activity cannot be recorded as already done in the future.');if(c.action==='save_workflow'){if(c.permission!=='unknown'&&c.permission_evidence.length<10)throw Error('Record the permission or opt-out evidence.');if(c.permission==='do_not_contact'&&c.outreach_draft.trim())throw Error('Clear the outbound draft before applying do-not-contact.');if(c.due_on&&!c.next_action)throw Error('A follow-up date needs a next action.');if(new Set(c.tags.map(v=>v.toLowerCase())).size!==c.tags.length)throw Error('Use distinct tags.');}return c;}
export type LeadWorkflow={lead_id:string;revision:number;assigned_to:string|null;priority:'low'|'normal'|'high';due_on:string|null;next_action:string;goal:string;availability:string;permission:'unknown'|'allowed'|'do_not_contact';permission_evidence:string;tags:string[];outreach_draft:string;archived_at:string|null;updated_at:string};
export type LeadActivity={id:string;lead_id:string;actor_id:string;kind:string;channel:string;occurred_at:string;note:string;created_at:string};
export const EMPTY_WORKFLOW:Omit<LeadWorkflow,'lead_id'|'updated_at'>={revision:0,assigned_to:null,priority:'normal',due_on:null,next_action:'',goal:'',availability:'',permission:'unknown',permission_evidence:'',tags:[],outreach_draft:'',archived_at:null};
export function currentInquiryEvidence(notes:string|null){return (notes??'').split('\n').some(line=>{const found=/^\[IMS inquiry:[0-9a-f-]{36}\] (.+)$/.exec(line);if(!found)return false;try{const r=JSON.parse(found[1]);return typeof r.evidence==='string'&&r.evidence.trim().length>=10&&typeof r.recorded_at==='string'&&Number.isFinite(Date.parse(r.recorded_at));}catch{return false;}});}
export function relationshipPriority(row:{stage:string;last_contacted_at:string|null;workflow?:LeadWorkflow},today:string){const w=row.workflow;if(w?.archived_at)return 'archived';if(w?.permission==='do_not_contact')return 'suppressed';if(['converted','not_interested'].includes(row.stage))return 'closed';if(w?.due_on&&w.due_on<=today)return 'due';if(!row.last_contacted_at)return 'first_contact';if(row.stage==='booked')return 'booked';return 'active';}
export function validRelationshipReceipt(value:unknown,command:RelationshipCommand){if(!value||typeof value!=='object')return false;const r=value as Record<string,unknown>;return r.ok===true&&r.request_id===command.request_id&&r.action===command.action&&uuid.safeParse(r.id).success&&typeof r.updated_at==='string'&&Number.isFinite(Date.parse(r.updated_at))&&typeof r.deduped==='boolean';}
