import {currentInquiryEvidence,type LeadWorkflow} from './relationships';
export const LEGACY_CONTACT_SOURCES = new Set(["vagaro", "jason_contacts", "marketing"]);
export const INQUIRY_SOURCES = new Set(["website_contact", "manual", "referral", "consultation", "event_inquiry"]);
export const RESEARCH_SOURCE = "agent_research";
export type LeadBucket = "pipeline" | "contacts" | "research";
export interface LeadRecord {
 id:string;full_name:string;email:string|null;phone:string|null;interest:string|null;source:string|null;stage:string;
 appointments_booked:number;last_visited:string|null;prior_trainer:string|null;last_contacted_at:string|null;created_at:string;updated_at:string;notes:string|null;workflow?:LeadWorkflow;
}
export function hasWebsiteInquiry(notes:string|null):boolean{return (notes??'').split('\n').some(line=>{const match=/^\[Website enquiry:[A-Za-z0-9_-]+\] (.+)$/.exec(line);if(!match)return false;try{const data:unknown=JSON.parse(match[1]);return !!data&&typeof data==='object'&&'message' in data&&typeof data.message==='string'&&!!data.message.trim();}catch{return false;}});}
/** Import status 'new' does not establish present interest. Preserve the source. */
export function leadBucket(lead:Pick<LeadRecord,'source'|'notes'>):LeadBucket{if(lead.source===RESEARCH_SOURCE)return 'research';if(INQUIRY_SOURCES.has(lead.source??'')||hasWebsiteInquiry(lead.notes)||currentInquiryEvidence(lead.notes))return 'pipeline';return 'contacts';}
export function leadWorkspace(rows:LeadRecord[]){const pipeline=rows.filter(r=>leadBucket(r)==='pipeline'),contacts=rows.filter(r=>leadBucket(r)==='contacts'),research=rows.filter(r=>leadBucket(r)==='research'),open=pipeline.filter(r=>!r.workflow?.archived_at&&!['converted','not_interested'].includes(r.stage));return {pipeline,contacts,research,open,untouched:open.filter(r=>!r.last_contacted_at&&r.workflow?.permission!=='do_not_contact'),booked:open.filter(r=>r.stage==='booked'),converted:pipeline.filter(r=>r.stage==='converted')};}
export function sourceLabel(source:string|null):string{return ({vagaro:'Historical Vagaro contact',jason_contacts:"Jason's contacts",marketing:'Historical marketing list',website_contact:'Website inquiry',manual:'Manually added inquiry',manual_contact:'Manually added contact',agent_research:'Research candidate — not qualified'} as Record<string,string>)[source??'']??(source?.replaceAll('_',' ')||'Source needs review');}
export function researchBrief(area:string,lane:string):string{return `Research new business opportunities for Innovative Movement Solutions (IMS Fitness), a personal training studio in Scripps Ranch, San Diego.\nArea: ${area.trim().slice(0,160)||'Scripps Ranch and nearby San Diego communities'}\nResearch lane: ${lane}\n\nServe the general population and private-coaching clients through public organizations. These are research candidates, NOT confirmed consumer leads. Favor strength, mobility, longevity and measurable performance channels; do not infer any individual person's income, health, age or buying intent.\nFind up to 10 current public organizations using official websites. Return a JSON array of organization, website_url, evidence_url, fit_reason, next_step, checked_on. Cite exact public source URLs. Omit unsupported claims, invented contact information or unverified demand. Never use private client records, scrape individuals, contact anyone, purchase lists or send email/SMS. Owner review is required.`;}
