import { NextResponse, type NextRequest } from "next/server";
import { createClient, createServiceClient } from "@/lib/supabase/server";
async function staff(){
 const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return {error:NextResponse.json({error:"Unauthorized"},{status:401})};
 const {data:p,error}=await supabase.from("profiles").select("role,deleted_at").eq("id",user.id).maybeSingle();if(error)return {error:NextResponse.json({error:"Authorization unavailable"},{status:503})};
 if(!p||p.deleted_at||!["owner","trainer"].includes(p.role))return {error:NextResponse.json({error:"Staff only"},{status:403})};return {user,role:p.role};
}
export async function GET(){const a=await staff();if(a.error)return a.error;const svc=createServiceClient();const [r,b]=await Promise.all([svc.from("trainer_availability_rules").select("*").order("trainer_id").order("weekday").order("start_time"),svc.from("trainer_time_blocks").select("*").gte("ends_at",new Date().toISOString()).order("starts_at")]);if(r.error||b.error)return NextResponse.json({error:"Availability settings unavailable"},{status:503});return NextResponse.json({rules:r.data??[],blocks:b.data??[]},{headers:{"Cache-Control":"private, no-store"}});}
export async function POST(request:NextRequest){const a=await staff();if(a.error)return a.error;const body=await request.json().catch(()=>({}));const svc=createServiceClient();
 if(body.kind==="block"){const trainerId=a.role==="owner"&&body.trainer_id?body.trainer_id:a.user!.id;const start=new Date(body.starts_at),end=new Date(body.ends_at);if(!Number.isFinite(start.getTime())||!Number.isFinite(end.getTime())||start>=end)return NextResponse.json({error:"Valid block start/end required"},{status:400});const {data,error}=await svc.from("trainer_time_blocks").insert({trainer_id:trainerId,starts_at:start.toISOString(),ends_at:end.toISOString(),reason:String(body.reason??"").slice(0,200)||null,created_by:a.user!.id}).select().single();if(error)return NextResponse.json({error:"Could not save blocked time"},{status:503});return NextResponse.json({block:data},{status:201});}
 const trainerId=a.role==="owner"&&body.trainer_id?body.trainer_id:a.user!.id;const weekday=Number(body.weekday);const start=String(body.start_time??""),end=String(body.end_time??"");if(!Number.isInteger(weekday)||weekday<0||weekday>6||!/^\d{2}:\d{2}$/.test(start)||!/^\d{2}:\d{2}$/.test(end)||start>=end)return NextResponse.json({error:"Valid weekday and hours required"},{status:400});const {data,error}=await svc.from("trainer_availability_rules").insert({trainer_id:trainerId,weekday,start_time:start,end_time:end,active:true}).select().single();if(error)return NextResponse.json({error:"Could not save availability rule"},{status:503});return NextResponse.json({rule:data},{status:201});
}
