"use client";
import {recurringPreview,type SeriesFields} from "@/lib/schedule/commands";
const input='mt-1 min-h-12 w-full rounded-xl border border-divider bg-white px-3 text-base';
const days=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];
export function RecurrenceFields({value,onChange,asOf}:{value:SeriesFields;onChange:(patch:Partial<SeriesFields>)=>void;asOf:string}){
 let preview:{occurrences:string[];generatedUntil:string}|null=null,error:string|null=null;
 try{preview=recurringPreview(value,new Date(asOf));}catch(cause){error=cause instanceof Error?cause.message:'Review the weekly slots.';}
 return <div className="space-y-4"><div className="grid gap-3 sm:grid-cols-3"><label className="text-sm font-semibold">Starts on · Pacific<input type="date" required className={input} value={value.start_date} onChange={e=>onChange({start_date:e.target.value})}/></label><label className="text-sm font-semibold">Repeat interval<select className={input} value={value.interval_weeks} onChange={e=>onChange({interval_weeks:Number(e.target.value)})}>{[1,2,3,4].map(n=><option key={n} value={n}>{n===1?'Every week':`Every ${n} weeks`}</option>)}</select></label><label className="text-sm font-semibold">Ends on · optional<input type="date" min={value.start_date} className={input} value={value.end_date??''} onChange={e=>onChange({end_date:e.target.value||null})}/></label></div>
 <p className="text-xs leading-5 text-cream-dim">No end date means an ongoing rule with an eight-week rolling window. Future extension requires the configured scheduler. Repeated fall-back times use the earlier Pacific occurrence; nonexistent spring times block saving.</p>
 {value.slots.map((slot,i)=><div className="grid grid-cols-[1fr_1fr_auto] items-end gap-2" key={i}><label className="min-w-0 text-sm font-semibold">Day {i+1}<select className={input} value={slot.weekday} onChange={e=>onChange({slots:value.slots.map((s,n)=>n===i?{...s,weekday:Number(e.target.value)}:s)})}>{days.map((d,n)=><option key={d} value={n}>{d}</option>)}</select></label><label className="min-w-0 text-sm font-semibold">Time · Pacific<input type="time" required className={input} value={slot.time} onChange={e=>onChange({slots:value.slots.map((s,n)=>n===i?{...s,time:e.target.value}:s)})}/></label><button className="min-h-12 rounded-xl border border-divider px-3 text-sm disabled:opacity-40" type="button" disabled={value.slots.length===1} onClick={()=>onChange({slots:value.slots.filter((_,n)=>n!==i)})} aria-label={`Remove weekly slot ${i+1}`}>×</button></div>)}
 <button type="button" disabled={value.slots.length>=4} className="min-h-12 rounded-xl border border-sky/30 px-4 text-sm font-semibold text-sky disabled:opacity-40" onClick={()=>onChange({slots:[...value.slots,{weekday:(value.slots.at(-1)!.weekday+1)%7,time:value.slots[0].time}]})}>Add another weekly slot</button>
 {error&&<p role="alert" className="text-sm text-status-limited">{error}</p>}{preview&&<details className="rounded-xl bg-sky/5 p-4" open><summary className="min-h-11 cursor-pointer font-semibold">Proposed dates · {preview.occurrences.length} in the first window</summary><p className="text-xs text-cream-dim">Through {preview.generatedUntil}. Not booked yet; availability and permissions are rechecked atomically when saved.</p><ol className="mt-2 grid gap-1 text-sm sm:grid-cols-2">{preview.occurrences.slice(0,8).map(iso=><li key={iso}>{new Date(iso).toLocaleString('en-US',{timeZone:'America/Los_Angeles',weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}</li>)}</ol>{preview.occurrences.length>8&&<p className="mt-2 text-xs">+ {preview.occurrences.length-8} more dates</p>}</details>}
 </div>;
}
