"use client";
import {useState} from 'react';
import Link from 'next/link';
import {ptWallClockToUtc} from '@/lib/recurring';
import {pacificDate,PACIFIC} from '@/lib/time/pacific';
import {calendarHref} from '@/lib/schedule/booking-context';
import {useBookingCommand} from './use-booking-command';
const button='inline-flex min-h-12 items-center rounded-xl border border-divider bg-white px-4 text-sm font-semibold disabled:opacity-40';
export function SessionScheduleControls({session,owner,asOf}:{session:{id:string;scheduled_at:string;duration_minutes:number;updated_at:string;status:string;trainer_id:string|null;recurring_series_id:string|null;vagaro_event_id:string|null};owner:boolean;asOf:string}){
 const date=new Date(session.scheduled_at),[when,setWhen]=useState(`${pacificDate(date)}T${date.toLocaleTimeString('en-GB',{timeZone:PACIFIC,hour:'2-digit',minute:'2-digit',hourCycle:'h23'})}`),[duration,setDuration]=useState(session.duration_minutes),[action,setAction]=useState<'reschedule'|'cancel_occurrence'>('reschedule'),[reason,setReason]=useState(''),[confirmed,setConfirmed]=useState(false),[error,setError]=useState<string|null>(null),command=useBookingCommand();
 if(!['scheduled','confirmed'].includes(session.status)||Date.parse(session.scheduled_at)<=Date.parse(asOf))return null;
 async function submit(event:React.FormEvent){event.preventDefault();if(!confirmed||command.locked)return;setError(null);try{await command.submit(action==='cancel_occurrence'?{action,session_id:session.id,expected_updated_at:session.updated_at}:{action,session_id:session.id,expected_updated_at:session.updated_at,scheduled_at:ptWallClockToUtc(when.slice(0,10),when.slice(11,16)).toISOString(),duration_minutes:duration},reason);}catch(cause){setError(cause instanceof Error?cause.message:'Review the new time.');}}
 return <details className="rounded-2xl border border-divider bg-white p-5"><summary className="min-h-12 cursor-pointer text-lg font-semibold text-sky">Schedule controls · this occurrence</summary><div className="mt-3 space-y-4">{session.recurring_series_id?<p className="text-sm">This session belongs to a standing rule. The form below changes only this occurrence. <Link className="font-semibold text-sky underline" href={`/schedule/standing?series=${session.recurring_series_id}`}>Edit future recurrence →</Link></p>:session.vagaro_event_id?<p className="text-sm text-cream-dim">Imported Vagaro occurrence. Its source ID is preserved; editing this session does not change other imported appointments or invent a repeat rule.</p>:<p className="text-sm text-cream-dim">One-time booking.</p>}
 {!command.result&&<form onSubmit={submit}><fieldset disabled={command.locked} className="space-y-4"><legend className="sr-only">Change only this session</legend><div className="flex flex-wrap gap-2"><button type="button" className={button} aria-pressed={action==='reschedule'} onClick={()=>{setAction('reschedule');setConfirmed(false);}}>Change time / duration</button>{owner&&<button type="button" className={button} aria-pressed={action==='cancel_occurrence'} onClick={()=>{setAction('cancel_occurrence');setConfirmed(false);}}>Cancel this occurrence · no charge</button>}</div>{action==='reschedule'&&<div className="grid gap-3 sm:grid-cols-2"><label className="block text-sm font-semibold">New time · Pacific<input className="mt-1 min-h-12 w-full rounded-xl border border-divider px-3 text-base" type="datetime-local" required value={when} onChange={e=>{setWhen(e.target.value);setConfirmed(false);}}/></label><label className="block text-sm font-semibold">Duration · minutes<input className="mt-1 min-h-12 w-full rounded-xl border border-divider px-3 text-base" type="number" min={1} max={480} required value={duration} onChange={e=>{setDuration(Number(e.target.value));setConfirmed(false);}}/></label></div>}
 <label className="block text-sm font-semibold">Reason · recorded in audit history<textarea className="mt-1 w-full rounded-xl border border-divider p-3 text-base" rows={2} required minLength={5} maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></label><label className="flex min-h-12 items-start gap-3 text-sm leading-6"><input className="mt-1 h-5 w-5" type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>Only this future occurrence. No package deduction, charge, client notification or Vagaro write.</label><button type="submit" className={button} disabled={!confirmed||reason.trim().length<5}>{action==='reschedule'?'Save this occurrence only':'Confirm no-charge cancellation'}</button></fieldset></form>}
 {(error||command.error)&&<p role="alert" className="text-sm text-status-limited">{error||command.error}</p>}{command.uncertain&&<button type="button" className={button} disabled={command.busy} onClick={()=>void command.retry()}>Retry exact change</button>}{command.result&&<div role="status" className="rounded-xl bg-sky/5 p-4"><p>Change confirmed. Package balances and other occurrences were not changed.</p><Link className={button+' mt-3'} href={calendarHref(action==='reschedule'?when.slice(0,10):pacificDate(date),session.trainer_id??'all')}>Return to calendar →</Link></div>}
 </div></details>;
}
