"use client";
import {useState} from 'react';
import Link from 'next/link';
import {RecurrenceFields} from './recurrence-fields';
import {useBookingCommand} from './use-booking-command';
import type {SeriesFields} from '@/lib/schedule/commands';
export type StandingSeries=SeriesFields&{id:string;revision:number;status:string;generated_until:string|null;clientName:string;trainerName:string;futureCount:number;replaces_series_id:string|null};
const button='inline-flex min-h-12 items-center rounded-xl border border-divider bg-white px-4 text-sm font-semibold disabled:opacity-40';
function SeriesCard({series,today,asOf,initialOpen}:{series:StandingSeries;today:string;asOf:string;initialOpen:boolean}){
 const [mode,setMode]=useState<'replace'|'cancel'|null>(null),[fields,setFields]=useState<SeriesFields>({client_id:series.client_id,trainer_id:series.trainer_id,start_date:series.start_date>today?series.start_date:today,end_date:series.end_date,interval_weeks:series.interval_weeks,duration_minutes:series.duration_minutes,slots:series.slots,location:series.location,notes:series.notes}),[reason,setReason]=useState(''),[confirmed,setConfirmed]=useState(false),command=useBookingCommand();
 return <details open={initialOpen} className="rounded-2xl border border-divider bg-white p-4"><summary className="min-h-12 cursor-pointer"><span className="font-semibold">{series.clientName}</span><span className="ml-2 text-xs text-cream-faint">{series.trainerName} · {series.status} · {series.futureCount} upcoming</span></summary><div className="mt-3 space-y-4"><p className="text-sm">{series.slots.map(slot=>`${['Sun','Mon','Tue','Wed','Thu','Fri','Sat'][slot.weekday]} ${slot.time}`).join(' · ')} Pacific · {series.duration_minutes} minutes · every {series.interval_weeks} week{series.interval_weeks===1?'':'s'}</p><p className="text-xs text-cream-dim">Starts {series.start_date} · {series.end_date?`ends ${series.end_date}`:'no fixed end date'} · generated through {series.generated_until??'not yet generated'}. Revision {series.revision}.</p>
 {series.replaces_series_id&&<p className="text-xs text-cream-faint">This is a replacement rule; earlier session history stays on the previous series.</p>}
 {series.status==='active'&&!command.result&&<><div className="flex flex-wrap gap-2"><button type="button" className={button} disabled={command.locked} onClick={()=>{setMode('replace');setConfirmed(false);}}>Edit future recurrence</button><button type="button" className={button} disabled={command.locked} onClick={()=>{setMode('cancel');setConfirmed(false);}}>Cancel remaining future sessions</button></div>
 {mode&&<form onSubmit={event=>{event.preventDefault();if(!confirmed)return;void command.submit(mode==='cancel'?{action:'cancel_series',series_id:series.id,expected_revision:series.revision}:{action:'replace_series',...fields,series_id:series.id,expected_revision:series.revision},reason);}}><fieldset disabled={command.locked} className="space-y-4 rounded-xl bg-surface-soft p-4"><legend className="sr-only">Review series change</legend>{mode==='replace'?<><p className="text-sm leading-6">Create a replacement rule from the chosen effective date. Earlier and completed sessions stay unchanged. Future scheduled/confirmed occurrences from that date are cancelled and replaced together. Existing exceptions block a bulk edit rather than being silently lost.</p><p className="text-xs text-cream-dim">For intervals longer than one week, the selected start date anchors the new repeat cycle.</p><RecurrenceFields value={fields} asOf={asOf} onChange={patch=>{setFields(v=>({...v,...patch}));setConfirmed(false);}}/><label className="block text-sm font-semibold">Duration · 15–180 minutes<input className="mt-1 min-h-12 w-full rounded-xl border border-divider px-3" type="number" min={15} max={180} required value={fields.duration_minutes} onChange={e=>{setFields(v=>({...v,duration_minutes:Number(e.target.value)}));setConfirmed(false);}}/></label><label className="block text-sm font-semibold">Pre-session note for new occurrences<textarea className="mt-1 w-full rounded-xl border border-divider p-3" rows={2} maxLength={4000} value={fields.notes} onChange={e=>{setFields(v=>({...v,notes:e.target.value}));setConfirmed(false);}}/></label></>:<p className="text-sm leading-6">Cancel the remaining future scheduled/confirmed occurrences and stop this rule from generating more. Past, completed and previously cancelled sessions remain untouched. This administrative change does not charge packages or send notifications.</p>}
 <label className="block text-sm font-semibold">Reason · recorded in audit history<textarea className="mt-1 w-full rounded-xl border border-divider p-3" rows={2} minLength={5} maxLength={1000} required value={reason} onChange={e=>setReason(e.target.value)}/></label><label className="flex min-h-12 items-start gap-3 text-sm leading-6"><input className="mt-1 h-5 w-5" type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I reviewed the future-only scope. No charges, package deductions or client messages will be created.</label><button className={button} type="submit" disabled={!confirmed||reason.trim().length<5}>{mode==='replace'?'Apply reviewed future changes':'Confirm future-series cancellation'}</button></fieldset></form>}</>}
 {command.error&&<p role="alert" className="text-sm text-status-limited">{command.error}</p>}{command.uncertain&&<button className={button} disabled={command.busy} type="button" onClick={()=>void command.retry()}>Retry exact request</button>}{command.result&&<div role="status" className="rounded-xl bg-sky/5 p-4"><p>Change confirmed: {command.result.created} created, {command.result.cancelled} cancelled. No billing change.</p><Link className={button+' mt-3'} href={`/schedule/standing?series=${command.result.series_id}`}>Open updated series →</Link><Link className={button+' ml-2 mt-3'} href={`/schedule?date=${fields.start_date}&trainer=${series.trainer_id}`}>View calendar →</Link></div>}
 </div></details>;
}
export function StandingBookings({series,today,asOf,selectedId}:{series:StandingSeries[];today:string;asOf:string;selectedId?:string}){
 const [history,setHistory]=useState(false),[search,setSearch]=useState('');const visible=series.filter(s=>(history||s.status==='active'||s.id===selectedId)&&`${s.clientName} ${s.trainerName}`.toLowerCase().includes(search.trim().toLowerCase()));
 return <section className="space-y-4"><div className="flex flex-wrap items-end gap-3"><label className="min-w-0 flex-1 text-sm font-semibold">Search standing bookings<input className="mt-1 min-h-12 w-full rounded-xl border border-divider px-3" type="search" value={search} onChange={e=>setSearch(e.target.value)}/></label><label className="flex min-h-12 items-center gap-2 text-sm"><input type="checkbox" checked={history} onChange={e=>setHistory(e.target.checked)}/>Include paused / cancelled history</label></div>{visible.map(s=><SeriesCard key={s.id+':'+s.revision} series={s} today={today} asOf={asOf} initialOpen={s.id===selectedId}/>)}{!visible.length&&<p className="rounded-xl border border-divider p-4 text-sm">No matching standing-booking rules. Imported individual appointments remain on the calendar; they are not automatically converted into recurring rules.</p>}</section>;
}
