import Link from "next/link";
import Image from "next/image";
import {notFound} from "next/navigation";
import {fuelAccess} from "@/lib/fuel/load";
import {FUEL_UUID,fuelDate,type PlanVersion} from "@/lib/fuel/model";
import {FuelPlanView} from "@/components/fuel/plan-view";
import {PrintFuelButton} from "@/components/fuel/controls";
export const dynamic="force-dynamic";
export default async function FuelPrint({searchParams}:{searchParams:Promise<{client_id?:string;version?:string}>}){const params=await searchParams;if(!params.client_id||!params.version||!FUEL_UUID.test(params.version))notFound();const {db,person,staff}=await fuelAccess(params.client_id);const versionQ=await db.from("fuel_plan_versions").select("id,client_id,revision,content,origin,source_reference,created_at").eq("id",params.version).eq("client_id",params.client_id).maybeSingle();if(versionQ.error)throw Error("Plan snapshot unavailable.");if(!versionQ.data)notFound();const v=versionQ.data as PlanVersion;const released=await db.from("fuel_plan_releases").select("id").eq("version_id",v.id).eq("client_id",params.client_id).limit(1);if(released.error)throw Error("Publication evidence unavailable.");const isReleased=!!released.data?.length;if(!staff&&!isReleased)notFound();return <main className="mx-auto max-w-4xl space-y-6 bg-white p-6 text-cream print:p-0"><div className="flex flex-wrap items-center gap-3 print:hidden"><PrintFuelButton/><Link href={staff?`/clients/${params.client_id}/fuel`:"/fuel"} className="inline-flex min-h-12 items-center text-sm font-semibold text-sky">Back to Fuel</Link></div><header className="border-b-4 border-sky pb-5"><Image src="/ims-logo.png" width={150} height={64} alt="Innovative Movement Solutions" unoptimized className="h-16 w-auto"/><p className="mt-4 text-xs font-semibold uppercase tracking-widest text-sky">Fuel & Performance · {isReleased?"Released snapshot":"Private draft · not a prescription"}</p><h1 className="mt-2 text-3xl font-bold">{person.full_name}</h1><p className="mt-2 text-xs text-cream-dim">Version {v.revision} · saved {v.created_at.slice(0,10)} · {v.origin.replaceAll("_"," ")}</p></header><FuelPlanView plan={v.content} today={fuelDate()}/><footer className="border-t border-divider pt-4 text-xs leading-5 text-cream-dim">This is a snapshot of a coach-authored plan, not an automatic assessment or medical nutrition therapy. Targets and meals are estimates requiring individual review. Measurements, client reports, and projections remain separate. Refer to the current in-app release for later changes.</footer></main>;}
