import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {CONNECTORS,querySpecs,validateBundle,reportWindow,priorWindow,validDay,metric,ratio,totalRow,brandedQuery,ownedPage,trackedLink,validAcquisitionReceipt,acquisitionCommandSchema,type AcquisitionSource,type AcquisitionBundle,type Snapshot} from '../lib/growth/acquisition/model';
import {acquisitionInsights} from '../lib/growth/acquisition/insights';
import {readAcquisition,providerRows} from '../lib/growth/acquisition/provider';
const now=new Date('2026-09-28T20:00:00Z'),id='11111111-1111-4111-8111-111111111111';
const source:AcquisitionSource={connector:'searchconsole',account_id:'sc-domain:example.com',label:'Synthetic property',hosts:['example.com','www.example.com'],brand_terms:['Example Fitness','EF Training'],daily_sync:false,revision:1,updated_at:now.toISOString()};
function bundle(rows:Record<string,string|number|null>[],connector:typeof CONNECTORS[number]='searchconsole'):AcquisitionBundle{const spec=querySpecs(connector)[0];return {version:1,start:'2026-08-29',end:'2026-09-25',observed_at:now.toISOString(),reports:[{kind:spec.kind,period:spec.period,fields:spec.fields,status:rows.length?'available':'empty',rows,note:spec.note}]};}
const web={account_id:'example.com',search_type:'web',clicks:10,impressions:1000,position:12.3};
function snapshot(payload=bundle([web])):Snapshot{return{id,connector:'searchconsole',account_id:source.account_id,origin:'connector_import',payload,fingerprint:'a'.repeat(64),created_at:now.toISOString()};}
test('report windows are inclusive, use a buffer and keep previous periods disjoint',()=>{assert.deepEqual(reportWindow('2026-09-28'),{start:'2026-08-29',end:'2026-09-25'});assert.deepEqual(priorWindow('2026-08-29','2026-09-25'),{start:'2026-08-01',end:'2026-08-28'});assert.equal(validDay('2026-02-30'),false);assert.equal(validDay('2024-02-29'),true);});
test('source registration is limited to the three authorized analytics families, not ads writes',()=>{assert.deepEqual(CONNECTORS,['searchconsole','googleanalytics4','google_my_business']);for(const c of CONNECTORS)for(const spec of querySpecs(c)){assert.ok(spec.fields.length<=12);assert.equal(spec.fields.some(f=>/user_id|email|phone|review_comment|review_reviewer/.test(f)),false);}});
test('snapshot validates account, field types, grain and dated provenance without altering values',()=>{const b=bundle([web]),before=JSON.stringify(b);assert.deepEqual(validateBundle(b,source.connector,source.account_id,now),b);assert.equal(JSON.stringify(b),before);for(const row of [{...web,clicks:'10'},{...web,impressions:-1},{...web,account_id:'other.example'},{...web,extra:'unknown'},{...web,clicks:1001}])assert.throws(()=>validateBundle(bundle([row]),source.connector,source.account_id,now));assert.throws(()=>validateBundle(bundle([web,web]),source.connector,source.account_id,now),/Duplicate/);assert.throws(()=>validateBundle({...b,reports:[...b.reports,...b.reports]},source.connector,source.account_id,now),/repeated/);});
test('empty, limited and unavailable reports cannot become zero traffic or complete totals',()=>{const empty=snapshot(bundle([]));assert.equal(totalRow(empty),null);const limited=snapshot();limited.payload.reports[0].status='limited';assert.equal(totalRow(limited),null);const zero=snapshot(bundle([{...web,clicks:0,impressions:0,position:0}]));assert.equal(metric(totalRow(zero),'clicks'),0);assert.equal(ratio(0,0),null);assert.equal(metric(null,'sessions'),null);assert.throws(()=>validateBundle({...empty.payload,reports:[{...empty.payload.reports[0],status:'available'}]},source.connector,source.account_id,now));});
test('future windows, invalid calendar days and future retrieval stamps are rejected',()=>{const b=bundle([web]);for(const patch of [{end:'2027-01-01'},{start:'2026-02-30'},{end:'2026-01-01'},{observed_at:'2027-01-01T00:00:00Z'}])assert.throws(()=>validateBundle({...b,...patch},source.connector,source.account_id,now));});
test('web, image and video totals stay separate and averages are not averaged together',()=>{const s=snapshot(bundle([web,{...web,search_type:'image',clicks:50,impressions:100,position:40}]));assert.equal(metric(totalRow(s),'clicks'),10);assert.equal(metric(totalRow(s),'position'),12.3);assert.equal(ratio(metric(totalRow(s),'clicks'),metric(totalRow(s),'impressions')),0.01);});
test('brand detection matches configured words, not just the website domain',()=>{assert.equal(brandedQuery('Example Fitness near me',source.brand_terms),true);assert.equal(brandedQuery('best personal trainer',source.brand_terms),false);assert.equal(brandedQuery('someftraining',source.brand_terms),false);assert.equal(brandedQuery('sims',[ 'ims']),false);});
test('tagged links allow only verified HTTPS hosts and remove any old query or fragment',()=>{assert.equal(ownedPage('https://example.com/page?token=private#secret',source.hosts),'https://example.com/page');for(const url of ['https://example.com.evil.org','https://example.com@evil.org/','http://example.com/','https://127.0.0.1/','javascript:alert(1)'])assert.equal(ownedPage(url,source.hosts),null);assert.equal(trackedLink('https://example.com/book?old=1#old',source.hosts,'gbp_profile'),'https://example.com/book?utm_source=google&utm_medium=organic&utm_campaign=gbp_profile');assert.throws(()=>trackedLink('https://example.com',source.hosts,'Name@person'));});
test('GA4 absence generates a measurement check, not a zero-visitor or client claim',()=>{const ga:Snapshot={...snapshot(bundle([],'googleanalytics4')),connector:'googleanalytics4',account_id:'12345'};const insights=acquisitionInsights([{...source,connector:'googleanalytics4',account_id:'12345'}],[ga]);assert.match(insights[0].title,/Verify website measurement/);assert.match(insights[0].evidence,/not proof of zero/);});
test('URL variants create an inspection action without merging page evidence',()=>{const b=bundle([web]),spec=querySpecs('searchconsole').find(s=>s.kind==='pages')!;b.reports.push({kind:'pages',period:'current',fields:spec.fields,status:'available',note:spec.note,rows:[{page:'https://example.com/coaching',search_type:'web',clicks:2,impressions:10,position:9},{page:'https://www.example.com/coaching.html',search_type:'web',clicks:3,impressions:12,position:8}]});const before=JSON.stringify(b);assert.ok(acquisitionInsights([source],[snapshot(b)]).some(i=>i.key==='canonical-paths'));assert.equal(JSON.stringify(b),before);});
test('private action commands reject role/spend changes and require identity receipts',()=>{const command={action:'source_options' as const,request_id:id,connector:'searchconsole' as const,expected_revision:1,daily_sync:false,brand_terms:['Example Fitness'],confirmed:true as const};assert.ok(acquisitionCommandSchema.safeParse(command).success);assert.equal(acquisitionCommandSchema.safeParse({...command,send:true}).success,false);assert.ok(validAcquisitionReceipt({ok:true,request_id:id,action:'source_options',revision:2,deduped:false},command));assert.equal(validAcquisitionReceipt({ok:true,request_id:id,action:'other',revision:2,deduped:false},command),false);});
test('read adapter only queries fixed Windsor hosts, exact accounts and declared aggregate fields',async()=>{const originalFetch=globalThis.fetch,oldKey=process.env.WINDSOR_API_KEY;process.env.WINDSOR_API_KEY='synthetic-only';const calls:URL[]=[];globalThis.fetch=async(input,init)=>{const u=new URL(String(input));calls.push(u);assert.equal(u.origin,'https://connectors.windsor.ai');assert.equal(u.pathname,'/searchconsole');assert.equal(u.searchParams.get('select_accounts'),source.account_id);assert.equal(init?.method,'GET');assert.equal(init?.redirect,'error');return new Response(JSON.stringify({data:[]}));};try{const out=await readAcquisition(source,'2026-08-29','2026-09-25',now);assert.equal(calls.length,4);assert.ok(out.reports.every(r=>r.status==='empty'));assert.equal(JSON.stringify(out).includes('synthetic-only'),false);assert.ok(calls.some(u=>u.searchParams.get('date_from')==='2026-08-01'));}finally{globalThis.fetch=originalFetch;if(oldKey===undefined)delete process.env.WINDSOR_API_KEY;else process.env.WINDSOR_API_KEY=oldKey;}});
test('provider failures and echoed credentials never escape in snapshot notes',async()=>{const originalFetch=globalThis.fetch,oldKey=process.env.WINDSOR_API_KEY;process.env.WINDSOR_API_KEY='synthetic-private';globalThis.fetch=async()=>{throw Error('Failed URL https://example.com?api_key=synthetic-private');};try{const out=await readAcquisition(source,'2026-08-29','2026-09-25',now);assert.ok(out.reports.every(r=>r.status==='unavailable'));assert.equal(JSON.stringify(out).includes('synthetic-private'),false);}finally{globalThis.fetch=originalFetch;if(oldKey===undefined)delete process.env.WINDSOR_API_KEY;else process.env.WINDSOR_API_KEY=oldKey;}});
test('provider error envelopes and row overflows are not interpreted as empty success',()=>{assert.deepEqual(providerRows({data:[]}),[]);assert.throws(()=>providerRows({error:'denied',data:[]}));assert.throws(()=>providerRows({ok:true}));assert.throws(()=>providerRows(Array.from({length:1001},()=>({}))));});
test('read-only boundary and rollout controls stay explicit',()=>{const provider=readFileSync('lib/growth/acquisition/provider.ts','utf8'),route=readFileSync('app/api/growth/acquisition/route.ts','utf8'),cron=readFileSync('app/api/cron/acquisition-sync/route.ts','utf8');assert.doesNotMatch(provider,/\/actions|api\.openai|google_ads/);assert.match(route,/requireGrowthOwner/);assert.match(route,/source_read_confirmed/);assert.match(cron,/VERCEL_ENV!=='production'/);assert.match(cron,/timingSafeEqual/);assert.match(cron,/daily_sync/);const sql=readFileSync('packages/db/migrations/0096_acquisition_intelligence.sql','utf8');assert.doesNotMatch(sql,/insert into public\.(clients|payments|leads|sessions)|alter table public\.(clients|payments|leads|sessions)/i);});
