const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),ts=require('typescript');
function load(file,deps={},globals={}){const exports={},code=ts.transpileModule(fs.readFileSync(path.join(__dirname,'..',file),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText;new Function('require','exports',...Object.keys(globals),code)(name=>{if(!(name in deps))throw Error('Unexpected dependency '+name);return deps[name];},exports,...Object.values(globals));return exports;}
const model=load('lib/growth/acquisition/model.ts',{zod:require('zod')}),id='11111111-1111-4111-8111-111111111111';
class AccessError extends Error{constructor(status,message){super(message);this.status=status;}}
const response={json:(body,init)=>({body,status:init?.status??200,headers:init?.headers})};
function api({denied=null,receipt=null}={}){let auth=0,reads=0,writes=0,refreshes=0;const mod=load('app/api/growth/acquisition/route.ts',{'next/server':{NextResponse:response},zod:require('zod'),'@/lib/media/request':{smallJson:async r=>r.body},'@/lib/growth/owner-access':{GrowthAccessError:AccessError,requireGrowthOwner:async()=>{auth++;if(denied)throw new AccessError(denied,'Denied');return{db:{rpc:async()=>{writes++;return{data:receipt,error:null}}},user:{id}};}},'@/lib/growth/acquisition/model':model,'@/lib/growth/acquisition/server':{loadAcquisition:async()=>{reads++;return{sources:[],snapshots:[]}},refreshAcquisition:async()=>{refreshes++;return{id,status:'completed'}}}});return{get:()=>mod.GET(),post:(body,origin='https://ims.example')=>mod.POST({body,headers:{get:()=>origin},nextUrl:{origin:'https://ims.example'}}),stats:()=>({auth,reads,writes,refreshes})};}
test('anonymous and nonowner callers cannot load snapshots or dispatch reads',async()=>{for(const denied of [401,403]){const h=api({denied});assert.equal((await h.get()).status,denied);assert.equal((await h.post({})).status,denied);assert.equal(h.stats().reads,0);assert.equal(h.stats().refreshes,0);assert.equal(h.stats().writes,0);}});
test('cross-origin acquisition mutations are rejected before identity or provider work',async()=>{const h=api();assert.equal((await h.post({},'https://unrelated.example')).status,403);assert.equal(h.stats().auth,0);});
test('malformed refresh or injected account/write fields cannot reach provider',async()=>{for(const patch of [{connector:'google_ads'},{source_read_confirmed:false},{account_id:'other'},{send_post:true}]){const h=api(),body={action:'refresh',request_id:id,connector:'searchconsole',start:'2020-01-01',end:'2020-01-28',source_read_confirmed:true,...patch};assert.equal((await h.post(body)).status,400);assert.equal(h.stats().refreshes,0);}});
test('a valid owner refresh returns a matching read receipt without an external write',async()=>{const h=api(),r=await h.post({action:'refresh',request_id:id,connector:'searchconsole',start:'2020-01-01',end:'2020-01-28',source_read_confirmed:true});assert.equal(r.status,200);assert.equal(r.body.request_id,id);assert.equal(h.stats().writes,0);assert.equal(h.stats().refreshes,1);});
test('incomplete owner-save receipt is an error, not success',async()=>{const h=api({receipt:{ok:true}});assert.equal((await h.post({action:'source_options',request_id:id,connector:'searchconsole',expected_revision:1,daily_sync:false,brand_terms:['Example Fitness'],confirmed:true})).status,503);});
function hooks(){const slots=[];let cursor=0,handler;const react={useRef(v){const i=cursor++;return slots[i]??(slots[i]={current:v});},useState(v){const i=cursor++;if(!(i in slots))slots[i]=v;return[slots[i],next=>{slots[i]=typeof next==='function'?next(slots[i]):next;}];}};const hook=load('components/growth/acquisition/controls.tsx',{'react':react,'next/navigation':{useRouter:()=>({refresh(){}})},'react/jsx-runtime':{jsx(){},jsxs(){}},'@/components/fuel/controls':{},'@/lib/growth/acquisition/model':model},{fetch:(...args)=>handler(...args)}).useAcquisitionMutation;return{render(){cursor=0;return hook();},set(fn){handler=fn;}};}
test('lost acquisition save locks edits and replays the original request after a later permission error',async()=>{const h=hooks(),sent=[],command={action:'source_options',request_id:id,connector:'searchconsole',expected_revision:1,daily_sync:false,brand_terms:['Example Fitness'],confirmed:true};h.set(async(_,o)=>{sent.push(o.body);throw Error('lost')});h.render().submit(command);await new Promise(r=>setTimeout(r,0));assert.equal(h.render().uncertain,true);h.render().submit({...command,daily_sync:true});assert.equal(sent.length,1);h.set(async(_,o)=>{sent.push(o.body);return{ok:false,status:403,json:async()=>({error:'Denied'})}});await h.render().retry();assert.equal(h.render().uncertain,true);h.set(async(_,o)=>{sent.push(o.body);return{ok:true,json:async()=>({ok:true,request_id:id,action:'source_options',revision:2,deduped:true})}});await h.render().retry();assert.equal(h.render().saved,true);assert.equal(new Set(sent).size,1);});
test('production scheduler stays inactive on preview and unauthenticated requests',async()=>{let service=0;const route=load('app/api/cron/acquisition-sync/route.ts',{'node:crypto':require('node:crypto'),'next/server':{NextResponse:response},'@/lib/supabase/server':{createServiceClient:()=>{service++;throw Error('should not run')}},'@/lib/growth/acquisition/provider':{acquisitionProviderReady:()=>true},'@/lib/growth/acquisition/server':{refreshAcquisition:()=>{throw Error('should not run')}},'@/lib/growth/acquisition/model':model},{process:{env:{CRON_SECRET:'synthetic-secret',VERCEL_ENV:'preview'}}});assert.equal((await route.GET({headers:{get:()=>''}})).status,401);assert.equal((await route.GET({headers:{get:()=> 'Bearer synthetic-secret'}})).status,200);assert.equal(service,0);});
