const {test}=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs");
const sql=fs.readFileSync("packages/db/migrations/0083_apple_health_daily.sql","utf8"),api=fs.readFileSync("app/api/mobile/health/route.ts","utf8"),swift=fs.readFileSync("ios/IMSFitness/HealthStore.swift","utf8"),card=fs.readFileSync("components/fuel/apple-health-card.tsx","utf8");
test("Apple Health evidence is client-controlled and staff read-only",()=>{assert.match(sql,/actor\.role='client' and actor\.id=client_health_daily\.client_id/);assert.match(sql,/Active client authorization required/);assert.match(sql,/grant execute on function public\.sync_client_health_day\(date,jsonb\) to authenticated/);});
test("Health sync accepts a narrow nonclinical daily summary only",()=>{for(const key of ["steps","active_energy_kcal","exercise_minutes","sleep_hours","weight_lb","workout_minutes","workout_count"])assert.match(sql,new RegExp(key));for(const forbidden of ["heart_rate","dietary","clinical","diagnosis"])assert.doesNotMatch(sql,new RegExp("'"+forbidden+"'"));});
test("missing permissions cannot become zero evidence",()=>{assert.match(sql,/case when 'steps'=any\(types\).*else null end/s);assert.match(sql,/case when 'sleep'=any\(types\).*else null end/s);assert.match(card,/Missing Health data is never treated as zero or failure/);});
test("Health endpoint requires authenticated session and delegates bounds to RPC",()=>{assert.match(api,/if\(!user\)/);assert.match(api,/sync_client_health_day/);assert.match(api,/No values were inferred/);});
test("iOS requests read-only granular HealthKit authorization",()=>{assert.match(swift,/requestAuthorization\(toShare:\[\],read:readTypes\)/);assert.match(swift,/stepCount/);assert.match(swift,/activeEnergyBurned/);assert.match(swift,/appleExerciseTime/);assert.match(swift,/bodyMass/);assert.match(swift,/sleepAnalysis/);assert.match(swift,/workoutType/);});
test("iOS sends only days with available evidence",()=>{assert.match(swift,/guard !available\.isEmpty else\{return\}/);assert.match(swift,/observed_types/);});
test("Fuel UI preserves Bod Pod as anchor and blocks automatic Watch/BIA prescription",()=>{assert.match(card,/Bod Pod remains the IMS body-composition anchor/);assert.match(card,/does not turn Watch calories or BIA estimates into automatic nutrition changes/);});
