const {test,before,after}=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),{randomUUID}=require("node:crypto");
const live=process.env.IMS_TEST_DATABASE_URL;let admin,db,name,client,coach,other;
before(async()=>{if(!live)return;const url=new URL(live);if(!["localhost","127.0.0.1"].includes(url.hostname)||url.pathname!=="/ims_ci")throw Error("Only isolated ims_ci is permitted");const {Client}=require("pg");admin=new Client({connectionString:live});await admin.connect();name="ims_health_"+randomUUID().replaceAll("-","");await admin.query('create database "'+name+'"');url.pathname="/"+name;db=new Client({connectionString:url.toString()});await db.connect();
 await db.query(`create schema auth;create role authenticated;create role anon;create role service_role;create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema public,auth to authenticated,anon,service_role;create table profiles(id uuid primary key,role text not null,deleted_at timestamptz);create table clients(id uuid primary key references profiles(id),primary_trainer_id uuid references profiles(id),status text not null);grant select on profiles,clients to authenticated;`);
 client=randomUUID();coach=randomUUID();other=randomUUID();await db.query("insert into profiles values($1,'client',null),($2,'trainer',null),($3,'trainer',null)",[client,coach,other]);await db.query("insert into clients values($1,$2,'active')",[client,coach]);await db.query(fs.readFileSync(path.join(__dirname,"../packages/db/migrations/0083_apple_health_daily.sql"),"utf8"));});
after(async()=>{if(db)await db.end();if(admin){try{await admin.query('drop database "'+name+'"')}finally{await admin.end()}}});
async function role(id,as="authenticated"){await db.query("reset role");await db.query("set role "+as);await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);}
async function sync(day,payload){return (await db.query("select public.sync_client_health_day($1,$2::jsonb) result",[day,JSON.stringify(payload)])).rows[0].result;}
test("actual Health SQL is client-write, assigned-coach-read and missing-is-null",{skip:!live},async()=>{const today=new Date().toISOString().slice(0,10);await role(client);const r=await sync(today,{steps:8123,weight_lb:181.2,weight_source:"Synthetic Scale",observed_types:["steps","weight"],time_zone:"America/Los_Angeles",utc_offset_minutes:-420});assert.equal(r.ok,true);let rows=(await db.query("select * from client_health_daily")).rows;assert.equal(rows.length,1);assert.equal(rows[0].steps,8123);assert.equal(rows[0].sleep_hours,null);assert.equal(rows[0].weight_source,"Synthetic Scale");await role(coach);assert.equal((await db.query("select * from client_health_daily")).rows.length,1);await assert.rejects(sync(today,{steps:1,observed_types:["steps"]}),/Active client/);await role(other);assert.equal((await db.query("select * from client_health_daily")).rows.length,0);});
test("actual Health SQL rejects hidden fields, unobserved values and anonymous sync",{skip:!live},async()=>{const today=new Date().toISOString().slice(0,10);await role(client);await assert.rejects(sync(today,{heart_rate:60,observed_types:[]}),/Unsupported/);await sync(today,{steps:100,observed_types:["sleep"]});await db.query("reset role");const sparse=(await db.query("select steps from client_health_daily where client_id=$1 and day=$2",[client,today])).rows[0];assert.equal(sparse.steps,null);await role(client,"anon");await assert.rejects(sync(today,{steps:1,observed_types:["steps"]}));});
test("Health resync replaces the daily snapshot without inventing newly missing types",{skip:!live},async()=>{const today=new Date().toISOString().slice(0,10);await role(client);await sync(today,{steps:5000,sleep_hours:7,observed_types:["steps","sleep"]});await sync(today,{steps:6000,observed_types:["steps"]});await db.query("reset role");const row=(await db.query("select * from client_health_daily where client_id=$1 and day=$2",[client,today])).rows[0];assert.equal(row.steps,6000);assert.equal(row.sleep_hours,null);assert.deepEqual(row.observed_types,["steps"]);});
