const {test}=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs");
const sql=fs.readFileSync("packages/db/migrations/0083_apple_health_daily.sql","utf8"),api=fs.readFileSync("app/api/mobile/health/route.ts","utf8"),swift=fs.readFileSync("ios/IMSFitness/HealthStore.swift","utf8"),card=fs.readFileSync("components/fuel/apple-health-card.tsx","utf8");
test("Apple Health evidence is client-controlled and staff read-only",()=>{assert.match(sql,/actor\.role='client' and actor\.id=client_health_daily\.client_id/);assert.match(sql,/Active client authorization required/);assert.match(sql,/grant execute on function public\.sync_client_health_day\(date,jsonb\) to authenticated/);});
test("Health sync accepts a narrow nonclinical daily summary only",()=>{for(const key of ["steps","active_energy_kcal","exercise_minutes","sleep_hours","weight_lb","workout_minutes","workout_count"])assert.match(sql,new RegExp(key));for(const forbidden of ["heart_rate","dietary","clinical","diagnosis"])assert.doesNotMatch(sql,new RegExp("'"+forbidden+"'"));});
test("missing permissions cannot become zero evidence",()=>{assert.match(sql,/case when 'steps'=any\(types\).*else null end/s);assert.match(sql,/case when 'sleep'=any\(types\).*else null end/s);assert.match(card,/Missing Health data is never treated as zero or failure/);});
test("Health endpoint requires authenticated session and delegates bounds to RPC",()=>{assert.match(api,/if\(!user\)/);assert.match(api,/sync_client_health_day/);assert.match(api,/No values were inferred/);});
test("iOS requests read-only granular HealthKit authorization",()=>{assert.match(swift,/requestAuthorization\(toShare:\[\],read:readTypes\)/);assert.match(swift,/stepCount/);assert.match(swift,/activeEnergyBurned/);assert.match(swift,/appleExerciseTime/);assert.match(swift,/bodyMass/);assert.match(swift,/sleepAnalysis/);assert.match(swift,/workoutType/);});
test("iOS sends only days with available evidence",()=>{assert.match(swift,/guard !available\.isEmpty else\{return\}/);assert.match(swift,/observed_types/);});
test("Fuel UI preserves Bod Pod as anchor and blocks automatic Watch/BIA prescription",()=>{assert.match(card,/Bod Pod remains the IMS body-composition anchor/);assert.match(card,/does not turn Watch calories or BIA estimates into automatic nutrition changes/);});

test("native Health sync and embedded login share one Coach OS origin",()=>{const session=fs.readFileSync("ios/IMSFitness/SessionStore.swift","utf8"),web=fs.readFileSync("ios/IMSFitness/WebSurface.swift","utf8");assert.match(session,/IMS_BASE_URL/);assert.match(web,/SessionStore\.apiBaseURL/);assert.doesNotMatch(web,/IMS_WEB_BASE_URL/);assert.match(session,/adoptWebCookies/);});

test("Health sync rejects empty/value-less evidence and oversized or impossible dates",()=>{assert.match(sql,/Empty Health summaries are not evidence/);assert.match(sql,/Health summary exceeds size limit/);assert.match(sql,/jsonb_typeof\(p_payload->\'steps\'\)/);assert.match(api,/content-length/);assert.match(api,/TextEncoder/);assert.match(api,/toISOString\(\)\.slice\(0,10\)===value/);});

test("Health coaching card labels stale evidence and noncalendar sample windows",()=>{const card=fs.readFileSync("components/fuel/apple-health-card.tsx","utf8");assert.match(card,/72 hours old/);assert.match(card,/not a guaranteed seven-calendar-day window/);assert.match(card,/Do not treat it as current activity or recovery context/);});
