const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),ts=require('typescript');
const root=path.join(__dirname,'..');
function load(file,deps){const out={};new Function('require','exports',ts.transpileModule(fs.readFileSync(path.join(root,file),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(name=>{if(!(name in deps))throw Error('Unexpected dependency '+name);return deps[name];},out);return out;}
const recurring=load('lib/recurring.ts',{}),pacific=load('lib/time/pacific.ts',{'../recurring':recurring}),context=load('lib/schedule/booking-context.ts',{'@/lib/recurring':recurring,'@/lib/time/pacific':pacific}),commands=load('lib/schedule/commands.ts',{'./booking-context':context,'@/lib/recurring':recurring});
const id='11111111-1111-4111-8111-111111111111',envelope={request_id:id,command:{action:'cancel_series',series_id:id,expected_revision:1,confirmed:true,reason:'Synthetic administrative change'}};
function harness(options={}){let calls=0;const db={auth:{getUser:async()=>({data:{user:options.anonymous?null:{id}}})},rpc:async(name,args)=>{calls++;assert.equal(name,'execute_booking_command');assert.equal(args.p_request_id,id);return options.failure?{error:options.failure}:{data:options.badReceipt?{}:{ok:true,request_id:id,action:'cancel_series',series_id:id,created:0,cancelled:3,charged:false,deduped:false}};}};const route=load('lib/schedule/command-route.ts',{'next/server':{NextResponse:{json:(body,init)=>({body,...init})}},'@/lib/supabase/server':{createClient:async()=>db},'@/lib/media/request':{smallJson:async req=>req.body},'./commands':commands}).bookingCommandRoute;return{run:(body=envelope,origin='https://example.test')=>route({body,headers:{get:()=>origin},nextUrl:{origin:'https://example.test'}}),calls:()=>calls};}
test('booking route denies cross-origin, anonymous and unconfirmed requests before any command',async()=>{let h=harness();assert.equal((await h.run(envelope,'https://other.test')).status,403);assert.equal(h.calls(),0);h=harness({anonymous:true});assert.equal((await h.run()).status,401);assert.equal(h.calls(),0);h=harness();assert.equal((await h.run({...envelope,command:{...envelope.command,confirmed:false}})).status,400);assert.equal(h.calls(),0);});
test('booking receipt is validated and never cacheable',async()=>{const h=harness(),result=await h.run();assert.equal(result.status,200);assert.equal(result.body.cancelled,3);assert.equal(result.headers['Cache-Control'],'private, no-store');assert.equal(h.calls(),1);assert.equal((await harness({badReceipt:true}).run()).status,503);});
test('database authorization and conflict errors stay failures; unknown errors remain uncertain',async()=>{for(const [code,status] of [['42501',403],['P0002',404],['40001',409],['23P01',409],['22023',409],['PGRST202',503]]){const h=harness({failure:{code,message:'Synthetic failure'}});assert.equal((await h.run()).status,status);assert.equal(h.calls(),1);}});
