const {test,before,after}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{randomUUID}=require('node:crypto');
const live=process.env.IMS_TEST_DATABASE_URL;let db,admin,name,peerUrl;const owner=randomUUID(),other=randomUUID(),disabled=randomUUID();
const today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Los_Angeles'}).format(new Date());
function days(date,n){const d=new Date(date+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10);}
before(async()=>{
 if(live){const url=new URL(live);if(!['localhost','127.0.0.1'].includes(url.hostname)||url.pathname!='/ims_ci')throw Error('Only isolated local ims_ci permitted');const {Client}=require('pg');admin=new Client({connectionString:live});await admin.connect();name='ims_calendar_'+randomUUID().replaceAll('-','');await admin.query('create database "'+name+'"');url.pathname='/'+name;peerUrl=url.toString();const pg=new Client({connectionString:peerUrl});await pg.connect();db={exec:s=>pg.query(s),query:(s,p)=>pg.query(s,p),close:()=>pg.end()};}else{const {PGlite}=await import('@electric-sql/pglite');db=new PGlite();}
 await db.exec(`create schema auth;do $$begin create role authenticated;exception when duplicate_object then null;end$$;do $$begin create role anon;exception when duplicate_object then null;end$$;do $$begin create role service_role;exception when duplicate_object then null;end$$;
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 grant usage on schema public,auth to authenticated,anon,service_role;
 create type session_type as enum('training','assessment');create type service_type as enum('training');
 create table profiles(id uuid primary key,full_name text,role text,deleted_at timestamptz);
 create table clients(id uuid primary key references profiles(id),primary_trainer_id uuid references profiles(id));
 create table sessions(id uuid primary key default gen_random_uuid(),client_id uuid references clients(id),trainer_id uuid references profiles(id),scheduled_at timestamptz not null,duration_minutes int not null,session_type session_type,service_type service_type,location text,status text,notes_pre text,notes_post text,completed_at timestamptz,cancelled_at timestamptz,cancelled_by uuid,cancellation_reason text,updated_at timestamptz default clock_timestamp());
 create table class_occurrences(id uuid primary key default gen_random_uuid(),trainer_id uuid,starts_at timestamptz,ends_at timestamptz,status text);
 create table trainer_time_blocks(id uuid primary key default gen_random_uuid(),trainer_id uuid,starts_at timestamptz,ends_at timestamptz);
 create table audit_logs(id uuid primary key,actor_id uuid,action text,entity_type text,entity_id uuid,changes jsonb);
 create function set_updated_at() returns trigger language plpgsql as $$begin new.updated_at:=clock_timestamp();return new;end$$;
 create function public.set_session_completion(p_id uuid,p_complete boolean,p_service text) returns jsonb language plpgsql as $$begin update sessions set status='completed',completed_at=now() where id=p_id;return jsonb_build_object('counter',1);end$$;
 create trigger session_updated before update on sessions for each row execute function set_updated_at();
 insert into profiles values('${owner}','Synthetic Owner','owner',null),('${other}','Unrelated Trainer','trainer',null),('${disabled}','Disabled Owner','owner',now());
 grant select on profiles,clients,sessions,class_occurrences,trainer_time_blocks to authenticated;
 `);
 await db.exec(fs.readFileSync(path.join(__dirname,'../packages/db/migrations/0012_recurring_series.sql'),'utf8'));
 await db.exec('grant all on all tables in schema public to service_role;grant all on recurring_series to authenticated;');
 for(let i=0;i<2;i++)await db.exec(fs.readFileSync(path.join(__dirname,'../packages/db/migrations/0092_calendar_booking_controls.sql'),'utf8'));
});
after(async()=>{await db?.close();if(admin){try{await admin.query('drop database "'+name+'"');}finally{await admin.end();}}});
async function raw(sql,p=[]){await db.exec('reset role');return(await db.query(sql,p)).rows;}
async function role(id=owner,connection=db,as='authenticated'){await connection.query('reset role;set role '+as);await connection.query("select set_config('request.jwt.claim.sub',$1,false)",[id??'']);}
async function subject(){const c=randomUUID(),t=randomUUID();await raw("insert into profiles values($1,'Synthetic Coach','trainer',null),($2,'Synthetic Client','client',null)",[t,c]);await raw('insert into clients values($1,$2)',[c,t]);return{c,t};}
function create(s,patch={}){const start=days(today,2);return{action:'create_series',client_id:s.c,trainer_id:s.t,start_date:start,end_date:days(start,28),interval_weeks:1,duration_minutes:60,slots:[{weekday:new Date(start+'T12:00:00Z').getUTCDay(),time:'09:15'}],location:'Synthetic room',notes:'Synthetic prep only',confirmed:true,reason:'Isolated booking verification',...patch};}
async function run(command,id=randomUUID(),connection=db){return(await connection.query('select public.execute_booking_command($1,$2::jsonb) result',[id,JSON.stringify(command)])).rows[0].result;}
async function seeded(s,patch={}){const command=create(s,patch);await role();const result=await run(command);return{command,result};}
const code=expected=>error=>error.code===expected;
test('new recurring command creates scheduled evidence only, with bounded end and preserved prep notes',async()=>{const s=await subject(),{result}=await seeded(s);assert.equal(result.created,5);assert.equal(result.charged,false);const rows=await raw('select * from sessions where recurring_series_id=$1 order by scheduled_at',[result.series_id]);assert.equal(rows.length,5);assert.ok(rows.every(r=>r.status==='scheduled'&&r.completed_at===null&&r.notes_pre==='Synthetic prep only'));assert.equal((await raw("select * from audit_logs where entity_id=$1 and action='schedule.create_series'",[result.series_id])).length,1);});
test('identical retries dedupe; a changed command cannot reuse an ID',async()=>{const s=await subject(),command=create(s),id=randomUUID();await role();const a=await run(command,id),b=await run(command,id);assert.equal(a.series_id,b.series_id);assert.equal(b.deduped,true);await assert.rejects(run({...command,notes:'Changed'},id),code('22023'));assert.equal((await raw('select * from recurring_series where client_id=$1',[s.c])).length,1);});
test('owner and assigned trainer are allowed; client, unrelated, disabled and missing actors are denied',async()=>{for(const who of [null,other,disabled,'client']){const s=await subject();await role(who==='client'?s.c:who);await assert.rejects(run(create(s)),code('42501'));}const s=await subject();await role(s.t);assert.equal((await run(create(s))).ok,true);});
test('direct series mutations and receipt access cannot bypass commands',async()=>{const s=await subject(),{result}=await seeded(s);await role(s.t);for(const sql of ["update recurring_series set status='cancelled' where id='"+result.series_id+"'",'delete from recurring_series','truncate recurring_series','select * from booking_command_receipts',"select fill_recurring_window('"+result.series_id+"',current_date)"])await assert.rejects(db.query(sql),code('42501'));await role(null,db,'anon');await assert.rejects(run(create(s)),code('42501'));});
test('recurring read scope excludes unrelated trainers and disabled accounts',async()=>{const s=await subject(),{result}=await seeded(s);for(const actor of [other,disabled]){await role(actor);assert.equal((await db.query('select * from recurring_series where id=$1',[result.series_id])).rows.length,0);}await role(s.t);assert.equal((await db.query('select * from recurring_series where id=$1',[result.series_id])).rows.length,1);});
test('invalid slots and impossible daylight-saving times fail without partial series',async()=>{const s=await subject();for(const slots of [[],[{weekday:1,time:'25:00'}],[{weekday:1.5,time:'09:00'}],[{weekday:1,time:'09:00'},{weekday:1,time:'09:00'}]]){await role();await assert.rejects(run(create(s,{slots})),code('22023'));}assert.equal((await raw('select * from recurring_series where client_id=$1',[s.c])).length,0);await assert.rejects(db.query("select booking_pacific_instant('2027-03-14','02:30')"),code('22023'));const repeated=(await raw("select booking_pacific_instant('2026-11-01','01:30')::text t"))[0].t;assert.match(repeated,/2026-11-01 08:30/);});
test('every-other-week pattern stays anchored to start week and stops at end',async()=>{const s=await subject(),{result}=await seeded(s,{interval_weeks:2});assert.equal(result.created,3);const dates=(await raw('select (scheduled_at at time zone \'America/Los_Angeles\')::date::text d from sessions where recurring_series_id=$1 order by scheduled_at',[result.series_id])).map(r=>r.d);assert.deepEqual(dates,[2,16,30].map(n=>days(today,n)));});
test('session, class and unavailable-block conflicts roll back the entire new series',async()=>{for(const kind of ['session','class','block']){const s=await subject(),start=days(today,2);const time=(await raw('select booking_pacific_instant($1,\'09:15\') t',[start]))[0].t;if(kind==='session')await raw("insert into sessions(client_id,trainer_id,scheduled_at,duration_minutes,status,session_type) values($1,$2,$3,60,'scheduled','training')",[s.c,s.t,time]);else if(kind==='class')await raw("insert into class_occurrences(trainer_id,starts_at,ends_at,status) values($1,$2,$2::timestamptz+interval '1 hour','scheduled')",[s.t,time]);else await raw("insert into trainer_time_blocks(trainer_id,starts_at,ends_at) values($1,$2,$2::timestamptz+interval '1 hour')",[s.t,time]);await role();await assert.rejects(run(create(s)),code('23P01'));assert.equal((await raw('select * from recurring_series where client_id=$1',[s.c])).length,0);}});
test('a client cannot be booked with two coaches at the same instant, including outside the recurring command',async()=>{const s=await subject(),{result}=await seeded(s),time=(await raw('select scheduled_at from sessions where recurring_series_id=$1 order by scheduled_at limit 1',[result.series_id]))[0].scheduled_at;await assert.rejects(db.query("insert into sessions(client_id,trainer_id,scheduled_at,duration_minutes,status,session_type) values($1,$2,$3,30,'scheduled','training')",[s.c,other,time]),code('23P01'));});
test('future replacement is atomic, preserves past, and rejects stale revisions',async()=>{const s=await subject(),{command,result}=await seeded(s);const past=randomUUID();await raw("insert into sessions(id,client_id,trainer_id,scheduled_at,duration_minutes,status,session_type,completed_at,recurring_series_id) values($1,$2,$3,now()-interval '10 days',60,'completed','training',now()-interval '10 days',$4)",[past,s.c,s.t,result.series_id]);const replacement={...command,action:'replace_series',series_id:result.series_id,expected_revision:1,slots:[{...command.slots[0],time:'11:45'}]};await role();const next=await run(replacement);assert.equal(next.created,5);assert.equal(next.cancelled,5);assert.notEqual(next.series_id,result.series_id);assert.equal((await raw('select status from sessions where id=$1',[past]))[0].status,'completed');await role();await assert.rejects(run(replacement),code('40001'));});
test('replacement conflict keeps the old rule and bookings intact',async()=>{const s=await subject(),{command,result}=await seeded(s),time=(await raw("select booking_pacific_instant($1,'11:45') t",[command.start_date]))[0].t;await raw("insert into trainer_time_blocks(trainer_id,starts_at,ends_at) values($1,$2,$2::timestamptz+interval '1 hour')",[s.t,time]);await role();await assert.rejects(run({...command,action:'replace_series',series_id:result.series_id,expected_revision:1,slots:[{...command.slots[0],time:'11:45'}]}),code('23P01'));assert.equal((await raw('select status from recurring_series where id=$1',[result.series_id]))[0].status,'active');assert.equal((await raw("select * from sessions where recurring_series_id=$1 and status='scheduled'",[result.series_id])).length,5);});
test('single occurrence reschedule preserves repeat exception and retries safely',async()=>{const s=await subject(),{result}=await seeded(s),original=(await raw('select *, updated_at::text as stamp from sessions where recurring_series_id=$1 order by scheduled_at limit 1',[result.series_id]))[0],time=new Date(Date.parse(original.scheduled_at)+2*3600000).toISOString();const command={action:'reschedule',session_id:original.id,expected_updated_at:original.stamp,scheduled_at:time,duration_minutes:45,confirmed:true,reason:'Move only this synthetic occurrence'},id=randomUUID();await role();await run(command,id);assert.equal((await run(command,id)).deduped,true);const updated=(await raw('select * from sessions where id=$1',[original.id]))[0];assert.equal(new Date(updated.recurring_original_at).toISOString(),new Date(original.scheduled_at).toISOString());assert.equal(updated.duration_minutes,45);await raw('update recurring_series set generated_until=start_date-1 where id=$1',[result.series_id]);await raw('select fill_recurring_window($1,$2)',[result.series_id,days(today,30)]);assert.equal((await raw('select * from sessions where recurring_series_id=$1',[result.series_id])).length,5);});
test('exceptions block bulk rewrite, while explicit owner single cancellation stays nonbilling',async()=>{const s=await subject(),{command,result}=await seeded(s),one=(await raw('select *, updated_at::text as stamp from sessions where recurring_series_id=$1 order by scheduled_at limit 1',[result.series_id]))[0],cancel={action:'cancel_occurrence',session_id:one.id,expected_updated_at:one.stamp,confirmed:true,reason:'Owner administrative correction'};await role(s.t);await assert.rejects(run(cancel),code('42501'));await role();assert.equal((await run(cancel)).charged,false);await assert.rejects(run({...command,action:'replace_series',series_id:result.series_id,expected_revision:1}),/Future exceptions/);});
test('series cancellation touches future scheduled and confirmed only, leaving audit receipts immutable',async()=>{const s=await subject(),{result}=await seeded(s);await raw("update sessions set status='confirmed' where id=(select id from sessions where recurring_series_id=$1 limit 1)",[result.series_id]);await role();const receipt=await run({action:'cancel_series',series_id:result.series_id,expected_revision:1,confirmed:true,reason:'Cancel future synthetic series'});assert.equal(receipt.cancelled,5);assert.equal((await raw('select fill_recurring_window($1,$2) n',[result.series_id,days(today,60)]))[0].n,0);await assert.rejects(db.query('update booking_command_receipts set result=result'),code('42501'));});
test('simultaneous identical PostgreSQL commands create one series and one receipt',{skip:!live},async()=>{const s=await subject(),command=create(s),id=randomUUID(),{Client}=require('pg'),peers=[new Client({connectionString:peerUrl}),new Client({connectionString:peerUrl})];try{await Promise.all(peers.map(async p=>{await p.connect();await role(owner,p);}));const outcomes=await Promise.all(peers.map(p=>run(command,id,p)));assert.deepEqual(outcomes.map(r=>r.deduped).sort(),[false,true]);assert.equal((await raw('select * from recurring_series where client_id=$1',[s.c])).length,1);}finally{await Promise.all(peers.map(p=>p.end()));}});

function single(s,id=randomUUID()){return{request_id:id,mode:'schedule',client_id:s.c,trainer_id:s.t,scheduled_at:new Date(Date.now()+3*86400000).toISOString(),duration_minutes:60,session_type:'training',service_type:'training',notes_pre:'Synthetic booking',notes_post:null};}
async function singleRun(body){return(await db.query('select create_staff_session($1,$2) result',[body.request_id,JSON.stringify(body)])).rows[0].result;}
test('one-time creation closes self-trainer and assigned-other-trainer authorization bypasses',async()=>{const s=await subject();await role(other);await assert.rejects(singleRun({...single(s),trainer_id:other}),code('42501'));await role(s.t);await assert.rejects(singleRun({...single(s),trainer_id:other}),code('42501'));assert.equal((await singleRun(single(s))).ok,true);});
test('one-time receipt dedupes and rejects changed notes or switching schedule to completed log',async()=>{const s=await subject(),body=single(s);await role();const one=await singleRun(body),two=await singleRun(body);assert.equal(one.session_id,two.session_id);assert.equal(two.deduped,true);await assert.rejects(singleRun({...body,notes_pre:'Changed'}),code('22023'));await assert.rejects(singleRun({...body,mode:'log'}),code('22023'));assert.equal((await raw('select status from sessions where id=$1',[body.request_id]))[0].status,'scheduled');});
test('one-time creation is covered by cross-calendar conflicts and safe missing-receipt handling',async()=>{const s=await subject(),body=single(s);await role();await singleRun(body);await assert.rejects(singleRun({...body,request_id:randomUUID()}),code('23P01'));const legacy=single(s);legacy.scheduled_at=new Date(Date.now()+4*86400000).toISOString();await raw("insert into sessions(id,client_id,trainer_id,scheduled_at,duration_minutes,status,session_type) values($1,$2,$3,$4,60,'scheduled','training')",[legacy.request_id,s.c,s.t,legacy.scheduled_at]);await role();await assert.rejects(singleRun(legacy),/Original request receipt unavailable/);});
