const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),ts=require('typescript');const root=path.join(__dirname,'..');
function load(file,deps={},globals={}){const out={},code=ts.transpileModule(fs.readFileSync(path.join(root,file),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText;new Function('require','exports',...Object.keys(globals),code)(name=>{if(name in deps)return deps[name];throw Error('Unexpected dependency '+name)},out,...Object.values(globals));return out;}
const recurring=load('lib/recurring.ts'),pacific=load('lib/time/pacific.ts',{'../recurring':recurring}),context=load('lib/schedule/booking-context.ts',{'@/lib/recurring':recurring,'@/lib/time/pacific':pacific}),commands=load('lib/schedule/commands.ts',{'./booking-context':context,'@/lib/recurring':recurring});
const coach='11111111-1111-4111-8111-111111111111',client='22222222-2222-4222-8222-222222222222',requestId='33333333-3333-4333-8333-333333333333';
const series=()=>({action:'create_series',client_id:client,trainer_id:coach,start_date:'2026-10-05',end_date:'2026-11-02',duration_minutes:60,interval_weeks:1,slots:[{weekday:1,time:'09:15'}],location:'Synthetic studio',notes:'',reason:'Synthetic reviewed booking',confirmed:true});
test('tap-to-book URL carries exact date, quarter-hour and trainer with no return-URL injection',()=>{const href=context.bookingHref('2026-10-05','09:15',coach),q=new URL(href,'https://example.test').searchParams;assert.equal(q.get('time'),'09:15');assert.equal(q.get('date'),'2026-10-05');assert.equal(q.get('trainer_id'),coach);assert.equal(q.get('mode'),'schedule');assert.throws(()=>context.bookingHref('2026-02-30','09:00',coach));assert.throws(()=>context.bookingHref('2026-10-05','29:00',coach));assert.doesNotMatch(context.calendarHref('2026-10-05','https://evil.test'),/evil/);});
test('selected Pacific wall time does not depend on browser timezone; spring gaps are rejected',()=>{assert.equal(context.bookingWallClock('2026-11-02','09:15'),'2026-11-02T09:15');assert.throws(()=>context.bookingWallClock('2027-03-14','02:30'));assert.equal(recurring.ptWallClockToUtc('2026-11-01','01:30').toISOString(),'2026-11-01T08:30:00.000Z');});
test('actual-minute placement preserves 9:15 and 45-minute sessions instead of rounding to half hours',()=>{const e={id:'a',trainerId:coach,startsAt:'2026-10-05T16:15:00Z',endsAt:'2026-10-05T17:00:00Z',kind:'session'};assert.deepEqual(context.eventPosition(e,'2026-10-05',270,1140),{top:285,height:45,start:555,end:600});assert.equal(context.slotOccupied([e],coach,'2026-10-05',570),true);assert.equal(context.slotOccupied([e],coach,'2026-10-05',600),false);});
test('overlapping event cards remain individually accessible, adjacent events share a lane',()=>{const make=(id,from,to)=>({id,startsAt:`2026-10-05T${from}:00Z`,endsAt:`2026-10-05T${to}:00Z`});const lanes=context.eventLanes([make('a','16:00','17:00'),make('b','16:30','17:30'),make('c','17:30','18:00')]);assert.equal(lanes.get('a').lanes,2);assert.notEqual(lanes.get('a').lane,lanes.get('b').lane);assert.equal(lanes.get('c').lanes,1);});
test('recurrence preview is bounded, future-only and supports multiweek periods across DST',()=>{const built=recurring.buildSeriesOccurrences({slots:[{weekday:1,time:'09:15'}],startDate:'2026-10-26',endDate:'2026-11-23',intervalWeeks:2,now:new Date('2026-10-20T15:00:00Z')});assert.deepEqual(built.occurrences,['2026-10-26T16:15:00.000Z','2026-11-09T17:15:00.000Z','2026-11-23T17:15:00.000Z']);assert.throws(()=>recurring.buildSeriesOccurrences({slots:[{weekday:1,time:'09:15'},{weekday:1,time:'09:15'}],startDate:'2026-10-26'}));});
test('command parser rejects unsupported fields, malformed slots, stale identity and unconfirmed writes',()=>{const envelope={request_id:requestId,command:series()};assert.ok(commands.parseBookingEnvelope(envelope));for(const patch of [{confirmed:false},{interval_weeks:0},{duration_minutes:NaN},{end_date:'2026-02-30'},{slots:[{weekday:1.5,time:'09:00'}]},{charge:true},{notes:undefined}])assert.throws(()=>commands.parseBookingEnvelope({...envelope,command:{...series(),...patch}}));});
function hookHarness(file,exportName,deps){const slots=[];let cursor=0,handler=async()=>{throw Error('offline')};const react={useRef(value){const i=cursor++;if(!slots[i])slots[i]={current:value};return slots[i]},useState(value){const i=cursor++;if(!(i in slots))slots[i]=typeof value==='function'?value():value;return[slots[i],v=>{slots[i]=typeof v==='function'?v(slots[i]):v}];}};const hook=load(file,{react,...deps},{fetch:(...args)=>handler(...args),crypto:{randomUUID:()=>requestId}})[exportName];return{render(){cursor=0;return hook()},setHandler(h){handler=h}};}
const response=(body,status=200)=>({ok:status<300,status,json:async()=>body});
test('recurring save retains exact request after network and auth ambiguity, without duplicate taps',async()=>{const h=hookHarness('components/schedule/use-booking-command.tsx','useBookingCommand',{'@/lib/schedule/commands':commands}),sent=[];h.setHandler(async(_,o)=>{sent.push(o.body);throw Error('network')});await h.render().submit(series(),'Synthetic reason');assert.ok(h.render().uncertain);await h.render().submit({...series(),notes:'changed'},'Changed reason');assert.equal(sent.length,1);h.setHandler(async(_,o)=>{sent.push(o.body);return response({},403)});await h.render().retry();assert.ok(h.render().uncertain);h.setHandler(async(_,o)=>{sent.push(o.body);return response({ok:true,request_id:requestId,action:'create_series',series_id:coach,created:5,cancelled:0,charged:false,deduped:true})});await h.render().retry();assert.equal(new Set(sent).size,1);assert.ok(h.render().result);});
test('one-time creation also retains identity after ambiguous write and validates the session receipt',async()=>{const h=hookHarness('components/schedule/use-session-create.tsx','useSessionCreate',{'@/lib/schedule/booking-context':context}),sent=[];const input={mode:'schedule',client_id:client,trainer_id:coach};h.setHandler(async(_,o)=>{sent.push(o.body);return response({ok:true,session_id:'wrong'})});await h.render().submit(input);assert.ok(h.render().uncertain);h.setHandler(async(_,o)=>{sent.push(o.body);return response({ok:true,session_id:requestId})});await h.render().retry();assert.equal(h.render().id,requestId);assert.equal(new Set(sent).size,1);});
test('grid uses document scrolling, native touch and no per-slot prefetch, with no hard minimum width',()=>{const shell=fs.readFileSync('components/layout/app-shell.tsx','utf8'),grid=fs.readFileSync('components/schedule/day-grid.tsx','utf8'),css=fs.readFileSync('components/schedule/schedule-grid.css','utf8');assert.doesNotMatch(shell,/flex-1 overflow-y-auto/);assert.match(shell,/min-w-0 flex-1/);assert.match(grid,/prefetch=\{false\}/);assert.doesNotMatch(grid,/onTouchMove|onWheel|preventDefault|overflow-x-auto|min-w-\[/);assert.match(css,/touch-action: pan-y pinch-zoom/);});
test('rolling extension continues other rules and reports failed series without claiming full success',async()=>{const list=[{id:coach,status:'active',start_date:'2026-01-01'},{id:client,status:'active',start_date:'2026-01-01'}],svc={from(){const q={select:()=>q,eq:async()=>({data:list,error:null})};return q;},rpc:async(_,args)=>args.p_series_id===coach?{error:{code:'23P01'}}:{data:2}};assert.deepEqual(await recurring.generateAllActiveSeries(svc),{series:2,created:2,failed:[coach]});});

// Exercise the real grid, not only the source spelling of its delegated links.
test('rendered event links keep session identity and package context after calendar extraction',()=>{
 const jsx={jsx:(type,props)=>({type,props}),jsxs:(type,props)=>({type,props})};
 const {ScheduleDayGrid}=load('components/schedule/day-grid.tsx',{'next/link':{default:'Link'},'@/lib/schedule/booking-context':context,'@/lib/time/pacific':pacific,'./schedule-grid.css':{},'react/jsx-runtime':jsx});
 const event={id:requestId,trainerId:coach,startsAt:'2026-10-05T16:15:00Z',endsAt:'2026-10-05T17:00:00Z',label:'Synthetic client',detail:'Training · 6 sessions remaining',href:'/sessions/'+requestId,kind:'session'};
 const tree=ScheduleDayGrid({date:'2026-10-05',trainers:[{id:coach,full_name:'Synthetic coach'}],events:[event]}),links=[];
 function visit(node){if(!node)return;if(Array.isArray(node))return node.forEach(visit);if(typeof node==='object'){if(node.type==='Link')links.push(node.props);visit(node.props?.children);}}
 visit(tree);const link=links.find(p=>p.href===event.href);assert.ok(link);assert.match(link['aria-label'],/6 sessions remaining/);assert.equal(link.prefetch,false);
 const slot=links.find(p=>p.href.includes('time=10%3A00'));assert.ok(slot);assert.match(slot.href,new RegExp('trainer_id='+coach));
});
