import test from "node:test";import assert from "node:assert/strict";import {readFileSync} from "node:fs";
test("classes are integrated but private until explicitly published",()=>{const migration=readFileSync("packages/db/migrations/0048_group_classes.sql","utf8"),admin=readFileSync("app/api/classes/admin/route.ts","utf8");assert.match(migration,/visibility text not null default 'private'/);assert.match(migration,/clients read published class templates/);assert.match(admin,/visibility:"private"/);assert.doesNotMatch(admin,/visibility:"published"/);assert.match(admin,/createServiceClient/);});
test("class booking is capacity safe and waitlists atomically",()=>{const migration=readFileSync("packages/db/migrations/0048_group_classes.sql","utf8"),route=readFileSync("app/api/classes/book/route.ts","utf8");assert.match(migration,/for update of o/);assert.match(migration,/v_status:=case when v_count<v_capacity then 'booked' else 'waitlisted'/);assert.match(migration,/order by booked_at,id limit 1 for update skip locked/);assert.match(route,/book_class/);assert.match(route,/cancel_class_booking/);assert.match(migration,/grant select on public.class_templates,public.class_occurrences,public.class_enrollments to authenticated/);assert.doesNotMatch(migration,/grant (?:insert|update|delete|all) on public.class_/i);});
test("classes stay separate from personal-training packages and payroll",()=>{const migration=readFileSync("packages/db/migrations/0048_group_classes.sql","utf8"),manage=readFileSync("app/classes/manage/page.tsx","utf8");assert.doesNotMatch(migration,/plans|trainer_compensation_rules|payments/);assert.match(manage,/Class credits and trainer compensation remain separate systems/);assert.match(manage,/does not announce a class, charge a client, consume a training package, or create trainer payroll/);});
test("class operations connect booking schedule staff and client surfaces",()=>{const booking=readFileSync("app/book/page.tsx","utf8"),schedule=readFileSync("app/schedule/page.tsx","utf8"),sidebar=readFileSync("components/layout/app-sidebar.tsx","utf8"),mobile=readFileSync("components/layout/staff-bottom-nav.tsx","utf8");assert.match(booking,/Browse IMS classes/);assert.match(schedule,/class_occurrences/);assert.match(schedule,/Group coaching today/);assert.match(sidebar,/\/classes\/manage/);assert.match(mobile,/\/classes\/manage/);});

test("class attendance is scoped, audited, and financially inert",()=>{const api=readFileSync("app/api/classes/attendance/route.ts","utf8"),roster=readFileSync("app/classes/manage/[id]/page.tsx","utf8");assert.match(api,/assigned coach or owner/);assert.match(api,/recordAudit/);assert.match(api,/class.attendance_marked/);assert.doesNotMatch(api,/plans|trainer_compensation_rules|payments|checkout/);assert.match(roster,/does not automatically consume a personal-training package or calculate trainer payroll/);});

test("recurring classes and access products stay bounded and separate",()=>{const migration=readFileSync("packages/db/migrations/0049_class_series_access.sql","utf8"),series=readFileSync("app/api/classes/series/route.ts","utf8"),client=readFileSync("components/classes/client-class-access.tsx","utf8");assert.match(migration,/class_series/);assert.match(migration,/class_access_products/);assert.match(migration,/Access is intentionally not consumed by class booking yet/);assert.match(series,/rows.length<30/);assert.match(series,/180/);assert.match(client,/Booking does not consume credits/);});

test("class credit ledger is immutable and not yet an automatic charge path",()=>{const ledger=readFileSync("packages/db/migrations/0050_class_credit_ledger.sql","utf8");assert.match(ledger,/class_credit_ledger/);assert.match(ledger,/unique index.*enrollment_attendance/i);assert.match(ledger,/grant select/);assert.doesNotMatch(ledger,/grant (?:insert|update|delete|all)/i);assert.match(ledger,/Future entitlement commands must transact ledger \+ balance \+ attendance together/);});

test("class compensation can never be inferred from class pricing",()=>{const migration=readFileSync("packages/db/migrations/0053_class_compensation_rules.sql","utf8");assert.match(migration,/flat_class/);assert.match(migration,/per_attendee/);assert.match(migration,/owner reads class compensation rules/);assert.match(migration,/Calculation\/submission is intentionally absent/);assert.doesNotMatch(migration,/payments|price_cents|class_access_products/);});

test("client progress counts recorded class attendance without inventing outcomes",()=>{const page=readFileSync("app/progress/page.tsx","utf8");assert.match(page,/class_enrollments/);assert.match(page,/status","attended/);assert.match(page,/classes attended · recorded attendance only/);assert.doesNotMatch(page,/calories|strength gained|mobility improved|class progress score/i);});

test("owner operating system includes group coaching without merging class finance into PT",()=>{const page=readFileSync("app/operating-system/page.tsx","utf8");assert.match(page,/Group coaching loop/);assert.match(page,/class_occurrences/);assert.match(page,/Credits and payroll remain separate/);});

test("class growth attribution remains explicit rather than inferred",()=>{const migration=readFileSync("packages/db/migrations/0055_class_growth_attribution.sql","utf8"),booking=readFileSync("app/api/classes/book/route.ts","utf8");assert.match(migration,/Source is null unless an explicit, auditable workflow sets it later/);assert.doesNotMatch(booking,/source_type|source_reference|campaign_id/);});
