import test from "node:test";import assert from "node:assert/strict";import {readFileSync} from "node:fs";
test("classes are integrated but private until explicitly published",()=>{const migration=readFileSync("packages/db/migrations/0048_group_classes.sql","utf8"),admin=readFileSync("app/api/classes/admin/route.ts","utf8");assert.match(migration,/visibility text not null default 'private'/);assert.match(migration,/clients read published class templates/);assert.match(admin,/visibility:"private"/);assert.doesNotMatch(admin,/visibility:"published"/);assert.match(admin,/createServiceClient/);});
test("prototype booking remains present but is not a verified launch path",()=>{const migration=readFileSync("packages/db/migrations/0048_group_classes.sql","utf8"),route=readFileSync("app/api/classes/book/route.ts","utf8"),guard=readFileSync("packages/db/migrations/0057_class_prelaunch_boundary.sql","utf8");assert.match(migration,/for update of o/);assert.match(route,/book_class/);assert.match(route,/cancel_class_booking/);assert.match(route,/CLASS_PRELAUNCH/);assert.match(guard,/revoke execute on function public.book_class/);assert.match(migration,/grant select on public.class_templates,public.class_occurrences,public.class_enrollments to authenticated/);assert.doesNotMatch(migration,/grant (?:insert|update|delete|all) on public.class_/i);});
test("classes stay separate from personal-training packages and payroll",()=>{const migration=readFileSync("packages/db/migrations/0048_group_classes.sql","utf8"),manage=readFileSync("app/classes/manage/page.tsx","utf8");assert.doesNotMatch(migration,/plans|trainer_compensation_rules|payments/);assert.match(manage,/Class credits and trainer compensation remain separate systems/);assert.match(manage,/does not announce a class, charge a client, consume a training package, or create trainer payroll/);});
test("class operations connect booking schedule staff and client surfaces",()=>{const booking=readFileSync("app/book/page.tsx","utf8"),schedule=readFileSync("app/schedule/page.tsx","utf8"),sidebar=readFileSync("components/layout/app-sidebar.tsx","utf8"),mobile=readFileSync("components/layout/staff-bottom-nav.tsx","utf8");assert.match(booking,/Browse IMS classes/);assert.match(schedule,/class_occurrences/);assert.match(schedule,/Group coaching today/);assert.match(sidebar,/\/classes\/manage/);assert.match(mobile,/\/classes\/manage/);});
test("class attendance is scoped, audited, and financially inert",()=>{const api=readFileSync("app/api/classes/attendance/route.ts","utf8"),roster=readFileSync("app/classes/manage/[id]/page.tsx","utf8");assert.match(api,/assigned coach or owner/);assert.match(api,/recordAudit/);assert.match(api,/class.attendance_marked/);assert.doesNotMatch(api,/plans|trainer_compensation_rules|payments|checkout/);assert.match(roster,/does not automatically consume a personal-training package or calculate trainer payroll/);});
test("recurring classes and access products stay bounded and separate",()=>{const migration=readFileSync("packages/db/migrations/0049_class_series_access.sql","utf8"),series=readFileSync("app/api/classes/series/route.ts","utf8"),client=readFileSync("components/classes/client-class-access.tsx","utf8");assert.match(migration,/class_series/);assert.match(migration,/class_access_products/);assert.match(migration,/Access is intentionally not consumed by class booking yet/);assert.match(series,/rows.length<30/);assert.match(series,/180/);assert.match(client,/Booking does not consume credits/);});
test("class credit ledger is immutable and not yet an automatic charge path",()=>{const ledger=readFileSync("packages/db/migrations/0050_class_credit_ledger.sql","utf8");assert.match(ledger,/class_credit_ledger/);assert.match(ledger,/unique index.*enrollment_attendance/i);assert.match(ledger,/grant select/);assert.doesNotMatch(ledger,/grant (?:insert|update|delete|all)/i);assert.match(ledger,/Future entitlement commands must transact ledger \+ balance \+ attendance together/);});
test("class compensation can never be inferred from class pricing",()=>{const migration=readFileSync("packages/db/migrations/0053_class_compensation_rules.sql","utf8");assert.match(migration,/flat_class/);assert.match(migration,/per_attendee/);assert.match(migration,/owner reads class compensation rules/);assert.match(migration,/Calculation\/submission is intentionally absent/);assert.doesNotMatch(migration,/payments|price_cents|class_access_products/);});
test("client progress integrates class history through an own-client allowlist",()=>{const page=readFileSync("app/progress/page.tsx","utf8"),history=readFileSync("components/classes/client-class-participation.tsx","utf8");assert.match(page,/ClientClassParticipation/);assert.match(history,/get_my_class_participation/);assert.match(history,/Classes attended · recorded attendance only/);assert.doesNotMatch(page,/calories|strength gained|mobility improved|class progress score/i);});
test("owner operating system includes group coaching without merging class finance into PT",()=>{const page=readFileSync("app/operating-system/page.tsx","utf8");assert.match(page,/Group coaching loop/);assert.match(page,/class_occurrences/);assert.match(page,/Credits and payroll remain separate/);});
test("class growth attribution remains explicit rather than inferred",()=>{const migration=readFileSync("packages/db/migrations/0055_class_growth_attribution.sql","utf8"),booking=readFileSync("app/api/classes/book/route.ts","utf8");assert.match(migration,/Source is null unless an explicit, auditable workflow sets it later/);assert.doesNotMatch(booking,/source_type|source_reference|campaign_id/);});
test("trainer Today includes assigned group coaching without owner finance noise",()=>{const today=readFileSync("components/dashboard/trainer-dashboard.tsx","utf8");assert.match(today,/Group coaching today/);assert.match(today,/class_occurrences/);assert.match(today,/Open class/);assert.doesNotMatch(today,/class_compensation_rules|class_credit_ledger|payments/);});

test("waitlist promotion requires an explicit future offer acceptance path",()=>{const migration=readFileSync("packages/db/migrations/0059_class_waitlist_offers.sql","utf8"),guard=readFileSync("packages/db/migrations/0057_class_prelaunch_boundary.sql","utf8");assert.match(migration,/Promotion is an offer, not automatic consent/);assert.match(migration,/accepted_at/);assert.match(migration,/No write command is activated during prelaunch/);assert.match(guard,/revoke execute on function public.book_class/);});

test("staged attendance command is atomic audited and still ungranted in prelaunch",()=>{const migration=readFileSync("packages/db/migrations/0060_class_attendance_command.sql","utf8");assert.match(migration,/for update/);assert.match(migration,/Attendance changed elsewhere/);assert.match(migration,/public.audit_logs/);assert.match(migration,/gen_random_uuid/);assert.match(migration,/do not grant execute to authenticated yet/);assert.doesNotMatch(migration,/grant execute.*authenticated/i);});
