const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),ts=require('typescript');
const root=path.join(__dirname,'..'),client='11111111-1111-4111-8111-111111111111',assessmentId='22222222-2222-4222-8222-222222222222';
function load(file,deps={},globals={}){const out={},code=ts.transpileModule(fs.readFileSync(path.join(root,file),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText;new Function('require','exports',...Object.keys(globals),code)(name=>{if(!(name in deps))throw Error('Unexpected dependency '+name);return deps[name]},out,...Object.values(globals));return out;}
const model=load('lib/fuel/model.ts'),build=load('lib/coaching/build.ts',{'@/lib/fuel/model':model});
function harness({fail=[],assessment=null,sessionIds=[]}={}){const calls=[];const db={from(table){const call={table,filters:[],limit:null};calls.push(call);const q={select(){return q},eq(...args){call.filters.push(args);return q},in(...args){call.filters.push(args);return q},lte(...args){call.filters.push(args);return q},gte(...args){call.filters.push(args);return q},lt(...args){call.filters.push(args);return q},order(){return q},range(){return q},limit(n){call.limit=n;return q},maybeSingle:async()=>({data:table==='assessments'?assessment:null,error:fail.includes(table)?{}:null}),then(resolve){return Promise.resolve(resolve({data:table==='sessions'&&call.filters.some(([key,value])=>key==='status'&&value==='completed')?sessionIds.map(id=>({id})):[],error:fail.includes(table)?{}:null}));}};return q;}};
 const helper=load('lib/coaching/build-load.ts',{'@/lib/fuel/model':model,'@/lib/migration/complete-read':{readCompleteEvidence:async callback=>{const r=await callback(0,499);if(r.error)throw Error('Read failed');return r.data;}}});return{calls,run:target=>helper.loadBuildEvidence(db,client,'Synthetic client',target,new Date('2026-09-28T18:00:00Z'))};}
test('builder loader scopes every evidence read before returning data and never needs elevated access',async()=>{const h=harness();const r=await h.run();for(const call of h.calls)assert.ok(call.filters.some(([field,value])=>field==='client_id'&&value===client),call.table);assert.equal(r.latest,null);assert.deepEqual(r.unavailable,[]);assert.equal(h.calls.some(c=>c.table==='session_exercise_performance'),false);});
test('failed evidence is visibly unavailable, not an empty success',async()=>{const h=harness({fail:['fuel_plan_versions','body_comp_records','sessions']});const r=await h.run();for(const label of ['Fuel versions','Body composition','Upcoming schedule','Performed exercise history'])assert.ok(r.unavailable.includes(label));assert.match(build.buildBlocker(r,'quick'),/could not be checked/);});
test('explicit missing, cross-client or future assessment cannot silently select a different person',async()=>{for(const assessment of [null,{id:assessmentId,client_id:assessmentId,assessment_date:'2026-09-27'},{id:assessmentId,client_id:client,assessment_date:'2027-01-01'}]){const h=harness({assessment}),r=await h.run(assessmentId);assert.equal(r.assessment,null);assert.ok(r.unavailable.includes('Assessment'));assert.ok(h.calls.find(c=>c.table==='assessments').filters.some(([field,value])=>field==='id'&&value===assessmentId));}await assert.rejects(harness().run('bad-id'),/identity/);});
test('performance is explicitly tied to completed sessions; mere imported bookings never count as performed',async()=>{const h=harness({sessionIds:[assessmentId]});await h.run();const sessions=h.calls.find(c=>c.table==='sessions'&&c.filters.some(([key,value])=>key==='status'&&value==='completed'));assert.equal(sessions.limit,30);const perf=h.calls.find(c=>c.table==='session_exercise_performance');assert.ok(perf.filters.some(([key,value])=>key==='session_id'&&value[0]===assessmentId));assert.equal(perf.limit,12);});
const jsx={jsx:(type,props)=>({type,props}),jsxs:(type,props)=>({type,props})};
test('sample page denies nonstaff before any client read and has no persistent action',async()=>{for(const role of ['client','unknown','owner','trainer']){const calls=[];const db={auth:{getUser:async()=>({data:{user:{id:client}}})},from(table){calls.push(table);const q={select:()=>q,eq:()=>q,maybeSingle:async()=>({data:{role,deleted_at:null},error:null})};return q;}};const page=load('app/fuel/sample/page.tsx',{'next/link':'Link','next/navigation':{redirect:()=>{throw Error('redirect');}},'@/lib/supabase/server':{createClient:async()=>db},'@/components/layout/app-shell':{AppShell:'AppShell'},'@/components/fuel/plan-view':{FuelPlanView:'FuelPlanView'},'@/lib/fuel/model':model,'@/lib/coaching/build':build,'react/jsx-runtime':jsx}).default;if(['owner','trainer'].includes(role))assert.ok(await page());else await assert.rejects(page(),/redirect/);assert.deepEqual(calls,['profiles']);}});
test('client build page denies client personas before loading private source evidence',async()=>{let loaded=0;const page=load('app/clients/[id]/build/page.tsx',{'next/navigation':{notFound:()=>{throw Error('notfound');}},'@/components/layout/app-shell':{AppShell:'AppShell'},'@/lib/fuel/load':{fuelAccess:async()=>({staff:false})},'@/lib/coaching/build-load':{loadBuildEvidence:async()=>{loaded++;return {};}},'@/lib/coaching/build':build,'@/components/coaching/builder':{CoachingBuilder:'CoachingBuilder'},'react/jsx-runtime':jsx}).default;await assert.rejects(page({params:Promise.resolve({id:client}),searchParams:Promise.resolve({})}),/notfound/);assert.equal(loaded,0);});
