const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),ts=require('typescript');
const root=path.join(__dirname,'..'),client='11111111-1111-4111-8111-111111111111',coach='22222222-2222-4222-8222-222222222222',assessmentId='33333333-3333-4333-8333-333333333333',requestId='44444444-4444-4444-8444-444444444444',stamp='2026-09-28T00:00:00Z';
function load(file,deps={},globals={}){const out={},code=ts.transpileModule(fs.readFileSync(path.join(root,file),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;new Function('require','exports',...Object.keys(globals),code)(name=>{if(!(name in deps))throw Error('Unexpected dependency '+name);return deps[name];},out,...Object.values(globals));return out;}
const helper=load('lib/coaching/generation-request.ts',{'zod':require('zod')});
const body=()=>({assessment_id:assessmentId,client_id:client,request_id:requestId,response_format:'json',pdf_mode:'client',expected_assessment_updated_at:stamp,sessions_per_week:2,goal:'Coach confirmed goal'});
function api(options={}){
 const calls=[];let stored=options.stored??null,upstream=0,service=0,writes=0,payload=null;
 const db={auth:{getUser:async()=>({data:{user:options.anonymous?null:{id:coach}}})},from(table){const filters={};const q={select(){return q},eq(k,v){filters[k]=v;return q},async maybeSingle(){calls.push({table,filters});if(table==='profiles')return {data:filters.id===coach?{id:coach,role:options.role??'owner',deleted_at:options.disabled?'x':null}:{id:client,role:'client',full_name:'Synthetic Client',deleted_at:options.clientDisabled?'x':null},error:options.profileError?{}:null};if(table==='clients')return {data:{id:client,primary_trainer_id:options.unassigned?client:coach},error:null};if(table==='assessments')return {data:options.missingAssessment?null:{id:assessmentId,client_id:options.crossClient?coach:client,status:options.incomplete?'draft':'complete',updated_at:options.stale?'2026-09-28T01:00:00Z':stamp,data:{goals:{},body_comp:{weight_lbs:'999',body_fat_pct:'99'}}},error:null};if(table==='assessment_device_evidence')return {data:{},error:null};if(table==='programs')return {data:stored,error:null};throw Error('Unexpected '+table);}};return q;}};
 const svc={from(table){const q={insert(value){writes++;stored={...value,id:value.id??requestId,pdf_client_url:null};return q},select(){return q},async single(){return{data:{id:stored.id},error:null}},update(value){if(!options.linkError)stored={...stored,...value};return q},eq(){return Promise.resolve({error:options.linkError?{}:null})},delete(){throw Error('No destructive cleanup for workflow');}};assert.equal(table,'programs');return q},storage:{from(){return{upload:async()=>({error:options.uploadError?{}:null}),remove:async()=>{throw Error('No storage deletion for workflow')}};}}};
 class NextResponse{constructor(bytes,init){this.bytes=bytes;this.status=init?.status??200;}static json(value,init){return{body:value,status:init?.status??200,headers:init?.headers}}}
 const POST=load('app/api/generate/route.ts',{'next/server':{NextResponse},'@/lib/supabase/server':{createClient:async()=>db,createServiceClient:()=>{service++;return svc;}},'@/lib/media/request':{smallJson:async req=>req.body},'@/lib/coaching/generation-request':helper,'@/lib/programs/four-week-integrity':{fourWeekStructureIssues:()=>options.badStructure?['bad']:[]},'@/lib/programs/generator-endpoint':{generatorEndpoint:()=>'/synthetic'},'@/lib/devices/approved-evidence':{approvedDeviceEvidence:()=>({approved_voltra_notes:[]})},'@/lib/programs/cardio-assessment':{generatorCardioProfile:()=>({}),generatorRichRestrictions:()=>[],includeUnverifiedSurgicalHistory:x=>x,recommendedTrainingDays:days=>({days_per_week:days})}},
 {process:{env:{PROGRAM_GENERATOR_SECRET:'synthetic-secret-only',NODE_ENV:'test'}},fetch:async(_,input)=>{upstream++;payload=JSON.parse(input.body);return{ok:true,status:200,headers:{get:()=> 'application/json'},json:async()=>({program:options.nullProgram?null:{weeks:[]},pdf_base64:Buffer.from('%PDF-synthetic').toString('base64')})}}}).POST;
 return{run:(input=body(),origin='https://synthetic.test')=>POST({body:input,headers:{get:()=>origin},nextUrl:{origin:'https://synthetic.test'}}),stats:()=>({calls,upstream,service,writes,stored,payload})};
}
test('new generation refuses anonymous, disabled, unrelated and cross-client actors before elevation',async()=>{for(const options of [{anonymous:true},{disabled:true},{role:'client'},{profileError:true},{role:'trainer',unassigned:true},{clientDisabled:true},{crossClient:true},{missingAssessment:true}]){const h=api(options);assert.notEqual((await h.run()).status,200);assert.equal(h.stats().service,0);assert.equal(h.stats().upstream,0);}});
test('origin, incomplete/stale assessment and malformed commands cannot start a generator write',async()=>{let h=api();assert.equal((await h.run(body(),'https://other.test')).status,403);assert.equal(h.stats().calls.length,0);for(const options of [{stale:true},{incomplete:true}]){h=api(options);assert.equal((await h.run()).status,409);assert.equal(h.stats().service,0);}h=api();assert.equal((await h.run({...body(),publish:true})).status,400);});
test('training saves exactly one private draft, returns its receipt and replays without another generator call',async()=>{const h=api(),first=await h.run(),again=await h.run();assert.equal(first.status,200);assert.equal(first.body.state,'draft_saved');assert.equal(again.body.program_id,requestId);assert.equal(h.stats().writes,1);assert.equal(h.stats().upstream,1);assert.equal(h.stats().stored.status,'draft');assert.deepEqual(h.stats().payload.body_comp,{});assert.equal(h.stats().payload.primary_goal,'Coach confirmed goal');assert.equal(h.stats().payload.days_per_week,2);});
test('same request cannot be reused for changed input or another client',async()=>{const h=api();await h.run();assert.equal((await h.run({...body(),sessions_per_week:4})).status,409);assert.equal(h.stats().upstream,1);});
test('PDF failure leaves one recoverable private draft instead of deleting evidence and generating duplicates',async()=>{for(const options of [{uploadError:true},{linkError:true}]){const h=api(options);const first=await h.run();assert.equal(first.body.state,'needs_pdf_review');const retry=await h.run();assert.equal(retry.body.state,'needs_pdf_review');assert.equal(h.stats().writes,1);assert.equal(h.stats().upstream,1);}});
test('null or structurally empty generator response does not become a saved deliverable',async()=>{for(const options of [{nullProgram:true},{badStructure:true}]){const h=api(options);assert.equal((await h.run()).status,502);assert.equal(h.stats().writes,0);}});
