// Isolated synthetic fixtures only. No real client record or health data is written.
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),ts=require('typescript');
const root=path.join(__dirname,'..'),client='11111111-1111-4111-8111-111111111111',coach='22222222-2222-4222-8222-222222222222',assessmentId='33333333-3333-4333-8333-333333333333',requestId='44444444-4444-4444-8444-444444444444';
function load(file,deps={},globals={}){const out={},code=ts.transpileModule(fs.readFileSync(path.join(root,file),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText;new Function('require','exports',...Object.keys(globals),code)(name=>{if(!(name in deps))throw Error('Unexpected dependency '+name);return deps[name];},out,...Object.values(globals));return out;}
const model=load('lib/fuel/model.ts'),build=load('lib/coaching/build.ts',{'@/lib/fuel/model':model}),validation=load('lib/fuel/validation.ts',{'zod':require('zod'),'./model':model});
const evidence=(patch={})=>({clientId:client,name:'Synthetic Client',asOf:'2026-09-28',capturedAt:'2026-09-28T12:00:00Z',body:[],assessment:null,latest:null,release:null,upcoming:[],performance:[],unavailable:[],...patch});
const assessment={id:assessmentId,client_id:client,assessment_date:'2026-09-27',updated_at:'2026-09-28T00:00:00Z',status:'complete',data:{goals:{primary:'Support training',target_sessions_per_week:'2'},summary:{recommended_sessions_per_week:''},health:{surgeries:'PRIVATE HEALTH NOTE'}}};
const bod={id:requestId,recorded_at:'2026-09-27',weight_lb:180,body_fat_pct:25,lean_mass_lb:135,method:'bod_pod'};
test('Quick Start needs no assessment and leaves energy, macros, foods and measurements unassigned',()=>{const e=evidence(),input={...build.initialBuildInputs(e,'quick'),goal:'Build consistent habits'},draft=build.composeFuelStrategy(e,input);assert.ok(validation.fuelPlanSchema.safeParse(draft.content).success);assert.equal(draft.content.mode,'habits');assert.deepEqual(draft.content.phases[0].training,model.emptyTargets());assert.equal(draft.content.meals.length,0);assert.equal('weight_lb' in draft.content,false);assert.equal(draft.origin,'coach_authored');});
test('Bod Pod mode uses only a real, dated Bod Pod record and never overwrites source arithmetic',()=>{const e=evidence({body:[{...bod,method:'scale'}]});assert.throws(()=>build.composeFuelStrategy(e,{...build.initialBuildInputs(e,'bod_pod'),goal:'Body composition goal'}),/Bod Pod/);e.body.push({...bod,lean_mass_lb:100});const original=JSON.stringify(e.body),draft=build.composeFuelStrategy(e,{...build.initialBuildInputs(e,'bod_pod'),goal:'Body composition goal'});assert.equal(JSON.stringify(e.body),original);assert.match(draft.sourceReference,/body_comp:/);assert.deepEqual(draft.content.phases[0].training,model.emptyTargets());});
test('future and invalid dates cannot masquerade as the latest measured Bod Pod',()=>{const e=evidence({body:[bod,{...bod,id:client,recorded_at:'2027-01-01'},{...bod,recorded_at:'2026-02-30'}]});assert.equal(build.latestBodPod(e).id,requestId);assert.equal(build.latestBodPod(evidence()),null);});
test('private assessment notes never leak into a proposed client strategy',()=>{const e=evidence({assessment,body:[bod]});const input=build.initialBuildInputs(e,'performance');assert.equal(input.goal,'Support training');assert.equal(input.trainingDays,2);const draft=build.composeFuelStrategy(e,input);assert.doesNotMatch(JSON.stringify(draft.content),/PRIVATE HEALTH/);assert.match(draft.sourceReference,new RegExp(assessmentId));assert.equal(build.assessmentContext(assessment).restrictions.length,1);});
test('unknown frequency and missing evidence cannot become three training days or safe clearance',()=>{assert.equal(build.initialBuildInputs(evidence(),'quick').trainingDays,null);assert.match(build.buildBlocker(evidence(),'performance'),/assessment/);assert.match(build.buildBlocker(evidence({unavailable:['Fuel versions']}),'quick'),/could not be checked/);});
test('invalid inputs reject composition instead of coercing fake client or dates',()=>{const e=evidence(),input={...build.initialBuildInputs(e,'quick'),goal:'A coaching goal'};for(const patch of [{goal:''},{start:'2026-02-30'},{reviewOn:'2026-01-01'},{trainingDays:0},{trainingDays:7},{preferences:'x'.repeat(1501)}])assert.throws(()=>build.composeFuelStrategy(e,{...input,...patch}));assert.throws(()=>build.composeFuelStrategy(evidence({clientId:'sample'}),input),/real client/);});
test('coach-entered meals and groceries are retained without nutrient arithmetic or invented swaps',()=>{const e=evidence(),draft=build.composeFuelStrategy(e,{...build.initialBuildInputs(e,'quick'),goal:'Routine',meals:'Breakfast choice\nLunch choice',grocery:'Coach-chosen ingredient',preferences:'Discuss allergy before food selection'});assert.equal(draft.content.meals.length,2);assert.equal(draft.content.meals[0].swaps,'');assert.deepEqual(draft.content.meals[0].targets,model.emptyTargets());assert.deepEqual(draft.content.grocery,['Coach-chosen ingredient']);});
test('sample is isolated display content, not a fictional client assessment or publishable receipt',()=>{const sample=build.sampleFuelStrategy('2026-09-28');assert.match(sample.title,/SAMPLE/);assert.ok(validation.fuelPlanSchema.safeParse(sample).success);assert.equal('client_id' in sample,false);assert.equal('request_id' in sample,false);assert.equal('body_comp' in sample,false);assert.deepEqual(sample.phases[0].training,model.emptyTargets());const source=fs.readFileSync(path.join(root,'app/fuel/sample/page.tsx'),'utf8');assert.doesNotMatch(source,/\.insert\(|\.rpc\(|FuelPlanEditor|useFuelMutation|save_plan|release_plan/);});
const adjustment=load('lib/fuel/adjustment.ts',{'./model':model});
test('retest proposes a private copy preserving targets and AI/source origin, not automatic adjustment',()=>{const current={id:assessmentId,client_id:client,revision:2,origin:'ai_proposed',content:model.blankPlan('2026-09-01')};current.content.phases[0].training.kcal=2000;const draft=adjustment.fuelAdjustmentDraft({clientId:client,entryId:requestId,current,latest:current,evidenceKind:'body_comp'},coach);assert.match(draft.source_reference,/body_comp:/);assert.equal(draft.origin,'ai_proposed');assert.deepEqual(draft.content,current.content);assert.equal(draft.action,'save_plan');});
function hookHarness(){const slots=[];let cursor=0,handler=async()=>{throw Error('offline')};const react={useRef(value){const i=cursor++;if(!slots[i])slots[i]={current:value};return slots[i];},useState(value){const i=cursor++;if(!(i in slots))slots[i]=typeof value==='function'?value():value;return[slots[i],v=>{slots[i]=typeof v==='function'?v(slots[i]):v;}];}};const hook=load('components/coaching/training-draft.tsx',{'react':react,'@/lib/fuel/model':model},{fetch:(...args)=>handler(...args),crypto:{randomUUID:()=>requestId}}).useTrainingDraft;return{render(){cursor=0;return hook();},setHandler(h){handler=h;}};}
const trainingInput={assessment_id:assessmentId,client_id:client,expected_assessment_updated_at:assessment.updated_at,sessions_per_week:2,goal:'Support training'};
const response=(body,status=200)=>({ok:status>=200&&status<300,status,json:async()=>body});
test('training retry preserves request identity across lost response and later authorization failure',async()=>{const h=hookHarness(),sent=[];h.setHandler(async(_,o)=>{sent.push(o.body);throw Error('offline');});await h.render().generate(trainingInput);assert.ok(h.render().uncertain);await h.render().generate({...trainingInput,sessions_per_week:4});assert.equal(sent.length,1);h.setHandler(async(_,o)=>{sent.push(o.body);return response({},403)});await h.render().retry();assert.ok(h.render().uncertain);h.setHandler(async(_,o)=>{sent.push(o.body);return response({request_id:requestId,program_id:requestId,client_id:client,state:'draft_saved'});});await h.render().retry();assert.equal(new Set(sent).size,1);assert.equal(h.render().result.id,requestId);assert.ok(h.render().locked);});
test('training incomplete receipt never announces a saved draft and duplicate taps issue one request',async()=>{const h=hookHarness();let finish,calls=0;h.setHandler(()=>{calls++;return new Promise(r=>{finish=r;});});const state=h.render(),first=state.generate(trainingInput);await state.generate(trainingInput);assert.equal(calls,1);finish(response({ok:true}));await first;assert.equal(h.render().result,null);assert.ok(h.render().uncertain);});
test('training PDF recovery is distinct from a ready saved draft',async()=>{const h=hookHarness();h.setHandler(async()=>response({request_id:requestId,program_id:requestId,client_id:client,state:'needs_pdf_review'}));await h.render().generate(trainingInput);assert.equal(h.render().result.state,'needs_pdf_review');assert.equal(h.render().uncertain,false);});
const reqHelper=load('lib/coaching/generation-request.ts',{'zod':require('zod')});
test('generation contract disallows missing snapshot, unknown fields, forged frequency and changed reuse',()=>{const body={...trainingInput,response_format:'json',request_id:requestId};assert.ok(reqHelper.generationRequestSchema.safeParse(body).success);for(const patch of [{request_id:undefined},{client_id:undefined},{goal:''},{sessions_per_week:0},{publish:true},{expected_assessment_updated_at:'not-a-date'}])assert.equal(reqHelper.generationRequestSchema.safeParse({...body,...patch}).success,false);const identity=reqHelper.generationIdentity(body);assert.ok(reqHelper.sameGenerationIdentity(identity,identity));assert.equal(reqHelper.sameGenerationIdentity({...identity,goal:'Changed'},identity),false);});
test('builder keeps the sample, blank editor, measured test and dual-draft paths available without release',()=>{const source=fs.readFileSync(path.join(root,'components/coaching/builder.tsx'),'utf8');for(const label of ['Quick Start','Bod Pod Build','Full Performance','Training + Fuel','UNSAVED PREVIEW','allowRelease={false}','/fuel/sample','FuelBodyCompForm','Continue current private draft'])assert.ok(source.includes(label),label);assert.doesNotMatch(source,/action:\s*["']release_plan/);});

test('assessment Bod Pod fields prefill review only; missing date and values remain blank',()=>{const a={...assessment,data:{body_comp:{method:'bod_pod',weight_lbs:'180',body_fat_pct:'',lean_mass_lbs:null,tested_on:''}}};const candidate=build.assessmentBodPodCandidate(a,'2026-09-28');assert.equal(candidate.date,'');assert.equal(candidate.weight,180);assert.equal(candidate.fat,null);assert.equal(candidate.lean,null);assert.equal(build.assessmentBodPodCandidate({...a,data:{body_comp:{method:'scale'}}},'2026-09-28'),null);assert.equal(build.latestBodPod(evidence({assessment:a})),null);});
