const {test,before,after}=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),{randomUUID}=require("node:crypto");
const live=process.env.IMS_TEST_DATABASE_URL;let admin,db,name,lead,clientA,clientB,owner,trainer;
before(async()=>{if(!live)return;const url=new URL(live);if(!["localhost","127.0.0.1"].includes(url.hostname)||url.pathname!=="/ims_ci")throw Error("Only isolated ims_ci is permitted");const {Client}=require("pg");admin=new Client({connectionString:live});await admin.connect();name="ims_contact_"+randomUUID().replaceAll("-","");await admin.query('create database "'+name+'"');url.pathname="/"+name;db=new Client({connectionString:url.toString()});await db.connect();
 await db.query(`create schema auth;create role authenticated;create role anon;create role service_role;create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema public,auth to authenticated,anon,service_role;create table profiles(id uuid primary key,role text not null,deleted_at timestamptz);create table leads(id uuid primary key);grant select on profiles,leads to authenticated;`);
 lead=randomUUID();clientA=randomUUID();clientB=randomUUID();owner=randomUUID();trainer=randomUUID();await db.query("insert into profiles values($1,'client',null),($2,'client',null),($3,'owner',null),($4,'trainer',null)",[clientA,clientB,owner,trainer]);await db.query("insert into leads values($1)",[lead]);await db.query(fs.readFileSync(path.join(__dirname,"../packages/db/migrations/0084_contact_client_conversion_receipt.sql"),"utf8"));});
after(async()=>{if(db)await db.end();if(admin){try{await admin.query('drop database "'+name+'"')}finally{await admin.end()}}});
async function role(id,as="authenticated"){await db.query("reset role");await db.query("set role "+as);await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);}
test("conversion receipt enforces one contact to one client",{skip:!live},async()=>{await db.query("insert into lead_client_conversions(lead_id,client_id,converted_by) values($1,$2,$3)",[lead,clientA,owner]);await assert.rejects(db.query("insert into lead_client_conversions(lead_id,client_id,converted_by) values($1,$2,$3)",[lead,clientB,owner]),/duplicate key/);});
test("staff can read conversion receipt but clients and anonymous cannot",{skip:!live},async()=>{await role(owner);assert.equal((await db.query("select * from lead_client_conversions")).rows.length,1);await role(trainer);assert.equal((await db.query("select * from lead_client_conversions")).rows.length,1);await role(clientA);assert.equal((await db.query("select * from lead_client_conversions")).rows.length,0);await role(clientA,"anon");await assert.rejects(db.query("select * from lead_client_conversions"));});
