const {test}=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs");
const view=fs.readFileSync("components/leads/lead-workspace-view.tsx","utf8"),profile=fs.readFileSync("app/contacts/[id]/page.tsx","utf8"),form=fs.readFileSync("components/leads/contact-client-conversion.tsx","utf8"),convert=fs.readFileSync("app/api/leads/[id]/convert/route.ts","utf8");
test("historical contacts open a dedicated contact profile",()=>{assert.match(view,/\/contacts\/\$\{row\.id\}/);assert.match(profile,/Contact profile/);assert.match(profile,/Relationship history/);assert.match(profile,/Contact notes/);});
test("contact conversion is explicit, coach-selected and routes to full client profile",()=>{assert.match(form,/Confirm client conversion/);assert.match(form,/trainer_id/);assert.match(form,/router\.push\("\/clients\/"\+result\.client_id\)/);assert.match(form,/send_invite:false/);});
test("conversion never infers package, balance, appointment or invitation",()=>{assert.match(convert,/body\.send_invite!==false/);assert.match(convert,/billing_type:"unset"/);assert.match(convert,/invite_sent:false/);assert.match(convert,/package_inferred:false/);assert.match(convert,/balance_inferred:false/);assert.match(convert,/appointment_inferred:false/);assert.doesNotMatch(convert,/sendLoginInvite/);});
test("conversion checks active duplicate identity and active coach before account creation",()=>{assert.match(convert,/\.ilike\("email",email\)/);assert.match(convert,/An active Coach OS identity already uses this email/);assert.match(convert,/Choose an active IMS coach/);});
test("failed downstream conversion rolls back newly-created identity",()=>{assert.match(convert,/svc\.from\("clients"\)\.delete/);assert.match(convert,/svc\.auth\.admin\.deleteUser/);assert.match(convert,/rolled back/);});
test("contact profile does not treat history as present purchase intent",()=>{assert.match(profile,/historical relationship record/);assert.match(profile,/does not infer a package, balance, payment, appointment or current purchase intent/);});

test("conversion has a durable one-contact-one-client receipt before downstream creation",()=>{const sql=fs.readFileSync("packages/db/migrations/0084_contact_client_conversion_receipt.sql","utf8");assert.match(sql,/lead_id uuid primary key/);assert.match(sql,/client_id uuid not null unique/);assert.match(convert,/lead_client_conversions/);assert.match(convert,/CONTACT_ALREADY_CONVERTED/);assert.match(convert,/No duplicate client was kept/);});
