const {test,before,after}=require('node:test');const assert=require('node:assert/strict');const {randomUUID}=require('node:crypto');const fs=require('node:fs');const path=require('node:path');
const live=process.env.IMS_TEST_DATABASE_URL,owner=randomUUID(),coach=randomUUID(),other=randomUUID(),client=randomUUID();let db,admin,name;
before(async()=>{if(live){const u=new URL(live);if(!['127.0.0.1','localhost'].includes(u.hostname)||u.pathname!='/ims_ci')throw Error('Only isolated test database');const {Client}=require('pg');admin=new Client({connectionString:live});await admin.connect();name='ims_fuelsource_'+randomUUID().replaceAll('-','');await admin.query('create database "'+name+'"');u.pathname='/'+name;const pg=new Client({connectionString:u.toString()});await pg.connect();db={exec:s=>pg.query(s),query:(s,p)=>pg.query(s,p),close:()=>pg.end()};}else{const {PGlite}=await import('@electric-sql/pglite');db=new PGlite();}
 await db.exec(`create schema auth;create schema storage;do $$begin create role authenticated;exception when duplicate_object then null;end$$;do $$begin create role anon;exception when duplicate_object then null;end$$;do $$begin create role service_role;exception when duplicate_object then null;end$$;
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 grant usage on schema public,auth,storage to authenticated,anon,service_role;
 create table public.profiles(id uuid primary key,role text not null,deleted_at timestamptz);create table public.clients(id uuid primary key references public.profiles(id),primary_trainer_id uuid references public.profiles(id));
 create type public.bodycomp_method as enum('bod_pod','dexa','inbody','scale','calipers');create table public.body_comp_records(id uuid primary key default gen_random_uuid(),client_id uuid,recorded_at date,weight_lb numeric(5,2),body_fat_pct numeric(4,2),lean_mass_lb numeric(5,2),method public.bodycomp_method);
 create table public.audit_logs(id uuid primary key,actor_id uuid,action text,entity_type text,entity_id uuid,changes jsonb);
 create table storage.buckets(id text primary key,name text,public boolean,file_size_limit integer,allowed_mime_types text[]);create table storage.objects(bucket_id text,name text,primary key(bucket_id,name));
 alter table storage.objects enable row level security;grant all on storage.objects to anon,authenticated;create policy legacy_objects on storage.objects for all to anon,authenticated using(true) with check(true);
 grant select on public.profiles,public.clients to authenticated;
 insert into public.profiles values('${owner}','owner',null),('${coach}','trainer',null),('${other}','trainer',null),('${client}','client',null);insert into public.clients values('${client}','${coach}');
 insert into storage.objects values('other-bucket','public.txt');`);
 for(const file of ['0078_fuel_performance.sql','0079_fuel_private_sources.sql'])await db.exec(fs.readFileSync(path.join(__dirname,'../packages/db/migrations',file),'utf8'));
});
after(async()=>{await db?.close();if(admin){try{await admin.query('drop database "'+name+'"')}finally{await admin.end()}}});
async function role(id,as='authenticated'){await db.exec('reset role');await db.exec('set role '+as);await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);}
async function raw(sql,params=[]){await db.exec('reset role');return (await db.query(sql,params)).rows;}
function args(actor=coach,id=randomUUID()){return [actor,client,id,'Synthetic.pdf','a'.repeat(64),20];}
async function register(a){return (await db.query('select public.register_fuel_source($1,$2,$3,$4,$5,$6) result',a)).rows[0].result;}
async function upload(a){await raw('insert into storage.objects values($1,$2)',['fuel-sources',`${a[1]}/${a[0]}/${a[2]}.pdf`]);}
test('private source storage survives a broad legacy storage policy without changing other buckets',async()=>{const a=args();await upload(a);for(const who of [coach,client,other]){await role(who);const rows=(await db.query('select * from storage.objects')).rows;assert.deepEqual(rows.map(r=>r.bucket_id),['other-bucket']);await assert.rejects(db.query("insert into storage.objects values('fuel-sources','forged.pdf')"),/policy/);}await role(client,'anon');assert.equal((await db.query('select * from storage.objects')).rows.length,1);});
test('source registration is service-only and validates the real active staff assignment',async()=>{const a=args();await upload(a);for(const who of [owner,coach,client,other]){await role(who);await assert.rejects(register(a),/permission denied/);}await role(owner,'service_role');await assert.rejects(register(args(other)),/authorization/);await assert.rejects(register(args(client)),/authorization/);await assert.rejects(register(args()),/upload not found/);});
test('source registry and audit save once with exact retries; client cannot see private source metadata',async()=>{const a=args();await upload(a);await role(owner,'service_role');const r=await register(a);assert.equal(r.deduped,false);assert.equal((await register(a)).deduped,true);await assert.rejects(register([...a.slice(0,4),'b'.repeat(64),20]),/changed content/);assert.equal((await raw('select * from public.audit_logs where entity_id=$1',[a[2]])).length,1);await role(client);assert.equal((await db.query('select * from public.fuel_source_documents')).rows.length,0);await role(other);assert.equal((await db.query('select * from public.fuel_source_documents')).rows.length,0);await role(coach);assert.ok((await db.query('select * from public.fuel_source_documents')).rows.some(row=>row.id===r.id));});
test('source audit failure rolls back registry while preserved private bytes remain recoverable',async()=>{const a=args();await upload(a);await db.exec("reset role;create function public.fail_source_audit()returns trigger language plpgsql as $$begin raise exception 'Synthetic source audit failure';end$$;create trigger fail_source_audit before insert on public.audit_logs for each row execute function public.fail_source_audit();");try{await role(owner,'service_role');await assert.rejects(register(a),/Synthetic/);assert.equal((await raw('select * from public.fuel_source_documents where id=$1',[a[2]])).length,0);assert.equal((await raw('select * from storage.objects where name=$1',[`${a[1]}/${a[0]}/${a[2]}.pdf`])).length,1);}finally{await db.exec('reset role;drop trigger fail_source_audit on public.audit_logs;drop function public.fail_source_audit();');}await role(owner,'service_role');assert.equal((await register(a)).ok,true);});
test('original source history cannot be overwritten or removed by ordinary SQL',async()=>{await db.exec('reset role');await assert.rejects(db.exec('truncate public.fuel_source_documents'),/append-only/);await role(coach);await assert.rejects(db.exec("update public.fuel_source_documents set original_name='changed'"),/permission denied/);});
