import test from "node:test";
import assert from "node:assert/strict";
import {blankPlan,validDate,phaseForDate,dailyTargets,emptyTargets,targetWarnings,adherence,weightAverage,confirmedTrainingContext,pendingCheckins,type Journal,type Daily} from "../lib/fuel/model";
import {parseFuelCommand,validFuelReceipt} from "../lib/fuel/validation";
const client="11111111-1111-4111-8111-111111111111",request="22222222-2222-4222-8222-222222222222";
const payload:Daily={day_type:"unclassified",habits:{protein:null,fuel:null,water:null,steps:null,sleep:null,training:null},weight_lb:null,steps:null,sleep_hours:null,energy:null,hunger:null,note:""};
function row(date:string,weight:number|null,revision=1):Journal{return{id:date+revision,client_id:client,kind:"daily",entry_date:date,revision,payload:{...payload,habits:{...payload.habits},weight_lb:weight},plan_version_id:null,created_at:date+"T12:00:00Z"};}
test("academy skeleton preserves five phases without copying a person's targets or measurements",()=>{const p=blankPlan("2026-09-21","academy");assert.equal(p.phases.length,5);assert.equal(p.end,"2027-03-07");assert.equal(p.mode,"habits");assert.equal(p.event_date,null);assert.deepEqual(p.phases[0].training,emptyTargets());assert.equal(phaseForDate(p,"2026-12-21")?.name,"Diet break");assert.equal(phaseForDate(p,"2027-03-08"),null);});
test("date validation rejects overflow and phase gaps never choose a fictional prescription",()=>{assert.equal(validDate("2026-02-30"),false);const p=blankPlan("2026-09-21");p.mode="targets";assert.equal(dailyTargets(p,"2026-09-22","unclassified"),null);assert.equal(dailyTargets(p,"2027-01-01","training"),null);});
test("macro arithmetic reports disagreement without repairing source values",()=>{const t={kcal:1800,protein_g:150,carbs_g:185,fat_g:50};assert.match(targetWarnings(t)[0],/1790/);assert.equal(t.kcal,1800);assert.deepEqual(targetWarnings(emptyTargets()),[]);});
test("blank or not-due habits are not misses; revisions and other clients cannot inflate adherence",()=>{const a=row("2026-09-21",null),b=row("2026-09-22",null),revision=row("2026-09-21",null,2);(a.payload as Daily).habits.protein="missed";(revision.payload as Daily).habits.protein="met";(b.payload as Daily).habits.protein="not_due";const other={...row("2026-09-23",null),client_id:"other"};const s=adherence([a,b,revision,other],"2026-09-21","2026-09-27",client);assert.equal(s.loggedDays,2);assert.equal(s.habits[0].percent,100);assert.equal(s.habits[0].reported,1);assert.equal(s.habits[1].percent,null);});
test("weight summaries disclose sample count and never fill missing weights",()=>{const rows=[row("2026-09-21",180),row("2026-09-22",182)];assert.equal(weightAverage(rows,"2026-09-21","2026-09-27",client).average,null);rows.push(row("2026-09-23",181));assert.deepEqual(weightAverage(rows,"2026-09-21","2026-09-27",client),{samples:3,average:181});});
test("no booking is not a rest-day prescription, cancelled requests do not count as training",()=>{assert.equal(confirmedTrainingContext([],"2026-09-21"),false);assert.equal(confirmedTrainingContext([{scheduled_at:"2026-09-22T01:00:00Z",status:"confirmed",session_type:"training"}],"2026-09-21"),true);assert.equal(confirmedTrainingContext([{scheduled_at:"2026-09-22T01:00:00Z",status:"cancelled",session_type:"training"}],"2026-09-21"),false);});
test("new checkin revisions reopen coach review instead of borrowing an old response",()=>{const a={...row("2026-09-21",null),kind:"weekly" as const},b={...a,id:"revised",revision:2};assert.equal(pendingCheckins([a,b],[{id:"r",client_id:client,entry_id:a.id,note:"Old response",disposition:"reviewed",created_at:"2026-09-22"}]).length,1);});
test("strict command parser rejects hidden fields, impossible dates and incomplete publication approval",()=>{const c={action:"save_plan",request_id:request,expected_revision:0,content:blankPlan("2026-09-21"),origin:"coach_authored",source_reference:""};assert.equal(parseFuelCommand(c).action,"save_plan");assert.throws(()=>parseFuelCommand({...c,client_id:"forged"}));assert.throws(()=>parseFuelCommand({...c,content:{...c.content,start:"2026-02-30"}}));assert.throws(()=>parseFuelCommand({action:"release_plan",request_id:request,version_id:null,expected_sequence:0,confirmed:true,reason:"Owner paused the plan."}));const command=parseFuelCommand(c);assert.equal(validFuelReceipt({ok:true},command,client),false);});
