const {test,before,after}=require('node:test');const assert=require('node:assert/strict');const {randomUUID}=require('node:crypto');const fs=require('node:fs');const path=require('node:path');
const live=process.env.IMS_TEST_DATABASE_URL,owner=randomUUID(),coach=randomUUID(),other=randomUUID(),disabled=randomUUID();let db,admin,name,peerUrl;
before(async()=>{
 if(live){const url=new URL(live);if(!['localhost','127.0.0.1'].includes(url.hostname)||url.pathname!='/ims_ci')throw Error('Only isolated ims_ci is permitted');const {Client}=require('pg');admin=new Client({connectionString:live});await admin.connect();name='ims_fuel_'+randomUUID().replaceAll('-','');await admin.query('create database "'+name+'"');url.pathname='/'+name;peerUrl=url.toString();const pg=new Client({connectionString:peerUrl});await pg.connect();db={exec:s=>pg.query(s),query:(s,p)=>pg.query(s,p),close:()=>pg.end()};}else{const {PGlite}=await import('@electric-sql/pglite');db=new PGlite();}
 await db.exec(`create schema auth;do $$begin create role authenticated;exception when duplicate_object then null;end$$;do $$begin create role anon;exception when duplicate_object then null;end$$;do $$begin create role service_role;exception when duplicate_object then null;end$$;
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 grant usage on schema public,auth to authenticated,anon,service_role;
 create table public.profiles(id uuid primary key,role text not null,deleted_at timestamptz);
 create table public.clients(id uuid primary key references public.profiles(id),primary_trainer_id uuid references public.profiles(id));
 create type public.bodycomp_method as enum('bod_pod','dexa','inbody','scale','calipers');
 create table public.body_comp_records(id uuid primary key default gen_random_uuid(),client_id uuid references public.clients(id),recorded_at date,weight_lb numeric(5,2),body_fat_pct numeric(4,2),lean_mass_lb numeric(5,2),method public.bodycomp_method);
 create table public.audit_logs(id uuid primary key,actor_id uuid,action text,entity_type text,entity_id uuid,changes jsonb);
 create table public.sessions(id uuid primary key);create table public.plans(id uuid primary key);create table public.payments(id uuid primary key);
 grant select on public.profiles,public.clients to authenticated;
 insert into public.profiles values('${owner}','owner',null),('${coach}','trainer',null),('${other}','trainer',null),('${disabled}','owner',now());`);
 await db.exec(fs.readFileSync(path.join(__dirname,'../packages/db/migrations/0078_fuel_performance.sql'),'utf8'));
});
after(async()=>{await db?.close();if(admin){try{await admin.query('drop database "'+name+'"');}finally{await admin.end();}}});
async function raw(s,p=[]){await db.exec('reset role');return(await db.query(s,p)).rows;}
async function role(id,connection=db,as='authenticated'){await connection.query('reset role');await connection.query('set role '+as);await connection.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);}
async function subject(){const id=randomUUID();await raw("insert into public.profiles values($1,'client',null)",[id]);await raw('insert into public.clients values($1,$2)',[id,coach]);return id;}
async function run(client,command,connection=db){return(await connection.query('select public.execute_fuel_command($1,$2::jsonb) result',[client,JSON.stringify(command)])).rows[0].result;}
const targets=()=>({kcal:null,protein_g:null,carbs_g:null,fat_g:null});
const plan=()=>({schema_version:1,title:'Synthetic fuel plan',goal:'Coach reviewed goal',start:'2026-01-01',end:'2026-12-31',event_date:null,mode:'habits',habits:['protein','sleep'],phases:[{name:'Foundation',start:'2026-01-01',end:'2026-12-31',focus:'Synthetic guidance',training:targets(),rest:targets()}],meals:[],grocery:[],guidance:'',review_on:null});
const draft=()=>({action:'save_plan',request_id:randomUUID(),expected_revision:0,content:plan(),origin:'coach_authored',source_reference:''});
const publish=(version,seq=0)=>({action:'release_plan',request_id:randomUUID(),version_id:version,expected_sequence:seq,confirmed:true,individual_review_confirmed:true,reason:'Individually reviewed targets and context.'});
const daily=()=>({action:'save_daily',request_id:randomUUID(),date:'2026-01-02',expected_revision:0,plan_version_id:null,payload:{day_type:'unclassified',habits:{protein:null,fuel:null,water:null,steps:null,sleep:null,training:null},weight_lb:null,steps:null,sleep_hours:null,energy:null,hunger:null,note:''}});
const weekly=()=>({action:'save_checkin',request_id:randomUUID(),date:'2026-01-02',expected_revision:0,plan_version_id:null,payload:{hardest_moment:'',barriers:'',training:'not_reported',symptoms:'',upcoming:'',next_step:'',contact_requested:false,energy:null,hunger:null,sleep:null}});
test('fuel draft is private, release is explicit, pause does not rewrite historical versions',async()=>{const c=await subject(),cmd=draft();await role(coach);const saved=await run(c,cmd);assert.equal(saved.revision,1);await role(c);assert.equal((await db.query('select * from public.fuel_plan_versions')).rows.length,0);await assert.rejects(run(c,publish(saved.entity_id)),/role denied/);await role(coach);await assert.rejects(run(c,{...publish(saved.entity_id),individual_review_confirmed:false}),/review required/);await run(c,publish(saved.entity_id));await role(c);assert.equal((await db.query('select * from public.fuel_plan_versions where client_id=$1',[c])).rows.length,1);await role(coach);await run(c,publish(null,1));assert.equal((await raw('select * from public.fuel_plan_versions where client_id=$1',[c])).length,1);});
test('owner and assigned coach are allowed; unrelated coach, disabled and anonymous actors cannot read or mutate',async()=>{const c=await subject();await role(owner);await run(c,draft());for(const who of [other,disabled]){await role(who);await assert.rejects(run(c,draft()),/access denied/);assert.equal((await db.query('select * from public.fuel_plan_versions where client_id=$1',[c])).rows.length,0);}await role(c,db,'anon');await assert.rejects(run(c,daily()),/permission denied/);});
test('actual SQL enforces strict fields, phase bounds and provenance independently of TypeScript',async()=>{const c=await subject();await role(coach);const d=draft();for(const change of [{content:{...d.content,extra:'unsafe'}},{content:{...d.content,start:'2026-02-30'}},{content:{...d.content,phases:[d.content.phases[0],d.content.phases[0]]}},{content:{...d.content,habits:['sleep','sleep']}},{expected_revision:null},{origin:'source_transcription',source_reference:''},{content:{...d.content,phases:[{...d.content.phases[0],training:{...targets(),kcal:'1800'}}]}}])await assert.rejects(run(c,{...d,...change}));assert.equal((await raw('select * from public.fuel_plan_versions where client_id=$1',[c])).length,0);});
test('same request retries once; changed content and stale revisions fail without overwriting',async()=>{const c=await subject(),d=draft();await role(coach);const r=await run(c,d);assert.equal((await run(c,d)).deduped,true);await assert.rejects(run(c,{...d,source_reference:'changed'}),/reused/);await assert.rejects(run(c,{...d,request_id:randomUUID()}),/changed/);await run(c,{...d,request_id:randomUUID(),expected_revision:1});assert.equal((await raw('select * from public.fuel_plan_versions where client_id=$1',[c])).length,2);assert.equal((await raw('select * from public.audit_logs where entity_id=$1',[r.entity_id])).length,1);});
test('client reports remain distinct from appointments, measurements, money, and other clients',async()=>{const c=await subject(),b=await subject(),d=daily();await role(c);await run(c,d);await assert.rejects(run(b,daily()),/access denied/);await role(coach);await assert.rejects(run(c,daily()),/role denied/);for(const table of ['sessions','plans','payments','body_comp_records'])assert.equal((await raw('select * from public.'+table)).length,0);await role(c);const rows=(await db.query('select * from public.fuel_journal_entries where client_id=$1',[c])).rows;assert.equal(rows[0].payload.habits.protein,null);assert.equal(rows[0].payload.weight_lb,null);});
test('unreleased or another client plan cannot be attached to a client journal',async()=>{const c=await subject(),b=await subject();await role(coach);const r=await run(c,draft());await role(c);await assert.rejects(run(c,{...daily(),plan_version_id:r.entity_id}),/not released/);await role(coach);await run(c,publish(r.entity_id));await role(b);await assert.rejects(run(b,{...daily(),plan_version_id:r.entity_id}),/not released/);});
test('daily dates and numeric fields reject future, nonfinite encodings and hidden keys',async()=>{const c=await subject();await role(c);const d=daily();for(const patch of [{date:'2099-01-01'},{date:'2026-02-30'},{payload:{...d.payload,weight_lb:0}},{payload:{...d.payload,energy:0}},{payload:{...d.payload,steps:1.5}},{payload:{...d.payload,sleep_hours:25}},{payload:{...d.payload,role:'owner'}}])await assert.rejects(run(c,{...d,...patch}));});
test('check-in feedback rechecks latest revision, is client-visible, and does not change calories',async()=>{const c=await subject(),w=weekly();await role(c);const one=await run(c,w),two=await run(c,{...w,request_id:randomUUID(),expected_revision:1,payload:{...w.payload,contact_requested:true,symptoms:'Please discuss recovery.'}});const review={action:'review_checkin',request_id:randomUUID(),entry_id:one.entity_id,note:'We should review this together.',disposition:'contact',confirmed:true};await role(coach);await assert.rejects(run(c,review),/latest/);await run(c,{...review,entry_id:two.entity_id});await role(c);assert.equal((await db.query('select * from public.fuel_coach_reviews where client_id=$1',[c])).rows.length,1);assert.equal((await raw('select * from public.fuel_plan_releases where client_id=$1',[c])).length,0);});
test('measurement command shares canonical body_comp_records and keeps source values separately',async()=>{const c=await subject();await role(coach);const cmd={action:'record_body_comp',request_id:randomUUID(),date:'2026-01-02',weight_lb:180,body_fat_pct:30,lean_mass_lb:126,method:'bod_pod',source_kind:'source_transcription',source_reference:'Synthetic report, page 2',protocol:'Test conditions not available in source.',confirmed:true};const r=await run(c,cmd);assert.equal((await run(c,cmd)).deduped,true);const rows=await raw('select * from public.body_comp_records where id=$1',[r.entity_id]);assert.equal(Number(rows[0].weight_lb),180);assert.equal((await raw('select * from public.fuel_body_comp_sources where id=$1',[r.entity_id]))[0].reported_values.weight_lb,180);await role(c);assert.equal((await db.query('select * from public.fuel_body_comp_sources where client_id=$1',[c])).rows.length,0);});
test('audit failures roll back plans and receipts; direct updates and truncation cannot rewrite history',async()=>{const c=await subject(),d=draft();await db.exec("create function public.fail_fuel_audit()returns trigger language plpgsql as $$begin raise exception 'Synthetic fuel audit failure';end$$;create trigger fail_fuel_audit before insert on public.audit_logs for each row execute function public.fail_fuel_audit();");try{await role(coach);await assert.rejects(run(c,d),/Synthetic/);assert.equal((await raw('select * from public.fuel_plan_versions where client_id=$1',[c])).length,0);}finally{await db.exec('reset role;drop trigger fail_fuel_audit on public.audit_logs;drop function public.fail_fuel_audit();');}await role(coach);await run(c,d);await assert.rejects(db.query('delete from public.fuel_plan_versions where client_id=$1',[c]),/permission denied/);await db.exec('reset role');await assert.rejects(db.query('truncate public.fuel_command_receipts'),/append-only/);});
test('two PostgreSQL requests for one client check-in create one journal and receipt',{skip:!live},async()=>{const c=await subject(),command=daily(),{Client}=require('pg'),peers=[new Client({connectionString:peerUrl}),new Client({connectionString:peerUrl})];try{await Promise.all(peers.map(async p=>{await p.connect();await role(c,p);}));const results=await Promise.all(peers.map(p=>run(c,command,p)));assert.deepEqual(results.map(r=>r.deduped).sort(),[false,true]);assert.equal((await raw('select * from public.fuel_journal_entries where client_id=$1',[c])).length,1);}finally{await Promise.all(peers.map(p=>p.end()));}});
