const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const ts=require('typescript');
const root=path.join(__dirname,'..'),client='11111111-1111-4111-8111-111111111111',coach='22222222-2222-4222-8222-222222222222',requestId='33333333-3333-4333-8333-333333333333';
function load(file,deps={},globals={}){const source=ts.transpileModule(fs.readFileSync(path.join(root,file),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText,out={};new Function('require','exports',...Object.keys(globals),source)(name=>{if(!(name in deps))throw Error('Unexpected dependency '+name);return deps[name]},out,...Object.values(globals));return out;}
const model=load('lib/fuel/model.ts'),validation=load('lib/fuel/validation.ts',{'zod':require('zod'),'./model':model});
const draft=()=>({action:'save_plan',request_id:requestId,expected_revision:0,content:model.blankPlan('2026-09-21'),origin:'coach_authored',source_reference:''});
function api({role='owner',who=coach,deleted=false,user=true,profileError=false,subjectError=false,assignment=coach,rpcError=null,receipt=null,throws=false}={}){
 const calls=[],db={auth:{getUser:async()=>({data:{user:user?{id:who}:null}})},from(table){calls.push(table);const q={select:()=>q,eq:()=>q,maybeSingle:async()=>table==='profiles'?{data:{role,deleted_at:deleted?'2026-01-01':null},error:profileError?{}:null}:{data:{id:client,primary_trainer_id:assignment},error:subjectError?{}:null}};return q;},async rpc(name,p){calls.push(name);if(throws)throw Error('offline');return{data:receipt??{ok:true,request_id:p.p_command.request_id,client_id:p.p_client_id,action:p.p_command.action,entity_id:requestId,revision:1,deduped:false},error:rpcError};}};
 const {POST}=load('app/api/fuel/[clientId]/route.ts',{'next/server':{NextResponse:{json:(body,o)=>({body,...o})}},'@/lib/supabase/server':{createClient:async()=>db},'@/lib/media/request':{smallJson:async r=>r.body},'@/lib/fuel/model':model,'@/lib/fuel/validation':validation});
 return {calls,run:(body=draft(),origin='https://ims.example.invalid')=>POST({body,nextUrl:{origin:'https://ims.example.invalid'},headers:{get:()=>origin}},{params:Promise.resolve({clientId:client})})};
}
test('actual Fuel route rejects anonymous, disabled, other-client and unrelated-trainer writes before RPC',async()=>{for(const opts of [{user:false},{deleted:true},{profileError:true},{subjectError:true},{role:'client',who:coach},{role:'trainer',assignment:client}]){const h=api(opts);assert.notEqual((await h.run()).status,200);assert.ok(!h.calls.includes('execute_fuel_command'));}});
test('actual Fuel route scopes authorship, validates origin and extra fields, and verifies complete receipt',async()=>{let h=api();assert.equal((await h.run()).status,200);assert.deepEqual(h.calls,['profiles','clients','execute_fuel_command']);h=api();assert.equal((await h.run(draft(),'https://other.example.invalid')).status,403);assert.equal(h.calls.length,0);h=api();assert.equal((await h.run({...draft(),client_id:coach})).status,400);h=api({role:'client',who:client});assert.equal((await h.run()).status,403);h=api({receipt:{ok:true}});assert.equal((await h.run()).status,503);});
test('Fuel backend errors are not fabricated success or empty results',async()=>{for(const [code,status] of [['42501',403],['40001',409],['PGRST202',503],['22023',400],['P0002',404]])assert.equal((await api({rpcError:{code}}).run()).status,status);assert.equal((await api({throws:true}).run()).status,503);});
function hookHarness(){const slots=[];let cursor=0,handler=async()=>{throw Error('offline')},refreshes=0;const react={useRef(value){const i=cursor++;if(!slots[i])slots[i]={current:value};return slots[i];},useState(value){const i=cursor++;if(!(i in slots))slots[i]=typeof value==='function'?value():value;return[slots[i],v=>{slots[i]=typeof v==='function'?v(slots[i]):v;}];}};
 const controls=load('components/fuel/controls.tsx',{'react':react,'react/jsx-runtime':{jsx:()=>null,jsxs:()=>null},'next/navigation':{useRouter:()=>({refresh:()=>refreshes++})},'@/lib/fuel/validation':validation},{fetch:(url,opts)=>handler(url,opts)});
 return {render(){cursor=0;return controls.useFuelMutation(client)},setHandler(h){handler=h},refreshes:()=>refreshes};}
const response=(body,status=200)=>({ok:status>=200&&status<300,status,json:async()=>body});
test('actual Fuel mutation hook prevents duplicate taps and preserves exact retry after a lost response and later 403',async()=>{const h=hookHarness(),sent=[];h.setHandler(async(url,options)=>{sent.push(options.body);throw Error('offline');});await h.render().submit(draft());assert.equal(h.render().uncertain,true);assert.equal(h.render().disabled,true);await h.render().submit({...draft(),request_id:client});assert.equal(sent.length,1);h.setHandler(async(url,o)=>{sent.push(o.body);return response({error:'expired session'},403)});await h.render().retry();assert.equal(h.render().uncertain,true);assert.equal(sent[0],sent[1]);h.setHandler(async(url,o)=>{sent.push(o.body);return response({ok:true,client_id:client,request_id:requestId,action:'save_plan',entity_id:coach,revision:1,deduped:true})});await h.render().retry();assert.equal(sent[1],sent[2]);assert.equal(h.refreshes(),1);assert.equal(h.render().disabled,true);await h.render().submit(draft());assert.equal(sent.length,3);});
test('actual Fuel mutation hook rejects malformed success receipt and does not announce success',async()=>{const h=hookHarness();h.setHandler(async()=>response({ok:true}));await h.render().submit(draft());assert.equal(h.render().uncertain,true);assert.equal(h.render().message,null);assert.equal(h.refreshes(),0);});
test('actual Fuel mutation hook locks concurrent submissions synchronously, not only after rerender',async()=>{const h=hookHarness();let finish,count=0;h.setHandler(()=>{count++;return new Promise(resolve=>{finish=resolve})});const state=h.render(),one=state.submit(draft());await state.submit(draft());assert.equal(count,1);finish(response({ok:true,client_id:client,request_id:requestId,action:'save_plan',entity_id:coach,revision:1,deduped:false}));await one;assert.equal(h.refreshes(),1);});
test('Fuel is linked to client profile, Today, Action Center and both desktop/mobile staff navigation',()=>{for(const file of ['app/clients/[id]/page.tsx','components/layout/app-sidebar.tsx','components/layout/staff-bottom-nav.tsx'])assert.ok(fs.readFileSync(path.join(root,file),'utf8').includes('/fuel'));assert.match(fs.readFileSync(path.join(root,'app/dashboard/page.tsx'),'utf8'),/FuelTodayCard/);assert.match(fs.readFileSync(path.join(root,'app/action-center/page.tsx'),'utf8'),/FuelReviewQueue/);});

test('coach adjustment candidates remain private copies until the existing explicit release gate',()=>{const forms=fs.readFileSync(path.join(root,'components/fuel/coach-forms.tsx'),'utf8'),workspace=fs.readFileSync(path.join(root,'components/fuel/workspace.tsx'),'utf8');assert.match(forms,/Create private adjustment candidate/);assert.match(forms,/origin:"coach_authored"/);assert.match(forms,/same prescription/);assert.doesNotMatch(forms,/action:"release_plan"/);assert.match(workspace,/FuelAdjustmentCandidate/);assert.match(workspace,/review\.disposition==="reviewed"/);});
