const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const ts=require('typescript');const crypto=require('node:crypto');
const root=path.join(__dirname,'..'),client='11111111-1111-4111-8111-111111111111',actor='22222222-2222-4222-8222-222222222222',id='33333333-3333-4333-8333-333333333333';
function load(file,deps={}){const source=ts.transpileModule(fs.readFileSync(path.join(root,file),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,exp={};new Function('require','exports',source)(n=>{if(!(n in deps))throw Error('Unexpected '+n);return deps[n]},exp);return exp;}
const model=load('lib/fuel/model.ts'),source=load('lib/fuel/source.ts'),bytes=new TextEncoder().encode('%PDF-1.7\nSynthetic original\n%%EOF');
function harness({user=true,allow=true,authError=false,uploadError=false,existingBytes=bytes,registryError=false}={}){const calls=[],q={select:()=>q,eq:()=>q,maybeSingle:async()=>({data:null,error:null})},db={auth:{getUser:async()=>({data:{user:user?{id:actor}:null}})},rpc:async(name,p)=>{calls.push([name,p]);return{data:allow,error:authError?{}:null}},from:()=>q};const svc={storage:{from:()=>({upload:async(path,data,options)=>{calls.push(['upload',path,data,options]);return{error:uploadError?{}:null}},download:async()=>({data:new Blob([existingBytes]),error:null})})},rpc:async(name,p)=>{calls.push([name,p]);return{error:registryError?{}:null,data:{ok:true,id:p.p_id,client_id:p.p_client,sha256:p.p_sha256,byte_size:p.p_bytes,deduped:false}}}};
 const {POST}=load('app/api/fuel/[clientId]/sources/route.ts',{'node:crypto':crypto,'next/server':{NextResponse:{json:(body,opts)=>({body,...opts})}},'@/lib/supabase/server':{createClient:async()=>db,createServiceClient:()=>{calls.push(['service']);return svc}},'@/lib/fuel/model':model,'@/lib/fuel/source':source});
 return {calls,run:async(origin='https://ims.example.invalid')=>{const req=new Request('https://ims.example.invalid/api/source',{method:'POST',headers:{origin,'content-type':'application/pdf','x-source-id':id,'x-source-name':'Synthetic.pdf'},body:bytes});Object.defineProperty(req,'nextUrl',{value:{origin:'https://ims.example.invalid'}});return POST(req,{params:Promise.resolve({clientId:client})})}};
}
test('actual source upload route cannot elevate before authentication and assignment checks',async()=>{for(const options of [{user:false},{allow:false},{authError:true}]){const h=harness(options);assert.notEqual((await h.run()).status,200);assert.ok(!h.calls.some(c=>c[0]==='service'));}const h=harness();assert.equal((await h.run('https://other.example.invalid')).status,403);assert.equal(h.calls.length,0);});
test('source upload preserves original bytes, uses canonical actor path and prevents overwrite',async()=>{const h=harness(),result=await h.run();assert.equal(result.status,200);const upload=h.calls.find(c=>c[0]==='upload');assert.equal(upload[1],`${client}/${actor}/${id}.pdf`);assert.deepEqual(upload[2],bytes);assert.equal(upload[3].upsert,false);assert.equal(result.body.sha256,crypto.createHash('sha256').update(bytes).digest('hex'));assert.equal(h.calls.find(c=>c[0]==='register_fuel_source')[1].p_actor,actor);});
test('a lost source response recovers only identical stored bytes, not changed content',async()=>{const good=harness({uploadError:true});assert.equal((await good.run()).status,200);const bad=harness({uploadError:true,existingBytes:new TextEncoder().encode('%PDF-1.7 DIFFERENT')});assert.equal((await bad.run()).status,409);assert.ok(!bad.calls.some(c=>c[0]==='register_fuel_source'));});
test('source registration failure is explicitly unconfirmed and never a published prescription',async()=>{const h=harness({registryError:true}),result=await h.run();assert.equal(result.status,503);assert.match(result.body.error,/registration is unconfirmed/);assert.ok(!h.calls.some(c=>/release|body_comp|execute_fuel_command/.test(c[0])));});
