const {test}=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs");
const health=fs.readFileSync("ios/IMSFitness/HealthStore.swift","utf8"),session=fs.readFileSync("ios/IMSFitness/SessionStore.swift","utf8"),web=fs.readFileSync("ios/IMSFitness/WebSurface.swift","utf8"),app=fs.readFileSync("ios/IMSFitness/IMSFitnessApp.swift","utf8"),ent=fs.readFileSync("ios/IMSFitness/IMSFitness.entitlements","utf8"),sql=fs.readFileSync("packages/db/migrations/0083_apple_health_daily.sql","utf8"),clientApi=fs.readFileSync("app/api/clients/route.ts","utf8");
test("native web login cookies are adopted before native API authentication",()=>{assert.match(web,/adoptWebCookies/);assert.match(session,/HTTPCookieStorage\.shared\.setCookie/);assert.match(session,/await bootstrap\(\)/);});
test("Health connection is a deliberate native Progress action",()=>{assert.match(app,/ProgressHealthView/);assert.match(app,/Connect \/ refresh Apple Health/);assert.match(app,/Missing access is never treated as zero or failure/);});
test("Health entitlement is read-only and background delivery is deferred until observers are device-tested",()=>{assert.match(ent,/com\.apple\.developer\.healthkit/);assert.doesNotMatch(ent,/background-delivery/);});
test("sleep intervals are merged so overlapping Health sources do not double-count sleep",()=>{assert.match(health,/var merged:/);assert.match(health,/interval\.0<=last\.1/);assert.match(health,/merged\.reduce/);});
test("weight source and timezone context survive Health sync",()=>{assert.match(health,/sourceRevision\.source\.name/);assert.match(health,/calendar\.timeZone\.identifier/);assert.match(sql,/weight_source text/);assert.match(sql,/time_zone text/);assert.match(sql,/utc_offset_minutes integer/);});
test("Health table never turns unavailable types into zero",()=>{assert.match(sql,/case when 'steps'=any\(types\).*else null end/s);assert.match(sql,/case when 'weight'=any\(types\).*else null end/s);});
test("direct client creation validates optional plans before auth identity creation",()=>{const validate=clientApi.indexOf("Validate the optional plan before creating an auth identity"),create=clientApi.indexOf("auth.admin.createUser");assert(validate>=0&&create>validate);assert.match(clientApi,/Coach OS packages currently support training only/);});

test("Health data is explicitly barred from growth and marketing use",()=>{const boundary=fs.readFileSync("docs/HEALTH-DATA-BOUNDARY.md","utf8"),growth=fs.readFileSync("components/leads/growth-workspace.tsx","utf8"),research=fs.readFileSync("lib/leads/research.ts","utf8");assert.match(boundary,/Prohibited product use/);assert.match(boundary,/Growth Center, Research Desk/);assert.match(boundary,/advertising/);assert.doesNotMatch(growth,/client_health_daily|HealthKit|Apple Health/);assert.doesNotMatch(research,/client_health_daily|HealthKit|Apple Health/);});

test("Health sync uses device-local days and sparse JSON so missing values cannot serialize as fake data",()=>{const health=fs.readFileSync("ios/IMSFitness/HealthStore.swift","utf8");assert.match(health,/value\\s*\.timeZone\\s*=\\s*\.current/);assert.match(health,/formatter\.timeZone=calendar\.timeZone/);assert.match(health,/var payload:\[String:Any\]/);assert.match(health,/if let v=values\.0\{payload\["steps"\]=v\}/);assert.doesNotMatch(health,/"steps":values\.0 as Any/);});

test("Health refreshes device timezone before each sync batch",()=>{assert.match(health,/refreshed\\s*\.timeZone\\s*=\\s*\.current;\\s*calendar\\s*=\\s*refreshed/);assert.match(health,/formatter\.timeZone=calendar\.timeZone/);});
