const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const ts=require('typescript');
const root=path.join(__dirname,'..'),id='11111111-1111-4111-8111-111111111111';
function load(file,deps={}){const code=ts.transpileModule(fs.readFileSync(path.join(root,file),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText;const loaded={exports:{}};new Function('require','exports',code)(name=>{if(!(name in deps))throw Error('Unexpected import '+name);return deps[name];},loaded.exports);return loaded.exports;}
function harness(kind='client',frozen=false){let cursor=0;const state=[],requests=[];let refreshes=0;const useState=initial=>{const index=cursor++;if(!(index in state))state[index]=typeof initial==='function'?initial():initial;return[state[index],next=>{state[index]=typeof next==='function'?next(state[index]):next;}];};const useRef=initial=>{const index=cursor++;if(!(index in state))state[index]={current:initial};return state[index];};
 const {OwnerReviewForm}=load('components/migration/owner-review-form.tsx',{'react':{useState,useRef},'next/navigation':{useRouter:()=>({refresh:()=>{refreshes++;}})},'react/jsx-runtime':{jsx:(type,props)=>({type,props}),jsxs:(type,props)=>({type,props})},'@/lib/migration/owner-review':load('lib/migration/owner-review.ts')});
 const props={recordId:id,sourceHash:'a'.repeat(64),kind,latest:null,clients:[{id,full_name:'Synthetic client',email:'client@example.invalid'}],trainers:[{id,full_name:'Synthetic coach',email:'coach@example.invalid'}],frozen};
 function render(){cursor=0;return OwnerReviewForm(props);}function nodes(node){if(!node||typeof node!=='object')return[];if(Array.isArray(node))return node.flatMap(nodes);return[node,...nodes(node.props?.children)];}function text(n){if(n==null||typeof n==='boolean')return'';if(Array.isArray(n))return n.map(text).join(' ');if(typeof n!=='object')return String(n);return text(n.props?.children);}
 const find=(label)=>nodes(render()).find(n=>n.props?.['aria-label']===label);const change=(label,value)=>find(label).props.onChange({target:{value}});
 function complete(){change('Destination client',id);change('Review decision','reviewed');change('Reason and evidence checked','Owner checked synthetic source documents.');nodes(render()).find(n=>n.type==='input'&&n.props.type==='checkbox').props.onChange({target:{checked:true}});}
 const submit=()=>nodes(render()).find(n=>n.type==='button'&&/Save owner review|Retry exact review|Confirming save/.test(text(n))).props.onClick();
 return{requests,render,nodes,text,find,change,complete,submit,refreshes:()=>refreshes,receipt:r=>({ok:true,status:200,json:async()=>({ok:true,request_id:r.request_id,record_id:id,revision:r.expected_revision+1,source_hash:r.source_hash,decision:r.decision})})};}
const tick=()=>new Promise(resolve=>setImmediate(resolve));
test('form requires a reviewed decision to be confirmed and never prefills a source balance',async()=>{const h=harness('package'),original=global.fetch;let calls=0;global.fetch=async()=>{calls++;throw Error('unexpected')};try{assert.equal(h.find('Verified sessions remaining').props.value,'');assert.equal(h.find('Owner-reported paid amount ($)').props.value,'');h.change('Destination client',id);h.change('Review decision','reviewed');h.change('Reason and evidence checked','Synthetic source checked by owner.');h.submit();await tick();assert.equal(calls,0);assert.match(h.text(h.render()),/confirmation is required/i);}finally{global.fetch=original;}});
test('actual form saves verified zero and unknown money distinctly, and rejects a double tap',async()=>{const h=harness('package'),original=global.fetch;global.fetch=async(_url,options)=>{const r=JSON.parse(options.body);h.requests.push(r);return h.receipt(r)};try{h.change('Opening balance as of','2026-01-01');h.change('Verified sessions remaining','0');h.complete();h.submit();h.submit();await tick();assert.equal(h.requests.length,1);assert.equal(h.requests[0].proposal.sessions_remaining,0);assert.equal(h.requests[0].proposal.amount_paid_cents,null);assert.equal(h.refreshes(),1);assert.match(h.text(h.render()),/Not imported/);}finally{global.fetch=original;}});
test('ambiguous form save locks edits and retries the exact preserved request',async()=>{const h=harness(),original=global.fetch;global.fetch=async(_url,options)=>{const r=JSON.parse(options.body);h.requests.push(r);if(h.requests.length===1)throw Error('lost response');return h.receipt(r)};try{h.complete();h.submit();await tick();assert.equal(h.nodes(h.render()).find(n=>n.type==='fieldset').props.disabled,true);assert.equal(h.refreshes(),0);h.submit();await tick();assert.deepEqual(h.requests[1],h.requests[0]);assert.equal(h.refreshes(),1);}finally{global.fetch=original;}});
test('invalid success receipt is not saved and frozen records cannot submit',async()=>{const original=global.fetch;let calls=0;global.fetch=async()=>{calls++;return{ok:true,status:200,json:async()=>({ok:true})}};try{let h=harness();h.complete();h.submit();await tick();assert.equal(h.refreshes(),0);assert.match(h.text(h.render()),/not confirmed/);h=harness('client',true);h.submit();await tick();assert.equal(calls,1);}finally{global.fetch=original;}});
