const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const ts=require('typescript');
const root=path.join(__dirname,'..'),id='11111111-1111-4111-8111-111111111111';
function load(file,deps={}){const code=ts.transpileModule(fs.readFileSync(path.join(root,file),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText;const loaded={exports:{}};new Function('require','exports',code)(name=>{if(!(name in deps))throw Error('Unexpected import '+name);return deps[name];},loaded.exports);return loaded.exports;}
function harness({role='owner',deleted=false,user=true,failReview=false,failSource=false,empty=false,batchStatus='draft'}={}){
 const calls=[];const db={auth:{getUser:async()=>({data:{user:user?{id}:null}})},from(table){calls.push(table);const result=()=>({data:failReview&&table.includes('review')?null:[],error:failReview&&table.includes('review')?{}:null});const q={select(){return q},eq(){return q},order(){return q},is(){return q},in(){return q},limit(){return q},then(resolve,reject){return Promise.resolve(result()).then(resolve,reject)},maybeSingle:async()=>({data:table==='profiles'?{role,deleted_at:deleted?'2026-01-01':null}:{id,label:'Synthetic batch',status:batchStatus},error:null}),range:async()=>{
 if(table==='migration_records')return{data:failSource?null:empty?[]:[{id,source_id:'synthetic',source_hash:'a'.repeat(64),record_type:'client',reconciliation_status:'unmatched',source_payload:{fields:{'Source Name':'Synthetic client'}}}],count:failSource?null:empty?0:1,error:failSource?{}:null};
 const data=table==='clients'?[{id}]:[{id,role:'client',full_name:'Synthetic client',email:'client@example.invalid'}];return{data,count:data.length,error:null};}};return q;}};
 const Page=load('app/settings/migration/review/page.tsx',{'next/link':{default:'a'},'next/navigation':{redirect:to=>{throw Error('redirect:'+to)},notFound:()=>{throw Error('not-found')}},'@/components/layout/app-shell':{AppShell:'shell'},'@/lib/supabase/server':{createClient:async()=>db},'@/lib/migration/complete-read':{readCompleteEvidence:async fn=>{const r=await fn(0,249);if(r.error)throw Error('query failed');return r.data}},'@/lib/migration/owner-review':load('lib/migration/owner-review.ts'),'@/components/migration/owner-review-form':{OwnerReviewForm:'review-form'},'react/jsx-runtime':{jsx:(type,props)=>({type,props}),jsxs:(type,props)=>({type,props})}}).default;
 return{calls,render:()=>Page({searchParams:Promise.resolve({batch:id})})};}
function nodes(n){if(!n||typeof n!=='object')return[];if(Array.isArray(n))return n.flatMap(nodes);return[n,...nodes(n.props?.children)];}
function text(n){if(n==null||typeof n==='boolean')return'';if(Array.isArray(n))return n.map(text).join(' ');if(typeof n!=='object')return String(n);return text(n.props?.children);}
test('actual review page rejects other roles before source, identity or financial reads',async()=>{for(const option of [{user:false},{role:'trainer'},{role:'client'},{deleted:true}]){const h=harness(option);await assert.rejects(h.render());assert.ok(!h.calls.includes('migration_records'));assert.ok(!h.calls.includes('clients'));}});
test('failed review storage removes the save form rather than inventing no reviews',async()=>{const h=harness({failReview:true}),page=await h.render();assert.match(text(page),/Owner review is unavailable/);assert.equal(nodes(page).some(n=>n.type==='review-form'),false);});
test('source failures are not empty batches; real empty source shows no save form',async()=>{await assert.rejects(harness({failSource:true}).render(),/Source evidence unavailable/);const page=await harness({empty:true}).render();assert.match(text(page),/No saved/);assert.equal(nodes(page).some(n=>n.type==='review-form'),false);});
test('frozen batch renders historical evidence with disabled editor and no operational writes',async()=>{const h=harness({batchStatus:'approved'}),page=await h.render();assert.equal(nodes(page).find(n=>n.type==='review-form').props.frozen,true);assert.ok(!h.calls.some(t=>['sessions','plans','payments'].includes(t)));assert.match(text(page),/not import approvals/);});
