const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),ts=require('typescript');
const root=path.join(__dirname,'..');
function load(file,deps={},globals={}){const out={},code=ts.transpileModule(fs.readFileSync(path.join(root,file),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText;new Function('require','exports',...Object.keys(globals),code)(key=>{if(!(key in deps))throw Error('Unexpected '+key);return deps[key];},out,...Object.values(globals));return out;}
const zod=require('zod'),model=load('lib/fuel/model.ts'),bodPdf=load('lib/fuel/bod-pod-pdf.ts',{'./model':model}),report=load('lib/fuel/report.ts',{'zod':zod,'./model':model,'./bod-pod-pdf':bodPdf}),nutrition=load('lib/fuel/nutrition.ts',{'zod':zod,'./model':model,'./report':report}),foods=load('lib/fuel/foods.ts'),validation=load('lib/fuel/validation.ts',{'zod':zod,'./model':model}),requests=load('lib/fuel/nutrition-request.ts',{'zod':zod,'./report':report,'./nutrition':nutrition,'./validation':validation});
const m={date:'2026-09-28',weight_lb:200,body_fat_pct:25,lean_pct:75,fat_mass_lb:50,lean_mass_lb:150,model_label:'Synthetic test model'};
const input={age:45,height_cm:180,equation_coefficient:'male',activity:'moderate',goal:'maintenance',training_days:3,diet:'mixed',meals_per_day:'3',budget:'economy',prep:'batch',avoid:[],other_food_restrictions:'',preferences:'Synthetic preference',screen:{pregnancy_or_breastfeeding:'no',eating_disorder_or_restrictive_history:'no',medical_nutrition_or_medication:'no',unexplained_symptoms_or_weight_change:'no',high_training_demand:'no'},food_reviewed:true};
test('source screenshots keep percentages and pounds distinct, preserve rounding and never invent identity/date',()=>{const result={document_kind:'bod_pod_screen',person_name:null,test_date:null,model_label:'Lohman',observations:[{field:'fat_pct',value:25,unit:'percent',quote:'Fat = 25.0%',location:'screen'}],warnings:[]};assert.ok(report.reportExtractionSchema.safeParse(result).success);const merged=report.mergeReportCandidates([result]);assert.equal(merged.date,null);assert.deepEqual(merged.candidates,{fat_pct:25});assert.equal(merged.candidates.weight,undefined);assert.equal(report.reportExtractionSchema.safeParse({...result,observations:[{...result.observations[0],unit:'lb'}]}).success,false);});
test('blank IMS reference-table percentages are never accepted as result observations',()=>{const result={document_kind:'blank_template',person_name:null,test_date:null,model_label:null,observations:[],warnings:[]};assert.ok(report.reportExtractionSchema.safeParse(result).success);assert.equal(report.reportExtractionSchema.safeParse({...result,observations:[{field:'fat_pct',value:30,unit:'percent',quote:'reference 30%',location:'table'}]}).success,false);assert.match(report.REPORT_PROMPT,/prechecked goal boxes/);assert.match(report.REPORT_PROMPT,/blank_template/);});
test('exact IMS fillable worksheet fields parse locally while reference-table numbers are ignored',()=>{
 const field=(name,value)=>'1 0 obj << /T ('+name+') /V ('+value+') >> endobj\\n';
 const filled=Buffer.from(field('Name','Synthetic Client')+field('Date','09/28/2026')+field('Text10','21.0')+field('Text11','79.0')+field('Text12','147.3')+field('Text13','116.5')+field('Text14','30.8')+field('Text15','reference 30% 40% 15%'));
 const out=report.extractLocalImsBodPod(filled);assert.equal(out.document_kind,'body_composition_report');assert.equal(out.person_name,'Synthetic Client');assert.equal(out.test_date,'2026-09-28');assert.deepEqual(Object.fromEntries(out.observations.map(o=>[o.field,o.value])),{weight:147.3,fat_pct:21,lean_pct:79,fat_mass:30.8,lean_mass:116.5});assert.equal(out.observations.some(o=>o.value===40||o.value===15),false);
 const blank=Buffer.from(field('Name','')+field('Date','')+field('Text10','')+field('Text11','')+field('Text12','')+field('Text13','')+field('Text14','')+field('Text15','>30% 21-30% 13-20% 9-12%'));
 const blankOut=report.extractLocalImsBodPod(blank);assert.equal(blankOut.document_kind,'blank_template');assert.deepEqual(blankOut.observations,[]);
});
test('conflicting photos leave fields unresolved; kg conversions are explicit and non-mutating',()=>{const base={document_kind:'bod_pod_screen',person_name:null,test_date:null,model_label:null,warnings:[],observations:[{field:'weight',value:100,unit:'kg',quote:'100 kg',location:'screen'}]};const before=JSON.stringify(base),out=report.mergeReportCandidates([base]);assert.equal(out.candidates.weight,220.4623);assert.equal(JSON.stringify(base),before);assert.deepEqual(report.mergeReportCandidates([base,{...base,observations:[{...base.observations[0],value:90}]}]).conflicts,['weight']);});
test('reported values are not silently reconciled and clinical reference tables do not drive nutrition',()=>{assert.equal(report.measurementWarnings(m).length,0);const bad={...m,lean_mass_lb:210};assert.ok(report.measurementWarnings(bad).length);assert.throws(()=>nutrition.calculateNutrition(bad,input,'2026-09-28'),/conflicting/);assert.equal(bad.lean_mass_lb,210);});
test('calculation is reproducible, labeled estimated, preserves baseline, and uses no invented rest-day deficit',()=>{const before=JSON.stringify(m),n=nutrition.calculateNutrition(m,input,'2026-09-28');assert.equal(n.rmr,1812);assert.equal(n.maintenance,2628);assert.equal(n.proposed.kcal,2625);assert.equal(n.proposed.protein_g,145);const plan=nutrition.nutritionStrategy('Synthetic',m,input,n,'2026-09-28');assert.ok(validation.fuelPlanSchema.safeParse(plan).success);assert.deepEqual(plan.phases[0].training,plan.phases[0].rest);assert.equal(JSON.stringify(m),before);assert.match(plan.guidance,/Not measured metabolism/);assert.equal(plan.review_on,'2026-10-12');});
test('all unknown or positive screening answers pause automated targets',()=>{for(const key of Object.keys(input.screen)){for(const value of ['yes','unknown'])assert.throws(()=>nutrition.calculateNutrition(m,{...input,screen:{...input.screen,[key]:value}},'2026-09-28'),/professional review/);}assert.throws(()=>nutrition.calculateNutrition(m,{...input,age:17},'2026-09-28'));assert.throws(()=>nutrition.calculateNutrition(m,{...input,equation_coefficient:''},'2026-09-28'));});
test('future/stale tests, restricted-energy and out-of-pathway body size cannot silently produce targets',()=>{for(const date of ['2027-01-01','2025-01-01'])assert.throws(()=>nutrition.calculateNutrition({...m,date},input,'2026-09-28'));assert.throws(()=>nutrition.calculateNutrition({...m,weight_lb:90,body_fat_pct:null,lean_pct:null,fat_mass_lb:null,lean_mass_lb:null},input,'2026-09-28'),/outside/);});
test('food restrictions withhold menu instead of assuming safe substitutions',()=>{assert.equal(foods.menuEligibility(input),null);assert.match(foods.menuEligibility({...input,avoid:['milk']}),/restriction/);assert.match(foods.menuEligibility({...input,other_food_restrictions:'sesame allergy'}),/manual/);assert.equal(foods.menuEligibility({...input,diet:'plant',avoid:['milk']}),null);assert.match(foods.menuEligibility({...input,diet:'plant',avoid:['soy']}),/restriction/);});
test('food facts must match exact entry and preparation state; missing nutrients are not zero',()=>{const row={fdcId:12345,dataType:'SR Legacy',description:foods.FOOD_SPECS.chicken.description,foodNutrients:[{nutrientId:1008,unitName:'kcal',value:165},{nutrientId:1003,unitName:'g',value:31},{nutrientId:1004,unitName:'g',value:3.6},{nutrientId:1005,unitName:'g',value:0}]};assert.equal(foods.parseFoodFact('chicken',row).per100.carbs_g,0);assert.throws(()=>foods.parseFoodFact('chicken',{...row,foodNutrients:row.foodNutrients.slice(0,3)}),/unavailable/);assert.throws(()=>foods.parseFoodFact('chicken',{...row,description:'raw chicken'}),/Exact/);});
test('source reader bounds actual bytes and supports photos without pretending HEIC is JPEG',async()=>{const jpeg=new Uint8Array([255,216,255,224,0,2,0,0,255,217]);const r=await report.readReport(new Request('https://test.invalid',{method:'POST',headers:{'Content-Type':'image/jpeg'},body:jpeg}));assert.deepEqual(r.bytes,jpeg);await assert.rejects(report.readReport(new Request('https://test.invalid',{method:'POST',headers:{'Content-Type':'image/png'},body:jpeg})),/signature/);await assert.rejects(report.readReport(new Request('https://test.invalid',{method:'POST',headers:{'Content-Type':'image/heic'},body:jpeg})),/HEIC/);await assert.rejects(report.readReport(new Request('https://test.invalid',{method:'POST',headers:{'Content-Type':'image/jpeg'},body:new Uint8Array(report.REPORT_LIMIT+1)})),/3 MB/);});
test('provider is opt-in, fixed-host, structured-output-only and sends no client profile',async()=>{let sent;const provider=load('lib/fuel/report-provider.ts',{'./report':report},{process:{env:{FUEL_REPORT_READER_ENABLED:'true',FUEL_REPORT_READER_API_KEY:'synthetic-only'}},fetch:async(url,o)=>{sent={url,body:JSON.parse(o.body)};return{ok:true,text:async()=>JSON.stringify({status:'completed',output:[{type:'message',content:[{type:'output_text',text:JSON.stringify({document_kind:'blank_template',person_name:null,test_date:null,model_label:null,observations:[],warnings:[]})}]}]})};}});const r=await provider.extractReport(new Uint8Array([1,2,3]),'image/jpeg');assert.equal(r.document_kind,'blank_template');assert.equal(sent.url,'https://api.openai.com/v1/responses');assert.equal(sent.body.store,false);assert.equal(sent.body.text.format.strict,true);assert.equal(sent.body.input[0].content[0].type,'input_image');assert.equal('client_id' in sent.body,false);});
test('partial or invalid extraction never becomes a successful read',async()=>{for(const body of [{status:'incomplete',output:[]},{status:'completed',output:[{type:'message',content:[{type:'refusal'}]}]},{status:'completed',output:[]}]){const provider=load('lib/fuel/report-provider.ts',{'./report':report},{process:{env:{FUEL_REPORT_READER_ENABLED:'true',FUEL_REPORT_READER_API_KEY:'synthetic-only'}},fetch:async()=>({ok:true,text:async()=>JSON.stringify(body)})});await assert.rejects(provider.extractReport(new Uint8Array([1]),'application/pdf'));}});
const client='11111111-1111-4111-8111-111111111111',id='22222222-2222-4222-8222-222222222222',mid='33333333-3333-4333-8333-333333333333';
test('paired save receipt requires both action-specific request IDs and client scope',()=>{const rec=(action,request_id)=>({ok:true,action,request_id,client_id:client,entity_id:request_id,revision:1,deduped:false}),r={ok:true,client_id:client,measurement:rec('record_body_comp',mid),strategy:rec('save_plan',id)};assert.ok(requests.validNutritionReceipt(r,id,mid,client));assert.equal(requests.validNutritionReceipt({...r,measurement:null},id,mid,client),false);assert.equal(requests.validNutritionReceipt(r,id,mid,id),false);});
function hooks(){const slots=[];let cursor=0,handler;const react={useRef(v){const n=cursor++;if(!slots[n])slots[n]={current:v};return slots[n];},useState(v){const n=cursor++;if(!(n in slots))slots[n]=v;return[slots[n],x=>{slots[n]=x;}];}};const hook=load('components/fuel/use-nutrition-save.tsx',{'react':react,'@/lib/fuel/nutrition-request':requests},{fetch:(...a)=>handler(...a)}).useNutritionSave;return{render(){cursor=0;return hook(client);},set(h){handler=h;}};}
test('lost paired save locks inputs and replays exactly, including after later permission rejection',async()=>{const h=hooks(),sent=[],plan=nutrition.nutritionStrategy('Synthetic',m,input,nutrition.calculateNutrition(m,input,'2026-09-28'),'2026-09-28'),body={action:'save',measurement:m,intake:input,sources:[{id,sha256:'a'.repeat(64)}],same_person_test_confirmed:true,reported_values_confirmed:true,content:plan,expected_revision:0,request_id:id,measurement_request_id:mid,strategy_reviewed:true};h.set(async(_,o)=>{sent.push(o.body);throw Error('lost');});await h.render().save(body);assert.ok(h.render().uncertain);h.set(async(_,o)=>{sent.push(o.body);return{ok:false,status:403,json:async()=>({})};});await h.render().retry();assert.ok(h.render().uncertain);await h.render().save({...body,request_id:client});assert.equal(sent.length,2);assert.equal(new Set(sent).size,1);});
test('sample meal totals and three-day groceries use sourced portions without changing targets',()=>{const per100={kcal:100,protein_g:10,carbs_g:10,fat_g:2};const facts=Object.keys(foods.FOOD_SPECS).map((key,n)=>({key,fdcId:900000+n,description:'Isolated synthetic composition fixture',source:'https://example.invalid/fixture/'+key,retrievedAt:'2026-09-28T00:00:00Z',per100:{...per100}}));const target={kcal:1360,protein_g:136,carbs_g:136,fat_g:27.2},before=JSON.stringify(target),menu=foods.createMenus(input,target,facts);assert.equal(menu.meals.length,3);assert.equal(menu.summaries.length,1);for(const key of ['kcal','protein_g','carbs_g','fat_g'])assert.ok(Math.abs(menu.meals.reduce((s,m)=>s+m.targets[key],0)-menu.summaries[0].totals[key])<0.4);assert.equal(menu.summaries[0].energyDifference,0);assert.equal(JSON.stringify(target),before);assert.ok(menu.grocery.every(g=>g.includes('3 repetitions')));const base=nutrition.nutritionStrategy('Synthetic',m,input,nutrition.calculateNutrition(m,input,'2026-09-28'),'2026-09-28');assert.ok(validation.fuelPlanSchema.safeParse(foods.attachMenu(base,menu,facts)).success);assert.throws(()=>foods.createMenus(input,{kcal:10000,protein_g:900,carbs_g:1200,fat_g:200},facts),/cannot fit/);});
test('missing food connection is an explicit unavailable state, not fallback invented nutrients',async()=>{const offline=load('lib/fuel/foods.ts',{}, {process:{env:{}}});await assert.rejects(offline.loadFoodFacts(['oats']),/not configured/);});
test('all source-history downloads use the MIME-aware authorized report route',()=>{const source=fs.readFileSync(path.join(root,'components/fuel/source-documents.tsx'),'utf8');assert.ok(source.includes('reports?id=${row.id}'));});
