const {test,before,after}=require('node:test'),assert=require('node:assert/strict'),{randomUUID}=require('node:crypto'),fs=require('node:fs'),path=require('node:path');
const live=process.env.IMS_TEST_DATABASE_URL,owner=randomUUID(),coach=randomUUID(),other=randomUUID(),client=randomUUID(),disabled=randomUUID();let db,admin,name;
before(async()=>{if(live){const u=new URL(live);if(!['127.0.0.1','localhost'].includes(u.hostname)||u.pathname!='/ims_ci')throw Error('Only isolated test database');const {Client}=require('pg');admin=new Client({connectionString:live});await admin.connect();name='ims_nutrition_'+randomUUID().replaceAll('-','');await admin.query('create database "'+name+'"');u.pathname='/'+name;const pg=new Client({connectionString:u.toString()});await pg.connect();db={exec:s=>pg.query(s),query:(s,p)=>pg.query(s,p),close:()=>pg.end()};}else{const {PGlite}=await import('@electric-sql/pglite');db=new PGlite();}
 await db.exec(`create schema auth;create schema storage;do $$begin create role authenticated;exception when duplicate_object then null;end$$;do $$begin create role anon;exception when duplicate_object then null;end$$;do $$begin create role service_role;exception when duplicate_object then null;end$$;
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 grant usage on schema public,auth,storage to authenticated,anon,service_role;
 create table public.profiles(id uuid primary key,role text not null,deleted_at timestamptz);create table public.clients(id uuid primary key references public.profiles(id),primary_trainer_id uuid references public.profiles(id));
 create type public.bodycomp_method as enum('bod_pod','dexa','inbody','scale','calipers');create table public.body_comp_records(id uuid primary key default gen_random_uuid(),client_id uuid,recorded_at date,weight_lb numeric(5,2),body_fat_pct numeric(4,2),lean_mass_lb numeric(5,2),method public.bodycomp_method);
 create table public.audit_logs(id uuid primary key,actor_id uuid,action text,entity_type text,entity_id uuid,changes jsonb);
 create table storage.buckets(id text primary key,name text,public boolean,file_size_limit integer,allowed_mime_types text[]);create table storage.objects(bucket_id text,name text,primary key(bucket_id,name));
 alter table storage.objects enable row level security;grant all on storage.objects to anon,authenticated;create policy legacy_objects on storage.objects for all to anon,authenticated using(true) with check(true);
 grant select on public.profiles,public.clients to authenticated;
 insert into public.profiles values('${owner}','owner',null),('${coach}','trainer',null),('${other}','trainer',null),('${client}','client',null),('${disabled}','owner',now());insert into public.clients values('${client}','${coach}');`);
 for(const f of ['0078_fuel_performance.sql','0079_fuel_private_sources.sql','0093_nutrition_report_builder.sql'])await db.exec(fs.readFileSync(path.join(__dirname,'../packages/db/migrations',f),'utf8'));
});
after(async()=>{await db?.close();if(admin){try{await admin.query('drop database "'+name+'"')}finally{await admin.end()}}});
async function raw(s,p=[]){await db.exec('reset role');return(await db.query(s,p)).rows;}
async function role(id,as='authenticated'){await db.exec('reset role;set role '+as);await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);}
async function original(mime='image/jpeg',actor=coach){const id=randomUUID(),ext={'image/jpeg':'jpg','image/png':'png','application/pdf':'pdf'}[mime];await raw('insert into storage.objects values($1,$2)',['fuel-sources',`${client}/${actor}/${id}.${ext}`]);await role(actor,'service_role');return(await db.query('select register_fuel_report_source($1,$2,$3,$4,$5,$6,$7) result',[actor,client,id,'Synthetic.'+ext,'a'.repeat(64),100,mime])).rows[0].result;}
const plan=()=>({schema_version:1,title:'Synthetic nutrition draft',goal:'Synthetic goal',start:'2026-01-01',end:'2026-01-28',event_date:null,mode:'habits',habits:['fuel'],phases:[{name:'Foundation',start:'2026-01-01',end:'2026-01-28',focus:'Review',training:{kcal:null,protein_g:null,carbs_g:null,fat_g:null},rest:{kcal:null,protein_g:null,carbs_g:null,fat_g:null}}],meals:[],grocery:[],guidance:'Synthetic only',review_on:null});
async function commands(source){const rev=(await raw('select count(*)::int n from fuel_plan_versions where client_id=$1',[client]))[0].n;return{measure:{action:'record_body_comp',request_id:randomUUID(),date:'2026-01-01',weight_lb:200,body_fat_pct:25,lean_mass_lb:150,method:'bod_pod',source_kind:'source_transcription',source_reference:'placeholder',protocol:'Synthetic protocol',confirmed:true},strategy:{action:'save_plan',request_id:randomUUID(),expected_revision:rev,content:plan(),origin:'coach_authored',source_reference:'placeholder'},sources:[{id:source.id,sha256:source.sha256}]};}
async function save(c){return(await db.query('select save_fuel_nutrition_draft($1,$2,$3,$4) result',[client,JSON.stringify(c.measure),JSON.stringify(c.strategy),JSON.stringify(c.sources)])).rows[0].result;}
test('photos and PDFs share private immutable originals without changing existing PDF paths',async()=>{for(const mime of ['image/jpeg','image/png','application/pdf']){const s=await original(mime);const r=(await raw('select content_type,storage_path from fuel_source_documents where id=$1',[s.id]))[0];assert.equal(r.content_type,mime);assert.match(r.storage_path,new RegExp(s.id));await role(client);assert.equal((await db.query('select * from fuel_source_documents where id=$1',[s.id])).rows.length,0);}await role(other);assert.equal((await db.query('select * from storage.objects')).rows.length,0);});
test('report registration and paid-reading reservation are service-only, with active owner/assignment revalidation',async()=>{const s=await original();for(const who of [owner,coach,client,other]){await role(who);await assert.rejects(db.query('select reserve_fuel_report_read($1,$2,$3,$4)',[who,client,s.id,randomUUID()]),/permission denied/);}for(const who of [client,other,disabled]){await role(owner,'service_role');await assert.rejects(db.query('select reserve_fuel_report_read($1,$2,$3,$4)',[who,client,s.id,randomUUID()]),/coach required/);}});
test('paired save commits baseline and private version once, and never releases it',async()=>{const s=await original(),c=await commands(s);await role(coach);const first=await save(c),again=await save(c);assert.equal(first.ok,true);assert.equal(again.measurement.deduped,true);assert.equal(again.strategy.deduped,true);assert.equal(first.measurement.entity_id,again.measurement.entity_id);assert.equal((await raw('select count(*)::int n from fuel_plan_releases'))[0].n,0);assert.match((await raw('select source_reference from fuel_plan_versions where id=$1',[first.strategy.entity_id]))[0].source_reference,/body_comp:/);});
test('failed second command rolls back its new baseline and audit receipts',async()=>{const s=await original(),c=await commands(s),before=(await raw('select count(*)::int n from body_comp_records'))[0].n;c.strategy.expected_revision=999;await role(coach);await assert.rejects(save(c),/changed/);assert.equal((await raw('select count(*)::int n from body_comp_records'))[0].n,before);assert.equal((await raw('select count(*)::int n from fuel_command_receipts where request_id=$1',[c.measure.request_id]))[0].n,0);});
test('unrelated trainer, disabled account, client and anonymous calls cannot save nutrition',async()=>{const s=await original(),c=await commands(s);for(const who of [other,disabled,client]){await role(who);await assert.rejects(save(c),/coach required/);}await role(client,'anon');await assert.rejects(save(c),/permission denied/);});
test('wrong source hash, false baseline confirmation and release action are rejected independently of API',async()=>{const s=await original(),c=await commands(s);await role(coach);await assert.rejects(save({...c,sources:[{id:s.id,sha256:'b'.repeat(64)}]}),/mismatch/);await assert.rejects(save({...c,measure:{...c.measure,confirmed:false}}));await assert.rejects(save({...c,strategy:{...c.strategy,action:'release_plan'}}),/private nutrition/);});
test('paid reads are capped across sources; duplicate request never silently starts another call',async()=>{const s=await original(),request=randomUUID();await role(coach,'service_role');await db.query('select reserve_fuel_report_read($1,$2,$3,$4)',[coach,client,s.id,request]);await assert.rejects(db.query('select reserve_fuel_report_read($1,$2,$3,$4)',[coach,client,s.id,request]),/already attempted/);for(let n=1;n<30;n++)await db.query('select reserve_fuel_report_read($1,$2,$3,$4)',[coach,client,s.id,randomUUID()]);await assert.rejects(db.query('select reserve_fuel_report_read($1,$2,$3,$4)',[coach,client,s.id,randomUUID()]),/hourly limit/);await role(client);assert.equal((await db.query('select * from fuel_report_read_attempts')).rows.length,0);});
test('reopening the wizard with new request IDs does not duplicate the same source test',async()=>{const s=await original(),first=await commands(s);await role(coach);await save(first);const before=(await raw('select count(*)::int n from body_comp_records'))[0].n,next=await commands(s);await role(coach);await assert.rejects(save(next),/already recorded/);assert.equal((await raw('select count(*)::int n from body_comp_records'))[0].n,before);assert.equal((await raw('select count(*)::int n from fuel_command_receipts where request_id=$1',[next.measure.request_id]))[0].n,0);});
