const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),ts=require('typescript');
const root=path.join(__dirname,'..'),client='11111111-1111-4111-8111-111111111111',actor='22222222-2222-4222-8222-222222222222',id='33333333-3333-4333-8333-333333333333',requestId='44444444-4444-4444-8444-444444444444';
function load(file,deps={},globals={}){const out={},code=ts.transpileModule(fs.readFileSync(path.join(root,file),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;new Function('require','exports',...Object.keys(globals),code)(n=>{if(!(n in deps))throw Error('Unexpected '+n);return deps[n];},out,...Object.values(globals));return out;}
const model=load('lib/fuel/model.ts'),zod=require('zod'),report=load('lib/fuel/report.ts',{'zod':zod,'./model':model});
function extraction({user=true,allow=true,authError=false,missing=false,consent=true,configured=true,checksum=true,recheck=true}={}){const calls=[],bytes=Buffer.from('Synthetic original'),hash=require('node:crypto').createHash('sha256').update(bytes).digest('hex');let checks=0;const q={select:()=>q,eq:()=>q,maybeSingle:async()=>({data:missing?null:{id,client_id:client,sha256:checksum?hash:'a'.repeat(64),byte_size:bytes.length,storage_path:'synthetic.jpg',content_type:'image/jpeg'},error:null})},db={auth:{getUser:async()=>({data:{user:user?{id:actor}:null}})},rpc:async()=>{checks++;return{data:checks>1?recheck:allow,error:authError?{}:null}},from:()=>q};const svc={rpc:async()=>{calls.push('reserve');return{data:true,error:null}},storage:{from:()=>({download:async()=>({data:new Blob([bytes]),error:null})})}};
 const route=load('app/api/fuel/[clientId]/reports/extract/route.ts',{'node:crypto':require('node:crypto'),'next/server':{NextResponse:{json:(body,o)=>({body,...o})}},'zod':zod,'@/lib/supabase/server':{createClient:async()=>db,createServiceClient:()=>{calls.push('service');return svc;}},'@/lib/media/request':{smallJson:async()=>({source_id:id,request_id:requestId,external_processing_consent:consent})},'@/lib/fuel/model':model,'@/lib/fuel/report':report,'@/lib/fuel/report-provider':{reportReaderConfigured:()=>configured,extractReport:async()=>{calls.push('provider');return{observations:[]}}}});
 return{calls,run:()=>route.POST({headers:{get:()=> 'https://test.invalid'},nextUrl:{origin:'https://test.invalid'}},{params:Promise.resolve({clientId:client})})};}
test('extraction denies missing auth, scope, consent, source and configuration before external processing',async()=>{for(const o of [{user:false},{allow:false},{authError:true},{missing:true},{consent:false},{configured:false}]){const h=extraction(o),r=await h.run();assert.notEqual(r.status,200);assert.equal(h.calls.includes('provider'),false);assert.equal(h.calls.includes('service'),false);}});
test('checksum mismatch never reaches provider; revoked access cannot return private extraction',async()=>{const bad=extraction({checksum:false});assert.equal((await bad.run()).status,409);assert.equal(bad.calls.includes('provider'),false);const revoked=extraction({recheck:false});assert.equal((await revoked.run()).status,403);});
test('extraction response carries unreviewed source identity and never performs measurement writes',async()=>{const h=extraction(),r=await h.run();assert.equal(r.status,200);assert.equal(r.body.reviewed,false);assert.equal(r.body.client_id,client);assert.equal(r.body.source_id,id);assert.deepEqual(h.calls,['service','reserve','provider']);});
