const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),ts=require('typescript');
const root=path.join(__dirname,'..'),client='11111111-1111-4111-8111-111111111111',actor='22222222-2222-4222-8222-222222222222',id='33333333-3333-4333-8333-333333333333',requestId='44444444-4444-4444-8444-444444444444';
function load(file,deps={},globals={}){const out={},code=ts.transpileModule(fs.readFileSync(path.join(root,file),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;new Function('require','exports',...Object.keys(globals),code)(n=>{if(!(n in deps))throw Error('Unexpected '+n);return deps[n];},out,...Object.values(globals));return out;}
const model=load('lib/fuel/model.ts'),zod=require('zod'),report=load('lib/fuel/report.ts',{'zod':zod,'./model':model});
function extraction({user=true,allow=true,authError=false,missing=false,consent=true,configured=true,checksum=true,recheck=true}={}){const calls=[],bytes=Buffer.from('Synthetic original'),hash=require('node:crypto').createHash('sha256').update(bytes).digest('hex');let checks=0;const q={select:()=>q,eq:()=>q,maybeSingle:async()=>({data:missing?null:{id,client_id:client,sha256:checksum?hash:'a'.repeat(64),byte_size:bytes.length,storage_path:'synthetic.jpg',content_type:'image/jpeg'},error:null})},db={auth:{getUser:async()=>({data:{user:user?{id:actor}:null}})},rpc:async()=>{checks++;return{data:checks>1?recheck:allow,error:authError?{}:null}},from:()=>q};const svc={rpc:async()=>{calls.push('reserve');return{data:true,error:null}},storage:{from:()=>({download:async()=>({data:new Blob([bytes]),error:null})})}};
 const route=load('app/api/fuel/[clientId]/reports/extract/route.ts',{'node:crypto':require('node:crypto'),'next/server':{NextResponse:{json:(body,o)=>({body,...o})}},'zod':zod,'@/lib/supabase/server':{createClient:async()=>db,createServiceClient:()=>{calls.push('service');return svc;}},'@/lib/media/request':{smallJson:async()=>({source_id:id,request_id:requestId,external_processing_consent:consent})},'@/lib/fuel/model':model,'@/lib/fuel/report':report,'@/lib/fuel/report-provider':{reportReaderConfigured:()=>configured,extractReport:async()=>{calls.push('provider');return{observations:[]}}}});
 return{calls,run:()=>route.POST({headers:{get:()=> 'https://test.invalid'},nextUrl:{origin:'https://test.invalid'}},{params:Promise.resolve({clientId:client})})};}
test('extraction denies missing auth, scope, consent, source and configuration before external processing',async()=>{for(const o of [{user:false},{allow:false},{authError:true},{missing:true},{consent:false},{configured:false}]){const h=extraction(o),r=await h.run();assert.notEqual(r.status,200);assert.equal(h.calls.includes('provider'),false);assert.equal(h.calls.includes('service'),false);}});
test('checksum mismatch never reaches provider; revoked access cannot return private extraction',async()=>{const bad=extraction({checksum:false});assert.equal((await bad.run()).status,409);assert.equal(bad.calls.includes('provider'),false);const revoked=extraction({recheck:false});assert.equal((await revoked.run()).status,403);});
test('extraction response carries unreviewed source identity and never performs measurement writes',async()=>{const h=extraction(),r=await h.run();assert.equal(r.status,200);assert.equal(r.body.reviewed,false);assert.equal(r.body.client_id,client);assert.equal(r.body.source_id,id);assert.deepEqual(h.calls,['service','reserve','provider']);});
const nutrition=load('lib/fuel/nutrition.ts',{'zod':zod,'./model':model,'./report':report}),validation=load('lib/fuel/validation.ts',{'zod':zod,'./model':model}),requests=load('lib/fuel/nutrition-request.ts',{'zod':zod,'./report':report,'./nutrition':nutrition,'./validation':validation});
const measurement={date:'2026-09-28',weight_lb:200,body_fat_pct:25,lean_pct:75,fat_mass_lb:50,lean_mass_lb:150,model_label:'Synthetic'};
const intake={age:45,height_cm:180,equation_coefficient:'male',activity:'moderate',goal:'maintenance',training_days:3,diet:'mixed',meals_per_day:'3',budget:'economy',prep:'batch',avoid:[],other_food_restrictions:'',preferences:'',screen:{pregnancy_or_breastfeeding:'no',eating_disorder_or_restrictive_history:'no',medical_nutrition_or_medication:'no',unexplained_symptoms_or_weight_change:'no',high_training_demand:'no'},food_reviewed:true};
const proposal=()=>({action:'propose',measurement,intake,sources:[{id,sha256:'a'.repeat(64)}],same_person_test_confirmed:true,reported_values_confirmed:true});
function nutritionApi(options={}){const calls=[];let check=0;const db={auth:{getUser:async()=>({data:{user:options.anonymous?null:{id:actor}}})},rpc:async(name,args)=>{calls.push(name);if(name==='fuel_can_access'){check++;return{data:options.denied?false:check>1?!options.revoked:true,error:options.authError?{}:null}}if(name==='save_fuel_nutrition_draft'){const rec=(cmd)=>({ok:true,request_id:cmd.request_id,client_id:client,entity_id:cmd.request_id,action:cmd.action,revision:1,deduped:false});return{data:options.badReceipt?{}:{ok:true,client_id:client,measurement:rec(args.p_measure),strategy:rec(args.p_plan)},error:options.saveError?{code:options.saveError}:null};}throw Error('Unexpected command')},from(table){calls.push('read:'+table);const q={select:()=>q,eq:()=>q,in:()=>q,maybeSingle:async()=>({data:{id:client,full_name:'Synthetic Client',deleted_at:options.deleted?'x':null},error:null}),then(resolve){return Promise.resolve(resolve({data:options.missingSources?null:[{id,sha256:options.wrongHash?'b'.repeat(64):'a'.repeat(64)}],error:options.readError?{}:null}));}};return q;}};
 const route=load('app/api/fuel/[clientId]/nutrition/route.ts',{'next/server':{NextResponse:{json:(body,o)=>({body,...o})}},'@/lib/supabase/server':{createClient:async()=>db},'@/lib/media/request':{smallJson:async req=>req.input},'@/lib/fuel/model':{...model,fuelDate:()=> '2026-09-28'},'@/lib/fuel/validation':validation,'@/lib/fuel/nutrition-request':requests,'@/lib/fuel/nutrition':nutrition,'@/lib/fuel/foods':{menuEligibility:()=>null,foodKeys:()=>['oats'],loadFoodFacts:async()=>{calls.push('food-provider');throw Error('USDA unavailable')},createMenus:()=>{throw Error('must not fabricate menu')},attachMenu:()=>{throw Error('must not fabricate menu')}}});
 return{calls,run:(input=proposal(),origin='https://test.invalid')=>route.POST({input,headers:{get:()=>origin},nextUrl:{origin:'https://test.invalid'}},{params:Promise.resolve({clientId:client})})};}
test('nutrition route requires origin, current authorization and client-scoped originals before provider work',async()=>{for(const options of [{anonymous:true},{denied:true},{authError:true},{missingSources:true},{wrongHash:true},{readError:true},{deleted:true}]){const h=nutritionApi(options),r=await h.run();assert.notEqual(r.status,200);assert.equal(h.calls.includes('food-provider'),false);assert.equal(h.calls.includes('save_fuel_nutrition_draft'),false);}const h=nutritionApi();assert.equal((await h.run(proposal(),'https://evil.invalid')).status,403);assert.equal(h.calls.length,0);});
test('positive screening and unknown fields never start a numeric/menu provider request',async()=>{let h=nutritionApi();assert.equal((await h.run({...proposal(),intake:{...intake,screen:{...intake.screen,medical_nutrition_or_medication:'yes'}}})).status,422);assert.equal(h.calls.includes('food-provider'),false);h=nutritionApi();assert.equal((await h.run({...proposal(),publish:true})).status,400);});
test('food failure still returns explicit targets-only unsaved draft without claiming a full menu',async()=>{const h=nutritionApi(),r=await h.run();assert.equal(r.status,200);assert.equal(r.body.persisted,false);assert.equal(r.body.content.meals.length,0);assert.match(r.body.menuWarning,/USDA unavailable/);assert.match(r.body.content.guidance,/not a complete meal plan/);assert.equal(h.calls.includes('save_fuel_nutrition_draft'),false);});
test('nutrition proposal is not returned if assignment changes during food lookup',async()=>{const h=nutritionApi({revoked:true});assert.equal((await h.run()).status,403);});
test('private save uses exactly one atomic command, not direct data writes or provider regeneration',async()=>{const draft=nutrition.nutritionStrategy('Synthetic Client',measurement,intake,nutrition.calculateNutrition(measurement,intake,'2026-09-28'),'2026-09-28'),body={...proposal(),action:'save',content:draft,expected_revision:0,request_id:requestId,measurement_request_id:id,strategy_reviewed:true};const h=nutritionApi(),r=await h.run(body);assert.equal(r.status,200);assert.ok(requests.validNutritionReceipt(r.body,requestId,id,client));assert.equal(h.calls.filter(c=>c==='save_fuel_nutrition_draft').length,1);assert.equal(h.calls.includes('food-provider'),false);assert.equal((await nutritionApi({badReceipt:true}).run(body)).status,503);assert.equal((await nutritionApi({saveError:'40001'}).run(body)).status,409);assert.equal((await nutritionApi().run({...body,measurement_request_id:requestId})).status,400);});
