import Link from 'next/link';
import {notFound,redirect} from 'next/navigation';
import {AppShell} from '@/components/layout/app-shell';
import {createClient} from '@/lib/supabase/server';
import {ContactClientConversion} from '@/components/leads/contact-client-conversion';
import {RelationshipWorkbench} from '@/components/leads/relationship-workbench';
import {LEAD_COLUMNS} from '@/lib/leads/queries';
import {leadBucket,sourceLabel,type LeadRecord} from '@/lib/leads/workspace';
export const dynamic='force-dynamic';
export default async function ContactProfile({params}:{params:Promise<{id:string}>}){const {id}=await params,db=await createClient(),{data:{user}}=await db.auth.getUser();if(!user)redirect('/login?next=/contacts/'+id);const me=await db.from('profiles').select('role,deleted_at').eq('id',user.id).maybeSingle();if(me.error||me.data?.role!=='owner'||me.data.deleted_at)redirect('/dashboard');
 const {data:contact,error}=await db.from('leads').select(LEAD_COLUMNS).eq('id',id).maybeSingle();if(error)throw Error('Contact profile could not be loaded.');if(!contact)notFound();if(leadBucket(contact)==='pipeline')redirect('/leads/'+id);if(leadBucket(contact)!=='contacts')notFound();
 const [staff,existing,receipt]=await Promise.all([db.from('profiles').select('id,full_name').in('role',['owner','trainer']).is('deleted_at',null).order('full_name'),contact.email?db.from('profiles').select('id,full_name,role').eq('email',contact.email.trim().toLowerCase()).is('deleted_at',null):Promise.resolve({data:[],error:null}),db.from('lead_client_conversions').select('client_id').eq('lead_id',id).maybeSingle()]);if(staff.error||existing.error||receipt.error)throw Error('Conversion identity evidence unavailable.');const receiptId=receipt.data?.client_id??null,emailMatch=(existing.data??[]).find(row=>row.role==='client');
 return <AppShell expectedRole="owner"><main className="mx-auto max-w-5xl space-y-5 pb-16"><Link href="/contacts" className="inline-flex min-h-11 items-center font-semibold text-sky">← All contacts</Link><header className="rounded-3xl bg-band p-6 text-white"><p className="text-xs uppercase tracking-widest text-white/60">IMS / Contact profile</p><h1 className="mt-2 text-3xl font-bold">{contact.full_name}</h1><p className="mt-2 text-sm text-white/75">{sourceLabel(contact.source)} · historical relationship record</p></header><section className="rounded-2xl border border-divider bg-white p-5"><h2 className="font-semibold">Relationship history</h2><dl className="mt-4 grid grid-cols-2 gap-4 sm:grid-cols-4">{[['Historical source appointments',contact.appointments_booked??'Unknown'],['Last recorded visit',contact.last_visited??'Unknown'],['Prior trainer',contact.prior_trainer??'Unknown'],['Interest tag',contact.interest??'Not recorded']].map(([label,value])=><div key={String(label)}><dt className="text-xs text-cream-faint">{label}</dt><dd className="mt-2 text-sm font-semibold">{value}</dd></div>)}</dl><p className="mt-3 text-xs text-cream-dim">Historical appointment counts do not establish completed sessions, new consultations or package balances.</p></section>
 <RelationshipWorkbench lead={contact as LeadRecord} isContact/>
 <section className="rounded-2xl border border-divider bg-white p-5"><h2 className="font-semibold">Contact notes · original source history</h2><p className="mt-3 whitespace-pre-wrap break-words text-sm leading-6">{contact.notes??'No source notes recorded.'}</p></section>
 <section className="rounded-2xl border border-divider bg-white p-5"><h2 className="font-semibold">Coach OS client</h2><p className="mt-2 text-sm leading-6 text-cream-dim">Conversion does not infer a package, balance, payment, appointment or current purchase intent. Adding contact details does not create or change a portal login.</p>{receiptId?<Link href={'/clients/'+receiptId} className="mt-3 inline-flex min-h-11 items-center font-semibold text-sky">Open verified linked client →</Link>:emailMatch?<div className="mt-3 rounded-xl bg-surface-soft p-4"><p className="text-sm">An existing client uses this email. This is a possible identity conflict, not proof they are the same person. No automatic merge or second identity is allowed.</p><Link href={'/clients/'+emailMatch.id} className="mt-2 inline-flex min-h-11 items-center font-semibold text-sky">Inspect possible match →</Link></div>:contact.stage==="converted"?<div role="alert" className="mt-3 rounded-xl border border-status-moderate/40 p-4"><h3 className="font-semibold">Conversion needs reconciliation</h3><p className="mt-2 text-sm">This historical contact is marked converted but has no verified client link. Coach OS will not create another identity until reconciled.</p></div>:<ContactClientConversion contactId={contact.id} defaultEmail={contact.email??''} trainers={(staff.data??[]).map(p=>({id:p.id,name:p.full_name}))}/>}</section></main></AppShell>;
}
