"use client";
import {useCallback,useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {RESEARCH_AREAS,RESEARCH_LANES,LANE_LABELS,RUN_ALLOWANCE_CENTS,type ResearchSettings,type ResearchRun,type ResearchControl} from '@/lib/growth/research-engine';
import {Field,fieldClass,primaryClass,secondaryClass} from '@/components/fuel/controls';
type Snapshot={control:ResearchControl;runs:ResearchRun[];providerReady:boolean;reservedCents:number;monthRuns:number};
export function AIResearchDesk(){
 const router=useRouter(),lock=useRef(false),pending=useRef<Record<string,unknown>|null>(null),ambiguous=useRef(false);
 const [data,setData]=useState<Snapshot|null>(null),[draft,setDraft]=useState<ResearchSettings|null>(null),[busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(false),[error,setError]=useState<string|null>(null),[notice,setNotice]=useState(''),[approved,setApproved]=useState(false);
 const reload=useCallback(async()=>{const r=await fetch('/api/leads/research/engine',{cache:'no-store'}),v=await r.json();if(!r.ok||!v.control||!Array.isArray(v.runs))throw Error(v.error??'Research storage unavailable.');setData(v);setDraft(old=>old??v.control.config);return v as Snapshot;},[]);
 useEffect(()=>{let active=true;void reload().catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[reload]);
 const running=data?.runs.find(r=>r.status==='researching'&&r.response_id);
 useEffect(()=>{if(!running)return;const timer=setInterval(()=>{if(document.visibilityState!=='visible'||lock.current)return;void fetch('/api/leads/research/engine',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'poll',run_id:running.id})}).then(async r=>{if(!r.ok)throw Error('Run refresh unavailable. Use Recover run below.');const v=await r.json();if(v.run?.id!==running.id)throw Error('Run receipt mismatch.');await reload();if(v.run.status==='completed')router.refresh();}).catch(e=>setError(e.message));},10000);return()=>clearInterval(timer);},[running,reload,router]);
 async function send(command:Record<string,unknown>){if(lock.current)return;lock.current=true;setBusy(true);setError(null);try{const r=await fetch('/api/leads/research/engine',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(command)}),v=await r.json().catch(()=>null);
  if(!r.ok){if(r.status>=500||ambiguous.current){ambiguous.current=true;setUncertain(true);}else pending.current=null;setError(v?.error??'Research request unconfirmed.');return;}
  const valid=command.action==='settings'?v?.ok===true&&v.request_id===command.request_id&&v.revision===Number(command.expected_revision)+1:v?.ok===true&&v.run?.id===(command.request_id??command.run_id);
  if(!valid){ambiguous.current=true;setUncertain(true);setError('Incomplete receipt. Retry the preserved request.');return;}
  pending.current=null;ambiguous.current=false;setUncertain(false);const snapshot=await reload();if(command.action==='settings'){setDraft(snapshot.control.config);setApproved(false);setNotice('Research controls saved. No outreach was enabled.');}else{setNotice(command.action==='run'?'Research request recorded. Results will appear as unqualified opportunities, not consumer leads.':'Run state refreshed.');router.refresh();}
 }catch{ambiguous.current=true;setUncertain(true);setError('Connection interrupted. Retry the same request to recover its state, not start another paid run.');}finally{lock.current=false;setBusy(false);}}
 function submit(command:Record<string,unknown>){if(lock.current||pending.current)return;pending.current=command;void send(command);}
 const frozen=busy||uncertain;
 return <section className="space-y-5 rounded-3xl border border-sky/20 bg-white p-5 sm:p-6" aria-label="AI Growth Engine"><header><p className="text-xs font-semibold uppercase tracking-wider text-sky">IMS AI Growth Engine</p><h2 className="mt-2 text-3xl font-bold">Find opportunities. Keep the relationships human.</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-cream-dim">Live public research → source-linked fit signals → duplicate checks → owner review. No copying prompts or pasting JSON. Public organizations are prospects, not people who have asked to buy.</p></header>
 {error&&<p role="alert" className="rounded-xl border border-status-moderate/40 p-4 text-sm">{error}</p>}{notice&&<p role="status" className="rounded-xl bg-sky/5 p-3 text-sm">{notice}</p>}{uncertain&&<button className={secondaryClass} disabled={busy} onClick={()=>pending.current&&void send(pending.current)}>Recover preserved request</button>}
 {!data||!draft?<button className={secondaryClass} onClick={()=>void reload().catch(e=>setError(e.message))}>Load research controls</button>:<>
  <div className="grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-surface-soft p-4"><p className="text-xs text-cream-faint">Provider connection</p><p className="mt-2 font-semibold">{data.providerReady?'Configured · live acceptance still required':'Not enabled'}</p></div><div className="rounded-2xl bg-surface-soft p-4"><p className="text-xs text-cream-faint">Dispatches this UTC month</p><p className="mt-2 text-2xl font-bold">{data.monthRuns} / {data.control.config.monthly_runs}</p></div><div className="rounded-2xl bg-surface-soft p-4"><p className="text-xs text-cream-faint">Planning allowance reserved · not invoiced spend</p><p className="mt-2 text-2xl font-bold">${(data.reservedCents/100).toFixed(2)}</p></div></div>
  {!data.providerReady&&<p className="rounded-xl border border-divider p-4 text-sm leading-6">An owner must configure the dedicated research API key and server enable flag. No paid call is made while unavailable. Do not paste keys into this page or chat.</p>}
  <details open={!data.control.revision}><summary className="min-h-12 cursor-pointer font-semibold text-sky">Hunting lanes, geographic scope &amp; run limits</summary><fieldset disabled={frozen} className="mt-3 space-y-4"><legend className="sr-only">Research settings</legend><Field label="Geographic scope · named communities, not unverified mileage"><select className={fieldClass} value={draft.area} onChange={e=>{setDraft({...draft,area:e.target.value as ResearchSettings['area']});setApproved(false);}}>{Object.entries(RESEARCH_AREAS).map(([k,label])=><option key={k} value={k}>{label}</option>)}</select></Field><div className="grid gap-2 sm:grid-cols-2">{RESEARCH_LANES.map(l=><label className="flex min-h-12 items-center gap-3 rounded-xl border border-divider px-3 text-sm" key={l}><input type="checkbox" checked={draft.lanes.includes(l)} disabled={!draft.lanes.includes(l)&&draft.lanes.length>=4} onChange={e=>{setDraft({...draft,lanes:e.target.checked?[...draft.lanes,l]:draft.lanes.filter(x=>x!==l)});setApproved(false);}}/>{LANE_LABELS[l]}</label>)}</div><div className="grid gap-3 sm:grid-cols-2">{([['max_candidates','Maximum candidates per run',1,12],['min_score','Minimum evidence-fit score',0,100],['daily_runs','Maximum dispatches per UTC day',1,3],['monthly_runs','Maximum dispatches per UTC month',1,60]] as const).map(([key,label,min,max])=><Field key={key} label={label}><input type="number" min={min} max={max} className={fieldClass} value={draft[key]} onChange={e=>{setDraft({...draft,[key]:Number(e.target.value)});setApproved(false);}}/></Field>)}<Field label="Monthly planning allowance · USD"><input className={fieldClass} type="number" min={2} max={200} step={2} value={draft.monthly_allowance_cents/100} onChange={e=>{setDraft({...draft,monthly_allowance_cents:Math.round(Number(e.target.value)*100)});setApproved(false);}}/></Field></div><Field label="Exclude organization domains · one per line"><textarea className={fieldClass} rows={3} maxLength={10000} value={draft.blocked_domains.join('\n')} onChange={e=>{setDraft({...draft,blocked_domains:e.target.value.split('\n').map(x=>x.trim().toLowerCase()).filter(Boolean)});setApproved(false);}}/></Field>
   <label className="flex min-h-12 items-center gap-3 text-sm"><input type="checkbox" checked={draft.enabled} onChange={e=>{setDraft({...draft,enabled:e.target.checked,radar_enabled:e.target.checked?draft.radar_enabled:false});setApproved(false);}}/>Enable owner-triggered paid public research</label><label className="flex min-h-12 items-center gap-3 text-sm"><input type="checkbox" disabled={!draft.enabled} checked={draft.radar_enabled} onChange={e=>{setDraft({...draft,radar_enabled:e.target.checked});setApproved(false);}}/>Enable daily Lead Radar on the production scheduler</label><p className="text-xs leading-5 text-cream-dim">Radar is not active on previews. The scheduled handler checks at 15:00 UTC (8 AM PDT / 7 AM PST). Background results are reconciled when this desk is open or the scheduler checks again. There is no promise of 24/7 completed results without a configured scheduler. Each dispatch reserves ${RUN_ALLOWANCE_CENTS/100} of a planning allowance; this is not a quoted price, invoice, or provider hard spending cap. Set a separate provider budget. Failed/unconfirmed starts still consume the allowance. Search and output-token limits also apply.</p>
   <label className="flex items-start gap-3 text-sm leading-6"><input className="mt-1 h-5 w-5 shrink-0" type="checkbox" checked={approved} onChange={e=>setApproved(e.target.checked)}/>I reviewed the provider budget and authorize these public-only research settings. No client/contact/health data, messages or ads are sent. Background responses are stored by the provider under its retention policy.</label><button className={primaryClass} disabled={!approved||!draft.lanes.length} onClick={()=>submit({action:'settings',request_id:crypto.randomUUID(),expected_revision:data.control.revision,config:{...draft,public_research_approved:true}})}>Save research controls</button></fieldset></details>
  <div className="flex flex-wrap items-center gap-3"><button className={primaryClass} disabled={frozen||!data.providerReady||!data.control.config.enabled||data.runs.some(r=>['starting','researching'].includes(r.status))} onClick={()=>submit({action:'run',request_id:crypto.randomUUID(),expected_revision:data.control.revision,public_research_approved:true})}>Find opportunities with saved settings</button><Link href="/growth#opportunities" className={secondaryClass}>Review &amp; plan outreach →</Link></div><p className="text-xs text-cream-faint">A fit score measures supported prospecting signals, not a probability of purchase. Source links do not certify every AI-written claim. Owner review remains required.</p>
  <details open={Boolean(running)}><summary className="min-h-12 cursor-pointer font-semibold">Run history · last 20</summary><div className="space-y-3">{data.runs.length===0&&<p className="text-sm text-cream-dim">No recorded runs. Nothing has been researched by this engine yet.</p>}{data.runs.map(r=><article key={r.id} className="rounded-xl border border-divider p-4"><div className="flex flex-wrap justify-between gap-2"><p className="font-semibold capitalize">{r.status} · {r.origin}</p><p className="text-xs text-cream-faint">{r.created_at} · {r.environment}</p></div><p className="mt-2 text-sm">{r.counts?`${r.counts.accepted} new prospects · ${r.counts.duplicates} duplicates · ${r.counts.rejected} rejected · ${r.counts.returned} returned`:'No completed candidate counts yet.'}</p>{r.error_code&&<p className="mt-2 text-sm text-status-moderate">{r.error_code.replaceAll('_',' ')}. No empty-success state is inferred.</p>}{r.usage&&<p className="mt-2 text-xs text-cream-faint">Input tokens {r.usage.input_tokens??'unavailable'} · output {r.usage.output_tokens??'unavailable'} · search calls {r.usage.search_calls??'unavailable'}. Provider invoice remains separate.</p>}{r.response_id&&['researching','unconfirmed'].includes(r.status)&&<div className="mt-2 flex flex-wrap gap-3"><button className={secondaryClass} disabled={frozen} onClick={()=>submit({action:'poll',run_id:r.id})}>Recover run</button><button className={secondaryClass} disabled={frozen} onClick={()=>submit({action:'cancel',run_id:r.id})}>Request provider cancellation</button></div>}{r.status==='unconfirmed'&&!r.response_id&&<p className="mt-2 text-xs leading-5">The upstream request identity was not confirmed. Do not blindly restart it; inspect provider usage first. Its planning reservation is retained.</p>}</article>)}</div></details>
 </>}
 </section>;
}
