import Link from 'next/link';
import {redirect} from 'next/navigation';
import {createClient} from '@/lib/supabase/server';
import {AppShell} from '@/components/layout/app-shell';
import {loadLeadWorkspace} from '@/lib/leads/queries';
import {LeadWorkspaceView} from '@/components/leads/lead-workspace-view';
import {LeadResearchDesk} from '@/components/leads/lead-research-desk';
import {AIResearchDesk} from '@/components/leads/ai-research-desk';
import {ResearchOpportunities} from '@/components/growth/research-opportunities';
import {allCatalogPages} from '@/lib/exercises/catalog';
import type {GrowthCampaign,OpportunityReview} from '@/lib/growth/model';
import {relationshipPriority} from '@/lib/leads/relationships';
import {fuelDate} from '@/lib/fuel/model';
export async function GrowthWorkspace({mode='pipeline'}:{mode?:'pipeline'|'contacts'|'research'}){
 const db=await createClient(),{data:{user}}=await db.auth.getUser();if(!user)redirect('/login?next=/leads');const {data:me,error}=await db.from('profiles').select('role,deleted_at').eq('id',user.id).maybeSingle();if(error||!me||me.deleted_at||me.role!=='owner')redirect('/dashboard');
 let workspace;try{workspace=await loadLeadWorkspace(db);}catch{return <AppShell expectedRole="owner"><main className="mx-auto max-w-6xl space-y-5"><h1 className="text-3xl font-bold">Growth &amp; contacts</h1><p role="alert" className="rounded-2xl border border-status-moderate/40 bg-white p-5">This workspace could not be loaded. Existing records have not been changed. No empty pipeline or successful save was inferred.</p></main></AppShell>;}
 const [campaigns,reviews]=mode==='research'?await Promise.all([allCatalogPages<GrowthCampaign>((a,b)=>db.from('growth_campaigns').select('id,name,channel,audience,area,offer,budget_cents,status,updated_at',{count:'exact'}).order('id').range(a,b)),allCatalogPages<OpportunityReview>((a,b)=>db.from('growth_opportunity_reviews').select('*',{count:'exact'}).order('candidate_id').range(a,b) as any)]):[[],[]];
 const today=fuelDate(),rows=mode==='contacts'?workspace.contacts:mode==='research'?workspace.research:workspace.pipeline;
 rows.sort((a,b)=>mode==='contacts'?a.full_name.localeCompare(b.full_name):b.updated_at.localeCompare(a.updated_at));
 const title=mode==='contacts'?'Contacts & relationships':mode==='research'?'Research Desk':'New Business';
 return <AppShell expectedRole="owner"><main className="mx-auto flex w-full max-w-6xl flex-col gap-5 pb-16"><header className="rounded-3xl bg-band p-6 text-white sm:p-8"><p className="text-xs font-semibold uppercase tracking-widest text-white/65">IMS / Relationships &amp; growth</p><h1 className="mt-2 text-4xl font-bold">{title}</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-white/80">{mode==='contacts'?'Preserve the relationship, edit the details, and own the next step. An old contact is not automatically a current inquiry.':mode==='research'?'AI searches public organizations and shows its evidence. You decide which relationships to pursue.':'Real inquiries and referrals, with a responsible person, stated goals, follow-up dates and a factual activity history—not just a list of names.'}</p></header>
 <nav aria-label="Growth workspaces" className="flex flex-wrap gap-2">{[{key:'pipeline',href:'/leads',label:'New Business',count:workspace.pipeline.length},{key:'research',href:'/leads/research',label:'Research Desk',count:workspace.research.length},{key:'contacts',href:'/contacts',label:'Contacts',count:workspace.contacts.length},{key:'growth',href:'/growth',label:'Growth Center',count:null}].map(tab=><Link key={tab.key} href={tab.href} aria-current={mode===tab.key?'page':undefined} className={'inline-flex min-h-12 items-center gap-2 rounded-xl border px-4 text-sm font-semibold '+(mode===tab.key?'border-sky bg-sky text-white':'border-divider bg-white text-sky')}>{tab.label}{tab.count!==null&&<span className="rounded-full bg-black/5 px-2 py-1 text-xs">{tab.count}</span>}</Link>)}</nav>
 {mode==='pipeline'&&<><section aria-label="Current inquiry health" className="grid grid-cols-2 gap-3 sm:grid-cols-4">{[['Open inquiries',workspace.open.length],['Needs first contact',workspace.untouched.length],['Follow-ups due',workspace.open.filter(r=>relationshipPriority(r,today)==='due').length],['Booked',workspace.booked.length]].map(([label,value])=><div key={label} className="rounded-2xl border border-divider bg-white p-4"><p className="text-xs text-cream-faint">{label}</p><p className="mt-2 text-3xl font-bold">{value}</p></div>)}</section><details className="rounded-2xl border border-divider bg-white p-4"><summary className="min-h-11 cursor-pointer font-semibold">Find better-fit acquisition channels</summary><div className="mt-3 grid gap-3 sm:grid-cols-3"><Link href="/leads/research" className="rounded-xl bg-sky/5 p-4"><p className="font-semibold text-sky">Research Desk →</p><p className="mt-2 text-xs leading-5">Public organization opportunities, with evidence and owner review.</p></Link><div className="rounded-xl bg-surface-soft p-4"><p className="font-semibold">General-population clients</p><p className="mt-2 text-xs leading-5">Strength, mobility, active aging and a sustainable routine.</p></div><div className="rounded-xl bg-surface-soft p-4"><p className="font-semibold">Premium-fit segment</p><p className="mt-2 text-xs leading-5">Channels for people who choose individualized coaching. No inferred wealth, health or purchase intent.</p></div></div></details></>}
 {mode==='research'?<><AIResearchDesk/><ResearchOpportunities rows={rows} reviews={reviews} campaigns={campaigns} today={today}/><details className="rounded-2xl border border-divider bg-white p-4"><summary className="min-h-11 cursor-pointer text-sm font-semibold text-cream-dim">Advanced · import independently reviewed research</summary><LeadResearchDesk/></details></>:<LeadWorkspaceView key={mode+':'+rows.map(r=>r.updated_at+':'+(r.workflow?.revision??0)).join(',')} rows={rows} contacts={mode==='contacts'} today={today}/>}
 <p className="text-xs leading-5 text-cream-faint">Source labels and original histories are preserved. Research approval does not prove interest, consent or purchase intent. Contact permission is not channel-specific marketing consent. Nothing here sends outreach or creates a login.</p></main></AppShell>;
}
