"use client";
import {useMemo,useState} from 'react';
import Link from 'next/link';
import {sourceLabel,type LeadRecord} from '@/lib/leads/workspace';
import {relationshipPriority} from '@/lib/leads/relationships';
import {CreateRelationshipForm} from './relationship-forms';
const control='min-h-11 rounded-xl border border-divider bg-white px-3 py-2 text-base focus-visible:ring-2 focus-visible:ring-sky';
export function LeadWorkspaceView({rows,contacts=false,research=false,today=new Date().toISOString().slice(0,10)}:{rows:LeadRecord[];contacts?:boolean;research?:boolean;today?:string}){
 const [query,setQuery]=useState(''),[filter,setFilter]=useState('active'),[source,setSource]=useState('all'),[shown,setShown]=useState(40),[create,setCreate]=useState(false);
 const filtered=useMemo(()=>rows.filter(row=>{const p=relationshipPriority(row,today),w=row.workflow;return [row.full_name,row.email,row.phone,row.interest,w?.goal,w?.next_action,...w?.tags??[]].join(' ').toLowerCase().includes(query.trim().toLowerCase())&&(source==='all'||row.source===source)&&(filter==='all'||filter==='active'?!w?.archived_at||filter==='all':filter===p);}),[rows,query,filter,source,today]);
 const sources=[...new Set(rows.map(r=>r.source).filter((s):s is string=>Boolean(s)))];
 function choose(value:string){setFilter(value);setShown(40);}
 return <section className="space-y-4"><div className="flex flex-wrap gap-3"><input type="search" aria-label={contacts?'Search contacts':'Search new business'} className={control+' min-w-0 flex-1'} value={query} onChange={e=>{setQuery(e.target.value);setShown(40);}} placeholder="Search name, contact details, goals, tags or next action"/>{!research&&<button className={control+' text-sm font-semibold text-sky'} onClick={()=>setCreate(!create)}>{create?'Close form':contacts?'Add contact':'Add inquiry'}</button>}</div>
 {!research&&<div className="flex flex-wrap gap-2" role="group" aria-label="Relationship filters">{(contacts?[['active','Current contacts'],['due','Follow-up due'],['suppressed','Do not contact'],['archived','Archived'],['all','All records']]:[['active','All current inquiries'],['first_contact','Needs first contact'],['due','Follow-up due'],['booked','Booked'],['closed','Closed'],['suppressed','Do not contact'],['archived','Archived'],['all','All records']]).map(([key,label])=><button type="button" key={key} aria-pressed={filter===key} className={control+' text-sm '+(filter===key?'border-sky bg-sky/5 text-sky':'')} onClick={()=>choose(key)}>{label}</button>)}</div>}
 <label className="inline-flex flex-wrap items-center gap-2 text-sm">Original source<select className={control} value={source} onChange={e=>{setSource(e.target.value);setShown(40);}}><option value="all">All sources</option>{sources.map(s=><option key={s} value={s}>{sourceLabel(s)}</option>)}</select></label>
 {create&&<CreateRelationshipForm kind={contacts?'contact':'inquiry'}/>}
 {!contacts&&!research&&<div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{['new','contacted','nurturing','booked','converted','not_interested'].map(stage=><div key={stage} className="rounded-xl border border-divider bg-white p-3"><p className="text-xs capitalize text-cream-faint">{stage.replaceAll('_',' ')}</p><p className="mt-1 text-xl font-semibold">{rows.filter(r=>r.stage===stage&&!r.workflow?.archived_at).length}</p></div>)}</div>}
 <p className="text-xs text-cream-faint">Showing {Math.min(shown,filtered.length)} of {filtered.length} matching {contacts?'contacts':'records'} · {rows.length} total in this workspace. Source history is not buying intent.</p>
 {filtered.length===0&&<div className="rounded-2xl border border-divider bg-white p-6"><h2 className="font-semibold">{contacts?'No contacts match these filters':'No inquiries match these filters'}</h2><p className="mt-2 text-sm text-cream-dim">Historical contacts and research remain separate. No records were deleted.</p></div>}
 <div className="grid gap-3 lg:grid-cols-2">{filtered.slice(0,shown).map(row=>{const w=row.workflow,p=relationshipPriority(row,today);return <article key={row.id} className="min-w-0 rounded-2xl border border-divider bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-2"><h2 className="font-semibold">{row.full_name}</h2><span className="rounded-full bg-surface-soft px-3 py-1 text-xs capitalize">{p==='suppressed'?'Do not contact':contacts?'Contact history':row.stage.replaceAll('_',' ')}</span></div><p className="mt-2 text-xs text-cream-faint">{sourceLabel(row.source)}</p><p className="mt-2 text-sm text-cream-dim">{row.interest??'Interest not recorded'}</p><p className="mt-3 break-all text-sm">{row.email??'Email not recorded'}{row.phone?' · '+row.phone:''}</p>{w?.next_action&&<div className="mt-3 rounded-xl bg-sky/5 p-3"><p className="text-sm font-semibold">{w.next_action}</p><p className="mt-1 text-xs">{w.due_on?'Due '+w.due_on:'No follow-up date'} · {w.priority} priority</p></div>}{w?.tags.length? <div className="mt-3 flex flex-wrap gap-1">{w.tags.map(t=><span key={t} className="rounded-full bg-surface-soft px-2 py-1 text-xs">{t}</span>)}</div>:null}
 {contacts?<><p className="mt-3 text-xs text-cream-faint">{row.last_visited?'Last recorded visit '+row.last_visited:'No last visit established'} · historical record, not a current inquiry</p><Link href={`/contacts/${row.id}`} className="mt-3 inline-flex min-h-11 items-center font-semibold text-sky">Open contact profile →</Link></>:research?<Link className="mt-3 inline-flex min-h-11 items-center font-semibold text-sky" href={`/growth#opportunity-${row.id}`}>Review opportunity →</Link>:<Link className="mt-3 inline-flex min-h-11 items-center font-semibold text-sky" href={`/leads/${row.id}`}>Open inquiry &amp; next actions →</Link>}
 </article>;})}</div>{shown<filtered.length&&<button className={control} onClick={()=>setShown(shown+40)}>Show 40 more</button>}
 </section>;
}
