import Link from 'next/link';
import {requireGrowthOwner} from '@/lib/growth/owner-access';
import {allCatalogPages} from '@/lib/exercises/catalog';
import {ActivityForm,ContactDetailsEditor,InquiryActions,WorkflowEditor} from './relationship-forms';
import type {LeadRecord} from '@/lib/leads/workspace';
import type {LeadActivity,LeadWorkflow} from '@/lib/leads/relationships';
export async function RelationshipWorkbench({lead,isContact=false}:{lead:LeadRecord;isContact?:boolean}){const {db}=await requireGrowthOwner();const [work,activity,staff,link]=await Promise.all([db.from('lead_workflows').select('*').eq('lead_id',lead.id).maybeSingle(),db.from('lead_activity').select('*').eq('lead_id',lead.id).order('occurred_at',{ascending:false}).order('id').limit(100),allCatalogPages<{id:string;full_name:string}>((a,b)=>db.from('profiles').select('id,full_name',{count:'exact'}).in('role',['owner','trainer']).is('deleted_at',null).order('id').range(a,b)),db.from('lead_client_conversions').select('client_id').eq('lead_id',lead.id).maybeSingle()]);if(work.error||activity.error||link.error)throw Error('Relationship history unavailable. No empty workflow was inferred.');const w=work.data as LeadWorkflow|undefined,rows=(activity.data??[]) as LeadActivity[];return <div className="space-y-5">
 {w?.permission==='do_not_contact'&&<aside role="status" className="rounded-2xl border border-status-moderate/40 bg-white p-5"><h2 className="font-semibold">Do not contact</h2><p className="mt-2 text-sm">{w.permission_evidence}</p><p className="mt-2 text-xs text-cream-dim">Records stay available for continuity. This is not an outreach queue.</p></aside>}
 {link.data?.client_id&&<div className="flex flex-wrap gap-3 rounded-2xl bg-sky/5 p-4"><Link className="inline-flex min-h-11 items-center font-semibold text-sky" href={`/clients/${link.data.client_id}`}>Open verified client profile →</Link><Link className="inline-flex min-h-11 items-center font-semibold text-sky" href={`/sessions/new?client_id=${link.data.client_id}`}>Book a session →</Link><Link className="inline-flex min-h-11 items-center font-semibold text-sky" href={`/messages/${link.data.client_id}`}>Client conversation →</Link></div>}
 <ContactDetailsEditor key={'contact:'+lead.updated_at} lead={lead}/>
 <WorkflowEditor key={'workflow:'+(w?.revision??0)} leadId={lead.id} workflow={w} staff={staff}/>
 {(!isContact||lead.stage!=='converted')&&<InquiryActions key={'inquiry:'+lead.updated_at} lead={lead} isContact={isContact}/>}
 <ActivityForm key={'activity:'+(rows[0]?.id??'none')} leadId={lead.id} suppressed={w?.permission==='do_not_contact'}/>
 <section className="rounded-2xl border border-divider bg-white p-5"><h2 className="text-xl font-semibold">Relationship timeline</h2><p className="mt-2 text-xs text-cream-dim">Last 100 recorded activities. Original source notes remain separately preserved below. A recorded outreach event is not a message sent by Coach OS.</p><div className="mt-4 space-y-3">{rows.length?rows.map(r=><article className="rounded-xl bg-surface-soft p-4" key={r.id}><p className="text-sm font-semibold capitalize">{r.kind.replaceAll('_',' ')} · {r.channel.replaceAll('_',' ')}</p><p className="mt-1 text-xs text-cream-faint">{r.occurred_at} · recorded {r.created_at}</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6">{r.note}</p></article>):<p className="text-sm text-cream-dim">No activities have been recorded in this timeline.</p>}</div></section>
 {!isContact&&<Link className="inline-flex min-h-11 items-center text-sm font-semibold text-sky" href="/growth">Connect campaign / referral attribution in Growth Center →</Link>}
 </div>;}
