"use client";
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {usePathname,useSearchParams} from 'next/navigation';
import {LayoutDashboard,Users,CalendarDays,MoreHorizontal,Target,Search,Dumbbell,MessageCircle,DollarSign,CreditCard,BarChart3,Settings,Mail,X,ListChecks,BookOpen,ClipboardList,Activity,GraduationCap} from 'lucide-react';
import {cn} from '@/lib/utils';
import {activeWorkspace,navigationGroup,WORKSPACE_GROUPS} from '@/lib/navigation/workspaces';
import type {UserRole} from '@/lib/types/database';
const coreItems = [
 {href:'/dashboard',label:'Today',icon:LayoutDashboard},{href:'/clients',label:'Clients',icon:Users},{href:'/schedule',label:'Schedule',icon:CalendarDays},{href: "/action-center", label: "Actions", icon:ListChecks},
];
const ownerMore = [
 {href:'/messages',label:'Communications',icon:MessageCircle},
 {href:'/programs',label:'Programs',icon:Dumbbell},{href:'/fuel',label:'Fuel & Performance',icon:Activity},{href:'/library',label:'Exercise Library',icon:Dumbbell},{href:'/classes/manage',label:'Classes',icon:GraduationCap},
 {href:'/leads',label:'New Business',icon:Target},{href:'/leads/research',label:'Research Desk',icon:Search},{href:'/contacts',label:'Contacts',icon:Users},{href:'/growth',label:'Growth Center',icon:Target},
 {href:'/financials',label:'Financials',icon:DollarSign},{href:'/checkout',label:'Checkout',icon:CreditCard},{href:'/reports',label:'Reports',icon:BarChart3},
 {href:'/staff',label:'People & Coaching',icon:Users},{href:'/team',label:'Team Hub',icon:BookOpen},{href:'/operating-system',label:'IMS OS',icon:Activity},{href:'/dashboard?view=owner',label:'Business Overview',icon:BarChart3},
 {href:'/settings',label:'Owner Settings',icon:Settings},{href:'/settings/services',label:'Services',icon:Settings},{href:'/settings/email',label:'Logins',icon:Mail},{href:'/settings/migration',label:'Migration Center',icon:ClipboardList},
];
const trainerMore = [
 {href:'/messages',label:'Communications',icon:MessageCircle},{href:'/assessments',label:'Assessments',icon:ClipboardList},{href:'/programs',label:'Programs',icon:Dumbbell},{href:'/fuel',label:'Fuel & Performance',icon:Activity},{href:'/library',label:'Exercise Library',icon:Dumbbell},{href:'/classes/manage',label:'Classes',icon:GraduationCap},{href:'/team',label:'Team Hub',icon:BookOpen},
];
export function StaffBottomNav({role}:{role:Exclude<UserRole,'client'>}){const pathname=usePathname(),params=useSearchParams(),[open,setOpen]=useState(false),dialog=useRef<HTMLElement|null>(null);const moreItems=role==='owner'?ownerMore:trainerMore,active=activeWorkspace([...coreItems,...moreItems].map(i=>i.href),pathname,params.get('view')==='owner');
 useEffect(()=>{if(!open)return;const before=document.activeElement instanceof HTMLElement?document.activeElement:null,overflow=document.body.style.overflow;document.body.style.overflow='hidden';const first=dialog.current?.querySelector<HTMLElement>('button,a[href]');first?.focus();function keys(e:KeyboardEvent){if(e.key==='Escape'){setOpen(false);return;}if(e.key!=='Tab'||!dialog.current)return;const nodes=[...dialog.current.querySelectorAll<HTMLElement>('button:not([disabled]),a[href]')];if(!nodes.length)return;const a=nodes[0],b=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===a){e.preventDefault();b.focus();}else if(!e.shiftKey&&document.activeElement===b){e.preventDefault();a.focus();}}window.addEventListener('keydown',keys);return()=>{document.body.style.overflow=overflow;window.removeEventListener('keydown',keys);before?.focus();};},[open]);
 return <>{open&&<div className="fixed inset-0 z-50 lg:hidden"><button tabIndex={-1} aria-label="Close more navigation" className="absolute inset-0 bg-black/50" onClick={()=>setOpen(false)}/><section ref={dialog} role="dialog" aria-modal="true" aria-label="More navigation" className="band absolute inset-x-0 bottom-0 max-h-[85dvh] space-y-4 overflow-y-auto overscroll-contain rounded-t-3xl border-t border-divider p-5 pb-24 shadow-2xl"><div className="flex items-center justify-between"><h2 className="text-lg font-semibold text-white">Workspaces</h2><button onClick={()=>setOpen(false)} className="flex min-h-11 min-w-11 items-center justify-center text-white" aria-label="Close menu"><X className="h-5 w-5"/></button></div>{WORKSPACE_GROUPS.map(group=>{const items=moreItems.filter(i=>navigationGroup(i.href)===group);if(!items.length)return null;return <section key={group}><h3 className="mb-2 text-xs font-semibold uppercase tracking-wider text-white/60">{group}</h3><div className="grid grid-cols-3 gap-2">{items.map(item=>{const Icon=item.icon;return <Link key={item.href} href={item.href} aria-current={active===item.href?'page':undefined} onClick={()=>setOpen(false)} className={cn('flex min-h-20 flex-col items-center justify-center gap-2 rounded-xl px-2 py-3 text-center text-xs',active===item.href?'bg-white/15 text-white':'bg-white/5 text-white/80')}><Icon aria-hidden="true" className="h-5 w-5"/>{item.label}</Link>;})}</div></section>;})}</section></div>}
 <nav aria-label="Staff mobile navigation" className="band safe-bottom fixed inset-x-0 bottom-0 z-40 border-t border-divider lg:hidden"><ul className="mx-auto grid max-w-2xl grid-cols-5 px-2">{coreItems.map(item=>{const Icon=item.icon;return <li key={item.href}><Link href={item.href} aria-current={active===item.href?'page':undefined} className={cn('flex min-h-14 flex-col items-center justify-center gap-1 rounded-xl py-2 text-[11px]',active===item.href?'bg-white/10 text-white':'text-white/65')}><Icon aria-hidden="true" className="h-5 w-5"/><span>{item.label}</span></Link></li>;})}<li><button aria-expanded={open} onClick={()=>setOpen(true)} className="flex min-h-14 w-full flex-col items-center justify-center gap-1 rounded-xl py-2 text-[11px] text-white/65"><MoreHorizontal aria-hidden="true" className="h-5 w-5"/><span>More</span></button></li></ul></nav></>;
}
