import Link from "next/link";
import {redirect} from "next/navigation";
import {Download, Clock3, Users, CalendarRange, BadgeDollarSign} from "lucide-react";
import {createClient} from "@/lib/supabase/server";
import {AppShell} from "@/components/layout/app-shell";
import {calculatePayrollEvidence,type PayrollRule} from "@/lib/payroll/calculate";

export const dynamic="force-dynamic";
const TZ="America/Los_Angeles";
const ymd=(d:Date)=>new Intl.DateTimeFormat("en-CA",{timeZone:TZ}).format(d);
const offset=(date:string)=>new Intl.DateTimeFormat("en-US",{timeZone:TZ,timeZoneName:"longOffset"}).formatToParts(new Date(date+"T12:00:00Z")).find(p=>p.type==="timeZoneName")?.value.replace("GMT","")||"-08:00";
function defaults(){const now=new Date();const parts=new Intl.DateTimeFormat("en-US",{timeZone:TZ,year:"numeric",month:"2-digit"}).formatToParts(now);const year=parts.find(p=>p.type==="year")?.value??String(now.getFullYear());const month=parts.find(p=>p.type==="month")?.value??String(now.getMonth()+1).padStart(2,"0");const from=`${year}-${month}-01`;const next=new Date(`${from}T12:00:00Z`);next.setUTCMonth(next.getUTCMonth()+1);return {from,to:next.toISOString().slice(0,10)};}
export default async function PayrollReport({searchParams}:{searchParams:Promise<{from?:string;to?:string}>}){
 const db=await createClient();const {data:{user}}=await db.auth.getUser();if(!user)redirect("/login?next=/reports/payroll");
 const me=await db.from("profiles").select("role").eq("id",user.id).maybeSingle();if(me.error||me.data?.role!=="owner")redirect("/dashboard");
 const d=defaults(),params=await searchParams;const from=/^\d{4}-\d{2}-\d{2}$/.test(params.from??"")?params.from!:d.from;const to=/^\d{4}-\d{2}-\d{2}$/.test(params.to??"")?params.to!:d.to;
 const start=new Date(`${from}T00:00:00${offset(from)}`).toISOString(),end=new Date(`${to}T00:00:00${offset(to)}`).toISOString();
 const sessions=await db.from("sessions").select("id,trainer_id,client_id,scheduled_at,duration_minutes,status,completed_at").gte("scheduled_at",start).lt("scheduled_at",end).in("status",["completed","late_cancelled","no_show"]).order("scheduled_at");
 if(sessions.error)throw new Error("Payroll session evidence is unavailable.");
 const trainerIds=[...new Set((sessions.data??[]).map(s=>s.trainer_id).filter(Boolean))] as string[];const clientIds=[...new Set((sessions.data??[]).map(s=>s.client_id))];
 const [trainers,clients,rulesQ]=await Promise.all([trainerIds.length?db.from("profiles").select("id,full_name").in("id",trainerIds):Promise.resolve({data:[],error:null}),clientIds.length?db.from("profiles").select("id,full_name").in("id",clientIds):Promise.resolve({data:[],error:null}),db.from("trainer_compensation_rules").select("trainer_id,compensation_type,rate_cents,late_cancel_rate_cents,no_show_rate_cents,effective_from,active").eq("active",true)]);
 if(trainers.error||clients.error||rulesQ.error)throw new Error("Payroll configuration is unavailable.");
 const rules=new Map((rulesQ.data??[]).map(r=>[r.trainer_id,r]));
 const trainerNames=new Map((trainers.data??[]).map(r=>[r.id,r.full_name]));const clientNames=new Map((clients.data??[]).map(r=>[r.id,r.full_name]));
 const groups=new Map<string,{name:string;completed:number;minutes:number;late:number;noShow:number}>();
 for(const s of sessions.data??[]){if(!s.trainer_id)continue;const g=groups.get(s.trainer_id)??{name:trainerNames.get(s.trainer_id)??"Trainer",completed:0,minutes:0,late:0,noShow:0};if(s.status==="completed"){g.completed++;g.minutes+=s.duration_minutes??60}else if(s.status==="late_cancelled")g.late++;else if(s.status==="no_show")g.noShow++;groups.set(s.trainer_id,g);}
 const calculations=(sessions.data??[]).map(s=>({session:s,calc:calculatePayrollEvidence(s,(rules.get(s.trainer_id??"")??null) as PayrollRule|null)}));
 const proposedCents=calculations.reduce((n,x)=>n+(x.calc.amount_cents??0),0);const needsReview=calculations.filter(x=>!x.calc.eligible).length;
 const totalCompleted=[...groups.values()].reduce((n,g)=>n+g.completed,0),totalMinutes=[...groups.values()].reduce((n,g)=>n+g.minutes,0);
 return <AppShell expectedRole="owner"><main className="mx-auto flex w-full max-w-6xl flex-col gap-5 py-6">
  <header className="rounded-3xl bg-band p-6 text-white sm:p-8"><p className="text-xs font-semibold uppercase tracking-[.2em] text-white/60">Owner / Payroll prep</p><h1 className="mt-2 text-4xl font-bold">Payroll Center</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-white/75">Completed-session evidence by trainer. Coach OS does not infer compensation rates, employment classification or taxes.</p></header>
  <form className="flex flex-wrap items-end gap-3 rounded-2xl border border-divider bg-white p-4"><label className="text-xs font-semibold text-cream-dim">From<input name="from" type="date" defaultValue={from} className="mt-1 min-h-11 rounded-xl border border-divider px-3 text-sm"/></label><label className="text-xs font-semibold text-cream-dim">To (exclusive)<input name="to" type="date" defaultValue={to} className="mt-1 min-h-11 rounded-xl border border-divider px-3 text-sm"/></label><button className="min-h-11 rounded-xl bg-sky px-4 text-sm font-semibold text-white">Apply period</button><a href={`/api/reports/payroll?from=${from}&to=${to}`} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-divider px-4 text-sm font-semibold text-cream"><Download className="h-4 w-4"/>Export evidence CSV</a></form>
  <section className="grid grid-cols-2 gap-3 sm:grid-cols-5"><div className="rounded-2xl border border-divider bg-white p-4"><CalendarRange className="h-5 w-5 text-sky"/><p className="mt-3 text-3xl font-bold">{totalCompleted}</p><p className="text-xs text-cream-faint">completed sessions</p></div><div className="rounded-2xl border border-divider bg-white p-4"><Clock3 className="h-5 w-5 text-sky"/><p className="mt-3 text-3xl font-bold">{(totalMinutes/60).toFixed(1)}</p><p className="text-xs text-cream-faint">delivered hours</p></div><div className="rounded-2xl border border-divider bg-white p-4"><Users className="h-5 w-5 text-sky"/><p className="mt-3 text-3xl font-bold">{groups.size}</p><p className="text-xs text-cream-faint">trainers with activity</p></div><div className="rounded-2xl border border-divider bg-white p-4"><BadgeDollarSign className="h-5 w-5 text-sky"/><p className="mt-3 text-2xl font-bold">{proposedCents>0?new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(proposedCents/100):"—"}</p><p className="text-xs text-cream-faint">proposed session compensation</p></div><div className="rounded-2xl border border-sky/20 bg-sky/5 p-4"><BadgeDollarSign className="h-5 w-5 text-sky"/><p className="mt-3 text-sm font-semibold">Provider sync next</p><p className="text-xs text-cream-faint">QuickBooks/Gusto connection can consume reviewed payroll evidence.</p></div></section>
  <section className="overflow-hidden rounded-2xl border border-divider bg-white"><div className="border-b border-divider p-5"><h2 className="font-semibold text-cream">Trainer summary</h2><p className="mt-1 text-xs text-cream-faint">Pay amounts remain blank until you explicitly configure compensation rules.</p></div><div className="divide-y divide-divider">{[...groups.entries()].map(([id,g])=><div key={id} className="grid grid-cols-2 gap-3 p-5 sm:grid-cols-5"><div className="col-span-2 sm:col-span-1"><p className="font-semibold text-cream">{g.name}</p></div><div><p className="text-xs text-cream-faint">Completed</p><p className="font-semibold">{g.completed}</p></div><div><p className="text-xs text-cream-faint">Hours</p><p className="font-semibold">{(g.minutes/60).toFixed(2)}</p></div><div><p className="text-xs text-cream-faint">Late cancels</p><p className="font-semibold">{g.late}</p></div><div><p className="text-xs text-cream-faint">No-shows</p><p className="font-semibold">{g.noShow}</p></div><div className="col-span-2 sm:col-span-5"><p className="text-xs text-cream-faint">Compensation rule</p><p className="text-sm font-semibold text-cream">{rules.get(id)?`${rules.get(id)!.compensation_type.replaceAll("_"," ")} · effective ${rules.get(id)!.effective_from}`:"Not configured"}</p></div></div>)}{groups.size===0&&<p className="p-6 text-sm text-cream-dim">No completed, late-cancelled or no-show sessions in this period.</p>}</div></section>
  <section className="rounded-2xl border border-divider bg-white p-5"><h2 className="font-semibold text-cream">Payroll integration boundary</h2><p className="mt-2 text-sm leading-6 text-cream-dim">Coach OS can prepare verified session/time evidence. A payroll provider should remain the system that calculates wages, withholding, payroll taxes and filings. Provider writes will require owner review before submission.</p></section>
 </main></AppShell>;
}