import Link from "next/link";
import {redirect} from "next/navigation";
import {Users,CalendarDays,ListChecks,Dumbbell,MessageCircle,BookOpen,ShieldCheck,BadgeDollarSign,ArrowRight,Phone,AlertTriangle} from "lucide-react";
import {createClient,createServiceClient} from "@/lib/supabase/server";
import {AppShell} from "@/components/layout/app-shell";
import {TEAM_RESOURCES,TEAM_HANDBOOK_VERSION,TEAM_HANDBOOK_UPDATED} from "@/lib/team/hr-resources";

export const dynamic="force-dynamic";
const money=(c:number|null)=>c==null?null:new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(c/100);

export default async function TeamHubPage(){
 const db=await createClient();const {data:{user}}=await db.auth.getUser();if(!user)redirect("/login?next=/team");
 const me=await db.from("profiles").select("id,role,full_name,email,phone,deleted_at").eq("id",user.id).maybeSingle();
 if(me.error||!me.data||me.data.deleted_at||!["owner","trainer"].includes(me.data.role))redirect("/dashboard");
 const profile=me.data,svc=createServiceClient(),since30=new Date(Date.now()-30*86400000).toISOString(),weekAhead=new Date(Date.now()+7*86400000).toISOString();
 const [clientsQ,doneQ,upcomingQ,ruleQ]=await Promise.all([
  svc.from("clients").select("id",{count:"exact",head:true}).eq("status","active").eq("primary_trainer_id",user.id),
  svc.from("sessions").select("id",{count:"exact",head:true}).eq("trainer_id",user.id).eq("status","completed").gte("scheduled_at",since30),
  svc.from("sessions").select("id",{count:"exact",head:true}).eq("trainer_id",user.id).in("status",["scheduled","confirmed","requested"]).gte("scheduled_at",new Date().toISOString()).lt("scheduled_at",weekAhead),
  svc.from("trainer_compensation_rules").select("compensation_type,rate_cents,late_cancel_rate_cents,no_show_rate_cents,provider,provider_employee_id,effective_from,active").eq("trainer_id",user.id).maybeSingle(),
 ]);
 if([clientsQ,doneQ,upcomingQ,ruleQ].some(q=>q.error))throw new Error("Team Hub could not be loaded.");
 const rule=ruleQ.data;const rateLabel=!rule||!rule.active?"Not configured":rule.compensation_type==="per_session"&&rule.rate_cents!=null?money(rule.rate_cents)+" / completed session":rule.compensation_type==="hourly"&&rule.rate_cents!=null?money(rule.rate_cents)+" / hour":rule.compensation_type.replaceAll("_"," ");
 const quick=[
  {href:"/schedule",label:"My schedule",icon:CalendarDays,detail:(upcomingQ.count??0)+" upcoming / requested · next 7d"},
  {href:"/action-center",label:"My actions",icon:ListChecks,detail:"Messages, programs and client follow-up"},
  {href:"/clients",label:"My clients",icon:Users,detail:(clientsQ.count??0)+" active clients assigned"},
  {href:"/library",label:"Exercise Library",icon:Dumbbell,detail:"Programming, demos and new exercises"},
  {href:"/messages",label:"Communications",icon:MessageCircle,detail:"Client coaching conversations"},
 ];
 return <AppShell><main className="mx-auto flex w-full max-w-6xl flex-col gap-5 py-6">
  <header className="rounded-3xl bg-band p-6 text-white shadow-lg sm:p-8"><p className="text-xs font-semibold uppercase tracking-[.2em] text-sky-light">IMS Team Hub</p><h1 className="mt-2 text-4xl font-bold">Welcome, {profile.full_name.split(" ")[0]}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-white/75">Your internal home for coaching standards, schedule, payroll setup, facility expectations and IMS operating resources.</p><div className="mt-5 flex flex-wrap gap-2 text-xs text-white/70"><span className="rounded-full bg-white/10 px-3 py-1.5">Role · {profile.role}</span><span className="rounded-full bg-white/10 px-3 py-1.5">Handbook v{TEAM_HANDBOOK_VERSION}</span><span className="rounded-full bg-white/10 px-3 py-1.5">Updated {TEAM_HANDBOOK_UPDATED}</span></div></header>
  <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{quick.map(q=>{const Icon=q.icon;return <Link key={q.href} href={q.href} className="group rounded-2xl border border-divider bg-white p-4 shadow-sm transition hover:border-sky/40"><Icon className="h-5 w-5 text-sky"/><p className="mt-3 font-semibold text-cream">{q.label}</p><p className="mt-1 text-xs leading-5 text-cream-faint">{q.detail}</p><ArrowRight className="mt-3 h-4 w-4 text-cream-faint transition group-hover:translate-x-1 group-hover:text-sky"/></Link>})}</section>
  <section className="grid gap-4 lg:grid-cols-3"><div className="rounded-2xl border border-divider bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><Users className="h-5 w-5 text-sky"/><h2 className="font-semibold text-cream">My IMS profile</h2></div><dl className="mt-4 space-y-3 text-sm"><div><dt className="text-xs text-cream-faint">Name</dt><dd className="font-medium text-cream">{profile.full_name}</dd></div><div><dt className="text-xs text-cream-faint">Email</dt><dd className="font-medium text-cream">{profile.email??"—"}</dd></div><div><dt className="text-xs text-cream-faint">Phone</dt><dd className="font-medium text-cream">{profile.phone??"Not added"}</dd></div><div><dt className="text-xs text-cream-faint">Completed sessions · 30d</dt><dd className="font-medium text-cream">{doneQ.count??0}</dd></div></dl></div>
  <div className="rounded-2xl border border-divider bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><BadgeDollarSign className="h-5 w-5 text-sky"/><h2 className="font-semibold text-cream">My payroll setup</h2></div><p className="mt-4 text-xs text-cream-faint">Compensation structure</p><p className="mt-1 text-lg font-semibold text-cream">{rateLabel}</p><p className="mt-3 text-xs text-cream-faint">Effective date</p><p className="mt-1 text-sm font-medium text-cream">{rule?.effective_from??"Not configured"}</p><p className="mt-3 text-xs text-cream-faint">Provider status</p><p className="mt-1 text-sm font-medium text-cream">{rule?.provider_employee_id?"Mapped to payroll provider":rule?.provider?"Provider selected · mapping pending":"Not mapped"}</p><p className="mt-3 text-xs leading-5 text-cream-dim">Session records are payroll evidence. Final payroll remains owner-reviewed and processed through the payroll provider.</p></div>
  <div className="rounded-2xl border border-divider bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-sky"/><h2 className="font-semibold text-cream">Safety & escalation</h2></div><p className="mt-3 text-sm leading-6 text-cream-dim">If there is an immediate emergency, call 911. For facility hazards, client incidents, privacy concerns, billing issues or conduct concerns, contact the IMS owner promptly and document the operational facts in the appropriate system.</p><div className="mt-4 rounded-xl bg-status-moderate/10 p-3"><div className="flex items-center gap-2"><AlertTriangle className="h-4 w-4 text-status-moderate"/><p className="text-xs font-semibold text-cream">Never bypass a safety restriction to keep a session moving.</p></div></div>{profile.role==="owner"&&<Link href="/settings/staff" className="mt-4 inline-flex min-h-11 items-center gap-1 text-sm font-semibold text-sky">Owner staff controls <ArrowRight className="h-4 w-4"/></Link>}</div></section>
  <section className="rounded-3xl border border-divider bg-white p-5 shadow-sm sm:p-6"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2"><BookOpen className="h-5 w-5 text-sky"/><h2 className="text-lg font-semibold text-cream">IMS Team Handbook</h2></div><p className="mt-1 text-sm leading-6 text-cream-dim">Versioned internal operating guidance for trainers. This is an operational guide, not an employment contract or replacement for applicable law or signed agreements.</p></div></div><div className="mt-5 grid gap-4 md:grid-cols-2">{TEAM_RESOURCES.map(resource=><article key={resource.key} id={resource.key} className="rounded-2xl border border-divider p-5"><h3 className="font-semibold text-cream">{resource.title}</h3><p className="mt-1 text-sm leading-6 text-cream-dim">{resource.summary}</p><ul className="mt-3 space-y-2">{resource.points.map(point=><li key={point} className="flex gap-2 text-sm leading-6 text-cream-dim"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-sky"/><span>{point}</span></li>)}</ul></article>)}</div></section>
  <section className="rounded-2xl border border-sky/20 bg-sky/5 p-5"><div className="flex items-center gap-2"><Phone className="h-5 w-5 text-sky"/><h2 className="font-semibold text-cream">Need help?</h2></div><p className="mt-2 text-sm leading-6 text-cream-dim">Use Coach OS Communications for client-related coaching questions. For employment, payroll, role, facility or sensitive operational questions, contact the IMS owner directly.</p></section>
 </main></AppShell>;
}
