import {metric,ownedPage,reportOf,totalRow,type Snapshot,type AcquisitionSource} from './model';
export type AcquisitionInsight={key:string;title:string;kind:'measurement'|'seo'|'local'|'conversion';priority:'high'|'normal';evidence:string;snapshot_ids:string[];next_step:string};
/** Deterministic evidence rules, not AI forecasts, causal attribution or permission to advertise. */
export function acquisitionInsights(sources:AcquisitionSource[],snapshots:Snapshot[]):AcquisitionInsight[]{
 const output:AcquisitionInsight[]=[],get=(connector:string)=>snapshots.find(s=>s.connector===connector);
 const ga=get('googleanalytics4'),gsc=get('searchconsole'),local=get('google_my_business');
 if(ga){const overview=reportOf(ga,'overview');if(!totalRow(ga))output.push({key:'ga4-coverage',title:'Verify website measurement before scaling traffic',kind:'measurement',priority:'high',evidence:`GA4 account ${ga.account_id} returned ${overview?.status==='empty'?'no summary rows':'no usable summary'} for ${ga.payload.start}–${ga.payload.end}. This is not proof of zero website visitors.`,snapshot_ids:[ga.id],next_step:'Verify the intended web stream, collected hostname, tag/consent setup and Realtime with a real visit. Keep key events separate from confirmed inquiries.'});
  const hosts=reportOf(ga,'hosts'),allowed=sources.find(s=>s.connector==='googleanalytics4')?.hosts??[];
  if(hosts?.status==='available'&&hosts.rows.some(r=>typeof r.hostname==='string'&&!allowed.includes(r.hostname)))output.push({key:'ga4-hostnames',title:'Review unexpected tracked hostnames',kind:'measurement',priority:'high',evidence:'The GA4 hostname report includes hosts outside the configured IMS website list. No host was automatically excluded or merged.',snapshot_ids:[ga.id],next_step:'Review internal traffic, old domains and web streams before interpreting acquisition performance.'});
 }
 if(gsc){const queries=reportOf(gsc,'queries'),anomalies=queries?.rows.filter(r=>typeof r.query==='string'&&/train|mobility|gym/i.test(r.query)&&Number(r.impressions)>=30&&r.clicks===0&&typeof r.position==='number'&&r.position<=3)??[];
  if(anomalies.length)output.push({key:'search-rank-ctr',title:'Validate high-visibility, zero-click search queries',kind:'seo',priority:'high',evidence:`${anomalies.length} returned web-query rows have at least 30 impressions, zero clicks and reported average position ≤3. These are averaged search observations, not a guaranteed local rank.`,snapshot_ids:[gsc.id],next_step:'Inspect country, device and search appearance in Search Console. Review the result snippet and matching service page; do not buy ads solely from the position number.'});
  const pages=reportOf(gsc,'pages'),paths=new Map<string,Set<string>>();
  for(const r of pages?.rows??[]){const href=ownedPage(r.page,sources.find(s=>s.connector==='searchconsole')?.hosts??[]);if(!href)continue;const u=new URL(href),key=u.pathname.replace(/\.html$/,'').replace(/\/$/,'')||'/';const set=paths.get(key)??new Set<string>();set.add(href);paths.set(key,set);}
  if([...paths.values()].some(set=>set.size>1))output.push({key:'canonical-paths',title:'Review duplicate URL variants before creating more pages',kind:'seo',priority:'normal',evidence:'Search Console returned multiple www/non-www or .html/extensionless variants of at least one path. This indicates variants in report evidence, not a confirmed indexing defect.',snapshot_ids:[gsc.id],next_step:'Inspect canonical tags, internal links and redirects. Keep the original source URLs separate; do not redirect or remove pages automatically.'});
 }
 if(local){const row=totalRow(local),directions=metric(row,'direction_requests'),web=metric(row,'website_clicks');if(web!==null||directions!==null)output.push({key:'local-attribution',title:'Make the Business Profile website link traceable',kind:'local',priority:'normal',evidence:`The profile reported ${web??'unknown'} website clicks and ${directions??'unknown'} directions requests for ${local.payload.start}–${local.payload.end}. Neither measures completed consultations.`,snapshot_ids:[local.id],next_step:'Prepare a tagged link to the verified IMS site, review it, then manually update the public profile only after approval. Check form success and inquiry-source capture.'});}
 if(output.length===0&&snapshots.length)output.push({key:'measurement-review',title:'Review source coverage and conversion definitions',kind:'conversion',priority:'normal',evidence:'Connected-source snapshots exist, but these conservative rules did not identify a specific actionable pattern. No result or acquisition target was invented.',snapshot_ids:snapshots.slice(0,3).map(s=>s.id),next_step:'Review reported traffic alongside actual inquiry outcomes before choosing an experiment.'});
 return output;
}
