"use client";
import {useRef,useState} from "react";
import {Check,Loader2,Users} from "lucide-react";
import {useRouter} from "next/navigation";
type ClassRow={id:string;name:string;category:string;description:string;starts_at:string;ends_at:string;location:string|null;capacity:number;booked:number;trainer:string;enrollment_id:string|null;enrollment_status:string|null};
export function ClassBookingList({rows}:{rows:ClassRow[]}){
 const router=useRouter(),lock=useRef(false),[busy,setBusy]=useState<string|null>(null),[error,setError]=useState<string|null>(null),[message,setMessage]=useState<string|null>(null);
 async function book(id:string){if(lock.current)return;lock.current=true;setBusy(id);setError(null);setMessage(null);try{const response=await fetch("/api/classes/book",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({occurrence_id:id,request_id:crypto.randomUUID()})});const data=await response.json().catch(()=>null);if(!response.ok||!data?.ok)throw new Error(data?.error||"Booking was not confirmed.");setMessage(data.status==="waitlisted"?"Class is full. You are on the waitlist.":"Class spot confirmed.");router.refresh();}catch(e){setError(e instanceof Error?e.message:"Could not book class.");}finally{lock.current=false;setBusy(null);}}
 async function cancel(id:string){if(lock.current)return;lock.current=true;setBusy(id);setError(null);setMessage(null);try{const response=await fetch("/api/classes/book?enrollment_id="+encodeURIComponent(id),{method:"DELETE"});const data=await response.json().catch(()=>null);if(!response.ok||!data?.ok)throw new Error(data?.error||"Cancellation was not confirmed.");setMessage("Class booking cancelled.");router.refresh();}catch(e){setError(e instanceof Error?e.message:"Could not cancel class.");}finally{lock.current=false;setBusy(null);}}
 return <div className="space-y-3">{error&&<p role="alert" className="rounded-xl border border-status-limited/30 p-3 text-sm text-status-limited">{error}</p>}{message&&<p role="status" className="rounded-xl border border-status-optimal/30 p-3 text-sm text-status-optimal">{message}</p>}{rows.length===0?<p className="rounded-2xl border border-dashed border-divider p-5 text-sm text-cream-dim">No classes are published yet. Private class setup remains hidden until IMS is ready to launch it.</p>:rows.map(row=>{const remaining=Math.max(0,row.capacity-row.booked),active=["booked","waitlisted"].includes(row.enrollment_status??"");return <article key={row.id} className="rounded-2xl border border-divider bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wide text-sky">{row.category}</p><h3 className="mt-1 text-lg font-semibold text-cream">{row.name}</h3><p className="mt-1 text-sm text-cream-dim">{new Date(row.starts_at).toLocaleString("en-US",{timeZone:"America/Los_Angeles",weekday:"short",month:"short",day:"numeric",hour:"numeric",minute:"2-digit"})} · {row.trainer}{row.location?" · "+row.location:""}</p></div><div className="text-right"><p className="inline-flex items-center gap-1 text-sm font-semibold text-cream"><Users className="h-4 w-4 text-sky"/>{remaining} spots</p><p className="mt-1 text-xs text-cream-faint">{row.booked}/{row.capacity} booked</p></div></div>{row.description&&<p className="mt-3 text-sm leading-6 text-cream-dim">{row.description}</p>}<div className="mt-4">{active?<button disabled={busy===row.enrollment_id} onClick={()=>void cancel(row.enrollment_id!)} className="inline-flex min-h-11 items-center rounded-xl border border-divider px-4 text-sm font-semibold text-cream">{busy===row.enrollment_id?<Loader2 className="mr-2 h-4 w-4 animate-spin"/>:null}{row.enrollment_status==="waitlisted"?"Leave waitlist":"Cancel class"}</button>:<button disabled={busy===row.id} onClick={()=>void book(row.id)} className="inline-flex min-h-11 items-center rounded-xl bg-sky px-4 text-sm font-semibold text-white">{busy===row.id?<Loader2 className="mr-2 h-4 w-4 animate-spin"/>:<Check className="mr-2 h-4 w-4"/>}{remaining>0?"Book class":"Join waitlist"}</button>}</div></article>})}</div>;
}
