import Link from "next/link";
import {createClient} from "@/lib/supabase/server";
import {participationSummary,type ClassParticipation} from "@/lib/classes/launch";
export async function ClientClassParticipation(){
 const db=await createClient();const {data:{user}}=await db.auth.getUser();if(!user)return null;
 const profile=await db.from("profiles").select("role,deleted_at").eq("id",user.id).maybeSingle();if(profile.error)throw new Error("Class-history authorization unavailable.");if(!profile.data||profile.data.deleted_at||profile.data.role!=="client")return null;
 const history=await db.rpc("get_my_class_participation");
 if(history.error||!Array.isArray(history.data))return <section className="rounded-2xl border border-status-limited/30 bg-white p-5"><h2 className="text-xl font-semibold">Class participation</h2><p role="alert" className="mt-2 text-sm text-status-limited">Class-history evidence is unavailable or its rollout is pending. No attendance count was inferred.</p></section>;
 const rows=history.data as ClassParticipation[],summary=participationSummary(rows,new Date().toISOString());
 return <section className="rounded-2xl border border-divider bg-white p-5"><p className="text-xs font-semibold uppercase tracking-wide text-sky">Group coaching history</p><h2 className="mt-2 text-xl font-semibold">Classes attended · recorded attendance only</h2><p className="mt-3 text-3xl font-bold">{summary.attended}</p><p className="mt-2 text-sm leading-6 text-cream-dim">Documented attendance at completed classes in the loaded history. These visits stay separate from your private sessions and from what exercises you actually performed.</p>{summary.needsReview>0&&<p className="mt-2 text-sm text-cream-dim">{summary.needsReview} records still need attendance or class-close review.</p>}
 <div className="mt-4 divide-y divide-divider">{rows.slice(0,8).map(row=><article key={row.enrollment_id} className="py-3"><h3 className="font-semibold">{row.class_name}</h3><p className="mt-1 text-xs text-cream-dim">{new Date(row.starts_at).toLocaleString("en-US",{timeZone:"America/Los_Angeles",month:"short",day:"numeric",year:"numeric",hour:"numeric",minute:"2-digit"})} · {row.enrollment_status.replaceAll("_"," ")}</p></article>)}</div>{!rows.length&&<p className="mt-3 text-sm text-cream-dim">No past class-participation records yet. Your individual training progress remains separate.</p>}<p className="mt-3 text-xs text-cream-faint">Showing up to 8 of the latest 100 past class records. This is not a lifetime total or a payment balance.</p><Link href="/classes" className="mt-2 inline-flex min-h-11 items-center text-sm font-semibold text-sky">IMS classes →</Link></section>;
}
