"use client";
import {useMemo,useState} from "react";
import {useRouter} from "next/navigation";
import Link from "next/link";

type Canonical={canonical_id:string;canonical_name:string;source_status:string;source_confidence:string;source_primary_joints:string;category:string;movement_pattern:string;equipment:string;mapping_status:string;matched_exercise_id:string|null;review_notes:string;review_priority:number;review_priority_reason:string;exact_candidate_id:string|null;exact_candidate_name:string|null;exact_candidate_count:number;safety_data_gap:string};
type Exercise={id:string;name:string;ims_label:string|null;primary_joints:string[]|null};
export function CanonicalMappingWorkspace({rows,exercises,isOwner=false,catalogAttested=false}:{rows:Canonical[];exercises:Exercise[];isOwner?:boolean;catalogAttested?:boolean}) {
 const router=useRouter();
 const [search,setSearch]=useState("");
 const [priority,setPriority]=useState(0);
 const [selected,setSelected]=useState<Canonical|null>(null);
 const [candidate,setCandidate]=useState("");
 const [candidateSearch,setCandidateSearch]=useState("");
 const [notes,setNotes]=useState("");
 const [busy,setBusy]=useState(false);
 const [bulkProgress,setBulkProgress]=useState("");
 const [message,setMessage]=useState("");
 const [showUnmatched,setShowUnmatched]=useState(true);
 const [completed,setCompleted]=useState<string[]>([]);
 const [bulkConsent,setBulkConsent]=useState(false);
 const [attestConsent,setAttestConsent]=useState(false);
 const [attested,setAttested]=useState(catalogAttested);
 const [attestStatus,setAttestStatus]=useState("");
 const matched=rows.filter(r=>r.mapping_status==="coach_confirmed").length;
 const filtered=rows.filter(r=>(priority===0?r.exact_candidate_count===1:r.review_priority===priority)&&(showUnmatched?r.mapping_status!=="coach_confirmed"&&!completed.includes(r.canonical_id):true)&&(r.canonical_name+" "+r.canonical_id).toLowerCase().includes(search.toLowerCase())).sort((a,b)=>Number(a.mapping_status==="coach_confirmed")-Number(b.mapping_status==="coach_confirmed")||b.exact_candidate_count-a.exact_candidate_count||a.canonical_id.localeCompare(b.canonical_id));
 const suggestions=useMemo(()=>{if(!selected)return [];let q=selected.canonical_name.toLowerCase().trim();let tokens=q.split(/\s+/).filter(t=>t.length>2);return exercises.map(e=>({e,score:(e.name.toLowerCase()===q?100:0)+tokens.filter(t=>e.name.toLowerCase().includes(t)).length})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,12).map(x=>x.e)},[selected,exercises]);
 const exactEligible=rows.filter(r=>r.exact_candidate_count===1&&r.exact_candidate_id&&r.mapping_status!=="coach_confirmed"&&!completed.includes(r.canonical_id));
 async function bulkExact(){if(!isOwner||!bulkConsent||busy)return;setBusy(true);setMessage("");let ok=0;let failed=0;for(const row of exactEligible){try{const res=await fetch("/api/exercise-reviews/canonical",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({canonical_id:row.canonical_id,exercise_id:row.exact_candidate_id,review_notes:`Owner attestation: I personally reviewed ${row.canonical_name} and confirmed its exact-name library identity. This does not grant client-specific safety clearance.`})});if(res.ok){ok++;setCompleted(old=>[...old,row.canonical_id]);}else failed++;}catch{failed++;}setBulkProgress(`${ok+failed}/${exactEligible.length} checked`);}setMessage(`${ok} identity matches saved; ${failed} need individual review. Safety approvals and client publication remain unchanged.`);setBulkConsent(false);setBusy(false);router.refresh();}
 async function attestCatalog(){if(!isOwner||!attestConsent||busy)return;setBusy(true);setAttestStatus("");try{const res=await fetch("/api/exercise-reviews/catalog-attestation",{method:"POST"});const data=await res.json();if(!res.ok){setAttestStatus(data.error||"Could not record owner review.");return;}setAttested(true);setAttestStatus(`${data.reviewed_count} source exercises recorded as owner-reviewed. Identity exceptions and safety metadata remain separate.`);}catch{setAttestStatus("Connection failed; no attestation recorded.")}finally{setBusy(false)}}
 const missingCandidate=!!selected&&!candidate;
 const exactSelection=!!selected&&selected.exact_candidate_count===1&&candidate===selected.exact_candidate_id;
 const missingRationale=!!selected&&!exactSelection&&notes.trim().length<15;
 const options=candidateSearch.trim()?exercises.filter(e=>(e.name+" "+(e.ims_label??"")).toLowerCase().includes(candidateSearch.toLowerCase())).slice(0,30):suggestions;
 async function save(){if(!selected||!candidate)return;setBusy(true);setMessage("");try{let res=await fetch("/api/exercise-reviews/canonical",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({canonical_id:selected.canonical_id,exercise_id:candidate,review_notes:notes.trim()||(exactSelection?`Coach confirmed identity: ${selected.canonical_name} matches library entry ${exercises.find(e=>e.id===candidate)?.name??selected.exact_candidate_name}.`:notes)})});let data=await res.json();if(!res.ok){setMessage(data.error||"Unable to save");return;}setMessage("Identity confirmed. Safety review remains separate.");setCompleted(old=>[...old,selected.canonical_id]);setSelected(null);setCandidate("");setNotes("");router.refresh();}catch{setMessage("Connection error. No mapping saved.")}finally{setBusy(false)}}
 return <div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_minmax(320px,420px)]">
  <section className="overflow-hidden rounded-2xl border border-divider bg-navy-soft">
   {isOwner&&<div className="space-y-3 border-b border-divider bg-navy p-4"><h2 className="text-lg font-semibold text-cream">Step 1 — Source library owner review</h2><p className="text-sm text-cream-dim">{attested?"Your signed source-catalog review is on record.":"Record your personal review of all 423 source exercises in the database. This is distinct from 604 library mappings and client-specific safety clearance."}</p>{!attested&&<><label className="flex items-start gap-2 text-sm text-cream"><input type="checkbox" checked={attestConsent} onChange={e=>setAttestConsent(e.target.checked)} disabled={busy}/>I personally reviewed all 423 source exercises and recognize them as part of my IMS exercise library.</label><button type="button" disabled={!attestConsent||busy} onClick={attestCatalog} className="min-h-11 rounded-lg border border-divider px-4 text-sm font-semibold text-cream disabled:opacity-40">Record my 423-exercise review</button></>}{attestStatus&&<p role="status" className="text-sm text-cream-dim">{attestStatus}</p>}<hr className="border-divider"/><h2 className="text-lg font-semibold text-cream">Owner bulk review — exact-name matches</h2><p className="text-sm text-cream-dim">{exactEligible.length} unique exact-name suggestions ready for your identity attestation. The remaining entries need manual matching or a verified import. This does not grant safety clearance or publish to clients.</p><label className="flex items-start gap-2 text-sm text-cream"><input type="checkbox" checked={bulkConsent} onChange={e=>setBulkConsent(e.target.checked)} disabled={busy}/>I personally reviewed these source exercises and authorize confirmation of their exact-name identity matches.</label><button type="button" disabled={!bulkConsent||busy||exactEligible.length===0} onClick={bulkExact} className="min-h-11 rounded-lg bg-sky px-4 font-semibold text-navy disabled:opacity-40">{busy?"Confirming…":`Confirm ${exactEligible.length} exact matches`}</button>{bulkProgress&&<p role="status" className="text-xs text-cream-dim">{bulkProgress}</p>}</div>}
   <div className="space-y-3 border-b border-divider p-4"><div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{[0,1,2,3].map(p=><button type="button" key={p} onClick={()=>{setPriority(p);setSelected(null)}} aria-pressed={priority===p} className={`rounded-lg border px-2 py-2 text-xs ${priority===p?"border-sky bg-sky/10 text-sky":"border-divider text-cream-dim"}`}>{p===0?"Quick matches":`Wave ${p}`} · {rows.filter(r=>p===0?r.exact_candidate_count===1:r.review_priority===p).length}</button>)}</div><p className="text-sm text-cream-dim">{matched} of {rows.length} coach-confirmed canonical mappings. Unconfirmed entries cannot receive safety approval.</p><input aria-label="Search canonical exercises" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search canonical ID or exercise" className="min-h-11 w-full rounded-lg border border-divider bg-navy px-3 text-sm text-cream"/></div>
   <label className="flex items-center gap-2 text-xs text-cream-dim"><input type="checkbox" checked={showUnmatched} onChange={e=>setShowUnmatched(e.target.checked)}/> Show pending only</label>
   <div className="max-h-[650px] divide-y divide-divider overflow-auto">{filtered.map(r=><button key={r.canonical_id} type="button" onClick={()=>{setSelected(r);setCandidate(r.matched_exercise_id??r.exact_candidate_id??"");setCandidateSearch("");setNotes(r.review_notes);setMessage("")}} aria-pressed={selected?.canonical_id===r.canonical_id} className="flex w-full items-center justify-between gap-3 p-4 text-left hover:bg-navy-elev"><div><p className="text-sm font-semibold text-cream">{r.canonical_name}</p><p className="mt-1 text-xs text-cream-faint">{r.canonical_id} · {r.exact_candidate_count===1?"Exact-name suggestion":r.exact_candidate_count>1?"Ambiguous names":"Manual search needed"}</p></div><span className={`shrink-0 text-xs ${r.mapping_status==="coach_confirmed"?"text-sky":"text-cream-faint"}`}>{r.mapping_status==="coach_confirmed"?"Confirmed":"Pending"}</span></button>)}</div>
  </section>
  <section className="h-fit space-y-4 rounded-2xl border border-divider bg-navy-soft p-5 lg:sticky lg:top-5">{!selected?<p className="text-sm text-cream-dim">Select a canonical source exercise to confirm its matching library entry.</p>:<>
   <div><h2 className="text-lg font-semibold text-cream">{selected.canonical_name}</h2><p className="mt-1 text-xs text-cream-faint">{selected.canonical_id} · {selected.source_status}</p><p className="mt-2 text-xs text-cream-dim">{selected.source_confidence}</p><p className="mt-2 rounded-lg border border-divider p-2 text-xs text-sky">{selected.review_priority_reason} · {selected.exact_candidate_count===1?"One exact-name candidate (not yet confirmed)":selected.exact_candidate_count===0?"No exact-name candidate":"Multiple exact-name candidates"} · {selected.safety_data_gap||"Safety data must be verified"}</p><p className="mt-2 text-xs text-cream-dim">{selected.review_priority_reason}</p><p role="note" className="mt-2 rounded-lg border border-divider p-3 text-xs text-cream-dim">Safety review gaps: {selected.safety_data_gap||"No source gaps flagged; coach verification still required."}</p>{selected.exact_candidate_name&&<p className="mt-2 text-xs text-sky">Exact-name candidate: {selected.exact_candidate_name} (not approved)</p>}</div>
   <div className="rounded-lg border border-divider p-3 text-sm text-cream-dim"><h3 className="font-semibold text-cream">Exercise context from your source library</h3><p>Category: {selected.category||"Not tagged"} · Movement pattern: {selected.movement_pattern||"Not tagged"}</p><p>Joint focus: {selected.source_primary_joints||"Needs tagging"} · Equipment: {selected.equipment||"Needs tagging"}</p><p className="mt-2 text-xs">Selection role and contraindication rules still require verified metadata. Exercise familiarity is not blanket clearance for restricted clients.</p></div>
   <p className="text-xs text-cream-dim">Suggestions are name-based only and are never automatic identity or safety approvals.</p>
   {exactSelection&&<div className="rounded-xl border border-sky/50 bg-sky/10 p-4"><p className="text-sm font-semibold text-cream">Quick review: are these the same movement?</p><p className="mt-2 text-sm text-cream">{selected.canonical_name} → {exercises.find(e=>e.id===candidate)?.name??selected.exact_candidate_name}</p><p className="mt-2 text-xs text-cream-dim">If yes, use the confirmation button below. Your identity decision will be documented automatically; safety approval is still separate.</p></div>}
   {!exactSelection&&<p className="rounded-lg border border-sky/30 p-3 text-sm text-cream-dim">For manual matches, select the correct library movement and explain how you verified it. If no equivalent exists, skip this item; do not guess.</p>}
   <label className="block text-xs text-cream-dim">Search all 604 library entries<input value={candidateSearch} onChange={e=>setCandidateSearch(e.target.value)} placeholder="Search by exercise name" className="mt-2 min-h-11 w-full rounded-lg border border-divider bg-navy px-3 text-sm text-cream"/></label>
   <label className="block text-xs text-cream-dim">Library match<select value={candidate} onChange={e=>setCandidate(e.target.value)} className="mt-2 min-h-11 w-full rounded-lg border border-divider bg-navy px-3 text-sm text-cream"><option value="">Choose verified match</option>{options.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}{candidate&&!options.some(e=>e.id===candidate)&&<option value={candidate}>Existing mapped exercise</option>}</select></label>
   <Link href="/exercise-reviews" className="block text-xs text-sky underline">Inspect full exercise library and safety metadata</Link>
   <label className="block text-xs text-cream-dim">{exactSelection?"Optional extra notes":"Identity verification rationale"}<textarea value={notes} onChange={e=>setNotes(e.target.value)} rows={4} maxLength={3000} placeholder="Explain how you verified these are the same exercise." className="mt-2 w-full rounded-lg border border-divider bg-navy p-3 text-sm text-cream"/></label>
   {missingCandidate&&<p role="status" className="text-xs text-status-limited">Choose a matching library exercise. Wave 1 contains entries with no exact-name candidate; search the full library or leave unmatched.</p>}
   {!missingCandidate&&missingRationale&&<p role="status" className="text-xs text-status-limited">Add your verification rationale (at least 15 characters; {notes.trim().length}/15).</p>}
   <button type="button" disabled={busy||missingCandidate||missingRationale} onClick={save} className="min-h-11 w-full rounded-lg bg-sky px-4 text-sm font-semibold text-navy disabled:opacity-40">{busy?"Saving…":exactSelection?"Yes — same movement":"Confirm manual match"}</button>
   <button type="button" disabled={busy} onClick={()=>{const current=filtered.findIndex(r=>r.canonical_id===selected.canonical_id);const next=filtered[current+1]??filtered[current-1];if(next){setSelected(next);setCandidate(next.matched_exercise_id??next.exact_candidate_id??"");setNotes(next.review_notes);setCandidateSearch("");setMessage("");}else{setSelected(null);setMessage("No more exercises in this filter.");}}} className="min-h-11 w-full rounded-lg border border-divider px-4 text-sm text-cream-dim">Skip / review next</button>
   {message&&<p role="status" className="text-xs text-cream-dim">{message}</p>}
  </>}</section>
 </div>;
}
