import {createClient} from "@/lib/supabase/server";
import {readCompleteEvidence} from "@/lib/migration/complete-read";
type HealthDay={day:string;steps:number|null;active_energy_kcal:number|null;exercise_minutes:number|null;sleep_hours:number|null;weight_lb:number|null;weight_source:string|null;workout_minutes:number|null;workout_count:number|null;available_types:string[];time_zone:string|null;utc_offset_minutes:number|null;synced_at:string};
const card="rounded-2xl border border-divider bg-white p-5";
function average(rows:HealthDay[],key:"steps"|"sleep_hours"|"exercise_minutes"){const v=rows.map(r=>r[key]).filter((x):x is number=>typeof x==="number"&&Number.isFinite(x));return{samples:v.length,value:v.length?Math.round(v.reduce((a,b)=>a+b,0)/v.length*10)/10:null};}
export async function AppleHealthCard({clientId}:{clientId:string}){
 const db=await createClient();let rows:HealthDay[];
 try{rows=await readCompleteEvidence<HealthDay>((a,b)=>db.from("client_health_daily").select("day,steps,active_energy_kcal,exercise_minutes,sleep_hours,weight_lb,weight_source,workout_minutes,workout_count,available_types,time_zone,utc_offset_minutes,synced_at",{count:"exact"}).eq("client_id",clientId).order("day",{ascending:false}).range(a,b));}
 catch{return <section className={card}><p className="text-xs font-semibold uppercase tracking-wider text-sky">Optional evidence</p><h2 className="mt-2 text-lg font-semibold">Apple Health + Apple Watch</h2><p className="mt-2 text-sm leading-6 text-cream-dim">Health evidence is unavailable right now. No activity, sleep, workout or weight value was inferred. Existing Fuel and Bod Pod history are unchanged.</p></section>;}
 const recent=rows.slice(0,7),steps=average(recent,"steps"),sleep=average(recent,"sleep_hours"),exercise=average(recent,"exercise_minutes"),weight=rows.find(r=>r.weight_lb!==null)??null;
 return <section className={card}><p className="text-xs font-semibold uppercase tracking-wider text-sky">Optional evidence</p><h2 className="mt-2 text-lg font-semibold">Apple Health + Apple Watch</h2><p className="mt-2 text-sm leading-6 text-cream-dim">Client-authorized daily context. Missing Health data is never treated as zero or failure. Bod Pod remains the IMS body-composition anchor.</p>
 {rows.length?<><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4">{[["Steps",steps.value===null?"Not available":Math.round(steps.value).toLocaleString(),steps.samples],["Sleep",sleep.value===null?"Not available":sleep.value+" h",sleep.samples],["Exercise",exercise.value===null?"Not available":exercise.value+" min",exercise.samples],["Latest weight",weight?.weight_lb===null||!weight?"Not available":weight.weight_lb+" lb",weight?1:0]].map(([label,value,samples])=><div key={String(label)} className="rounded-xl bg-surface-soft p-3"><p className="text-xs text-cream-faint">{label}</p><p className="mt-1 font-semibold">{value}</p><p className="mt-1 text-[11px] text-cream-faint">{samples} available sample{samples===1?"":"s"}</p></div>)}</div>{weight&&<p className="mt-3 text-xs text-cream-faint">Latest weight source: {weight.weight_source??"Apple Health source not identified"} · {weight.day}. Different scale/BIA methods remain separate from Bod Pod.</p>}<p className="mt-2 text-xs text-cream-faint">Showing up to 7 synced daily summaries. Last sync {rows[0].synced_at}. Client timezone is preserved when reported.</p></>:<p className="mt-4 text-sm text-cream-dim">No Apple Health summaries have been shared yet. Connect from the IMS iPhone app → Progress. Sharing is optional and can be changed in Apple Health settings.</p>}
 <div className="mt-3 rounded-xl bg-surface-soft p-3 text-xs leading-5 text-cream-dim"><strong>Coach context, not prescription.</strong> Watch calories, sleep estimates, workouts and home BIA can support a coaching conversation. They do not automatically change nutrition targets or mark a training session complete.</div></section>;
}
