"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import Link from "next/link";
import {FuelPlanEditor} from "./plan-editor";
import {FuelPlanView} from "./plan-view";
import {Field,NumberField,fieldClass,primaryClass,secondaryClass} from "./controls";
import {createNutritionDraft,type DietStyle,type NutritionGoal} from "@/lib/fuel/nutrition-draft";
import {validFuelReceipt,type FuelCommand} from "@/lib/fuel/validation";
import type {PlanVersion,Release} from "@/lib/fuel/model";
type Source={id:string;original_name:string;created_at:string};
type Extraction={recognized:boolean;blankTemplate:boolean;name:string;date:string;weightLb:number|null;bodyFatPct:number|null;fatMassLb:number|null;leanPct:number|null;leanMassLb:number|null;energySummary:string;warnings:string[]};
export function BodPodNutritionBuilder({clientId,clientName,today,sources,initialSourceId,latest,release}:{clientId:string;clientName:string;today:string;sources:Source[];initialSourceId?:string;latest:PlanVersion|null;release:Release|null}){
 const [sourceId,setSourceId]=useState(initialSourceId&&sources.some(s=>s.id===initialSourceId)?initialSourceId:sources[0]?.id??""),[extraction,setExtraction]=useState<Extraction|null>(null),[loadError,setLoadError]=useState<string|null>(null);
 const [date,setDate]=useState(""),[weight,setWeight]=useState<number|null>(null),[fat,setFat]=useState<number|null>(null),[lean,setLean]=useState<number|null>(null);
 const [goal,setGoal]=useState<NutritionGoal>("fat_loss"),[activity,setActivity]=useState(1.4),[days,setDays]=useState<number|null>(2),[style,setStyle]=useState<DietStyle>("flexible"),[allergies,setAllergies]=useState(""),[preferences,setPreferences]=useState(""),[meals,setMeals]=useState<3|4|5>(4),[clinical,setClinical]=useState(false),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[savedMeasurement,setSavedMeasurement]=useState(false),[draft,setDraft]=useState<ReturnType<typeof createNutritionDraft>|null>(null);
 const lock=useRef(false);
 useEffect(()=>{if(!sourceId){setExtraction(null);return;}const controller=new AbortController();setLoadError(null);setExtraction(null);fetch("/api/fuel/"+clientId+"/sources/"+sourceId+"/bod-pod",{cache:"no-store",signal:controller.signal}).then(async r=>{const body=await r.json();if(!r.ok)throw Error(body?.error??"Unable to read source.");return body.extraction as Extraction;}).then(x=>{if(controller.signal.aborted)return;setExtraction(x);setDate(x.date);setWeight(x.weightLb);setFat(x.bodyFatPct);setLean(x.leanMassLb);setConfirmed(false);setDraft(null);setSavedMeasurement(false);}).catch(e=>{if(!controller.signal.aborted)setLoadError(e instanceof Error?e.message:"Unable to read source.");});return()=>controller.abort();},[clientId,sourceId]);
 const source=sources.find(s=>s.id===sourceId),measurementReady=Boolean(sourceId&&date&&date<=today&&weight!==null&&weight>0&&lean!==null&&lean>0&&lean<=weight);
 const math=useMemo(()=>measurementReady?createNutritionDraft({clientName,start:today,weightLb:weight!,leanMassLb:lean!,bodyFatPct:fat,goal,activityFactor:activity,trainingDays:days,dietStyle:style,allergies,preferences,mealsPerDay:meals,clinicalReferral:clinical,sourceReference:"document:"+sourceId}):null,[measurementReady,clientName,today,weight,lean,fat,goal,activity,days,style,allergies,preferences,meals,clinical,sourceId]);
 async function confirmAndCreate(){if(lock.current||!measurementReady||!confirmed||!sourceId)return;lock.current=true;setBusy(true);setError(null);try{
  const command:FuelCommand={action:"record_body_comp",request_id:sourceId,date,weight_lb:weight!,body_fat_pct:fat,lean_mass_lb:lean,method:"bod_pod",source_kind:"source_transcription",source_reference:"document:"+sourceId+"; IMS Body Composition Test Results; coach-confirmed",protocol:"Imported from the selected IMS Bod Pod source after coach confirmation. Original source values are preserved; this record does not represent measured metabolic rate.",confirmed:true};
  const response=await fetch("/api/fuel/"+clientId,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(command)}),body=await response.json().catch(()=>null);
  if(!response.ok||!validFuelReceipt(body,command,clientId))throw Error(body?.error??"Bod Pod measurement receipt was not confirmed. Retry before creating a new request.");
  setSavedMeasurement(true);setDraft(math);
 }catch(e){setError(e instanceof Error?e.message:"Bod Pod confirmation is unconfirmed. Retry the same source.");}finally{lock.current=false;setBusy(false);}}
 return <div className="space-y-5">
  <section className="rounded-3xl border border-divider bg-white p-5"><p className="text-xs font-semibold uppercase tracking-wider text-sky">1 · Source</p><h2 className="mt-1 text-xl font-semibold">Upload / select the Bod Pod report</h2><p className="mt-2 text-sm leading-6 text-cream-dim">The IMS two-page results worksheet is parsed from its actual fillable result fields. Classification-table percentages, educational copy and prechecked reference boxes are never treated as this client&apos;s measurements.</p>
   {sources.length?<Field label="Private source"><select className={fieldClass} value={sourceId} onChange={e=>setSourceId(e.target.value)}>{sources.map(s=><option key={s.id} value={s.id}>{s.original_name} · {new Date(s.created_at).toLocaleDateString()}</option>)}</select></Field>:<p className="mt-3 text-sm">No private source documents yet.</p>}
   <Link className={secondaryClass+" mt-3"} href={"/clients/"+clientId+"/fuel/sources"}>Upload Bod Pod PDF →</Link>{loadError&&<p role="alert" className="mt-3 text-sm text-status-limited">{loadError}</p>}
   {extraction&&<div className="mt-4 rounded-2xl bg-surface-soft p-4"><p className="font-semibold">{extraction.recognized?"IMS worksheet recognized":"Source preserved, but exact IMS form fields were not recognized"}</p><p className="mt-2 text-sm text-cream-dim">{extraction.blankTemplate?"This appears to be a blank/reference copy. Enter the real printed values below and confirm them; nothing was inferred from the classification table.":"Review every extracted value against the original before saving."}</p>{extraction.name&&extraction.name.toLowerCase()!==clientName.toLowerCase()&&<p className="mt-2 text-sm text-status-moderate">Report name reads “{extraction.name}”. You are working on {clientName}; confirm the person before saving.</p>}{extraction.warnings.map((w,i)=><p className="mt-2 text-sm text-status-moderate" key={i}>{w}</p>)}</div>}
  </section>
  <section className="rounded-3xl border border-divider bg-white p-5"><p className="text-xs font-semibold uppercase tracking-wider text-sky">2 · Confirm measurements</p><h2 className="mt-1 text-xl font-semibold">Bod Pod result</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><Field label="Actual test date"><input className={fieldClass} type="date" max={today} value={date} onChange={e=>{setDate(e.target.value);setConfirmed(false);setDraft(null);}}/></Field><NumberField label="Weight · lb" value={weight} max={999} onChange={v=>{setWeight(v);setConfirmed(false);setDraft(null);}}/><NumberField label="Body fat · %" value={fat} max={100} onChange={v=>{setFat(v);setConfirmed(false);setDraft(null);}}/><NumberField label="Fat-free / lean mass · lb" value={lean} max={999} onChange={v=>{setLean(v);setConfirmed(false);setDraft(null);}}/></div>{extraction?.fatMassLb!==null&&extraction?.fatMassLb!==undefined&&<p className="mt-3 text-xs text-cream-faint">Source fat mass: {extraction.fatMassLb} lb. It remains source evidence; the existing body-composition record stores weight, body-fat %, and lean mass.</p>}</section>
  <section className="rounded-3xl border border-divider bg-white p-5"><p className="text-xs font-semibold uppercase tracking-wider text-sky">3 · Coaching context</p><h2 className="mt-1 text-xl font-semibold">Tell Coach OS what this plan is for</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><Field label="Goal"><select className={fieldClass} value={goal} onChange={e=>{setGoal(e.target.value as NutritionGoal);setDraft(null);}}><option value="fat_loss">Fat loss</option><option value="recomposition">Recomposition</option><option value="maintenance">Maintain</option><option value="performance">Performance support</option><option value="lean_gain">Lean-mass gain</option></select></Field><Field label="Daily activity estimate"><select className={fieldClass} value={activity} onChange={e=>{setActivity(Number(e.target.value));setDraft(null);}}><option value={1.2}>Low · 1.20</option><option value={1.35}>Light · 1.35</option><option value={1.5}>Moderate · 1.50</option><option value={1.7}>High · 1.70</option><option value={1.9}>Very high · 1.90</option></select></Field><Field label="Training days / week"><select className={fieldClass} value={days??""} onChange={e=>{setDays(e.target.value?Number(e.target.value):null);setDraft(null);}}><option value="">Not confirmed</option>{[1,2,3,4,5].map(n=><option key={n} value={n}>{n}</option>)}</select></Field><Field label="Food style"><select className={fieldClass} value={style} onChange={e=>{setStyle(e.target.value as DietStyle);setDraft(null);}}><option value="flexible">Flexible</option><option value="omnivore">Omnivore</option><option value="vegetarian">Vegetarian</option><option value="vegan">Vegan</option></select></Field><Field label="Meals / day"><select className={fieldClass} value={meals} onChange={e=>{setMeals(Number(e.target.value) as 3|4|5);setDraft(null);}}><option value={3}>3</option><option value={4}>4</option><option value={5}>5</option></select></Field><Field label="Allergies / dietary restrictions"><textarea className={fieldClass} rows={2} maxLength={1000} value={allergies} onChange={e=>{setAllergies(e.target.value);setDraft(null);}} placeholder="Leave blank only if not reported"/></Field><Field label="Preferences, schedule, foods they actually like"><textarea className={fieldClass} rows={3} maxLength={1500} value={preferences} onChange={e=>{setPreferences(e.target.value);setDraft(null);}}/></Field></div>
   <label className="mt-4 flex items-start gap-3 text-sm leading-6"><input className="mt-1 h-5 w-5" type="checkbox" checked={clinical} onChange={e=>{setClinical(e.target.checked);setDraft(null);}}/>This client needs individualized medical nutrition therapy / clinical nutrition review. Keep this plan habit-led and do not calculate numeric targets.</label>
   {math?.estimate&&<div className="mt-4 rounded-2xl bg-sky/5 p-4"><p className="font-semibold">Starting estimate for coach review</p><p className="mt-2 text-2xl font-bold">{math.estimate.averageKcal} kcal</p><p className="mt-1 text-sm">{math.estimate.proteinG} g protein · {math.estimate.carbsG} g carbs · {math.estimate.fatG} g fat</p><p className="mt-3 text-xs leading-5 text-cream-dim">Estimated RMR {math.estimate.rmrKcal} kcal; estimated maintenance {math.estimate.tdeeKcal} kcal. {math.estimate.formula}. These are estimates, not a Bod Pod-measured metabolism or guaranteed rate of change.</p></div>}
   <label className="mt-4 flex items-start gap-3 text-sm leading-6"><input className="mt-1 h-5 w-5" type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I checked the original Bod Pod report, confirmed the person/date/results, and reviewed the goal, activity estimate and nutrition context. This creates private coaching work only.</label>
   {!measurementReady&&<p className="mt-3 text-sm text-status-moderate">A real test date, weight and fat-free/lean mass are required for the automated estimate. Missing values stay missing.</p>}
   <button className={primaryClass+" mt-3"} type="button" disabled={!confirmed||!measurementReady||busy||!sourceId} onClick={()=>void confirmAndCreate()}>{busy?"Confirming source…":"Confirm Bod Pod + create private nutrition draft"}</button>{error&&<p role="alert" className="mt-3 text-sm text-status-limited">{error}</p>}{savedMeasurement&&<p role="status" className="mt-3 text-sm text-sky">Bod Pod measurement saved with the private source reference. The nutrition result below is still a private draft.</p>}
  </section>
  {draft&&<section className="space-y-4 rounded-3xl border border-divider bg-white p-5"><p className="text-xs font-semibold uppercase tracking-wider text-sky">4 · Review</p><h2 className="text-xl font-semibold">Private nutrition draft</h2><FuelPlanView plan={draft.content} today={today}/><FuelPlanEditor clientId={clientId} latest={latest} release={release} today={today} initialDraft={{content:draft.content,origin:"source_transcription",sourceReference:draft.sourceReference}} allowRelease={false}/></section>}
 </div>;
}
