"use client";
import {useState} from "react";
import {Field,NumberField,MutationStatus,useFuelMutation,fieldClass,primaryClass,secondaryClass} from "./controls";
import type {FuelPlan,PlanVersion} from "@/lib/fuel/model";
export function FuelCheckinResponse({clientId,entryId}:{clientId:string;entryId:string}){const [note,setNote]=useState(""),[disposition,setDisposition]=useState("reviewed"),[confirmed,setConfirmed]=useState(false),mutation=useFuelMutation(clientId);return <form className="mt-4 space-y-3" onSubmit={e=>{e.preventDefault();void mutation.submit({action:"review_checkin",request_id:crypto.randomUUID(),entry_id:entryId,note,disposition,confirmed});}}><fieldset disabled={mutation.disabled} className="space-y-3"><legend className="sr-only">Respond to check-in</legend><Field label="Client-visible coach response"><textarea className={fieldClass} rows={3} minLength={10} maxLength={2000} required value={note} onChange={e=>setNote(e.target.value)}/></Field><Field label="Review outcome"><select className={fieldClass} value={disposition} onChange={e=>setDisposition(e.target.value)}><option value="reviewed">Reviewed · no automatic plan change</option><option value="contact">Follow-up contact needed</option><option value="referral">Discuss appropriate professional referral</option></select></Field><label className="flex min-h-12 items-center gap-2 text-sm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I reviewed this exact check-in.</label><button disabled={!confirmed} className={primaryClass} type="submit">Save coach response</button></fieldset><MutationStatus mutation={mutation}/></form>;}
export function FuelAdjustmentCandidate({clientId,entryId,current}:{clientId:string;entryId:string;current:PlanVersion|null}){
 const mutation=useFuelMutation(clientId),[open,setOpen]=useState(false),[note,setNote]=useState("");
 if(!current)return null;
 const source=\`checkin:\${entryId}\${note.trim()?\` · \${note.trim()}\`:""}\`;
 const candidate:FuelPlan=current.content;
 return <div className="mt-3 rounded-xl border border-divider bg-surface-soft p-3"><p className="text-sm font-semibold">Plan adjustment</p><p className="mt-1 text-xs leading-5 text-cream-dim">Create a private copy of the current released plan only when this check-in warrants an adjustment. Nothing changes for the client until you edit, review and explicitly publish the new version.</p>{!open?<button type="button" className={secondaryClass} onClick={()=>setOpen(true)}>Create private adjustment candidate</button>:<form className="mt-3 space-y-3" onSubmit={e=>{e.preventDefault();void mutation.submit({action:"save_plan",request_id:crypto.randomUUID(),expected_revision:current.revision,content:candidate,origin:"coach_authored",source_reference:source});}}><Field label="Private adjustment rationale · optional"><textarea className={fieldClass} rows={2} maxLength={400} value={note} onChange={e=>setNote(e.target.value)} placeholder="What evidence should the next version address?"/></Field><p className="text-xs text-cream-faint">This creates v{current.revision+1} as a private version with the same prescription. Use the normal plan editor to modify it. No automatic calorie or macro change is made.</p><div className="flex flex-wrap gap-2"><button className={primaryClass} disabled={mutation.disabled} type="submit">Create private v{current.revision+1}</button><button className={secondaryClass} type="button" onClick={()=>setOpen(false)}>Dismiss candidate</button></div><MutationStatus mutation={mutation}/></form>}</div>;
}
export function FuelBodyCompForm({clientId,today}:{clientId:string;today:string}){
 const [date,setDate]=useState(today),[weight,setWeight]=useState<number|null>(null),[fat,setFat]=useState<number|null>(null),[lean,setLean]=useState<number|null>(null),[method,setMethod]=useState("bod_pod"),[kind,setKind]=useState("coach_measurement"),[source,setSource]=useState(""),[protocol,setProtocol]=useState(""),[confirmed,setConfirmed]=useState(false);const mutation=useFuelMutation(clientId);
 return <form className="space-y-4" onSubmit={e=>{e.preventDefault();void mutation.submit({action:"record_body_comp",request_id:crypto.randomUUID(),date,weight_lb:weight,body_fat_pct:fat,lean_mass_lb:lean,method,source_kind:kind,source_reference:source,protocol,confirmed});}}><fieldset disabled={mutation.disabled} className="space-y-4"><legend className="sr-only">Record measured body composition</legend><p className="text-sm leading-6 text-cream-dim">Record a real test in the existing client body-composition history. A PDF baseline requires a verified client, test date and source—not merely a name match. Projections cannot be entered as future measured results. Lean mass is not a direct muscle measurement.</p><div className="grid gap-3 sm:grid-cols-2"><Field label="Actual test date"><input className={fieldClass} type="date" max={today} required value={date} onChange={e=>setDate(e.target.value)}/></Field><Field label="Method"><select className={fieldClass} value={method} onChange={e=>setMethod(e.target.value)}>{["bod_pod","dexa","inbody","scale","calipers"].map(v=><option key={v} value={v}>{v.replaceAll("_"," ")}</option>)}</select></Field><NumberField label="Reported body weight · lb" value={weight} max={999} onChange={setWeight}/><NumberField label="Reported body fat · % · optional" value={fat} max={99.99} onChange={setFat}/><NumberField label="Reported lean mass · lb · optional" value={lean} max={999} onChange={setLean}/><Field label="Evidence source"><select className={fieldClass} value={kind} onChange={e=>setKind(e.target.value)}><option value="coach_measurement">Coach-recorded measurement</option><option value="source_transcription">Verified source transcription</option></select></Field></div><Field label="Source reference · required"><input className={fieldClass} minLength={3} maxLength={500} required placeholder="Device report / test record / filename and page" value={source} onChange={e=>setSource(e.target.value)}/></Field><Field label="Test conditions and protocol · optional private coach context"><textarea className={fieldClass} maxLength={2000} rows={3} placeholder="Record known time, clothing, hydration and preparation conditions. Unknown stays unknown. Sensitive information should only be recorded when relevant and consented." value={protocol} onChange={e=>setProtocol(e.target.value)}/></Field><label className="flex items-start gap-3 text-sm leading-6"><input className="mt-1 h-5 w-5 shrink-0" type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I verified the person, actual measurement date and reported numbers. This is not a forecast, fabricated assessment or guarantee of lean-mass retention.</label><button className={primaryClass} type="submit" disabled={!confirmed||weight===null}>Save measured body composition</button></fieldset><MutationStatus mutation={mutation}/></form>;
}
