"use client";
import {useState} from "react";
import {HABITS,dailyTargets,type Daily,type Checkin,type Journal,type FuelPlan,type DayType,type HabitState} from "@/lib/fuel/model";
import {Field,NumberField,MutationStatus,useFuelMutation,fieldClass,primaryClass} from "./controls";
const habitNames={protein:"Protein goal",fuel:"Fuel plan",water:"Hydration goal",steps:"Movement / steps",sleep:"Sleep goal",training:"Training · self-reported"};
export function FuelDailyForm({clientId,date,entry,versionId,plan,hasBooking}:{clientId:string;date:string;entry:Journal|null;versionId:string|null;plan:FuelPlan|null;hasBooking:boolean}){
 const [data,setData]=useState<Daily>(entry?.payload as Daily??{day_type:"unclassified",habits:{protein:null,fuel:null,water:null,steps:null,sleep:null,training:null},weight_lb:null,steps:null,sleep_hours:null,energy:null,hunger:null,note:""});
 const mutation=useFuelMutation(clientId),targets=plan?dailyTargets(plan,date,data.day_type):null;
 const change=(patch:Partial<Daily>)=>setData(old=>({...old,...patch}));
 return <form className="space-y-4" onSubmit={e=>{e.preventDefault();void mutation.submit({action:"save_daily",request_id:crypto.randomUUID(),date,expected_revision:entry?.revision??0,plan_version_id:versionId,payload:data});}}><fieldset disabled={mutation.disabled} className="space-y-4"><legend className="sr-only">Daily fuel check-in</legend>
 <p className="text-sm leading-6 text-cream-dim">{date} · {hasBooking?"A training session is on your calendar. Confirm today's actual context below.":"No calendar booking does not mean a rest day. Include independent training when choosing."}</p>
 <Field label="Today is…"><select className={fieldClass} value={data.day_type} onChange={e=>change({day_type:e.target.value as DayType})}><option value="unclassified">Not specified · no automatic target</option><option value="training">Training day</option><option value="rest">Rest day</option></select></Field>
 {targets&&<div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{[["Energy",targets.kcal,"kcal"],["Protein",targets.protein_g,"g"],["Carbs",targets.carbs_g,"g"],["Fat",targets.fat_g,"g"]].map(([name,value,unit])=><div key={String(name)} className="rounded-xl bg-sky/5 p-3"><p className="text-xs text-cream-faint">{name}</p><p className="mt-1 font-semibold">{value===null?"Not assigned":`${value} ${unit}`}</p></div>)}</div>}
 {!targets&&<p className="rounded-xl bg-surface-soft p-3 text-sm text-cream-dim">No numeric target selected. Habit-only coaching and missing day context never invent calories.</p>}
 <div className="grid gap-3 sm:grid-cols-2">{HABITS.filter(h=>plan?.habits.includes(h)).map(h=><Field key={h} label={habitNames[h]}><select className={fieldClass} value={data.habits[h]??""} onChange={e=>change({habits:{...data.habits,[h]:(e.target.value||null) as HabitState}})}><option value="">Not reported</option><option value="met">Met</option><option value="missed">Not met</option><option value="not_due">Not due / not applicable</option></select></Field>)}</div>
 <p className="text-xs leading-5 text-cream-faint">Blank is not failure. Training here is your report, not a completed appointment or package debit. Weight and recovery fields are optional; skip tracking that does not serve your coaching goals.</p>
 <details className="rounded-xl border border-divider p-3"><summary className="min-h-11 cursor-pointer text-sm font-semibold">Optional measurements & recovery</summary><div className="mt-3 grid grid-cols-2 gap-3"><NumberField label="Morning weight · lb" value={data.weight_lb} max={999} onChange={weight_lb=>change({weight_lb})}/><NumberField label="Steps" value={data.steps} max={200000} onChange={steps=>change({steps})}/><NumberField label="Sleep · hours" value={data.sleep_hours} max={24} onChange={sleep_hours=>change({sleep_hours})}/><NumberField label="Energy · 1 low to 5 high" value={data.energy} max={5} onChange={energy=>change({energy})}/><NumberField label="Hunger · 1 low to 5 high" value={data.hunger} max={5} onChange={hunger=>change({hunger})}/></div></details>
 <Field label="Anything your coach should know? · optional"><textarea className={fieldClass} maxLength={2000} rows={2} value={data.note} onChange={e=>change({note:e.target.value})}/></Field><button type="submit" className={primaryClass}>{mutation.busy?"Saving…":entry?"Save corrected daily entry":"Save daily check-in"}</button></fieldset><MutationStatus mutation={mutation}/></form>;
}
export function FuelWeeklyForm({clientId,date,entry,versionId}:{clientId:string;date:string;entry:Journal|null;versionId:string|null}){
 const [data,setData]=useState<Checkin>(entry?.payload as Checkin??{hardest_moment:"",barriers:"",training:"not_reported",symptoms:"",upcoming:"",next_step:"",contact_requested:false,energy:null,hunger:null,sleep:null});
 const mutation=useFuelMutation(clientId),change=(patch:Partial<Checkin>)=>setData(old=>({...old,...patch}));
 return <form className="space-y-4" onSubmit={e=>{e.preventDefault();void mutation.submit({action:"save_checkin",request_id:crypto.randomUUID(),date,expected_revision:entry?.revision??0,plan_version_id:versionId,payload:data});}}><fieldset disabled={mutation.disabled} className="space-y-4"><legend className="sr-only">Weekly coach check-in</legend><p className="text-sm text-cream-dim">Review the past seven days, as of {date}. Corrections preserve the previous report and reopen coach review.</p>
 {([["hardest_moment","What was the hardest meal or moment this week?"],["barriers","Where did the plan break down, and what would have helped?"],["symptoms","Any digestion issues, headaches, dizziness, or other concerns? · optional"],["upcoming","What is coming up next week? Travel, events or schedule changes?"],["next_step","One thing to do better next week"]] as const).map(([key,label])=><Field key={key} label={label}><textarea className={fieldClass} maxLength={2000} rows={2} value={data[key]} onChange={e=>change({[key]:e.target.value})}/></Field>)}
 <Field label="How did training feel?"><select className={fieldClass} value={data.training} onChange={e=>change({training:e.target.value as Checkin["training"]})}><option value="not_reported">Not reported</option><option value="stronger">Stronger</option><option value="same">Same</option><option value="flat">Flat</option></select></Field><div className="grid grid-cols-3 gap-3"><NumberField label="Energy · 1–5" value={data.energy} max={5} onChange={energy=>change({energy})}/><NumberField label="Hunger · 1–5" value={data.hunger} max={5} onChange={hunger=>change({hunger})}/><NumberField label="Sleep quality · 1–5" value={data.sleep} max={5} onChange={sleep=>change({sleep})}/></div><p className="text-xs text-cream-faint">Energy/sleep: 1 low, 5 high. Hunger: 1 low, 5 high. Leave blank when not reported.</p>
 <label className="flex min-h-12 items-center gap-3 text-sm"><input type="checkbox" className="h-5 w-5" checked={data.contact_requested} onChange={e=>change({contact_requested:e.target.checked})}/>I would like my coach to follow up.</label><p className="rounded-xl bg-surface-soft p-3 text-xs leading-5 text-cream-dim">This is a coaching check-in, not medical diagnosis or continuously monitored care. For urgent symptoms seek appropriate medical care rather than waiting for a reply. No calories change automatically.</p><button type="submit" className={primaryClass}>{mutation.busy?"Saving…":"Send to coach review queue"}</button></fieldset><MutationStatus mutation={mutation}/></form>;
}
