"use client";
import Link from 'next/link';
import {useRef,useState} from 'react';
import {Field,NumberField,fieldClass,primaryClass,secondaryClass} from './controls';
import {FuelPlanView} from './plan-view';
import {useNutritionSave} from './use-nutrition-save';
import {validSourceReceipt} from '@/lib/fuel/source';
import {REPORT_LIMIT,reportExtractionSchema,mergeReportCandidates,measurementWarnings,measureSchema,type ReportExtraction,type NutritionMeasurement} from '@/lib/fuel/report';
import {nutritionIntakeSchema,type NutritionIntake,type NutritionNumbers} from '@/lib/fuel/nutrition';
import {fuelPlanSchema} from '@/lib/fuel/validation';
import type {FuelPlan} from '@/lib/fuel/model';
type Original={id:string;original_name:string;sha256:string;byte_size:number;content_type:string};
type Proposal={content:FuelPlan;calculation:NutritionNumbers;menuWarning:string|null};
const panel='min-w-0 space-y-4 rounded-3xl border border-divider bg-white p-5';
const checks=[['pregnancy_or_breastfeeding','Pregnant or breastfeeding?'],['eating_disorder_or_restrictive_history','Eating-disorder history, restrictive eating concerns or low energy availability?'],['medical_nutrition_or_medication','Medical nutrition needs or medications affecting glucose, appetite, fluid balance or protein needs?'],['unexplained_symptoms_or_weight_change','Unexplained weight changes, dizziness, persistent fatigue or concerning symptoms?'],['high_training_demand','High-volume endurance, competition cutting or other demands outside routine general-population training?']] as const;
export function NutritionBuilder({clientId,name,today,revision,hasPrivateDraft,originals,readerReady,foodsReady}:{clientId:string;name:string;today:string;revision:number;hasPrivateDraft:boolean;originals:Original[];readerReady:boolean;foodsReady:boolean}){
 const [rows,setRows]=useState(originals),[selected,setSelected]=useState<string[]>([]),[file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false),[uploadUncertain,setUploadUncertain]=useState(false),[error,setError]=useState<string|null>(null),[readerConsent,setReaderConsent]=useState(false),[reads,setReads]=useState<Record<string,ReportExtraction>>({});
 const lock=useRef(false),pendingUpload=useRef<{id:string;file:File;hash:string}|null>(null);
 const [m,setM]=useState({date:'',weight_lb:null as number|null,body_fat_pct:null as number|null,lean_pct:null as number|null,fat_mass_lb:null as number|null,lean_mass_lb:null as number|null,model_label:''});
 const [age,setAge]=useState<number|null>(null),[height,setHeight]=useState<number|null>(null),[coefficient,setCoefficient]=useState(''),[activity,setActivity]=useState(''),[trainingDays,setTrainingDays]=useState<number|null>(null),[goal,setGoal]=useState('maintenance'),[diet,setDiet]=useState('mixed'),[meals,setMeals]=useState('3'),[budget,setBudget]=useState('standard'),[prep,setPrep]=useState('quick'),[avoid,setAvoid]=useState<string[]>([]),[other,setOther]=useState(''),[preferences,setPreferences]=useState(''),[screen,setScreen]=useState<Record<string,string>>(Object.fromEntries(checks.map(([k])=>[k,'unknown']))),[foodReviewed,setFoodReviewed]=useState(false),[personConfirmed,setPersonConfirmed]=useState(false),[valuesConfirmed,setValuesConfirmed]=useState(false),[reviewed,setReviewed]=useState(false),[newVersion,setNewVersion]=useState(false),[proposal,setProposal]=useState<Proposal|null>(null),[snapshot,setSnapshot]=useState<{measurement:NutritionMeasurement;intake:NutritionIntake;sources:{id:string;sha256:string}[]}|null>(null);
 const save=useNutritionSave(clientId),frozen=busy||uploadUncertain||save.locked||proposal!==null;
 const sourceRows=rows.filter(r=>selected.includes(r.id)),merged=mergeReportCandidates(selected.flatMap(id=>reads[id]?[reads[id]]:[]));
 const parsedMeasurement=measureSchema.safeParse(m),warnings=parsedMeasurement.success?measurementWarnings(parsedMeasurement.data):[];
 function changeSources(ids:string[]){if(ids.length>3){setError('Use up to three originals from the same test.');return;}setSelected(ids);setReaderConsent(false);setPersonConfirmed(false);setValuesConfirmed(false);}
 async function upload(){if(lock.current||(!file&&!pendingUpload.current))return;lock.current=true;setBusy(true);setError(null);
  try{if(!pendingUpload.current){if(!file||file.size>REPORT_LIMIT)throw Error('Choose a PDF/JPEG/PNG of 3 MB or less.');const hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',await file.arrayBuffer()))].map(v=>v.toString(16).padStart(2,'0')).join('');pendingUpload.current={id:crypto.randomUUID(),file,hash};}
   const p=pendingUpload.current,response=await fetch(`/api/fuel/${clientId}/reports`,{method:'POST',headers:{'Content-Type':p.file.type,'x-source-id':p.id,'x-source-name':encodeURIComponent(p.file.name)},body:p.file}),result=await response.json().catch(()=>null);
   if(!response.ok||!validSourceReceipt(result,p.id,clientId,p.hash,p.file.size)){if(response.status>=500||response.ok||uploadUncertain)setUploadUncertain(true);else pendingUpload.current=null;setError(result?.error??'Original receipt unconfirmed.');return;}
   const row={id:p.id,original_name:p.file.name,sha256:p.hash,byte_size:p.file.size,content_type:p.file.type};setRows(v=>[row,...v.filter(r=>r.id!==row.id)]);if(selected.length<3)changeSources([...selected.filter(id=>id!==row.id),row.id]);setFile(null);pendingUpload.current=null;setUploadUncertain(false);
  }catch(cause){if(pendingUpload.current)setUploadUncertain(true);setError(cause instanceof Error?cause.message:'Upload interrupted.');}finally{lock.current=false;setBusy(false);}
 }
 async function readSource(id:string){if(lock.current||!readerConsent)return;lock.current=true;setBusy(true);setError(null);
  try{const requestId=crypto.randomUUID(),response=await fetch(`/api/fuel/${clientId}/reports/extract`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({source_id:id,request_id:requestId,external_processing_consent:true})}),r=await response.json();const original=rows.find(s=>s.id===id);if(!response.ok)throw Error(r.error??'Reading failed.');if(r.client_id!==clientId||r.source_id!==id||r.request_id!==requestId||r.source_hash!==original?.sha256||r.reviewed!==false)throw Error('Extraction identity mismatch.');const parsed=reportExtractionSchema.parse(r.extracted);setReads(v=>({...v,[id]:parsed}));setValuesConfirmed(false);
  }catch(cause){setError(cause instanceof Error?cause.message:'Reading did not complete. Enter values manually.');}finally{lock.current=false;setBusy(false);}
 }
 function applyRead(){const c=merged.candidates;setM(v=>({...v,date:merged.date??v.date,weight_lb:c.weight??null,body_fat_pct:c.fat_pct??null,lean_pct:c.lean_pct??null,fat_mass_lb:c.fat_mass??null,lean_mass_lb:c.lean_mass??null,model_label:[...new Set(selected.flatMap(id=>reads[id]?.model_label?[reads[id].model_label!]:[]))].join(' / ').slice(0,100)}));setValuesConfirmed(false);}
 async function propose(){if(lock.current||!personConfirmed||!valuesConfirmed)return;setError(null);
  try{const measurement=measureSchema.parse(m),intake=nutritionIntakeSchema.parse({age,height_cm:height===null?null:Math.round(height*2.54*100)/100,equation_coefficient:coefficient,activity,goal,training_days:trainingDays,diet,meals_per_day:meals,budget,prep,avoid,other_food_restrictions:other,preferences,screen,food_reviewed:foodReviewed});
   const sources=sourceRows.map(r=>({id:r.id,sha256:r.sha256}));if(!sources.length)throw Error('Save and select the source original first.');lock.current=true;setBusy(true);
   const response=await fetch(`/api/fuel/${clientId}/nutrition`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'propose',measurement,intake,sources,same_person_test_confirmed:true,reported_values_confirmed:true})}),r=await response.json();if(!response.ok)throw Error(r.error??'Draft could not be generated.');if(r.client_id!==clientId||r.persisted!==false||!r.calculation)throw Error('Proposal identity was not confirmed.');const content=fuelPlanSchema.parse(r.content);setSnapshot({measurement,intake,sources});setProposal({content,calculation:r.calculation,menuWarning:r.menuWarning??null});setReviewed(false);
  }catch(cause){setError(cause instanceof Error&& !cause.message.startsWith('[')?cause.message:'Complete the required measurements, age, height, activity, equation coefficient and screening. Unknown answers do not generate numeric targets.');}finally{lock.current=false;setBusy(false);}
 }
 return <main className="mx-auto w-full max-w-5xl space-y-5 pb-20"><header className="rounded-3xl bg-band p-6 text-white"><p className="text-xs uppercase tracking-widest text-white/70">IMS / Report → Nutrition</p><h1 className="mt-3 break-words text-3xl font-bold">Build nutrition for {name}</h1><p className="mt-3 text-sm leading-6 text-white/80">Upload a Bod Pod photo or PDF, confirm the results and add a short intake. Generate a private proposal—not a client release.</p><Link className="mt-3 inline-flex min-h-11 items-center font-semibold text-white" href={`/clients/${clientId}/fuel`}>← Fuel &amp; Performance</Link></header>
 {(!readerReady||!foodsReady)&&<aside className={panel}><h2 className="font-semibold">Connection status</h2><p className="text-sm">Report reading: {readerReady?'configured; verify extracted fields':'not enabled — manual result entry available'}. USDA menu nutrition: {foodsReady?'configured; exact entries checked per request':'not configured — numeric targets work, calculated food menu unavailable'}.</p><p className="text-xs text-cream-dim">A configured connection is not a successful live acceptance test. No API failure will be replaced with invented measurements or food values.</p></aside>}
 <section className={panel}><h2 className="text-xl font-semibold">1 · Original results</h2><p className="text-sm leading-6 text-cream-dim">Select up to three originals from the same person and test. For the machine, one photo can show percentages and another show pounds. The IMS blank form is a template, not measured data. Reference classifications and checked goal boxes are never imported as results.</p>
 <fieldset disabled={frozen} className="space-y-3"><legend className="sr-only">Report originals</legend><Field label="Add PDF, JPEG or PNG · maximum 3 MB each"><input className={fieldClass} type="file" accept="application/pdf,image/jpeg,image/png" onChange={e=>{setFile(e.target.files?.[0]??null);setError(null);}}/></Field><button type="button" className={primaryClass} disabled={!file||selected.length>=3} onClick={()=>void upload()}>Save private original</button><p className="text-xs text-cream-dim">HEIC must be exported as JPEG. Original bytes are private to authorized coaches and preserved with a checksum. No test or nutrition strategy is saved by uploading.</p>
 {rows.map(row=><div className="rounded-xl border border-divider p-3" key={row.id}><label className="flex min-h-11 items-center gap-3 text-sm"><input type="checkbox" checked={selected.includes(row.id)} onChange={e=>changeSources(e.target.checked?[...selected,row.id]:selected.filter(id=>id!==row.id))}/><span className="break-all">{row.original_name}</span></label><a className="inline-flex min-h-11 items-center text-sm font-semibold text-sky" href={`/api/fuel/${clientId}/reports?id=${row.id}`} target="_blank" rel="noreferrer">View / download original →</a></div>)}
 {readerReady&&sourceRows.length>0&&<><label className="flex items-start gap-3 text-sm leading-6"><input className="mt-1 h-5 w-5 shrink-0" type="checkbox" checked={readerConsent} onChange={e=>setReaderConsent(e.target.checked)}/>I have permission to send these selected reports to OpenAI for assisted transcription. The files may contain health information; provider retention rules apply. This is optional—manual entry sends no report to an AI provider.</label><div className="flex flex-wrap gap-2">{sourceRows.map(row=><button key={row.id} type="button" className={secondaryClass} disabled={!readerConsent} onClick={()=>void readSource(row.id)}>{reads[row.id]?'Read again (new attempt)':'Read report'} · {row.original_name.slice(0,32)}</button>)}</div></>}
 {Object.keys(reads).some(id=>selected.includes(id))&&<div className="space-y-3 rounded-xl bg-surface-soft p-4"><h3 className="font-semibold">Unconfirmed extraction candidates</h3>{selected.filter(id=>reads[id]).map(id=><article key={id}><p className="text-sm font-semibold">{rows.find(r=>r.id===id)?.original_name} · {reads[id].document_kind.replaceAll('_',' ')}</p><p className="text-xs text-cream-dim">Name: {reads[id].person_name??'not shown'} · Date: {reads[id].test_date??'not shown'}</p>{reads[id].observations.map((o,index)=><p key={index} className="mt-1 break-words text-sm">{o.field}: {o.value} {o.unit} — “{o.quote}” ({o.location})</p>)}{reads[id].warnings.map((w,index)=><p key={index} className="mt-1 text-sm text-status-moderate">{w}</p>)}</article>)}{(merged.conflicts.length>0||merged.dateConflict)&&<p role="alert" className="text-sm text-status-limited">Conflicting fields: {merged.conflicts.join(', ')}{merged.dateConflict?' test date':''}. Conflicts stay blank for manual review.</p>}<button type="button" className={secondaryClass} onClick={applyRead}>Copy candidates to review fields</button></div>}
 </fieldset>{uploadUncertain&&<button type="button" className={secondaryClass} disabled={busy} onClick={()=>void upload()}>Retry identical original upload</button>}</section>
 <section className={panel}><h2 className="text-xl font-semibold">2 · Confirm the actual test</h2><fieldset disabled={frozen} className="space-y-3"><legend className="sr-only">Verified Bod Pod values</legend><div className="grid gap-3 sm:grid-cols-2"><Field label="Actual test date · required, never inferred"><input className={fieldClass} type="date" max={today} value={m.date} onChange={e=>{setM(v=>({...v,date:e.target.value}));setValuesConfirmed(false);}}/></Field>{([['weight_lb','Total body weight · lb'],['body_fat_pct','Fat · %'],['lean_pct','Lean · %'],['fat_mass_lb','Fat mass · lb'],['lean_mass_lb','Lean / fat-free mass · lb']] as const).map(([key,label])=><NumberField key={key} label={label} value={m[key]} max={key.endsWith('pct')?100:999} onChange={value=>{setM(v=>({...v,[key]:value}));setValuesConfirmed(false);}}/>)}<Field label="Printed model · optional, e.g. Lohman"><input className={fieldClass} maxLength={100} value={m.model_label} onChange={e=>setM(v=>({...v,model_label:e.target.value}))}/></Field></div><p className="text-xs leading-5 text-cream-dim">Blank means not shown. Do not recalculate and overwrite the report. Lean mass is not skeletal-muscle mass. The saved source snapshot keeps reported fat mass, lean percentage and model even though the standard chart uses weight, fat percentage and lean mass.</p>{warnings.map(w=><p role="alert" key={w} className="text-sm text-status-moderate">{w}</p>)}<label className="flex min-h-12 items-start gap-3 text-sm leading-6"><input className="mt-1 h-5 w-5" type="checkbox" checked={personConfirmed} onChange={e=>setPersonConfirmed(e.target.checked)}/>These originals belong to {name} and describe the same test. A name match alone is not sufficient.</label><label className="flex min-h-12 items-start gap-3 text-sm leading-6"><input className="mt-1 h-5 w-5" type="checkbox" checked={valuesConfirmed} onChange={e=>setValuesConfirmed(e.target.checked)}/>I checked the actual date, units and numbers against the original, including any extraction corrections.</label></fieldset></section>
 <section className={panel}><h2 className="text-xl font-semibold">3 · Short nutrition intake</h2><fieldset disabled={frozen} className="space-y-4"><legend className="sr-only">Nutrition context</legend><div className="grid gap-3 sm:grid-cols-2"><NumberField label="Age · years" value={age} max={78} onChange={setAge}/><NumberField label="Height · total inches" value={height} max={91} onChange={setHeight}/><Field label="Mifflin equation coefficient · explicit choice"><select className={fieldClass} value={coefficient} onChange={e=>setCoefficient(e.target.value)}><option value="">Choose after review</option><option value="female">Female equation coefficient (−161)</option><option value="male">Male equation coefficient (+5)</option></select></Field><Field label="Usual total activity · include work and outside exercise"><select className={fieldClass} value={activity} onChange={e=>setActivity(e.target.value)}><option value="">Confirm activity</option><option value="low">Low activity · mostly seated (1.30)</option><option value="moderate">Moderate regular activity (1.45)</option><option value="active">Active daily routine (1.60)</option></select></Field><Field label="Goal"><select className={fieldClass} value={goal} onChange={e=>setGoal(e.target.value)}><option value="maintenance">Maintain / support recomposition</option><option value="fat_loss">Conservative fat loss</option><option value="gain">Gradual gain</option><option value="performance">Performance support</option></select></Field><NumberField label="Confirmed training days / week · include outside training" value={trainingDays} max={7} onChange={setTrainingDays}/></div><p className="text-xs leading-5 text-cream-dim">These equation categories are calculation inputs, not an inference of gender or a universal fit. Use individualized professional review when the equation is inappropriate. Activity factors are coaching assumptions, not measured expenditure.</p>
 <details open><summary className="min-h-12 cursor-pointer font-semibold">Required screening · not a diagnosis</summary><div className="mt-3 grid gap-3 sm:grid-cols-2">{checks.map(([key,label])=><Field key={key} label={label}><select className={fieldClass} value={screen[key]} onChange={e=>setScreen(v=>({...v,[key]:e.target.value}))}><option value="unknown">Not yet established</option><option value="no">No, confirmed with client</option><option value="yes">Yes / needs individualized review</option></select></Field>)}</div><p className="mt-3 text-xs text-cream-dim">A yes or unknown pauses automated targets. The habit-led editor remains available; a general fitness draft does not replace medical nutrition care.</p></details>
 <div className="grid gap-3 sm:grid-cols-2"><Field label="Food pattern"><select className={fieldClass} value={diet} onChange={e=>setDiet(e.target.value)}><option value="mixed">Mixed diet</option><option value="plant">Plant-based</option></select></Field><Field label="Meals per day"><select className={fieldClass} value={meals} onChange={e=>setMeals(e.target.value)}><option value="3">3 meals</option><option value="4">3 meals + snack</option></select></Field><Field label="Budget"><select className={fieldClass} value={budget} onChange={e=>setBudget(e.target.value)}><option value="standard">Standard</option><option value="economy">Economy / reuse ingredients</option></select></Field><Field label="Prep preference"><select className={fieldClass} value={prep} onChange={e=>setPrep(e.target.value)}><option value="quick">Quick assembly</option><option value="batch">Batch prep</option></select></Field></div><fieldset><legend className="text-sm font-semibold">Avoid due to allergy, intolerance or preference</legend><div className="mt-2 flex flex-wrap gap-2">{['milk','soy','oats','banana','chicken','rice','broccoli','oil'].map(key=><label className="flex min-h-12 items-center gap-2 rounded-xl border border-divider px-3 text-sm" key={key}><input type="checkbox" checked={avoid.includes(key)} onChange={e=>setAvoid(v=>e.target.checked?[...v,key]:v.filter(k=>k!==key))}/>{key}</label>)}</div></fieldset><Field label="Other allergies / restrictions · enter any not above"><textarea className={fieldClass} rows={2} maxLength={500} value={other} onChange={e=>setOther(e.target.value)}/></Field><Field label="Preferences / schedule notes · carried into coach review"><textarea className={fieldClass} rows={2} maxLength={800} value={preferences} onChange={e=>setPreferences(e.target.value)}/></Field><label className="flex min-h-12 items-start gap-3 text-sm leading-6"><input className="mt-1 h-5 w-5" type="checkbox" checked={foodReviewed} onChange={e=>setFoodReviewed(e.target.checked)}/>I reviewed food allergies, restrictions and preferences. The initial food library is limited; incompatible restrictions withhold the menu rather than guess a safe substitute.</label>
 {hasPrivateDraft&&<div className="rounded-xl bg-surface-soft p-4"><p className="text-sm">A private Fuel draft already exists. <Link className="font-semibold text-sky underline" href={`/clients/${clientId}/fuel#fuel-plan`}>Continue that draft</Link> or explicitly create a new version.</p><label className="mt-3 flex min-h-12 items-center gap-3 text-sm"><input type="checkbox" checked={newVersion} onChange={e=>setNewVersion(e.target.checked)}/>Create a new private version; do not release or delete the existing one.</label></div>}
 <button type="button" className={primaryClass} disabled={!personConfirmed||!valuesConfirmed||!foodReviewed||!selected.length||hasPrivateDraft&&!newVersion} onClick={()=>void propose()}>Create nutrition draft</button></fieldset></section>
 {busy&&<p role="status" className="rounded-xl bg-sky/5 p-4 text-sm">Working on this request… No strategy has been released.</p>}{error&&<p role="alert" className="rounded-xl border border-status-limited/40 bg-white p-4 text-sm text-status-limited">{error}</p>}
 {proposal&&snapshot&&<section className={panel}><h2 className="text-xl font-semibold">4 · Review proposal · not saved</h2><div className="grid gap-3 sm:grid-cols-3">{[['Estimated resting energy',proposal.calculation.rmr],['Estimated maintenance',proposal.calculation.maintenance],['Proposed daily intake',proposal.calculation.proposed.kcal]].map(([label,value])=><div className="rounded-xl bg-sky/5 p-4" key={label}><p className="text-xs text-cream-dim">{label}</p><p className="mt-2 text-xl font-semibold">{value} kcal</p></div>)}</div>{proposal.menuWarning&&<p role="alert" className="rounded-xl border border-status-moderate/30 p-3 text-sm">Meal plan incomplete: {proposal.menuWarning}</p>}<FuelPlanView plan={proposal.content} today={today}/><fieldset disabled={save.locked} className="space-y-3"><legend className="sr-only">Save private draft</legend><label className="flex min-h-12 items-start gap-3 text-sm leading-6"><input className="mt-1 h-5 w-5" type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>I reviewed the assumptions, proposed targets and any incomplete-menu warning. Save the confirmed Bod Pod baseline and this private strategy together. This is not a client release.</label><div className="flex flex-wrap gap-2"><button type="button" className={primaryClass} disabled={!reviewed} onClick={()=>void save.save({action:'save',...snapshot,content:proposal.content,expected_revision:revision,request_id:crypto.randomUUID(),measurement_request_id:crypto.randomUUID(),strategy_reviewed:true,same_person_test_confirmed:true,reported_values_confirmed:true})}>Save private strategy + baseline</button><button type="button" className={secondaryClass} onClick={()=>{setProposal(null);setSnapshot(null);setReviewed(false);}}>Back to inputs</button></div></fieldset></section>}
 {save.error&&<p role="alert" className="rounded-xl border border-status-limited/30 p-4 text-sm">{save.error}</p>}{save.uncertain&&<button className={secondaryClass} type="button" disabled={save.busy} onClick={()=>void save.retry()}>Retry exact baseline + strategy save</button>}{save.version&&<section role="status" className={panel}><h2 className="text-xl font-semibold">Saved privately—nothing released</h2><p className="text-sm">Baseline and strategy receipts confirmed. Open the saved strategy to make edits and review the exact version before client release.</p><Link className={primaryClass} href={`/clients/${clientId}/fuel#fuel-plan`}>Review saved strategy →</Link><Link className={secondaryClass} href={`/fuel/print?client_id=${clientId}&version=${save.version}`}>Preview / Print PDF →</Link></section>}
 </main>;
}
