"use client";
import {useState} from "react";
import {blankPlan,emptyTargets,planWarnings,type FuelPlan,type PlanVersion,type Release,type Phase} from "@/lib/fuel/model";
import {fuelPlanSchema} from "@/lib/fuel/validation";
import {Field,TargetFields,MutationStatus,useFuelMutation,fieldClass,primaryClass,secondaryClass} from "./controls";
export function FuelPlanEditor({clientId,latest,release,today}:{clientId:string;latest:PlanVersion|null;release:Release|null;today:string}){
 const [plan,setPlan]=useState<FuelPlan>(latest?.content??blankPlan(today));
 const [origin,setOrigin]=useState<PlanVersion["origin"]>(latest?.origin??"coach_authored"),[source,setSource]=useState(latest?.source_reference??"");
 const [reason,setReason]=useState(""),[confirmed,setConfirmed]=useState(false),[importError,setImportError]=useState<string|null>(null);
 const mutation=useFuelMutation(clientId),releaseMutation=useFuelMutation(clientId),warnings=planWarnings(plan);
 const locked=mutation.disabled||releaseMutation.disabled;
 const change=(patch:Partial<FuelPlan>)=>setPlan(previous=>({...previous,...patch}));
 function phase(index:number,patch:Partial<Phase>){change({phases:plan.phases.map((p,i)=>i===index?{...p,...patch}:p)});}
 async function importDraft(file:File|undefined){if(!file)return;setImportError(null);try{if(file.size>100000)throw Error("Plan JSON exceeds 100 KB.");const parsed=fuelPlanSchema.safeParse(JSON.parse(await file.text()));if(!parsed.success)throw Error("This file does not match the Fuel Plan schema. No values were imported.");if(window.confirm("Load this file into a private draft? This does not publish targets or record body measurements.")){setPlan(parsed.data);setOrigin("source_transcription");setSource(file.name);}}catch(cause){setImportError(cause instanceof Error?cause.message:"Unable to read draft.");}}
 return <div className="space-y-5"><form onSubmit={e=>{e.preventDefault();void mutation.submit({action:"save_plan",request_id:crypto.randomUUID(),expected_revision:latest?.revision??0,content:plan,origin,source_reference:source});}} className="space-y-5">
 <fieldset disabled={locked} className="space-y-5"><legend className="sr-only">Private fuel plan editor</legend>
 <div className="rounded-2xl bg-sky/5 p-4"><h3 className="font-semibold">Save a private version first</h3><p className="mt-2 text-sm leading-6 text-cream-dim">Habit-only coaching needs no calorie target, Bod Pod or assessment. Template numbers are blank. Imported and AI-proposed content requires individual review before client visibility.</p><div className="mt-3 flex flex-wrap gap-2"><button type="button" className={secondaryClass} onClick={()=>{if(window.confirm("Replace this unsaved draft with a blank habit plan?"))setPlan(blankPlan(plan.start));}}>Habit template</button><button type="button" className={secondaryClass} onClick={()=>{if(window.confirm("Use the five-phase academy structure with no copied targets?"))setPlan(blankPlan(plan.start,"academy"));}}>24-week academy structure</button></div><Field label="Import a structured draft · JSON only"><input className={fieldClass} type="file" accept=".json,application/json" onChange={e=>void importDraft(e.target.files?.[0])}/></Field><p className="mt-2 text-xs text-cream-faint">A PDF is source evidence, not this JSON format. Transcribe and review it; this uploader does not claim automatic PDF interpretation.</p>{importError&&<p role="alert" className="mt-2 text-sm text-status-limited">{importError}</p>}</div>
 <div className="grid gap-3 sm:grid-cols-2"><Field label="Plan title"><input className={fieldClass} required maxLength={120} value={plan.title} onChange={e=>change({title:e.target.value})}/></Field><Field label="Coaching mode"><select className={fieldClass} value={plan.mode} onChange={e=>change({mode:e.target.value as FuelPlan["mode"]})}><option value="habits">Habits without calorie targets</option><option value="targets">Coach-reviewed targets</option></select></Field><Field label="Start date"><input className={fieldClass} type="date" required value={plan.start} onChange={e=>change({start:e.target.value})}/></Field><Field label="End date"><input className={fieldClass} type="date" required value={plan.end} onChange={e=>change({end:e.target.value})}/></Field><Field label="Confirmed event date · optional"><input className={fieldClass} type="date" value={plan.event_date??""} onChange={e=>change({event_date:e.target.value||null})}/></Field><Field label="Next coach review / retest reminder · optional"><input className={fieldClass} type="date" value={plan.review_on??""} onChange={e=>change({review_on:e.target.value||null})}/></Field></div>
 <Field label="Goal and context"><textarea className={fieldClass} rows={3} maxLength={2000} value={plan.goal} onChange={e=>change({goal:e.target.value})}/></Field>
 <div><p className="mb-2 text-sm font-semibold">Assigned habits · tracking is optional</p><div className="flex flex-wrap gap-3">{["protein","fuel","water","steps","sleep","training"].map(h=><label key={h} className="flex min-h-12 items-center gap-2 rounded-xl border border-divider px-3 text-sm capitalize"><input type="checkbox" checked={plan.habits.includes(h)} onChange={e=>change({habits:e.target.checked?[...plan.habits,h]:plan.habits.filter(v=>v!==h)})}/>{h}</label>)}</div></div>
 <section className="space-y-4"><h3 className="text-lg font-semibold">Phase roadmap</h3>{plan.phases.map((p,i)=><details key={i} open={plan.phases.length===1} className="rounded-2xl border border-divider p-4"><summary className="min-h-11 cursor-pointer font-semibold">{i+1}. {p.name} · {p.start}–{p.end}</summary><div className="mt-3 space-y-3"><Field label="Phase name"><input className={fieldClass} value={p.name} maxLength={80} onChange={e=>phase(i,{name:e.target.value})}/></Field><div className="grid grid-cols-2 gap-3"><Field label="Phase starts"><input className={fieldClass} type="date" value={p.start} onChange={e=>phase(i,{start:e.target.value})}/></Field><Field label="Phase ends"><input className={fieldClass} type="date" value={p.end} onChange={e=>phase(i,{end:e.target.value})}/></Field></div><Field label="Phase focus"><textarea className={fieldClass} rows={2} maxLength={2000} value={p.focus} onChange={e=>phase(i,{focus:e.target.value})}/></Field>{plan.mode==="targets"&&<><p className="text-sm font-semibold text-sky">Training-day targets · optional unknown fields stay blank</p><TargetFields value={p.training} onChange={v=>phase(i,{training:v})}/><p className="text-sm font-semibold text-sky">Rest-day targets</p><TargetFields value={p.rest} onChange={v=>phase(i,{rest:v})}/></>}<button type="button" disabled={plan.phases.length===1} className={secondaryClass} onClick={()=>change({phases:plan.phases.filter((_,n)=>n!==i)})}>Remove phase</button></div></details>)}<button type="button" className={secondaryClass} disabled={plan.phases.length>=12} onClick={()=>change({phases:[...plan.phases,{name:"New phase",start:plan.start,end:plan.end,focus:"",training:emptyTargets(),rest:emptyTargets()}]})}>Add phase</button><p className="text-xs text-cream-faint">Overlaps and out-of-range phases block saving. A gap shows no assigned targets, never an invented phase.</p></section>
 <section className="space-y-3"><h3 className="text-lg font-semibold">Meal ideas, swaps & shopping</h3>{plan.meals.map((m,i)=><details key={i} className="rounded-2xl border border-divider p-4"><summary className="min-h-11 cursor-pointer font-semibold">{m.name||"New meal"}</summary><div className="mt-3 space-y-3"><Field label="Meal name"><input className={fieldClass} value={m.name} maxLength={120} onChange={e=>change({meals:plan.meals.map((v,n)=>n===i?{...v,name:e.target.value}:v)})}/></Field><Field label="Day context"><select className={fieldClass} value={m.day} onChange={e=>change({meals:plan.meals.map((v,n)=>n===i?{...v,day:e.target.value as "either"|"training"|"rest"}:v)})}><option value="either">Either day</option><option value="training">Training day</option><option value="rest">Rest day</option></select></Field>{([['serving','Serving and preparation'],['swaps','Reviewed substitutions']] as const).map(([key,label])=><Field key={key} label={label}><textarea className={fieldClass} rows={2} maxLength={1000} value={m[key]} onChange={e=>change({meals:plan.meals.map((v,n)=>n===i?{...v,[key]:e.target.value}:v)})}/></Field>)}<Field label="Ingredients · one per line, include quantity/unit"><textarea className={fieldClass} rows={3} value={m.ingredients.join("\n")} onChange={e=>change({meals:plan.meals.map((v,n)=>n===i?{...v,ingredients:e.target.value.split("\n")}:v)})}/></Field><TargetFields value={m.targets} onChange={targets=>change({meals:plan.meals.map((v,n)=>n===i?{...v,targets}:v)})}/><button type="button" className={secondaryClass} onClick={()=>change({meals:plan.meals.filter((_,n)=>n!==i)})}>Remove meal</button></div></details>)}<button type="button" className={secondaryClass} disabled={plan.meals.length>=30} onClick={()=>change({meals:[...plan.meals,{name:"New meal",day:"either",serving:"",ingredients:[],swaps:"",targets:emptyTargets()}]})}>Add meal idea</button><Field label="Grocery list · one item per line"><textarea className={fieldClass} rows={5} value={plan.grocery.join("\n")} onChange={e=>change({grocery:e.target.value.split("\n")})}/></Field><p className="text-xs text-cream-faint">Meal macros and substitutions are estimates to review. No food database or automatic nutrient equivalence is implied.</p></section>
 <Field label="Client guidance, fuel timing and practical strategies"><textarea className={fieldClass} rows={5} maxLength={6000} value={plan.guidance} onChange={e=>change({guidance:e.target.value})}/></Field><div className="grid gap-3 sm:grid-cols-2"><Field label="Draft provenance"><select className={fieldClass} value={origin} onChange={e=>setOrigin(e.target.value as PlanVersion["origin"])}><option value="coach_authored">Coach authored</option><option value="source_transcription">Transcribed from a source</option><option value="ai_proposed">AI proposed · review required</option></select></Field><Field label="Source reference · filename/page or private record reference"><input className={fieldClass} value={source} maxLength={500} onChange={e=>setSource(e.target.value)}/></Field></div>
 {warnings.length>0&&<div className="rounded-xl border border-status-moderate/30 p-4"><p className="text-sm font-semibold">Arithmetic checks · not clinical advice</p>{warnings.map((w,i)=><p key={i} className="mt-2 text-xs leading-5 text-cream-dim">{w}</p>)}</div>}
 <button type="submit" className={primaryClass}>{mutation.busy?"Saving…":`Save private version ${(latest?.revision??0)+1}`}</button></fieldset><MutationStatus mutation={mutation}/></form>
 {latest&&<section className="space-y-3 rounded-2xl border border-sky/25 bg-sky/5 p-4"><h3 className="font-semibold">Release saved version {latest.revision}</h3><p className="text-sm leading-6 text-cream-dim">This publishes the saved version, not unsaved edits above. The client sees only released plans. New versions never replace the current plan automatically.</p><fieldset disabled={locked} className="space-y-3"><Field label="Client-visible reason for this release or pause"><textarea className={fieldClass} rows={2} minLength={10} maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)}/></Field><label className="flex items-start gap-3 text-sm leading-6"><input className="mt-1 h-5 w-5 shrink-0" type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I reviewed this exact saved version for this person, including source accuracy, arithmetic, preferences/allergies, training demands and relevant clinical referral needs. Publishing is not an automated safety decision.</label><div className="flex flex-wrap gap-2"><button type="button" className={primaryClass} disabled={!confirmed||reason.trim().length<10||JSON.stringify(plan)!==JSON.stringify(latest.content)} onClick={()=>void releaseMutation.submit({action:"release_plan",request_id:crypto.randomUUID(),version_id:latest.id,expected_sequence:release?.sequence??0,confirmed:true,individual_review_confirmed:true,reason})}>Publish saved version to client</button>{release?.version_id&&<button type="button" className={secondaryClass} disabled={!confirmed||reason.trim().length<10} onClick={()=>void releaseMutation.submit({action:"release_plan",request_id:crypto.randomUUID(),version_id:null,expected_sequence:release.sequence,confirmed:true,individual_review_confirmed:true,reason})}>Pause current plan</button>}</div></fieldset><MutationStatus mutation={releaseMutation}/></section>}
 </div>;
}
