import type {FuelPlan,Targets} from "@/lib/fuel/model";
import {phaseForDate} from "@/lib/fuel/model";
function Numbers({targets}:{targets:Targets}){return <dl className="grid grid-cols-2 gap-2 sm:grid-cols-4">{[["Energy",targets.kcal,"kcal"],["Protein",targets.protein_g,"g"],["Carbs",targets.carbs_g,"g"],["Fat",targets.fat_g,"g"]].map(([label,value,unit])=><div key={String(label)} className="rounded-xl bg-surface-soft p-3"><dt className="text-xs text-cream-faint">{label}</dt><dd className="mt-1 text-sm font-semibold">{value===null?"Not assigned":`${value} ${unit}`}</dd></div>)}</dl>;}
export function FuelPlanView({plan,today}:{plan:FuelPlan;today:string}){const current=phaseForDate(plan,today);return <div className="space-y-5">
 <div><h2 className="text-2xl font-bold">{plan.title}</h2><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-cream-dim">{plan.goal||"Goal not yet recorded."}</p><p className="mt-2 text-xs text-cream-faint">{plan.start}–{plan.end} · {plan.event_date?`Confirmed event: ${plan.event_date}`:"Event date not confirmed"}</p></div>
 <section className="rounded-2xl border border-sky/25 bg-sky/5 p-4"><h3 className="font-semibold text-sky">{current?`Current phase · ${current.name}`:"No phase assigned for today"}</h3><p className="mt-2 whitespace-pre-wrap text-sm leading-6">{current?.focus||"Use the current coach-approved guidance; missing phase information is not an automatic adjustment."}</p>{current&&plan.mode==="targets"?<div className="mt-4 space-y-3"><h4 className="text-sm font-semibold">Training day · coach-assigned estimates</h4><Numbers targets={current.training}/><h4 className="text-sm font-semibold">Rest day · coach-assigned estimates</h4><Numbers targets={current.rest}/></div>:<p className="mt-3 text-sm text-cream-dim">Habit-led coaching. No calorie or macro requirement is implied.</p>}</section>
 <section><h3 className="text-lg font-semibold">Your roadmap</h3><div className="mt-3 grid gap-3 sm:grid-cols-2">{plan.phases.map((phase,i)=><article key={i} className={"break-inside-avoid rounded-2xl border p-4 "+(phase===current?"border-sky/50 bg-sky/5":"border-divider bg-white")}><p className="text-xs text-cream-faint">{phase.start}–{phase.end}</p><h4 className="mt-1 font-semibold">{phase.name}</h4><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-cream-dim">{phase.focus||"Focus not recorded."}</p></article>)}</div></section>
 {plan.guidance&&<section className="break-inside-avoid rounded-2xl bg-surface-soft p-4"><h3 className="font-semibold">Fuel timing & practical strategies</h3><p className="mt-3 whitespace-pre-wrap text-sm leading-7">{plan.guidance}</p></section>}
 <section id="fuel-meals" className="scroll-mt-24"><h3 className="text-lg font-semibold">Meal ideas & swaps</h3>{plan.meals.length?<div className="mt-3 grid gap-3 sm:grid-cols-2">{plan.meals.map((meal,i)=><article key={i} className="break-inside-avoid rounded-2xl border border-divider p-4"><p className="text-xs capitalize text-sky">{meal.day==="either"?"Flexible day":meal.day+" day"}</p><h4 className="mt-1 font-semibold">{meal.name}</h4><p className="mt-2 whitespace-pre-wrap text-sm leading-6">{meal.serving}</p><ul className="mt-3 list-inside list-disc space-y-1 text-sm text-cream-dim">{meal.ingredients.filter(Boolean).map((ingredient,n)=><li key={n}>{ingredient}</li>)}</ul>{meal.swaps&&<p className="mt-3 whitespace-pre-wrap text-sm leading-6"><strong>Reviewed swaps:</strong> {meal.swaps}</p>}<details className="mt-3"><summary className="min-h-11 cursor-pointer text-xs font-semibold text-sky">Reported meal estimates</summary><Numbers targets={meal.targets}/></details></article>)}</div>:<p className="mt-3 text-sm text-cream-dim">No meal templates assigned. Meal tracking can remain in your preferred food-logging app.</p>}</section>
 <section id="fuel-grocery" className="scroll-mt-24 break-inside-avoid rounded-2xl border border-divider p-4"><h3 className="font-semibold">Grocery list</h3><p className="mt-1 text-xs text-cream-faint">Coach-authored list. Quantities are not automatically calculated from a food database.</p>{plan.grocery.filter(Boolean).length?<ul className="mt-3 grid gap-2 sm:grid-cols-2">{plan.grocery.filter(Boolean).map((item,i)=><li key={i} className="rounded-lg bg-surface-soft px-3 py-2 text-sm">{item}</li>)}</ul>:<p className="mt-3 text-sm text-cream-dim">No shopping list assigned.</p>}</section>
 </div>;}
