"use client";
import {useEffect,useRef,useState} from "react";
import {MAX_FUEL_PDF_BYTES,validSourceReceipt} from "@/lib/fuel/source";
import {fieldClass,primaryClass,secondaryClass} from "./controls";
type Source={id:string;original_name:string;sha256:string;byte_size:number;created_at:string};
export function FuelSourceDocuments({clientId}:{clientId:string}){
 const [rows,setRows]=useState<Source[]|null>(null),[total,setTotal]=useState<number|null>(null),[loadError,setLoadError]=useState(false),[refresh,setRefresh]=useState(0),[file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(false),[error,setError]=useState<string|null>(null),[saved,setSaved]=useState(false);const lock=useRef(false),pending=useRef<{id:string;file:File;hash:string}|null>(null);
 useEffect(()=>{const controller=new AbortController();fetch(`/api/fuel/${clientId}/sources`,{signal:controller.signal,cache:"no-store"}).then(async response=>{const data=await response.json();if(!response.ok||!Array.isArray(data.sources)||!Number.isSafeInteger(data.total)||data.total<0)throw Error("Source history unavailable");if(!controller.signal.aborted){setRows(data.sources);setTotal(data.total);setLoadError(false);}}).catch(()=>{if(!controller.signal.aborted)setLoadError(true);});return()=>controller.abort();},[clientId,refresh]);
 async function upload(){if(lock.current||(!file&&!pending.current))return;lock.current=true;setBusy(true);setError(null);setSaved(false);try{
  if(!pending.current){if(!file||file.size>MAX_FUEL_PDF_BYTES)throw Error("Choose an original PDF of 8 MB or less.");const hash=[...new Uint8Array(await crypto.subtle.digest("SHA-256",await file.arrayBuffer()))].map(b=>b.toString(16).padStart(2,"0")).join("");pending.current={id:crypto.randomUUID(),file,hash};}
  const p=pending.current,response=await fetch(`/api/fuel/${clientId}/sources`,{method:"POST",headers:{"Content-Type":"application/pdf","x-source-id":p.id,"x-source-name":encodeURIComponent(p.file.name)},body:p.file});const data=await response.json().catch(()=>null);
  if(!response.ok||!validSourceReceipt(data,p.id,clientId,p.hash,p.file.size)){if(response.status>=500||response.ok||uncertain){setUncertain(true);}else{pending.current=null;setUncertain(false);}setError(data?.error??"Source receipt not confirmed.");return;}
  pending.current=null;setFile(null);setUncertain(false);setSaved(true);setRefresh(n=>n+1);
 }catch(cause){if(pending.current)setUncertain(true);setError(cause instanceof Error?cause.message:"Connection interrupted; retry the same original.");}finally{lock.current=false;setBusy(false);}}
 return <section className="space-y-3 rounded-2xl border border-divider bg-white p-4"><h3 className="font-semibold">Private source documents</h3><p className="text-sm leading-6 text-cream-dim">Upload an original PDF for this client. Bytes are preserved with a SHA-256 checksum. Raw sources remain private to the owner and assigned coach; uploading does not publish a plan, extract trusted targets or create a measurement.</p><label className="block text-sm font-semibold">Original PDF<input className={fieldClass} type="file" accept="application/pdf,.pdf" disabled={busy||uncertain} onChange={e=>{setFile(e.target.files?.[0]??null);setSaved(false);setError(null);}}/></label><button type="button" className={primaryClass} disabled={busy||(!file&&!pending.current)} onClick={()=>void upload()}>{busy?"Preserving original…":uncertain?"Retry preserved upload":"Save private original"}</button>{saved&&<p role="status" className="text-sm text-sky">Original saved and checksum confirmed. No client plan was changed.</p>}{error&&<p role="alert" className="text-sm text-status-limited">{error}</p>}
 {loadError?<div role="alert"><p className="text-sm text-status-limited">Source history unavailable. This may need the private-source database rollout; no empty-document state was inferred.</p><button className={secondaryClass} onClick={()=>setRefresh(n=>n+1)}>Retry source list</button></div>:rows===null?<p role="status" className="text-sm text-cream-dim">Loading private sources…</p>:<><p className="text-xs text-cream-faint">Showing {rows.length} of {total} source documents. Up to 100 latest originals.</p>{rows.map(row=><article key={row.id} className="rounded-xl bg-surface-soft p-3"><a href={`/api/fuel/${clientId}/sources?id=${row.id}`} className="inline-flex min-h-11 items-center break-all text-sm font-semibold text-sky">Download {row.original_name}</a><p className="break-all text-xs text-cream-faint">Source reference: document:{row.id}</p><p className="mt-1 break-all text-xs text-cream-faint">SHA-256: {row.sha256}</p></article>)}</>}
 </section>;
}
