import Link from "next/link";
import {AppShell} from "@/components/layout/app-shell";
import {fuelAccess,loadFuel,type FuelData} from "@/lib/fuel/load";
import {adherence,weightAverage,shiftDate,confirmedTrainingContext,bodyCompWarning,type Checkin} from "@/lib/fuel/model";
import {FuelPlanView} from "./plan-view";
import {FuelPlanEditor} from "./plan-editor";
import {FuelDailyForm,FuelWeeklyForm} from "./journal-forms";
import {FuelAdjustmentCandidate,FuelBodyCompForm,FuelCheckinResponse} from "./coach-forms";
const section="scroll-mt-24 space-y-4 rounded-3xl border border-divider bg-white p-5";
const navLink="inline-flex min-h-11 items-center rounded-xl border border-divider bg-white px-3 text-sm font-semibold text-sky";
export async function FuelWorkspace({clientId}:{clientId:string}){
 const access=await fuelAccess(clientId);let data:FuelData;
 try{data=await loadFuel(access.db,clientId);}catch{return <AppShell><main className="mx-auto max-w-3xl space-y-4 p-5"><h1 className="text-3xl font-bold">Fuel &amp; Performance</h1><section role="alert" className={section}><h2 className="font-semibold">Fuel workspace unavailable</h2><p className="text-sm leading-6">The Fuel &amp; Performance database rollout or an evidence query is unavailable. No empty history, targets, readiness score or saved state was inferred. Existing training and scheduling remain separate.</p></section><Link href={access.staff?`/clients/${clientId}`:"/dashboard"} className={navLink}>Return to coaching →</Link></main></AppShell>;}
 const {staff,person}=access,{versions,releases,journal,reviews,body,sessions,asOf,from}=data;
 const release=releases[0]??null,active=versions.find(v=>v.id===release?.version_id)??null,latest=versions[0]??null;
 const weekStart=shiftDate(asOf,-6),summary=adherence(journal,weekStart,asOf,clientId),weight=weightAverage(journal,weekStart,asOf,clientId),previousWeight=weightAverage(journal,shiftDate(asOf,-13),shiftDate(asOf,-7),clientId);
 const daily=journal.find(r=>r.kind==="daily"&&r.entry_date===asOf)??null,weekly=journal.find(r=>r.kind==="weekly"&&r.entry_date===asOf)??null,checkins=journal.filter(r=>r.kind==="weekly");
 const due=active?.content.review_on&&active.content.review_on<=asOf;
 return <AppShell><main className="mx-auto w-full max-w-6xl space-y-5 pb-16">
 <header className="rounded-3xl bg-band p-5 text-white sm:p-7"><p className="text-xs uppercase tracking-[.18em] text-white/60">IMS / Fuel &amp; Performance</p><h1 className="mt-2 text-3xl font-bold sm:text-4xl">{staff?person.full_name:"Fuel your training"}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-white/75">Your plan, daily habits, measured progress and coach conversations in one history. Training quality matters; no number changes your plan automatically.</p><div className="mt-4 flex flex-wrap gap-3"><Link href={staff?`/clients/${clientId}`:"/dashboard"} className="inline-flex min-h-11 items-center text-sm font-semibold text-white">← {staff?"Client profile":"Today"}</Link><Link href={staff?`/sessions/new?client_id=${clientId}`:"/plan"} className="inline-flex min-h-11 items-center text-sm font-semibold text-white">{staff?"Book training":"My training"} →</Link>{active&&<Link href={`/fuel/print?client_id=${clientId}&version=${active.id}`} className="inline-flex min-h-11 items-center text-sm font-semibold text-white">Current plan · Print / PDF →</Link>}{staff&&<Link href={`/clients/${clientId}/fuel/sources`} className="inline-flex min-h-11 items-center text-sm font-semibold text-white">Private original PDFs →</Link>}</div></header>
 <nav aria-label="Fuel workspace sections" className="flex flex-wrap gap-2">{[["#fuel-overview","Overview"],["#fuel-plan","Plan"],["#fuel-daily","Daily"],["#fuel-checkins","Coach check-ins"],["#fuel-body","Body composition"],["#fuel-history","Versions"]].map(([href,label])=><a key={href} href={href} className={navLink}>{label}</a>)}</nav>
 <section id="fuel-overview" className="scroll-mt-24 grid gap-3 sm:grid-cols-3"><article className="rounded-2xl border border-divider bg-white p-4"><h2 className="text-xs font-semibold uppercase text-cream-faint">Plan status</h2><p className="mt-2 font-semibold">{active?`Released version ${active.revision}`:release?"Current plan paused":"No released plan"}</p><p className="mt-2 text-xs text-cream-dim">{active?.content.review_on?`Coach review target: ${active.content.review_on}${due?" · due for review":""}`:"No review date assigned"}</p></article><article className="rounded-2xl border border-divider bg-white p-4"><h2 className="text-xs font-semibold uppercase text-cream-faint">Logging coverage</h2><p className="mt-2 text-2xl font-bold">{summary.loggedDays}/7 days</p><p className="mt-2 text-xs text-cream-dim">{weekStart}–{asOf}. Unreported days are not failures.</p></article><article className="rounded-2xl border border-divider bg-white p-4"><h2 className="text-xs font-semibold uppercase text-cream-faint">Reported weight average</h2><p className="mt-2 text-2xl font-bold">{weight.average===null?"Not enough samples":`${weight.average} lb`}</p><p className="mt-2 text-xs text-cream-dim">{weight.samples} reported weigh-ins in 7 days. At least 3 required.</p>{weight.average!==null&&previousWeight.average!==null&&<p className="mt-2 text-xs text-cream-dim">{Math.round((weight.average-previousWeight.average)*10)/10} lb versus previous window ({previousWeight.samples} samples). Scale change is not measured fat change.</p>}</article></section>
 <section id="fuel-plan" className={section}>{active?<FuelPlanView plan={active.content} today={asOf}/>:<><h2 className="text-xl font-semibold">No current client-visible plan</h2><p className="text-sm leading-6 text-cream-dim">Private drafts and source documents are not prescriptions. A coach must explicitly review and release a plan. A missing assessment does not block habit-led coaching.</p></>}{staff&&<details className="mt-6 border-t border-divider pt-3" open={!latest}><summary className="min-h-12 cursor-pointer text-lg font-semibold text-sky">Coach editor · private versions &amp; release</summary><FuelPlanEditor key={`${latest?.id??"new"}:${release?.sequence??0}`} clientId={clientId} latest={latest} release={release} today={asOf}/></details>}</section>
 <section id="fuel-daily" className={section}><h2 className="text-xl font-semibold">Daily scorecard</h2><p className="text-sm text-cream-dim">Reported habits, not a compliance or health score.</p>{!staff&&<FuelDailyForm key={`${asOf}:${daily?.revision??0}:${active?.id??"none"}`} clientId={clientId} date={asOf} entry={daily} versionId={active?.id??null} plan={active?.content??null} hasBooking={confirmedTrainingContext(sessions,asOf)}/>}<dl className="grid grid-cols-2 gap-3 sm:grid-cols-3">{summary.habits.map(h=><div key={h.habit} className="rounded-xl bg-surface-soft p-3"><dt className="text-sm font-semibold capitalize">{h.habit}</dt><dd className="mt-2 text-sm">{h.percent===null?"Not reported":`${h.met}/${h.reported} reported goals met`}</dd><dd className="mt-1 text-xs text-cream-faint">{h.notDue} not due. Missing entries excluded.</dd></div>)}</dl></section>
 <section id="fuel-checkins" className={section}><h2 className="text-xl font-semibold">Weekly coach check-in</h2>{!staff&&<details open={!weekly}><summary className="min-h-12 cursor-pointer font-semibold text-sky">{weekly?"Edit today&apos;s submitted check-in":"Review my week"}</summary><FuelWeeklyForm key={`${asOf}:${weekly?.revision??0}:${active?.id??"none"}`} clientId={clientId} date={asOf} entry={weekly} versionId={active?.id??null}/></details>}
 {checkins.length?checkins.map(entry=>{const payload=entry.payload as Checkin,review=reviews.find(r=>r.entry_id===entry.id);return <article key={entry.id} className="rounded-2xl border border-divider p-4"><div className="flex flex-wrap justify-between gap-2"><h3 className="font-semibold">{entry.entry_date} · revision {entry.revision}</h3><p className="text-xs font-semibold text-sky">{review?"Coach reviewed":"Awaiting coach review"}{payload.contact_requested?" · contact requested":""}</p></div><dl className="mt-3 grid gap-3 sm:grid-cols-2">{Object.entries(payload).map(([key,value])=><div key={key}><dt className="text-xs capitalize text-cream-faint">{key.replaceAll("_"," ")}</dt><dd className="mt-1 whitespace-pre-wrap text-sm">{value===null||value===""?"Not reported":typeof value==="boolean"?value?"Yes":"No":String(value)}</dd></div>)}</dl>{review?<><div className="mt-4 rounded-xl bg-sky/5 p-3"><h4 className="text-sm font-semibold">Coach response · {review.disposition}</h4><p className="mt-2 whitespace-pre-wrap text-sm leading-6">{review.note}</p></div>{staff&&review.disposition==="reviewed"&&<FuelAdjustmentCandidate clientId={clientId} entryId={entry.id} current={active}/>}</>:staff?<FuelCheckinResponse clientId={clientId} entryId={entry.id}/>:null}</article>;}):<p className="text-sm text-cream-dim">No check-in reported during this view&apos;s date window.</p>}<p className="text-xs text-cream-faint">Journal window: {from}–{asOf}. Earlier entries remain stored; this screen does not claim a lifetime summary.</p></section>
 <section id="fuel-body" className={section}><h2 className="text-xl font-semibold">Body composition · recorded measurements</h2><p className="text-sm leading-6 text-cream-dim">The same canonical records used by client Progress. Keep method and conditions comparable. No projected checkpoint is presented as a measurement and no fixed change threshold diagnoses muscle gain or loss.</p>{body.length?<div className="overflow-x-auto"><table className="w-full min-w-[540px] text-left text-sm"><caption className="sr-only">Recorded body composition by date and method</caption><thead><tr>{["Date / method","Weight · lb","Body fat · %","Lean mass · lb"].map(h=><th key={h} scope="col" className="border-b border-divider px-2 py-3">{h}</th>)}</tr></thead><tbody>{body.map(row=><tr key={row.id}><th scope="row" className="border-b border-divider px-2 py-3 font-normal"><span>{row.recorded_at}</span><span className="block text-xs text-cream-faint">{row.method.replaceAll("_"," ")}</span>{bodyCompWarning(row)&&<span className="mt-1 block max-w-64 text-xs text-status-moderate">{bodyCompWarning(row)}</span>}</th>{[row.weight_lb,row.body_fat_pct,row.lean_mass_lb].map((value,i)=><td key={i} className="border-b border-divider px-2 py-3">{value===null?"Not recorded":value}</td>)}</tr>)}</tbody></table></div>:<p className="text-sm text-cream-dim">No body-composition records. A test is optional for habit-led coaching.</p>}{staff&&<details><summary className="min-h-12 cursor-pointer font-semibold text-sky">Add a verified test to client history</summary><FuelBodyCompForm key={body.map(row=>row.id).join(":")} clientId={clientId} today={asOf}/></details>}</section>
 <section id="fuel-history" className={section}><h2 className="text-xl font-semibold">Plan versions &amp; portability</h2><p className="text-sm leading-6 text-cream-dim">Previous releases remain historical snapshots. Only the latest release controls today&apos;s plan. Corrections do not rewrite old versions.</p><div className="space-y-2">{versions.map(v=><div key={v.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl bg-surface-soft p-3"><div><p className="text-sm font-semibold">Version {v.revision} · {v.content.title}</p><p className="mt-1 text-xs text-cream-faint">{v.id===active?.id?"Current release":releases.some(r=>r.version_id===v.id)?"Previously released":"Private draft"} · {v.origin.replaceAll("_"," ")}</p></div><div className="flex gap-3"><Link className="inline-flex min-h-11 items-center text-sm font-semibold text-sky" href={`/fuel/print?client_id=${clientId}&version=${v.id}`}>Print / PDF</Link><a className="inline-flex min-h-11 items-center text-sm font-semibold text-sky" href={`/api/fuel/${clientId}/export?version=${v.id}`}>JSON export</a></div></div>)}</div></section>
 </main></AppShell>;
}
