import Link from "next/link";import {redirect} from "next/navigation";import {createClient} from "@/lib/supabase/server";import {Users,ShieldCheck,Mail,SlidersHorizontal,BrainCircuit,Video,Palette,History,ArrowRight,BadgeDollarSign} from "lucide-react";
export const dynamic="force-dynamic";
const sections=[
 {href:"/settings/services",title:"Services & pricing",copy:"Training services, packages and what clients can purchase.",icon:SlidersHorizontal},
 {href:"/settings/email",title:"Access & logins",copy:"Client invitations, account access and email diagnostics.",icon:Mail},
 {href:"/clients",title:"People & coaching",copy:"Client relationships, programming paths and account status.",icon:Users},
 {href:"/settings/staff",title:"Staff & roles",copy:"Team roles, coaching load, schedules and payroll mapping readiness.",icon:Users},
 {href:"/action-center",title:"Operations",copy:"Follow-ups, reviews and work that needs owner attention.",icon:ShieldCheck},
 {href:"/settings/payroll",title:"Payroll & compensation",copy:"Trainer evidence, provider connection and owner-reviewed payroll controls.",icon:BadgeDollarSign},
 {href:"/leads?tab=research",title:"AI & Research",copy:"Research Desk workflow. Budget controls arrive with paid AI connection.",icon:BrainCircuit},
 {href:"/library",title:"Video & exercise library",copy:"Exercise approvals, client visibility and reusable coaching media.",icon:Video},
 {href:"/settings/audit",title:"Operational history",copy:"Owner-visible audit trail for important system changes.",icon:History},
 {href:"/reports",title:"Reports",copy:"Operational, financial, engagement and client outcome reporting.",icon:History},
];
export default async function OwnerSettingsPage(){const db=await createClient();const {data:{user}}=await db.auth.getUser();if(!user)redirect("/login?next=/settings");const me=await db.from("profiles").select("role,full_name").eq("id",user.id).maybeSingle();if(me.error||me.data?.role!=="owner")redirect("/dashboard");return <main className="mx-auto w-full max-w-6xl space-y-6 pb-20"><header className="rounded-3xl bg-band p-6 text-white shadow-lg sm:p-8"><p className="text-xs font-semibold uppercase tracking-[.2em] text-sky-light">Owner control center</p><h1 className="mt-2 text-3xl font-bold sm:text-4xl">Run IMS from one place.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-white/70">Business controls, access, coaching systems and operational settings. High-impact changes remain deliberate and auditable.</p></header><section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{sections.map(s=>{const Icon=s.icon;return <Link key={s.href} href={s.href} className="group rounded-2xl border border-divider bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:border-sky/40 hover:shadow-md"><div className="flex items-start justify-between"><span className="rounded-xl bg-sky/10 p-2.5"><Icon className="h-5 w-5 text-sky"/></span><ArrowRight className="h-4 w-4 text-cream-faint transition group-hover:translate-x-1 group-hover:text-sky"/></div><h2 className="mt-4 font-semibold text-cream">{s.title}</h2><p className="mt-1 text-sm leading-6 text-cream-dim">{s.copy}</p></Link>})}</section><section className="rounded-2xl border border-divider bg-white p-5"><div className="flex items-center gap-2"><Palette className="h-5 w-5 text-sky"/><h2 className="font-semibold">Brand & experience</h2></div><p className="mt-2 text-sm leading-6 text-cream-dim">IMS logo, app identity and client experience are centrally controlled in the product build today. Editable brand controls will stay owner-only when exposed here.</p></section></main>}
