-- 0016_seed_leads.sql
-- Import 322 contacts from the Vagaro + Jason customer list as leads.
-- Idempotent: ON CONFLICT (name+phone) does nothing, so re-running is safe.

INSERT INTO leads (first_name, last_name, full_name, email, phone, interest, source, appointments_booked, last_visited, prior_trainer, address)
VALUES
  ('Barbara','Hunter','Barbara Hunter','bmhunter2@san.rr.com','6195171501','Leads for ALL','vagaro',32,NULL,'Jason Patterson',NULL),
  ('Maureen','Mintry','Maureen Mintry','mmittry@eusd.org','6199947131','Leads for ALL','vagaro',3,NULL,'Jason Patterson',NULL),
  ('Suzanne','Apgar','Suzanne Apgar','suzanneapgar@gmail.com','9166900575','Leads for ALL','vagaro',48,NULL,'Timothy Paschal, Jason Patterson','16760 Pinata Drive'),
  ('Beth','Mcneil','Beth Mcneil',NULL,'8582459291','Leads for ALL','vagaro',0,NULL,'Jason Patterson',NULL),
  ('Gabriel','Filkey','Gabriel Filkey','gabe@filkey.com','6199553868','Leads for ALL','vagaro',2,NULL,'Jason Patterson, Hollie Harris',NULL),
  ('Jen','Mohr','Jen Mohr',NULL,'8055502721','Leads for ALL','vagaro',0,NULL,'Jason Patterson',NULL),
  ('Jp','Mcneil','Jp Mcneil',NULL,'6195506052','Leads for ALL','vagaro',0,NULL,'Jason Patterson',NULL),
  ('Justin','Sun','Justin Sun',NULL,'8652743322','Leads for ALL','vagaro',0,NULL,'Jason Patterson',NULL),
  ('Mona','FQ10','Mona FQ10',NULL,'4152503756','Leads for ALL','vagaro',0,NULL,'Jason Patterson',NULL),
  ('Stacey','Lomedico','Stacey Lomedico',NULL,'6199803748','Leads for ALL','vagaro',0,NULL,'Jason Patterson',NULL),
  ('Steve Doc','Henry','Steve Doc Henry',NULL,'8586026454','Leads for ALL','vagaro',0,NULL,'Jason Patterson',NULL),
  ('Will','Lemkul','Will Lemkul','wlemkul@gmail.com','6195784975','Leads for ALL','vagaro',356,'2024-12-13','Jason Patterson',NULL),
  ('Tom','Ohrstrom','Tom Ohrstrom','ohrstromtom@gmail.com','8589223673','Leads for ALL','vagaro',283,NULL,'Jason Patterson, Hollie Harris',NULL),
  ('Julia','Wilcox','Julia Wilcox',NULL,'5712133992','Leads for ALL','vagaro',1,NULL,'Jason Patterson',NULL),
  ('Zach','Hale','Zach Hale',NULL,'4342840979','Leads for ALL','vagaro',0,NULL,NULL,NULL),
  ('Jorge','Marron','Jorge Marron',NULL,'6199226375','Leads for ALL','vagaro',0,NULL,NULL,NULL),
  ('Jeremy','Gonzales SR','Jeremy Gonzales SR',NULL,'6196513414','Leads for ALL','vagaro',0,NULL,NULL,NULL),
  ('Christine','Lawson','Christine Lawson',NULL,NULL,'Leads for ALL','vagaro',19,NULL,'Jason Patterson',NULL),
  ('Sarah','Harrison','Sarah Harrison',NULL,'8584374664','Leads for ALL','vagaro',154,NULL,'Jason Patterson',NULL),
  ('Glory','Wylie','Glory Wylie',NULL,'6192416453','Leads for ALL','vagaro',0,NULL,NULL,NULL),
  ('Steve','Hebert','Steve Hebert',NULL,NULL,'Leads for ALL','vagaro',0,NULL,NULL,NULL),
  ('Linda','Rios','Linda Rios',NULL,NULL,'Leads for ALL','vagaro',0,NULL,NULL,NULL),
  ('Sruthi','Kondakindi','Sruthi Kondakindi',NULL,'4802979036','Leads for ALL','vagaro',1,'2023-02-17','Jason Patterson',NULL),
  ('Tara','Romanczyk','Tara Romanczyk',NULL,NULL,'Leads for ALL','vagaro',0,NULL,NULL,NULL),
  ('Saman','Nemovi','Saman Nemovi',NULL,'8587761457','Leads for ALL','vagaro',9,NULL,'Jason Patterson',NULL),
  ('Karla','Anguiano','Karla Anguiano',NULL,'8587330307','Leads for ALL','vagaro',0,NULL,NULL,NULL),
  ('Olivia','Reynolds','Olivia Reynolds','yzkd85sdm9@privaterelay.appleid.com','5305183445','Leads for ALL','vagaro',1,NULL,'Jason Patterson',NULL),
  ('Sarah','Allen','Sarah Allen',NULL,'6193219587','Leads for ALL','vagaro',0,NULL,NULL,NULL),
  ('Camille','Khadr','Camille Khadr',NULL,'9257897187','Massage','vagaro',1,NULL,'Hollie Harris',NULL),
  ('Hannah','Jones','Hannah Jones',NULL,'8583376290','Massage','vagaro',96,NULL,'Jason Patterson',NULL),
  ('Kathy','Smith','Kathy Smith','ksmith92131@gmail.com','6199949611','Massage','vagaro',64,NULL,'Jason Patterson, Hollie Harris',NULL),
  ('Robert','Walton','Robert Walton',NULL,'6198209838','Massage','vagaro',0,NULL,'Jason Patterson',NULL),
  ('Taylor','Barry','Taylor Barry',NULL,'6198893516','Massage','vagaro',0,NULL,NULL,NULL),
  ('Donna','Luu','Donna Luu',NULL,'8582184648','Massage','vagaro',0,NULL,NULL,NULL),
  ('Teresa','Olcomedy','Teresa Olcomedy',NULL,'8583959745','Massage','vagaro',0,NULL,NULL,NULL),
  ('Michele','Fisher','Michele Fisher',NULL,NULL,'Massage','vagaro',0,NULL,NULL,NULL),
  ('Justin','Corbisez','Justin Corbisez',NULL,'6196339798','Massage','vagaro',1,NULL,'Jason Patterson',NULL),
  ('Marvin','Abou','Marvin Abou',NULL,'8587613597','Massage','vagaro',2,NULL,'Hollie Harris',NULL),
  ('Zayn','De Leon','Zayn De Leon',NULL,'6192467794','Massage','vagaro',0,NULL,NULL,NULL),
  ('Sophia','Dowell','Sophia Dowell',NULL,'6192436723','Massage','vagaro',0,NULL,NULL,NULL),
  ('Ross','Hendler','Ross Hendler','rhendler@mac.com','8587841224','Massage','vagaro',2,NULL,'Hollie Harris',NULL),
  ('Stan','Williams','Stan Williams',NULL,'4087993852','Maybe','vagaro',0,NULL,'Jason Patterson',NULL),
  ('Zoe','Allen','Zoe Allen','zoeallen1111@gmail.com','6198224551','Maybe','vagaro',0,NULL,NULL,NULL),
  ('Teresa','Fagan','Teresa Fagan',NULL,NULL,'Maybe','vagaro',1,'2024-08-15','Jason Patterson',NULL),
  ('Ally','Scripps Lax','Ally Scripps Lax',NULL,'6195382850','Maybe','vagaro',0,NULL,'Jason Patterson',NULL),
  ('Brody','Erickson','Brody Erickson',NULL,'8582323868','Maybe','vagaro',0,NULL,'Jason Patterson',NULL),
  ('Carly','S Fq10','Carly S Fq10',NULL,'6192088443','Maybe','vagaro',0,NULL,'Jason Patterson',NULL),
  ('Eric','Martin','Eric Martin',NULL,'9493003565','Maybe','vagaro',0,NULL,'Jason Patterson',NULL),
  ('Harrison','Rogers','Harrison Rogers',NULL,'8584149755','Maybe','vagaro',0,NULL,'Jason Patterson',NULL),
  ('Jackson','Bolitha','Jackson Bolitha',NULL,'8587741504','Maybe','vagaro',0,NULL,'Jason Patterson',NULL),
  ('Jeff','Granucci','Jeff Granucci',NULL,'6193007668','Maybe','vagaro',0,NULL,'Jason Patterson',NULL),
  ('Kathy','Ryan','Kathy Ryan',NULL,'8582486978','Maybe','vagaro',0,NULL,'Jason Patterson',NULL),
  ('Lauren','Norwood','Lauren Norwood',NULL,'7605860858','Maybe','vagaro',0,NULL,'Jason Patterson',NULL),
  ('Luiz','Perez','Luiz Perez',NULL,'6192008714','Maybe','vagaro',0,NULL,'Jason Patterson',NULL),
  ('Noel','Philips','Noel Philips',NULL,'7605867412','Maybe','vagaro',0,NULL,'Jason Patterson',NULL),
  ('Wes','Nichols','Wes Nichols',NULL,'3108975056','Maybe','vagaro',2,'2022-01-14','Jason Patterson',NULL),
  ('Nathan','Gumb','Nathan Gumb',NULL,'8582048286','Maybe','vagaro',56,'2022-07-19','Jason Patterson',NULL),
  ('Matt','Nuanez','Matt Nuanez',NULL,NULL,'Maybe','vagaro',0,NULL,NULL,NULL),
  ('Lance','Desorbo','Lance Desorbo',NULL,NULL,'Maybe','vagaro',0,NULL,NULL,NULL),
  ('Alex','Fakic','Alex Fakic',NULL,NULL,'Maybe','vagaro',0,NULL,NULL,NULL),
  ('Matt','Rochelle','Matt Rochelle',NULL,NULL,'Maybe','vagaro',0,NULL,NULL,NULL),
  ('Taylor','Travillion','Taylor Travillion',NULL,NULL,'Maybe','vagaro',0,NULL,NULL,NULL),
  ('Ryan','Ham','Ryan Ham','jangsik.ham@gmail.com','8583229295','Maybe','vagaro',1,NULL,'Jason Patterson',NULL),
  ('Todd','Harrison','Todd Harrison',NULL,'8582541304','Maybe','vagaro',27,NULL,'Jason Patterson',NULL),
  ('Nate','Gumbi','Nate Gumbi',NULL,NULL,'Maybe','vagaro',1,'2021-07-23','Jason Patterson',NULL),
  ('Demi','Torres','Demi Torres',NULL,'6193941202','Maybe','vagaro',14,NULL,'Jason Patterson',NULL),
  ('Devin','Gumb','Devin Gumb',NULL,NULL,'Maybe','vagaro',0,NULL,NULL,NULL),
  ('Louis','Rodriguez','Louis Rodriguez',NULL,'5628252046','Maybe','vagaro',0,NULL,NULL,NULL),
  ('Oscar','Jones','Oscar Jones',NULL,NULL,'Maybe','vagaro',0,NULL,NULL,NULL),
  ('Nick','Driscol','Nick Driscol',NULL,NULL,'Maybe','vagaro',5,'2022-05-07','Jason Patterson, Hollie Harris',NULL),
  ('Kaden','Rogers','Kaden Rogers',NULL,NULL,'Maybe','vagaro',0,NULL,NULL,NULL),
  ('Kannon','Virgilio','Kannon Virgilio',NULL,NULL,'Maybe','vagaro',0,NULL,NULL,NULL),
  ('Mia','Bento','Mia Bento',NULL,NULL,'Maybe','vagaro',0,NULL,NULL,NULL),
  ('Joey','V','Joey V',NULL,NULL,'Maybe','vagaro',0,NULL,NULL,NULL),
  ('Mike','Nguyen','Mike Nguyen',NULL,NULL,'Maybe','vagaro',0,NULL,NULL,NULL),
  ('Ryan','Simone','Ryan Simone',NULL,NULL,'Maybe','vagaro',0,NULL,NULL,NULL),
  ('Beca','Tomcho','Beca Tomcho',NULL,NULL,'Maybe','vagaro',0,NULL,NULL,NULL),
  ('Kayla','Virgilio','Kayla Virgilio',NULL,NULL,'Maybe','vagaro',0,NULL,NULL,NULL),
  ('Tonya','Brubaker','Tonya Brubaker',NULL,NULL,'Maybe','vagaro',1,'2022-08-03','Jason Patterson',NULL),
  ('Kim','Fearon','Kim Fearon',NULL,NULL,'Maybe','vagaro',0,NULL,NULL,NULL),
  ('Lisa','McDonald','Lisa McDonald',NULL,'8587747348','Maybe','vagaro',0,NULL,NULL,NULL),
  ('Hannah','Bloon','Hannah Bloon',NULL,NULL,'Maybe','vagaro',0,NULL,NULL,NULL),
  ('Jeff','Lee','Jeff Lee',NULL,NULL,'Maybe','vagaro',0,NULL,NULL,NULL),
  ('Donna','Cooper','Donna Cooper',NULL,'6192277646','Maybe','vagaro',19,NULL,'Marie Lemkul',NULL),
  ('Allison','Imam-hedrick','Allison Imam-hedrick',NULL,NULL,'Maybe','vagaro',0,NULL,NULL,NULL),
  ('Lexi','Epley','Lexi Epley',NULL,NULL,'Maybe','vagaro',0,NULL,NULL,NULL),
  ('Nicole','Amador','Nicole Amador',NULL,NULL,'Maybe','vagaro',0,NULL,NULL,NULL),
  ('Laureen','Hebert','Laureen Hebert',NULL,NULL,'Maybe','vagaro',0,NULL,NULL,NULL),
  ('Jean','McPhee','Jean McPhee',NULL,NULL,'Maybe','vagaro',0,NULL,NULL,NULL),
  ('Sam','Toninato','Sam Toninato',NULL,NULL,'Maybe','vagaro',0,NULL,NULL,NULL),
  ('Jenna','Spitzberg','Jenna Spitzberg',NULL,NULL,'Maybe','vagaro',0,NULL,NULL,NULL),
  ('Kristi','Wilson','Kristi Wilson','kristi.wilson@gmail.com','2174932700','Maybe','vagaro',0,NULL,NULL,NULL),
  ('Tim','Keenan','Tim Keenan',NULL,NULL,'Maybe','vagaro',0,NULL,NULL,NULL),
  ('Gena','Keenan','Gena Keenan',NULL,NULL,'Maybe','vagaro',0,NULL,NULL,NULL),
  ('Debra','Hernandez','Debra Hernandez',NULL,NULL,'Maybe','vagaro',0,NULL,NULL,NULL),
  ('Karim','Khadr','Karim Khadr',NULL,NULL,'Maybe','vagaro',0,NULL,NULL,NULL),
  ('Brian','Konisky','Brian Konisky',NULL,NULL,'Maybe','vagaro',0,NULL,NULL,NULL),
  ('Diya','Nair','Diya Nair','idiya2623@gmail.com','6196728716','Maybe','vagaro',0,NULL,NULL,NULL),
  ('Reese','Nguyen','Reese Nguyen','reeseanguyen@gmail.com','8587228860','Maybe','vagaro',0,NULL,NULL,NULL),
  ('Simone','Boattini','Simone Boattini','simonemitsuko@yahoo.com','6198405727','Maybe','vagaro',0,NULL,NULL,NULL),
  ('Giana','Reuter','Giana Reuter','gianareuter@gmail.com','6196654114','Maybe','vagaro',0,NULL,NULL,NULL),
  ('Lauren','Okuna','Lauren Okuna',NULL,'8583573503','Maybe','vagaro',0,NULL,NULL,NULL),
  ('Giovanni','Fiorella','Giovanni Fiorella',NULL,NULL,'Maybe','vagaro',0,NULL,NULL,NULL),
  ('Emily','Sonnet','Emily Sonnet',NULL,NULL,'Maybe','vagaro',0,NULL,NULL,NULL),
  ('Pat','Conroy','Pat Conroy',NULL,'8583954392','Maybe','vagaro',0,NULL,NULL,NULL),
  ('Jenna','Synder','Jenna Synder',NULL,'3162040819','Maybe','vagaro',1,NULL,'Hollie Harris',NULL),
  ('Chase','Svarka','Chase Svarka',NULL,'8582261236','Membership','vagaro',90,NULL,'Jason Patterson',NULL),
  ('Gregory','Soldier','Gregory Soldier','soldner@morrissullivanlaw.com','6199770066','Membership','vagaro',0,NULL,NULL,NULL),
  ('Mitchell','McNeil','Mitchell McNeil',NULL,NULL,'Membership','vagaro',2,NULL,'Jason Patterson',NULL),
  ('Ben','Sinclair','Ben Sinclair',NULL,'8582086163','Membership','vagaro',0,NULL,'Jason Patterson',NULL),
  ('Dakota','Hitson','Dakota Hitson',NULL,'6197787867','Membership','vagaro',0,NULL,'Jason Patterson',NULL),
  ('Diana','Fq10','Diana Fq10',NULL,'8054030861','Membership','vagaro',0,NULL,'Jason Patterson',NULL),
  ('Don','Netzke','Don Netzke',NULL,'8583371258','Membership','vagaro',0,NULL,'Jason Patterson',NULL),
  ('Jeff','Booch','Jeff Booch',NULL,'8586493905','Membership','vagaro',0,NULL,'Jason Patterson',NULL),
  ('Alaina','Kokovska','Alaina Kokovska',NULL,'8583332737','Membership','vagaro',4,NULL,'Jason Patterson',NULL),
  ('Anders','Ohrstrom','Anders Ohrstrom',NULL,'8589975135','Membership','vagaro',131,NULL,'Jason Patterson',NULL),
  ('Adrian','Ruano','Adrian Ruano',NULL,NULL,'Membership','vagaro',1,NULL,'Jason Patterson',NULL),
  ('Christian','Barton','Christian Barton',NULL,'7608455420','Membership','vagaro',0,NULL,NULL,NULL),
  ('Henrik','Orstrohm','Henrik Orstrohm',NULL,NULL,'Membership','vagaro',158,NULL,'Jason Patterson',NULL),
  ('Joseph','Lomedico','Joseph Lomedico',NULL,'6196724100','Membership','vagaro',2,NULL,'Jason Patterson',NULL),
  ('Gene','Wright','Gene Wright',NULL,'6193339013','Membership','vagaro',1,'2022-05-02','Jason Patterson',NULL),
  ('Joshua','Steichen','Joshua Steichen',NULL,'7143818305','Membership','vagaro',1,'2022-10-07','Jason Patterson',NULL),
  ('Navaneet','Danda','Navaneet Danda',NULL,'4803707083','Membership','vagaro',1,'2023-01-30','Jason Patterson',NULL),
  ('Ava','Schram','Ava Schram',NULL,NULL,'Membership','vagaro',1,'2024-06-27','Jason Patterson',NULL),
  ('Brooke','Griffin','Brooke Griffin',NULL,NULL,'Membership','vagaro',0,NULL,NULL,NULL),
  ('Clementine','Maunu','Clementine Maunu',NULL,NULL,'Membership','vagaro',0,NULL,NULL,NULL),
  ('Natalie','Piper','Natalie Piper','nataliepiper07@gmail.com','8588681215','Membership','vagaro',0,NULL,NULL,NULL),
  ('Sammy','Ippolito','Sammy Ippolito',NULL,NULL,'Membership','vagaro',0,NULL,NULL,NULL),
  ('Jacob','Genschaw','Jacob Genschaw',NULL,NULL,'Membership','vagaro',0,NULL,NULL,NULL),
  ('Brynn','Wiesbrock','Brynn Wiesbrock','brynn.wiesbrock@gmail.com','8582312810','Membership','vagaro',0,NULL,NULL,NULL),
  ('CJ','Bulato','CJ Bulato','c.bulatao08@gmail.com','8588771392','Membership','vagaro',0,NULL,NULL,NULL),
  ('Simi','Wimmer','Simi Wimmer','simran.wimmer@gmail.com','6192411226','Membership','vagaro',1,'2024-06-27','Jason Patterson',NULL),
  ('Leticia','Maza','Leticia Maza',NULL,NULL,'Membership','vagaro',0,NULL,NULL,NULL),
  ('Patrick','Sparkman','Patrick Sparkman',NULL,'8587408455','Membership','vagaro',9,NULL,'Timothy Paschal, Jason Patterson, Hollie Harris',NULL),
  ('Jen','Leader','Jen Leader',NULL,'6198900032','Membership','vagaro',3,NULL,'Timothy Paschal',NULL),
  ('Chloe','Philibert-Zumbro','Chloe Philibert-Zumbro',NULL,NULL,'Membership','vagaro',1,NULL,'Hollie Harris',NULL),
  ('Dan','Lehmann','Dan Lehmann',NULL,'2032186517','Membership','vagaro',1,NULL,'Hollie Harris',NULL),
  ('Hailey','Stepenoski','Hailey Stepenoski',NULL,NULL,'Membership','vagaro',0,NULL,NULL,NULL),
  ('Lily','Cumba','Lily Cumba','lilycumba03@gmail.com','8588332976','Membership','vagaro',0,NULL,NULL,NULL),
  ('Pete','Livkraft','Pete Livkraft',NULL,'8587508092','Networking','vagaro',0,NULL,'Jason Patterson',NULL),
  ('Rome','Weight','Rome Weight',NULL,NULL,'Networking','vagaro',1,'2022-04-06','Jason Patterson',NULL),
  ('Carlo','Boticano','Carlo Boticano',NULL,NULL,'Networking','vagaro',0,NULL,NULL,NULL),
  ('Hannah','Brubaker','Hannah Brubaker',NULL,NULL,'Networking','vagaro',1,'2022-06-22','Jason Patterson',NULL),
  ('Emily','Kloss','Emily Kloss',NULL,NULL,'Networking','vagaro',0,NULL,NULL,NULL),
  ('Emi','Okuna','Emi Okuna','laurenemi527@gmail.com','8583573503','Networking','vagaro',0,NULL,NULL,NULL),
  ('Ava','Pavik','Ava Pavik','amy.pavlik@sharp.com','8583957594','Networking','vagaro',0,NULL,NULL,NULL),
  ('Danielle','Merrigan','Danielle Merrigan','dm@merriganca.com',NULL,'Networking','vagaro',0,NULL,NULL,NULL),
  ('Lyla','Kaplan','Lyla Kaplan','lylakaplan2@gmail.com','8586058393','Networking','vagaro',0,NULL,NULL,NULL),
  ('Paul','Wall','Paul Wall',NULL,'6513480454','Networking','vagaro',1,'2022-04-02','Jason Patterson',NULL),
  ('Cheri','Southwick','Cheri Southwick',NULL,'6195178389','Not a Lead','vagaro',0,NULL,'Jason Patterson',NULL),
  ('Chris','Bowyer','Chris Bowyer',NULL,'8183900125','Not a Lead','vagaro',0,NULL,'Jason Patterson',NULL),
  ('Connor','C Fq10 Soccer','Connor C Fq10 Soccer',NULL,'8585006360','Not a Lead','vagaro',0,NULL,'Jason Patterson',NULL),
  ('Preston','Gable','Preston Gable',NULL,'8583427743','Not a Lead','vagaro',0,NULL,'Jason Patterson',NULL),
  ('Ava','Lawson','Ava Lawson',NULL,NULL,'Not a Lead','vagaro',0,NULL,NULL,NULL),
  ('Naavneet','Danda','Naavneet Danda',NULL,NULL,'Not a Lead','vagaro',0,NULL,NULL,NULL),
  ('Dianne','Patterson','Dianne Patterson','diannehouston@msn.com','6199943574','Not a Lead','vagaro',0,NULL,NULL,NULL),
  ('Duke','Ekstrom','Duke Ekstrom',NULL,'6197565287','Not a Lead','vagaro',230,NULL,'Jason Patterson',NULL),
  ('Amanda','Apgar','Amanda Apgar','amandaapgar1@gmail.com','9169178969','Not a Lead','vagaro',8,NULL,'Jason Patterson, Hollie Harris',NULL),
  ('Andy','Fq0','Andy Fq0',NULL,'8587901647','Not a Lead','vagaro',0,NULL,'Jason Patterson',NULL),
  ('Brady','Aiken','Brady Aiken',NULL,'6192012152','Not a Lead','vagaro',0,NULL,'Jason Patterson',NULL),
  ('Corey','Liuget','Corey Liuget',NULL,'3054581012','Not a Lead','vagaro',0,NULL,'Jason Patterson',NULL),
  ('Darren','Sproles','Darren Sproles',NULL,'9137478536','Not a Lead','vagaro',0,NULL,'Jason Patterson',NULL),
  ('George','Hardisty','George Hardisty',NULL,'5122949619','Not a Lead','vagaro',0,NULL,'Jason Patterson',NULL),
  ('Gerald','Mccoy','Gerald Mccoy',NULL,'4055930157','Not a Lead','vagaro',0,NULL,'Jason Patterson',NULL),
  ('Grant','Brittain','Grant Brittain',NULL,'6192439451','Not a Lead','vagaro',0,NULL,'Jason Patterson',NULL),
  ('Grant','Norberg','Grant Norberg',NULL,'8582086093','Not a Lead','vagaro',0,NULL,'Jason Patterson',NULL),
  ('Jake','FQ10','Jake FQ10',NULL,'5305748297','Not a Lead','vagaro',0,NULL,'Jason Patterson',NULL),
  ('James','McBride','James McBride','jamesmarkmcbride@icloud.com','7604107714','Not a Lead','vagaro',24,NULL,'Jason Patterson',NULL),
  ('Jared','Fq10','Jared Fq10',NULL,'6198475080','Not a Lead','vagaro',0,NULL,'Jason Patterson',NULL),
  ('Jason','Papliano','Jason Papliano',NULL,'3609035055','Not a Lead','vagaro',0,NULL,'Jason Patterson',NULL),
  ('Jeff','King','Jeff King',NULL,'6199485255','Not a Lead','vagaro',0,NULL,'Jason Patterson',NULL),
  ('Justin','Pugh','Justin Pugh',NULL,'2019788590','Not a Lead','vagaro',0,NULL,'Jason Patterson',NULL),
  ('Ko','Olinger','Ko Olinger',NULL,'2087409754','Not a Lead','vagaro',0,NULL,'Jason Patterson',NULL),
  ('Laura','Sams','Laura Sams','laura.martin1106@gmail.com','6192012311','Not a Lead','vagaro',26,'2021-08-03','Jason Patterson','3052 Palladian Lane'),
  ('Marie','Lemkul','Marie Lemkul','mlemkul@yahoo.com','7023013002','Not a Lead','vagaro',0,NULL,'Jason Patterson',NULL),
  ('Mary','Hollis','Mary Hollis',NULL,'8022331362','Not a Lead','vagaro',0,NULL,'Jason Patterson',NULL),
  ('max','Fq10','max Fq10',NULL,'6195407982','Not a Lead','vagaro',0,NULL,'Jason Patterson',NULL),
  ('Melvin','Gordon','Melvin Gordon',NULL,'6089574772','Not a Lead','vagaro',0,NULL,'Jason Patterson',NULL),
  ('Stephen','Gonsalvez','Stephen Gonsalvez',NULL,'7608153660','Not a Lead','vagaro',0,NULL,'Jason Patterson',NULL),
  ('Danel','Camarena','Danel Camarena',NULL,NULL,'Not a Lead','vagaro',10,NULL,'Jason Patterson',NULL),
  ('Charlie','Ekstrom','Charlie Ekstrom',NULL,NULL,'Not a Lead','vagaro',0,NULL,NULL,NULL),
  ('Jake','Carmen','Jake Carmen',NULL,NULL,'Not a Lead','vagaro',0,NULL,NULL,NULL),
  ('Wendy','Gumb','Wendy Gumb',NULL,'8582048286','Not a Lead','vagaro',0,NULL,NULL,NULL),
  ('Bradley','Benton','Bradley Benton',NULL,NULL,'Not a Lead','vagaro',0,NULL,NULL,NULL),
  ('Luke','Manors','Luke Manors',NULL,NULL,'Not a Lead','vagaro',0,NULL,NULL,NULL),
  ('Nick','Ole oak I','Nick Ole oak I',NULL,'8586633906','Not a Lead','vagaro',0,NULL,'Jason Patterson',NULL),
  ('Ty','Virgin','Ty Virgin',NULL,NULL,'Not a Lead','vagaro',0,NULL,NULL,NULL),
  ('Jordy','Deleon','Jordy Deleon',NULL,NULL,'Not a Lead','vagaro',0,NULL,NULL,NULL),
  ('Marco','Lopez','Marco Lopez',NULL,NULL,'Not a Lead','vagaro',0,NULL,NULL,NULL),
  ('Marguerite','Crump','Marguerite Crump',NULL,NULL,'Not a Lead','vagaro',0,NULL,NULL,NULL),
  ('Brandon','Ford','Brandon Ford',NULL,NULL,'Not a Lead','vagaro',0,NULL,NULL,NULL),
  ('Jason','Gilbert','Jason Gilbert',NULL,NULL,'Not a Lead','vagaro',0,NULL,NULL,NULL),
  ('Jason','Juadiness','Jason Juadiness',NULL,NULL,'Not a Lead','vagaro',0,NULL,NULL,NULL),
  ('Sandra','Hester','Sandra Hester',NULL,NULL,'Not a Lead','vagaro',0,NULL,NULL,NULL),
  ('Nancy','Labell','Nancy Labell',NULL,'7608030323','Not a Lead','vagaro',1,'2022-04-15','Jason Patterson',NULL),
  ('Mimi','Wright','Mimi Wright',NULL,NULL,'Not a Lead','vagaro',0,NULL,NULL,NULL),
  ('Jenifer','Perry','Jenifer Perry','matthew.perry@antherapies.com',NULL,'Not a Lead','vagaro',1,'2023-02-10','Jason Patterson',NULL),
  ('Cj','Ippolito','Cj Ippolito',NULL,NULL,'Not a Lead','vagaro',0,NULL,NULL,NULL),
  ('Peter','Madok','Peter Madok',NULL,NULL,'Not a Lead','vagaro',0,NULL,NULL,NULL),
  ('Alan','Joseph','Alan Joseph','gphckv8rgg@privaterelay.appleid.com','4255247022','Not a Lead','vagaro',1,NULL,'Jason Patterson',NULL),
  ('Daisy','Schell','Daisy Schell',NULL,NULL,'Not a Lead','vagaro',0,NULL,NULL,NULL),
  ('Jason','Patterson','Jason Patterson','pattersonjason7@gmail.com','6199371434','Not a Lead','vagaro',4,NULL,'Hollie Harris',NULL),
  ('Timothy','Paschal','Timothy Paschal','getright.mbs@gmail.com','9514380663','Not a Lead','vagaro',0,NULL,NULL,NULL),
  ('Jeremy','Patterson','Jeremy Patterson',NULL,'6192063722','Not a Lead','vagaro',0,NULL,NULL,NULL),
  ('Hollie','Harris','Hollie Harris','hollieharrisirl@gmail.com','8585311522','Not a Lead','vagaro',0,NULL,NULL,'1622 Meade Avenue'),
  ('Steven','Hinshaw','Steven Hinshaw',NULL,'8583362602','Online','vagaro',0,NULL,'Jason Patterson',NULL),
  ('Parker','Langenberg','Parker Langenberg',NULL,'8588866324','Online','vagaro',0,NULL,NULL,NULL),
  ('Melissa','Burton','Melissa Burton',NULL,NULL,'Online','vagaro',64,NULL,'Jason Patterson',NULL),
  ('Chris','Turtzo','Chris Turtzo',NULL,NULL,'Online','vagaro',0,NULL,NULL,NULL),
  ('Matty','Ice Erickson','Matty Ice Erickson',NULL,'7604841074','Personal Training','vagaro',0,NULL,'Jason Patterson',NULL),
  ('Albert','Aldava','Albert Aldava','albert.aldava@gmail.com','6198469450','Personal Training','vagaro',2,'2022-05-11','Jason Patterson',NULL),
  ('Vivian','Preclaro','Vivian Preclaro',NULL,NULL,'Personal Training','vagaro',0,NULL,NULL,NULL),
  ('Anya','Kirchhoff','Anya Kirchhoff',NULL,NULL,'Personal Training','vagaro',0,NULL,NULL,NULL),
  ('Enzo','Zumbro','Enzo Zumbro',NULL,'8582050243','Personal Training','vagaro',31,NULL,'Timothy Paschal',NULL),
  ('Stephanie','Rodriguez','Stephanie Rodriguez',NULL,'8582541503','Personal Training','vagaro',0,NULL,NULL,NULL),
  ('Janice','Crowell','Janice Crowell',NULL,'6198067590','Personal Training','vagaro',9,NULL,'Jason Patterson',NULL),
  ('Peyton','Witcher','Peyton Witcher',NULL,'8052668629','Personal Training','vagaro',18,'2025-04-10','Jason Patterson',NULL),
  ('Samantha','Stabb','Samantha Stabb',NULL,'8582044845','Personal Training','vagaro',18,NULL,'Jason Patterson',NULL),
  ('Donna','Steinbeck','Donna Steinbeck',NULL,'7608809931','Personal Training','vagaro',0,NULL,NULL,NULL),
  ('Timothy','Epps','Timothy Epps',NULL,NULL,'Personal Training','vagaro',0,NULL,NULL,NULL),
  ('Tevita','Mickelsen','Tevita Mickelsen',NULL,'6196096872','Personal Training','vagaro',18,NULL,'Timothy Paschal',NULL),
  ('Nancy','Grais','Nancy Grais',NULL,NULL,'Pilates','vagaro',205,NULL,'Jason Patterson',NULL),
  ('Andy','Cole','Andy Cole',NULL,'8023633712','Pilates','vagaro',0,NULL,'Jason Patterson',NULL),
  ('Cathy','Gross','Cathy Gross','catgr1953@gmail.com','6195072884','Pilates','vagaro',53,NULL,'Jason Patterson','11256 Normanton Court'),
  ('Madison','Jones','Madison Jones','madisonkaliejones@gmail.com','8583373292','Pilates','vagaro',0,NULL,NULL,NULL),
  ('Melissa','Eggleston','Melissa Eggleston',NULL,'6197948918','Pilates','vagaro',27,NULL,'Jason Patterson',NULL),
  ('Nancy','Madok','Nancy Madok',NULL,'18583536743','Pilates','vagaro',1,NULL,'Jason Patterson',NULL),
  ('Sophie','Ingles','Sophie Ingles',NULL,NULL,'Pilates','vagaro',0,NULL,NULL,NULL),
  ('Shelby','Smith','Shelby Smith',NULL,'7607037673','Pilates','vagaro',7,NULL,'Hollie Harris',NULL),
  ('Iris','Meyers','Iris Meyers',NULL,NULL,'Pilates','vagaro',0,NULL,NULL,NULL),
  ('Lisa','Corbisez','Lisa Corbisez',NULL,NULL,'Pilates','vagaro',0,NULL,NULL,NULL),
  ('Bridget','Trovillion','Bridget Trovillion','dantrovillion@gmail.com','8587353925','Personal Training','vagaro',124,'2024-11-22','Jason Patterson',NULL),
  ('Steve','Fisher','Steve Fisher','spfisher44@gmail.com','8584447846','Personal Training','vagaro',59,'2025-06-16','Jason Patterson',NULL),
  ('Matt','Yarling','Matt Yarling',NULL,NULL,'Personal Training','vagaro',0,NULL,NULL,NULL),
  ('Rich','Wilcox','Rich Wilcox',NULL,NULL,'Personal Training','vagaro',153,NULL,'Jason Patterson',NULL),
  ('Nicki','Ohrstrom','Nicki Ohrstrom','nohrstro@gmail.com','8589223254','Personal Training','vagaro',600,NULL,'Jason Patterson, Hollie Harris',NULL),
  ('An','Hong','An Hong','an@vinatechinc.com','8586993338','Personal Training','vagaro',287,NULL,'Jason Patterson',NULL),
  ('Delois','Bean','Delois Bean',NULL,'6199903408','Personal Training','vagaro',251,NULL,'Jason Patterson, Hollie Harris',NULL),
  ('Jim','Stepenosky','Jim Stepenosky','jestepenosky@gmail.com','6196657672','Personal Training','vagaro',54,'2025-05-21','Hollie Harris, Jason Patterson',NULL),
  ('Sarah','Slaughter','Sarah Slaughter',NULL,'6194178695','Personal Training','vagaro',290,NULL,'Jason Patterson',NULL),
  ('Diana','Skvarka','Diana Skvarka',NULL,'8584371810','Personal Training','vagaro',103,'2022-01-28','Jason Patterson',NULL),
  ('Rajanv Us','Yahoo.com','Rajanv Us Yahoo.com','rajanv_us@yahoo.com','8582121930','Personal Training','vagaro',1,NULL,'Jason Patterson',NULL),
  ('Rajan','Verma','Rajan Verma',NULL,'8582121930','Personal Training','vagaro',52,NULL,'Jason Patterson',NULL),
  ('Sarika','Dhawan','Sarika Dhawan',NULL,NULL,'Personal Training','vagaro',0,NULL,NULL,NULL),
  ('Amos','Meyers','Amos Meyers',NULL,'8587616557','Personal Training','vagaro',36,NULL,'Jason Patterson',NULL),
  ('Jerry','Zumbro','Jerry Zumbro',NULL,'8582050243','Personal Training','vagaro',142,NULL,'Jason Patterson, Hollie Harris',NULL),
  ('Frank','Muller','Frank Muller',NULL,'8589452649','Personal Training','vagaro',103,NULL,'Jason Patterson, Hollie Harris',NULL),
  ('Mark','Cumba','Mark Cumba',NULL,'6193061678','Personal Training','vagaro',6,NULL,'Jason Patterson, Timothy Paschal',NULL),
  ('Ryan','Childs','Ryan Childs',NULL,'6194058809','Personal Training','vagaro',161,NULL,'Hollie Harris, Jason Patterson',NULL),
  ('Robin','Sparkman','Robin Sparkman',NULL,'8582604027','Personal Training','vagaro',10,NULL,'Hollie Harris, Jason Patterson',NULL),
  ('Maverick','Lloyd','Maverick Lloyd','bwraay12@gmail.com','6195180416','Personal Training','vagaro',3,NULL,'Timothy Paschal',NULL),
  ('Matthew','Yarling','Matthew Yarling',NULL,'6193846986','Personal Training','vagaro',1,NULL,'Jason Patterson',NULL),
  ('Hannah','Stem','Hannah Stem',NULL,'8583376290',NULL,'marketing',0,NULL,NULL,NULL),
  ('Maureen','Mittry','Maureen Mittry','mmittry@eusd.org','6199947131',NULL,'marketing',0,NULL,NULL,NULL),
  ('Parker','Cathedral Soccer','Parker Cathedral Soccer',NULL,'8588866324',NULL,'marketing',0,NULL,NULL,NULL),
  ('Abruan','Torices','Abruan Torices',NULL,'6196068896','Jason Contact','jason_contacts',0,NULL,NULL,NULL),
  ('Haley','A','Haley A',NULL,'8586038801','Jason Contact','jason_contacts',0,NULL,NULL,NULL),
  ('Carole','Accountant','Carole Accountant',NULL,'7602719468','Jason Contact','jason_contacts',0,NULL,NULL,NULL),
  ('Christian','Barry','Christian Barry',NULL,'6198890268','Jason Contact','jason_contacts',0,NULL,NULL,NULL),
  ('Brock','Boser','Brock Boser',NULL,'5133834646','Jason Contact','jason_contacts',0,NULL,NULL,NULL),
  ('AJ','Bratlien','AJ Bratlien',NULL,'6199946403','Jason Contact','jason_contacts',0,NULL,NULL,NULL),
  ('Alex','Breidt','Alex Breidt',NULL,'6199715853','Jason Contact','jason_contacts',0,NULL,NULL,NULL),
  ('Briana','Hollenbeck','Briana Hollenbeck',NULL,'6192062013','Jason Contact','jason_contacts',0,NULL,NULL,NULL),
  ('Britt','Viboch','Britt Viboch',NULL,'8586028262','Jason Contact','jason_contacts',0,NULL,NULL,NULL),
  ('Josh','Burness','Josh Burness',NULL,'6199228683','Jason Contact','jason_contacts',0,NULL,NULL,NULL),
  ('Mary','Casas','Mary Casas',NULL,'6199566838','Jason Contact','jason_contacts',0,NULL,NULL,NULL),
  ('Becky','Castilla','Becky Castilla',NULL,'6262532189','Jason Contact','jason_contacts',0,NULL,NULL,NULL),
  ('Charleston','Delacruz','Charleston Delacruz',NULL,'6199954081','Jason Contact','jason_contacts',0,NULL,NULL,NULL),
  ('Chris FR Sorrento',NULL,'Chris FR Sorrento',NULL,'6615105697','Jason Contact','jason_contacts',0,NULL,NULL,NULL),
  ('Kaitlyn','Chrisco','Kaitlyn Chrisco',NULL,'6615997101','Jason Contact','jason_contacts',0,NULL,NULL,NULL),
  ('Jordan','Clark','Jordan Clark',NULL,'6193143763','Jason Contact','jason_contacts',0,NULL,NULL,NULL),
  ('Cody','Conner','Cody Conner',NULL,'6199726338','Jason Contact','jason_contacts',0,NULL,NULL,NULL),
  ('Colin','Dzubnar','Colin Dzubnar',NULL,'9498856647','Jason Contact','jason_contacts',0,NULL,NULL,NULL),
  ('Brad','Cornish','Brad Cornish',NULL,'6199935693','Jason Contact','jason_contacts',0,NULL,NULL,NULL),
  ('Karlton','Dennis','Karlton Dennis',NULL,'7142525822','Jason Contact','jason_contacts',0,NULL,NULL,NULL),
  ('Darien','Gasner','Darien Gasner',NULL,'6194549856','Jason Contact','jason_contacts',0,NULL,NULL,NULL),
  ('James','Doherty','James Doherty',NULL,'6198208949','Jason Contact','jason_contacts',0,NULL,NULL,NULL),
  ('Sammy','Dennis','Sammy Dennis',NULL,'7606000136','Jason Contact','jason_contacts',0,NULL,NULL,NULL),
  ('Jim','Daichendt','Jim Daichendt',NULL,'9493108400','Jason Contact','jason_contacts',0,NULL,NULL,NULL),
  ('Dalton','Pettus','Dalton Pettus',NULL,'6195171643','Jason Contact','jason_contacts',0,NULL,NULL,NULL),
  ('Chase','Daniels','Chase Daniels',NULL,'8173135487','Jason Contact','jason_contacts',0,NULL,NULL,NULL),
  ('Peter','Deluca','Peter Deluca',NULL,'6198131159','Jason Contact','jason_contacts',0,NULL,NULL,NULL),
  ('Denelle','Curry','Denelle Curry',NULL,'8589478435','Jason Contact','jason_contacts',0,NULL,NULL,NULL),
  ('Chris','Donlon','Chris Donlon',NULL,'7605755757','Jason Contact','jason_contacts',0,NULL,NULL,NULL),
  ('Nick','Enriguez','Nick Enriguez',NULL,'9096328404','Jason Contact','jason_contacts',0,NULL,NULL,NULL),
  ('Taylor','Fleury','Taylor Fleury',NULL,'6197339748','Jason Contact','jason_contacts',0,NULL,NULL,NULL),
  ('Kayla','Barber','Kayla Barber',NULL,'5592591664','Jason Contact','jason_contacts',0,NULL,NULL,NULL),
  ('Jodie','Oconnor','Jodie Oconnor',NULL,'7608151640','Jason Contact','jason_contacts',0,NULL,NULL,NULL),
  ('Sunny',NULL,'Sunny',NULL,'6193024444','Jason Contact','jason_contacts',0,NULL,NULL,NULL),
  ('Alyssa','Gianetti','Alyssa Gianetti',NULL,'7145988872','Jason Contact','jason_contacts',0,NULL,NULL,NULL),
  ('Jeremy','Gonzalez','Jeremy Gonzalez',NULL,'8583449548','Jason Contact','jason_contacts',0,NULL,NULL,NULL),
  ('Tali',NULL,'Tali',NULL,'6199948254','Jason Contact','jason_contacts',0,NULL,NULL,NULL),
  ('Garrett','Hath','Garrett Hath',NULL,'6194009456','Jason Contact','jason_contacts',0,NULL,NULL,NULL),
  ('Kenny','Heier','Kenny Heier',NULL,'6194025142','Jason Contact','jason_contacts',0,NULL,NULL,NULL),
  ('Andrew','Hougan','Andrew Hougan',NULL,'3086501150','Jason Contact','jason_contacts',0,NULL,NULL,NULL),
  ('Josh',NULL,'Josh',NULL,'6195520561','Jason Contact','jason_contacts',0,NULL,NULL,NULL),
  ('Katarina','Becker','Katarina Becker',NULL,'6196478449','Jason Contact','jason_contacts',0,NULL,NULL,NULL),
  ('Kyle','Gasner','Kyle Gasner',NULL,'6197299022','Jason Contact','jason_contacts',0,NULL,NULL,NULL),
  ('Kyle','O','Kyle O',NULL,'8587404692','Jason Contact','jason_contacts',0,NULL,NULL,NULL),
  ('Landon','Lozoya','Landon Lozoya',NULL,'6199224103','Jason Contact','jason_contacts',0,NULL,NULL,NULL),
  ('Bill','Lomdedico','Bill Lomdedico',NULL,'6197787690','Jason Contact','jason_contacts',0,NULL,NULL,NULL),
  ('Joey','Lomedico','Joey Lomedico',NULL,'6196724100','Jason Contact','jason_contacts',0,NULL,NULL,NULL),
  ('Alex','Klepper','Alex Klepper',NULL,'6192129111','Jason Contact','jason_contacts',0,NULL,NULL,NULL),
  ('Luis','Marriquin','Luis Marriquin',NULL,'6193224305','Jason Contact','jason_contacts',0,NULL,NULL,NULL),
  ('Michele','Boser','Michele Boser',NULL,'3475220070','Jason Contact','jason_contacts',0,NULL,NULL,NULL),
  ('Mckenna','Quinn','Mckenna Quinn',NULL,'6194026572','Jason Contact','jason_contacts',0,NULL,NULL,NULL),
  ('Cole','Tom','Cole Tom',NULL,'6199228348','Jason Contact','jason_contacts',0,NULL,NULL,NULL),
  ('Sima','Patel','Sima Patel',NULL,NULL,'Jason Contact','jason_contacts',0,NULL,NULL,NULL),
  ('Garrett','Landress','Garrett Landress',NULL,'8587740737','Jason Contact','jason_contacts',0,NULL,NULL,NULL),
  ('Reuben','Rosas','Reuben Rosas',NULL,'6198887134','Jason Contact','jason_contacts',0,NULL,NULL,NULL),
  ('Robbie',NULL,'Robbie',NULL,'6194384220','Jason Contact','jason_contacts',0,NULL,NULL,NULL),
  ('Roy','Richards','Roy Richards',NULL,'6195040922','Jason Contact','jason_contacts',0,NULL,NULL,NULL),
  ('Ryne','Provost','Ryne Provost',NULL,'6199472266','Jason Contact','jason_contacts',0,NULL,NULL,NULL),
  ('Saman','N','Saman N',NULL,'8587761457','Jason Contact','jason_contacts',0,NULL,NULL,NULL),
  ('Andi','Stem','Andi Stem',NULL,'8587221046','Jason Contact','jason_contacts',0,NULL,NULL,NULL),
  ('Tony','Skvarka','Tony Skvarka',NULL,'8584371809','Jason Contact','jason_contacts',0,NULL,NULL,NULL),
  ('Jirael','Hipplito','Jirael Hipplito',NULL,'4088931827','Jason Contact','jason_contacts',0,NULL,NULL,NULL),
  ('Patrick','Thunder','Patrick Thunder',NULL,'8589991783','Jason Contact','jason_contacts',0,NULL,NULL,NULL),
  ('Tim','Hu PT','Tim Hu PT',NULL,'8585279581','Jason Contact','jason_contacts',0,NULL,NULL,NULL),
  ('Tipton',NULL,'Tipton',NULL,'6192477261','Jason Contact','jason_contacts',0,NULL,NULL,NULL),
  ('Tyler','Stewart','Tyler Stewart',NULL,'6196722529','Jason Contact','jason_contacts',0,NULL,NULL,NULL),
  ('Brianna','Wray','Brianna Wray',NULL,'6195180416','Jason Contact','jason_contacts',0,NULL,NULL,NULL)
ON CONFLICT (lower(full_name), coalesce(phone,'')) DO NOTHING;
