import {redirect} from 'next/navigation';
import Link from 'next/link';
import {createClient} from '@/lib/supabase/server';
import {AppShell} from '@/components/layout/app-shell';
import {loadLeadWorkspace} from '@/lib/leads/queries';
import {allCatalogPages} from '@/lib/exercises/catalog';
import {actionableMessages,type StaffUnreadMessage} from '@/lib/messages/actionable';
import {ConversationList} from '@/components/messages/conversation-list';
import {RelationshipCommunications} from '@/components/messages/relationship-communications';
import type {OpportunityReview} from '@/lib/growth/model';
import {fuelDate} from '@/lib/fuel/model';
export const dynamic='force-dynamic';
export default async function MessagesPage(){const db=await createClient(),{data:{user}}=await db.auth.getUser();if(!user)redirect('/login');const {data:viewer,error:viewerError}=await db.from('profiles').select('role,deleted_at').eq('id',user.id).maybeSingle();if(viewerError||!viewer||viewer.deleted_at)redirect('/login');if(viewer.role==='client')redirect(`/messages/${user.id}`);if(!['owner','trainer'].includes(viewer.role))redirect('/dashboard');
 const assignedQ=viewer.role==='trainer'?await db.from('clients').select('id').eq('primary_trainer_id',user.id):{data:null,error:null};if(assignedQ.error)throw Error('Assigned client conversations could not be loaded.');const scopedIds=viewer.role==='trainer'?(assignedQ.data??[]).map((row:any)=>row.id):null,effectiveIds=scopedIds?.length?scopedIds:['00000000-0000-0000-0000-000000000000'];
 let recentQuery=db.from('messages').select('id,client_id,sender_id,body,created_at,read_at').order('created_at',{ascending:false}).order('id').limit(500);if(viewer.role==='trainer')recentQuery=recentQuery.in('client_id',effectiveIds);
 const [recentQ,unreadRows,clients,profiles,states]=await Promise.all([recentQuery,
  allCatalogPages<StaffUnreadMessage>((a,b)=>{let q=db.from('messages').select('id,client_id,sender_id,body,created_at,read_at',{count:'exact'}).is('read_at',null).order('id').range(a,b);if(viewer.role==='trainer')q=q.in('client_id',effectiveIds);return q;}),
  allCatalogPages<{id:string}>((a,b)=>{let q=db.from('clients').select('id',{count:'exact'}).order('id').range(a,b);if(viewer.role==='trainer')q=q.in('id',effectiveIds);return q;}),
  allCatalogPages<{id:string;full_name:string}>((a,b)=>{let q=db.from('profiles').select('id,full_name',{count:'exact'}).eq('role','client').is('deleted_at',null).order('id').range(a,b);if(viewer.role==='trainer')q=q.in('id',effectiveIds);return q;}),
  allCatalogPages<{client_id:string;archived_at:string|null}>((a,b)=>{let q=db.from('message_thread_state').select('client_id,archived_at',{count:'exact'}).order('client_id').range(a,b);if(viewer.role==='trainer')q=q.in('client_id',effectiveIds);return q;}),
 ]);if(recentQ.error)throw Error('Communications could not be loaded. Please refresh.');
 const names=new Map(profiles.map(p=>[p.id,p.full_name])),unread=actionableMessages(unreadRows,states).filter(m=>names.has(m.client_id)),unreadCounts=new Map<string,number>();for(const m of unread)unreadCounts.set(m.client_id,(unreadCounts.get(m.client_id)??0)+1);
 type Conversation={clientId:string;name:string;unread:number;last?:{body:string;created_at:string;fromClient:boolean}};const map=new Map<string,Conversation>();for(const c of clients)if(names.has(c.id))map.set(c.id,{clientId:c.id,name:names.get(c.id)!,unread:unreadCounts.get(c.id)??0});for(const m of recentQ.data??[]){const c=map.get(m.client_id);if(c&&!c.last)c.last={body:m.body,created_at:m.created_at,fromClient:m.sender_id===m.client_id};}
 const archived=new Set(states.filter(s=>s.archived_at&&!unreadCounts.has(s.client_id)).map(s=>s.client_id));const conversations=[...map.values()].filter(c=>!archived.has(c.clientId)).sort((a,b)=>Number(b.unread>0)-Number(a.unread>0)||(b.last?.created_at??'').localeCompare(a.last?.created_at??'')||a.name.localeCompare(b.name));
 // CRM unavailability must not erase an otherwise valid client inbox or appear as zero inquiries.
 let growth:Awaited<ReturnType<typeof loadLeadWorkspace>>|null=null,reviews:OpportunityReview[]=[];if(viewer.role==='owner'){try{[growth,reviews]=await Promise.all([loadLeadWorkspace(db),allCatalogPages<OpportunityReview>((a,b)=>db.from('growth_opportunity_reviews').select('*',{count:'exact'}).order('candidate_id').range(a,b) as any)]);}catch{growth=null;}}
 return <AppShell><main className="mx-auto w-full max-w-6xl space-y-5 pb-16"><header className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-widest text-sky">Communications</p><h1 className="mt-1 text-3xl font-bold">Inbox &amp; follow-ups</h1><p className="mt-2 text-sm text-cream-dim">{viewer.role==='trainer'?'Your assigned client conversations and unread coaching messages.':'Coach conversations, current inquiry follow-ups and unsent drafts. Different work queues—not one inflated inbox.'}</p></div><Link href="/messages/archived" className="inline-flex min-h-12 items-center rounded-xl border border-divider bg-white px-4 text-sm font-semibold text-sky">Archived conversations →</Link></header>
 <section aria-label="Communication overview" className="grid grid-cols-2 gap-3 sm:grid-cols-3"><div className="rounded-2xl border border-divider bg-white p-4"><p className="text-xs text-cream-faint">Incoming unread messages</p><p className="mt-2 text-3xl font-bold">{unread.length}</p></div><div className="rounded-2xl border border-divider bg-white p-4"><p className="text-xs text-cream-faint">Recent active conversations</p><p className="mt-2 text-3xl font-bold">{conversations.filter(c=>c.last).length}</p></div>{viewer.role==='owner'&&<Link href="/leads" className="rounded-2xl border border-sky/20 bg-sky/5 p-4"><p className="text-xs text-cream-faint">Current inquiries →</p><p className="mt-2 text-3xl font-bold">{growth?growth.open.length:'Unavailable'}</p></Link>}</section>
 <nav aria-label="Communication workspaces" className="flex flex-wrap gap-2"><a href="#conversations" className="inline-flex min-h-11 items-center rounded-xl border border-divider bg-white px-4 text-sm font-semibold text-sky">Client conversations</a>{viewer.role==='owner'&&<><a href="#relationship-followups" className="inline-flex min-h-11 items-center rounded-xl border border-divider bg-white px-4 text-sm font-semibold text-sky">Follow-ups &amp; unsent drafts</a><Link href="/leads" className="inline-flex min-h-11 items-center rounded-xl border border-divider bg-white px-4 text-sm font-semibold text-sky">New Business</Link><Link href="/contacts" className="inline-flex min-h-11 items-center rounded-xl border border-divider bg-white px-4 text-sm font-semibold text-sky">Contacts</Link></>}</nav>
 <ConversationList rows={conversations}/>
 {viewer.role==='owner'&&(growth?<RelationshipCommunications rows={[...growth.pipeline,...growth.contacts,...growth.research]} reviews={reviews} today={fuelDate()}/>:<p role="alert" className="rounded-2xl border border-status-moderate/40 bg-white p-5 text-sm">Business follow-up evidence is unavailable. The client inbox above remains available; no empty inquiry or draft counts were inferred.</p>)}
 <p className="text-xs leading-5 text-cream-faint">Conversation previews use the latest 500 messages. Incoming unread counts are checked separately; older history remains inside each client thread. New incoming unread messages reopen archived threads. Research candidates and historical contacts are not counted as new inquiries.</p></main></AppShell>;
}
