"use client";
import {useRef,useState} from 'react';
import {useRouter} from 'next/navigation';
import {Field,fieldClass,primaryClass,secondaryClass} from '@/components/fuel/controls';
import {acquisitionCommandSchema,validAcquisitionReceipt,reportWindow,trackedLink,type AcquisitionSource,type AcquisitionTask} from '@/lib/growth/acquisition/model';
import type {AcquisitionInsight} from '@/lib/growth/acquisition/insights';
export function useAcquisitionMutation(){const router=useRouter(),lock=useRef(false),pending=useRef<Record<string,unknown>|null>(null),ambiguous=useRef(false),done=useRef(false);const [busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(false),[error,setError]=useState<string|null>(null),[saved,setSaved]=useState(false);
 async function send(command:Record<string,unknown>){if(lock.current||done.current)return;lock.current=true;setBusy(true);setError(null);try{const response=await fetch('/api/growth/acquisition',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(command),signal:AbortSignal.timeout(65000)}),r=await response.json().catch(()=>null);
  if(!response.ok){if(response.status>=500||ambiguous.current){ambiguous.current=true;setUncertain(true);}else pending.current=null;setError(r?.error??'Save unconfirmed.');return;}
  const parsed=acquisitionCommandSchema.safeParse(command),valid=command.action==='refresh'?r?.ok===true&&r.request_id===command.request_id&&r.run?.id===command.request_id&&['completed','failed','pending'].includes(r.run.status):parsed.success&&validAcquisitionReceipt(r,parsed.data);
  if(!valid){ambiguous.current=true;setUncertain(true);setError('Incomplete receipt. Retry the exact request.');return;}
  if(command.action==='refresh'&&r.run.status==='pending'){ambiguous.current=true;setUncertain(true);setError('The refresh is still pending. Recover this same request; no new dispatch will be created.');return;}
  pending.current=null;done.current=true;setSaved(true);setUncertain(false);if(command.action==='refresh'&&r.run.status==='failed')setError('Refresh failed. Previous snapshots remain intact; inspect the connection and refresh history.');router.refresh();
 }catch{ambiguous.current=true;setUncertain(true);setError('Connection interrupted. Retry this same request before editing.');}finally{lock.current=false;setBusy(false);}}
 function submit(command:Record<string,unknown>){if(lock.current||pending.current||done.current)return;pending.current=command;void send(command);}
 return {submit,retry:()=>pending.current?send(pending.current):Promise.resolve(),busy,uncertain,error,saved,locked:busy||uncertain||saved};
}
export function AcquisitionFeedback({mutation}:{mutation:ReturnType<typeof useAcquisitionMutation>}){return <>{mutation.error&&<p role="alert" className="mt-3 rounded-xl border border-status-moderate/40 p-3 text-sm">{mutation.error}</p>}{mutation.uncertain&&<button className={secondaryClass+' mt-3'} disabled={mutation.busy} type="button" onClick={()=>void mutation.retry()}>Recover same request</button>}{mutation.saved&&!mutation.error&&<p role="status" className="mt-3 text-sm text-sky">Confirmed. No ad, message, profile post or payment was created.</p>}</>;}
export function SourceControls({source,today,runtimeReady}:{source:AcquisitionSource;today:string;runtimeReady:boolean}){const m=useAcquisitionMutation(),sync=useAcquisitionMutation(),[daily,setDaily]=useState(source.daily_sync),[brands,setBrands]=useState(source.brand_terms.join('\n')),[confirmed,setConfirmed]=useState(false),[window,setWindow]=useState<7|28|90>(28);return <div className="space-y-3"><div className="flex flex-wrap items-end gap-2"><Field label="Refresh reporting window"><select disabled={sync.locked} className={fieldClass} value={window} onChange={e=>setWindow(Number(e.target.value) as 7|28|90)}>{[7,28,90].map(n=><option key={n} value={n}>{n} completed days · 3-day reporting buffer</option>)}</select></Field><button type="button" className={primaryClass} disabled={!runtimeReady||sync.locked} onClick={()=>sync.submit({action:'refresh',request_id:crypto.randomUUID(),connector:source.connector,...reportWindow(today,window),source_read_confirmed:true})}>{sync.busy?'Reading source…':'Refresh this source'}</button></div><AcquisitionFeedback mutation={sync}/><details><summary className="min-h-11 cursor-pointer font-semibold text-sky">Source options</summary><form className="mt-3 space-y-3" onSubmit={e=>{e.preventDefault();m.submit({action:'source_options',request_id:crypto.randomUUID(),connector:source.connector,expected_revision:source.revision,daily_sync:daily,brand_terms:brands.split('\n').map(s=>s.trim()).filter(Boolean),confirmed});}}><fieldset disabled={m.locked} className="space-y-3"><legend className="sr-only">Source options</legend><Field label="IMS brand terms · one per line"><textarea className={fieldClass} rows={4} maxLength={1620} value={brands} onChange={e=>{setBrands(e.target.value);setConfirmed(false);}}/></Field><label className="flex min-h-12 items-start gap-3 text-sm leading-6"><input className="mt-1 h-5 w-5" type="checkbox" disabled={!runtimeReady&&!daily} checked={daily} onChange={e=>{setDaily(e.target.checked);setConfirmed(false);}}/>Refresh this source daily in production. Preview does not run the scheduler.</label><p className="text-xs leading-5 text-cream-dim">The scheduler requests a trailing 28-day snapshot at 15:00 UTC. No source writes, ads or AI generation. Report freshness also depends on Google and the connector cache. At most eight dispatches per source per 24 hours; interrupted requests count toward that limit.</p><label className="flex items-start gap-3 text-sm leading-6"><input className="mt-1 h-5 w-5" type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I reviewed the source identity and authorize these read-only options. Brand classification is a configurable label, not Google-provided intent.</label><button className={primaryClass} disabled={!confirmed}>Save source options</button></fieldset><AcquisitionFeedback mutation={m}/></form></details></div>;}
export function AcquisitionTaskEditor({task,insight}:{task?:AcquisitionTask;insight?:AcquisitionInsight}){const m=useAcquisitionMutation(),[title,setTitle]=useState(task?.title??insight?.title??''),[status,setStatus]=useState(task?.status??'planned'),[due,setDue]=useState(task?.due_on??''),[note,setNote]=useState(task?.note??insight?.next_step??'');const evidence=task?.evidence??insight?.evidence??'',ids=task?.snapshot_ids??insight?.snapshot_ids??[];return <form className="space-y-3" onSubmit={e=>{e.preventDefault();m.submit({action:'save_task',request_id:crypto.randomUUID(),task_id:task?.id??null,expected_revision:task?.revision??0,title,kind:task?.kind??insight?.kind??'measurement',evidence,snapshot_ids:ids,status,due_on:due||null,note});}}><fieldset disabled={m.locked} className="space-y-3"><legend className="sr-only">Internal acquisition task</legend><Field label="Action title"><input required minLength={5} maxLength={160} className={fieldClass} value={title} onChange={e=>setTitle(e.target.value)}/></Field><div className="grid gap-3 sm:grid-cols-2"><Field label="Internal status"><select className={fieldClass} value={status} onChange={e=>setStatus(e.target.value as AcquisitionTask['status'])}>{['planned','in_progress','done','dismissed'].map(s=><option key={s} value={s}>{s.replaceAll('_',' ')}</option>)}</select></Field><Field label="Target date"><input type="date" className={fieldClass} value={due} onChange={e=>setDue(e.target.value)}/></Field></div><Field label="Next step / actual outcome"><textarea rows={3} maxLength={2000} minLength={status==='done'?10:undefined} required={status==='done'} className={fieldClass} value={note} onChange={e=>setNote(e.target.value)}/></Field><p className="text-xs leading-5 text-cream-dim">Saves an internal task linked to the source snapshots. Completing a task does not publish content, change Google settings, submit conversions or claim a sale.</p><button className={primaryClass}>{task?'Save task update':'Save private action'}</button></fieldset><AcquisitionFeedback mutation={m}/></form>;}
export function TrackingLinkBuilder({hosts}:{hosts:string[]}){const [page,setPage]=useState(hosts[0]?'https://'+hosts[0]+'/':''),[campaign,setCampaign]=useState('gbp_profile'),[link,setLink]=useState(''),[error,setError]=useState('');return <section className="rounded-2xl border border-divider bg-white p-5"><h2 className="text-xl font-semibold">Prepare a traceable Business Profile link</h2><p className="mt-2 text-sm leading-6 text-cream-dim">Generate a tagged URL for a verified IMS website. Existing query parameters are removed. Copying it does not update Google or identify individual visitors.</p><form className="mt-4 space-y-3" onSubmit={e=>{e.preventDefault();try{setLink(trackedLink(page,hosts,campaign));setError('');}catch{setLink('');setError('Use a configured IMS website and a campaign label containing only lowercase letters, digits, underscores or hyphens.');}}}><Field label="Existing landing-page URL"><input className={fieldClass} type="url" required value={page} onChange={e=>{setPage(e.target.value);setLink('');}}/></Field><Field label="Campaign label"><input className={fieldClass} maxLength={64} value={campaign} onChange={e=>{setCampaign(e.target.value);setLink('');}}/></Field><button className={secondaryClass}>Generate draft link</button></form>{link&&<div className="mt-3 space-y-2"><p className="break-all rounded-xl bg-surface-soft p-3 text-sm">{link}</p><button className={secondaryClass} onClick={()=>void navigator.clipboard.writeText(link).then(()=>setError('Draft link copied. Nothing was published.')).catch(()=>setError('Clipboard unavailable. Select and copy the displayed link.'))}>Copy draft link</button></div>}{error&&<p role="status" className="mt-3 text-sm">{error}</p>}</section>;}
