import Link from 'next/link';
import {SOURCE_LABELS,metric,ratio,totalRow,reportOf,priorWindow,ownedPage,type AcquisitionSource,type AcquisitionReport,type Snapshot} from '@/lib/growth/acquisition/model';
import {acquisitionInsights} from '@/lib/growth/acquisition/insights';
import type {AcquisitionData} from '@/lib/growth/acquisition/server';
import {AcquisitionTaskEditor,SourceControls,TrackingLinkBuilder} from './controls';
import {SearchDemand} from './search-demand';
const panel='scroll-mt-24 space-y-4 rounded-3xl border border-divider bg-white p-5';
const format=(v:number|null)=>v===null?'Not available':new Intl.NumberFormat('en-US',{maximumFractionDigits:2}).format(v);
function Metric({label,value,prior,suffix=''}:{label:string;value:number|null;prior?:number|null;suffix?:string}){return <div className="min-w-0 rounded-2xl bg-surface-soft p-4"><p className="text-xs text-cream-faint">{label}</p><p className="mt-2 break-words text-2xl font-bold">{format(value)}{value===null?'':suffix}</p>{prior!==undefined&&<p className="mt-2 text-xs text-cream-dim">Previous: {format(prior)}{prior===null?'':suffix}</p>}</div>;}
function DetailsTable({report,source,label}:{report?:AcquisitionReport;source:AcquisitionSource;label:string}){if(!report)return <p className="text-sm text-cream-dim">{label}: not loaded.</p>;if(!report.rows.length)return <div role="status" className="rounded-xl bg-surface-soft p-4 text-sm"><p>{label}: {report.status==='empty'?'no rows returned':'unavailable'}.</p><p className="mt-2 text-xs leading-5">{report.note}</p></div>;return <details><summary className="min-h-12 cursor-pointer font-semibold text-sky">{label} · {report.rows.length} returned rows</summary><p className="my-3 text-xs leading-5 text-cream-dim">{report.note}</p><div className="max-h-[32rem] overflow-auto rounded-xl border border-divider"><table className="w-full min-w-[560px] text-left text-sm"><caption className="sr-only">{label} reported evidence</caption><thead><tr>{report.fields.filter(f=>!['account_id','search_type'].includes(f)).map(f=><th key={f} className="sticky top-0 border-b border-divider bg-white p-3 text-xs" scope="col">{f.replaceAll('_',' ')}</th>)}</tr></thead><tbody>{report.rows.map((r,i)=><tr key={i}>{report.fields.filter(f=>!['account_id','search_type'].includes(f)).map(f=>{const href=f==='page'?ownedPage(r[f],source.hosts):null;return <td key={f} className="max-w-80 break-words border-b border-divider p-3">{href?<a className="text-sky underline" href={href} target="_blank" rel="noreferrer">{String(r[f])} ↗</a>:r[f]===null?'Not reported':typeof r[f]==='number'?format(r[f]):String(r[f])}</td>;})}</tr>)}</tbody></table></div></details>;}
function SourceSummary({source,snapshot,today,runtimeReady,refreshKey}:{source:AcquisitionSource;snapshot?:Snapshot;today:string;runtimeReady:boolean;refreshKey:string}){const current=totalRow(snapshot),previous=totalRow(snapshot,'previous'),overview=reportOf(snapshot,'overview');const prior=snapshot?priorWindow(snapshot.payload.start,snapshot.payload.end):null;
 const daysOld=snapshot?Math.floor((Date.parse(today)-Date.parse(snapshot.payload.end))/86400000):null;
 return <section id={source.connector} className={panel}><header><p className="text-xs font-semibold uppercase tracking-wider text-sky">{SOURCE_LABELS[source.connector]}</p><h2 className="mt-2 break-words text-2xl font-bold">{source.label}</h2><p className="mt-2 break-all text-xs text-cream-faint">Account / property: {source.account_id}</p></header>
 {!snapshot?<p role="status" className="rounded-xl bg-surface-soft p-4 text-sm">Source registered; no snapshot has been saved. No zeros or success state were inferred.</p>:<><p className="text-sm">{snapshot.payload.start}–{snapshot.payload.end}{prior?` · Previous: ${prior.start}–${prior.end}`:''}</p><p className="text-xs leading-5 text-cream-dim">{source.connector==='searchconsole'?'Search Console dates follow its Pacific-time reporting convention.':'Dates follow the source account; its reporting timezone has not been independently verified.'} These panels are not a person-level cross-platform funnel.</p>{daysOld!==null&&daysOld>7&&<p role="status" className="text-sm text-status-moderate">Reporting period ends {daysOld} days before today. Refresh before acting on it.</p>}
 {source.connector==='searchconsole'&&<><div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Metric label="Web-search clicks" value={metric(current,'clicks')} prior={metric(previous,'clicks')}/><Metric label="Web-search impressions" value={metric(current,'impressions')} prior={metric(previous,'impressions')}/><Metric label="CTR · clicks / impressions" value={ratio(metric(current,'clicks'),metric(current,'impressions'))===null?null:ratio(metric(current,'clicks'),metric(current,'impressions'))!*100} prior={ratio(metric(previous,'clicks'),metric(previous,'impressions'))===null?null:ratio(metric(previous,'clicks'),metric(previous,'impressions'))!*100} suffix="%"/><Metric label="Reported average position" value={metric(current,'position')} prior={metric(previous,'position')}/></div><p className="text-xs leading-5 text-cream-dim">Web only; image/news/video data is not added to these cards. CTR is recomputed from its own numerator and denominator. Average position is source-reported, not a guaranteed local rank or an average of displayed query averages.</p></>}
 {source.connector==='googleanalytics4'&&<><div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Metric label="Sessions" value={metric(current,'sessions')} prior={metric(previous,'sessions')}/><Metric label="Engaged sessions" value={metric(current,'engaged_sessions')} prior={metric(previous,'engaged_sessions')}/><Metric label="Distinct total users" value={metric(current,'totalusers')} prior={metric(previous,'totalusers')}/><Metric label="GA4 key-event count · not clients" value={metric(current,'conversions')} prior={metric(previous,'conversions')}/></div>{!current&&<div role="status" className="rounded-xl border border-status-moderate/40 p-4"><h3 className="font-semibold">Website measurement needs verification</h3><p className="mt-2 text-sm leading-6">{overview?.status==='empty'?'The connected GA4 account returned no summary rows.':'The property summary is unavailable.'} This is not proof of zero visitors. Check the intended property and web stream, the collected hostname, tag installation, consent settings and Realtime. A property named after an old domain may still be valid; do not rename or replace it without checking.</p></div>}<p className="text-xs leading-5 text-cream-dim">Users are non-additive across breakdowns. Key events are the account&apos;s configured event counts, not verified leads, consultations or payments.</p></>}
 {source.connector==='google_my_business'&&<><div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Metric label="Website button clicks" value={metric(current,'website_clicks')} prior={metric(previous,'website_clicks')}/><Metric label="Directions requests · not visits" value={metric(current,'direction_requests')} prior={metric(previous,'direction_requests')}/><Metric label="Call button clicks · not calls answered" value={metric(current,'call_clicks')} prior={metric(previous,'call_clicks')}/><Metric label="Reserve with Google bookings" value={metric(current,'business_bookings')} prior={metric(previous,'business_bookings')}/></div><div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[['impressions_desktop_maps','Maps · desktop impressions'],['impressions_mobile_maps','Maps · mobile impressions'],['impressions_desktop_search','Search · desktop impressions'],['impressions_mobile_search','Search · mobile impressions']].map(([field,label])=><Metric key={field} label={label} value={metric(current,field)} prior={metric(previous,field)}/>)}</div><p className="text-xs leading-5 text-cream-dim">Surface/device impressions are not deduplicated reach across Google. Directions are not gym visits, call clicks are not answered calls, and Google bookings are not Coach OS appointments.</p><div className="grid gap-3 sm:grid-cols-2"><Metric label="Lifetime profile review count · at retrieval" value={metric(totalRow(snapshot,'profile'),'review_total_count')}/><Metric label="Lifetime average rating · out of 5" value={metric(totalRow(snapshot,'profile'),'review_average_rating_total')}/></div></>}
 <p className="text-xs leading-5 text-cream-faint">Observed by {snapshot.origin==='connector_import'?'authorized connector import':'the app refresh'} at {snapshot.payload.observed_at}. Upstream cache/finalization may differ; no upstream freshness timestamp was supplied. Source report status: {overview?.status??'not loaded'}.</p><a className="inline-flex min-h-11 items-center text-sm font-semibold text-sky" href={`/api/growth/acquisition/export?source=${source.connector}`}>Download this private evidence snapshot →</a>
 </>}
 <SourceControls key={source.revision+':'+(snapshot?.id??'empty')+':'+refreshKey} source={source} today={today} runtimeReady={runtimeReady}/>
 </section>;
}
export function AcquisitionWorkspace({data,today}:{data:AcquisitionData;today:string}){const get=(source:string)=>data.snapshots.find(s=>s.connector===source),search=data.sources.find(s=>s.connector==='searchconsole'),ga=data.sources.find(s=>s.connector==='googleanalytics4'),gbp=data.sources.find(s=>s.connector==='google_my_business'),insights=acquisitionInsights(data.sources,data.snapshots);return <main className="mx-auto w-full max-w-6xl space-y-5 pb-20"><header className="rounded-3xl bg-band p-6 text-white"><p className="text-xs font-semibold uppercase tracking-widest text-white/65">IMS / Acquisition Intelligence</p><h1 className="mt-2 text-3xl font-bold sm:text-4xl">Search. Website. Local discovery.</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-white/80">One place to inspect real Google evidence, identify measurement gaps and plan the next growth action. No purchased lists, automatic ad spend or invented conversion funnel.</p><div className="mt-4 flex flex-wrap gap-4"><Link className="inline-flex min-h-11 items-center font-semibold" href="/growth">← Growth Center</Link><Link className="inline-flex min-h-11 items-center font-semibold" href="/leads">Real inquiries →</Link><Link className="inline-flex min-h-11 items-center font-semibold" href="/leads/research">Partnership research →</Link></div></header>
 <nav aria-label="Acquisition sections" className="flex flex-wrap gap-2">{[['#actions','Next actions'],['#searchconsole','Search performance'],['#search-demand','Search demand'],['#googleanalytics4','Website measurement'],['#google_my_business','Business Profile'],['#connection','Connection & history']].map(([href,label])=><a className="inline-flex min-h-11 items-center rounded-xl border border-divider bg-white px-3 text-sm font-semibold text-sky" href={href} key={href}>{label}</a>)}</nav>
 <section id="actions" className={panel}><h2 className="text-2xl font-semibold">What to do next</h2><p className="text-sm leading-6 text-cream-dim">Versioned, deterministic evidence rules—not an AI promise of more clients. Each action keeps the source snapshots that support it. New suggestions are unsaved until you choose to keep one.</p>{insights.map(item=><article className="rounded-2xl bg-surface-soft p-4" key={item.key}><p className="text-xs font-semibold uppercase text-sky">{item.priority} priority · {item.kind}</p><h3 className="mt-2 text-lg font-semibold">{item.title}</h3><p className="mt-2 text-sm leading-6">{item.evidence}</p><p className="mt-2 text-sm leading-6 text-cream-dim">{item.next_step}</p><details className="mt-3"><summary className="min-h-11 cursor-pointer font-semibold text-sky">Turn this into a private action</summary><AcquisitionTaskEditor key={item.key+':'+data.tasks.length} insight={item}/></details></article>)}{!insights.length&&<p className="text-sm text-cream-dim">No source-backed suggestions yet. A missing report is not a reason to invent opportunities.</p>}</section>
 {data.sources.map(source=><SourceSummary key={source.connector} source={source} snapshot={get(source.connector)} today={today} runtimeReady={data.runtimeReady} refreshKey={data.refreshes.filter(r=>r.connector===source.connector).map(r=>r.id+':'+r.status).join(',')}/>)}
 {search&&<><SearchDemand report={reportOf(get('searchconsole'),'queries')} brandTerms={search.brand_terms}/><section className={panel}><h2 className="text-xl font-semibold">Search landing pages</h2><DetailsTable label="Original page URLs and their search metrics" report={reportOf(get('searchconsole'),'pages')} source={search}/></section></>}
 {ga&&<section className={panel}><h2 className="text-xl font-semibold">Website acquisition &amp; event evidence</h2><DetailsTable label="Collected hostnames" report={reportOf(get('googleanalytics4'),'hosts')} source={ga}/><DetailsTable label="Session source / medium" report={reportOf(get('googleanalytics4'),'channels')} source={ga}/><DetailsTable label="Landing pages" report={reportOf(get('googleanalytics4'),'pages')} source={ga}/><DetailsTable label="Event names and key-event counts" report={reportOf(get('googleanalytics4'),'events')} source={ga}/></section>}
 {gbp&&<TrackingLinkBuilder hosts={gbp.hosts}/>}
 <section className={panel}><h2 className="text-xl font-semibold">Saved acquisition actions</h2>{data.tasks.length?data.tasks.sort((a,b)=>b.updated_at.localeCompare(a.updated_at)).map(task=><details key={task.id+':'+task.revision} className="rounded-xl border border-divider p-4"><summary className="min-h-11 cursor-pointer font-semibold">{task.title} · {task.status.replaceAll('_',' ')}{task.due_on?' · '+task.due_on:''}</summary><p className="my-3 text-sm leading-6 text-cream-dim">{task.evidence}</p><AcquisitionTaskEditor task={task}/></details>):<p className="text-sm text-cream-dim">No actions saved yet. Suggestions above have not changed any external system.</p>}</section>
 <section id="connection" className={panel}><h2 className="text-xl font-semibold">Connection &amp; refresh status</h2><div className="rounded-xl bg-sky/5 p-4"><p className="font-semibold">{data.runtimeReady?'App refresh credential configured · verify a real read':'Saved source evidence available · app refresh not connected yet'}</p><p className="mt-2 text-sm leading-6 text-cream-dim">The Google accounts connected in ChatGPT do not automatically transfer their credentials into Coach OS. Server refresh uses a dedicated Windsor connection. The runtime only checks credential presence here; this is not proof that a live read succeeded.</p>{!data.runtimeReady&&<p className="mt-2 text-sm leading-6">For direct app refresh, securely set WINDSOR_API_KEY in the intended Vercel environment. Never paste it in chat or place it in a NEXT_PUBLIC variable. Manual snapshots already saved here remain reviewable without it. Daily synchronization remains off until an owner enables it.</p>}</div><p className="text-sm leading-6">Google Ads is intentionally disconnected while account security verification is pending. No attempts to bypass it, publish ads or upload conversions are included. Search queries, GA4 sessions, Business Profile actions and Coach OS inquiries remain separate populations.</p><div className="space-y-2">{data.refreshes.map(r=><article className="rounded-xl border border-divider p-3" key={r.id}><p className="text-sm font-semibold">{SOURCE_LABELS[r.connector]} · {r.status}</p><p className="mt-1 text-xs text-cream-faint">{r.start_on}–{r.end_on} · requested {r.created_at}</p>{r.error_code&&<p className="mt-1 text-xs text-status-moderate">{r.error_code.replaceAll('_',' ')} · previous snapshots preserved</p>}</article>)}</div><p className="text-xs leading-5 text-cream-dim">Shows the last 12 app refresh attempts. Connector-import snapshots are not fabricated app refreshes. Snapshot status and row coverage must still be reviewed even after a refresh completes.</p></section>
 </main>;}
