import {redirect} from "next/navigation";
import Link from "next/link";
import {AppShell} from "@/components/layout/app-shell";
import {createClient} from "@/lib/supabase/server";
import {ClassTemplateForm} from "@/components/classes/class-template-form";
import {ClassSeriesForm} from "@/components/classes/class-series-form";
export const dynamic="force-dynamic";
export default async function StaffClassesPage(){
 const db=await createClient();const {data:{user}}=await db.auth.getUser();if(!user)redirect("/login?next=/classes/manage");
 const me=await db.from("profiles").select("role,deleted_at").eq("id",user.id).maybeSingle();if(me.error)throw new Error("Class authorization unavailable.");if(!me.data||me.data.deleted_at||!["owner","trainer"].includes(me.data.role))redirect("/dashboard");
 const owner=me.data.role==="owner";
 let datesQuery=db.from("class_occurrences").select("id,template_id,trainer_id,starts_at,ends_at,capacity,status,location").gte("starts_at",new Date().toISOString()).order("starts_at").limit(81);
 if(!owner)datesQuery=datesQuery.eq("trainer_id",user.id);
 const [templatesQ,occQ,staffQ]=await Promise.all([
  db.from("class_templates").select("id,name,category,duration_minutes,capacity,visibility,location").order("name").limit(201),datesQuery,
  db.from("profiles").select("id,full_name").in("role",["owner","trainer"]).is("deleted_at",null).order("full_name"),
 ]);
 if(templatesQ.error||occQ.error||staffQ.error)throw new Error("Class operations could not be loaded. No empty roster was substituted.");
 const dates=(occQ.data??[]).slice(0,80),ids=dates.map(c=>c.id);
 const enrollQ=ids.length?await db.from("class_enrollments").select("occurrence_id,status").in("occurrence_id",ids).in("status",["booked","waitlisted"]).limit(1001):{data:[],error:null};
 const countsUnavailable=!!enrollQ.error||(enrollQ.data??[]).length>1000,counts=new Map<string,{booked:number;waitlisted:number}>();
 if(!countsUnavailable)for(const e of enrollQ.data??[]){const count=counts.get(e.occurrence_id)??{booked:0,waitlisted:0};if(e.status==="booked")count.booked++;else count.waitlisted++;counts.set(e.occurrence_id,count);}
 const templates=(templatesQ.data??[]).slice(0,200),names=new Map(templates.map(t=>[t.id,t])),coaches=new Map((staffQ.data??[]).map(t=>[t.id,t.full_name]));
 return <AppShell><div className="mx-auto w-full max-w-6xl space-y-5 pb-12"><header className="rounded-3xl bg-band p-6 text-white"><p className="text-xs uppercase tracking-widest text-white/60">IMS / Group coaching · Prelaunch</p><h1 className="mt-2 text-4xl font-bold">Class Operations</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-white/75">Build the offering, assign coaches and prepare class programs. Class credits and trainer compensation remain separate systems.</p></header>
 {owner&&<><Link href="/classes/manage/launch" className="block rounded-2xl border border-sky/30 bg-sky/5 p-5"><h2 className="text-xl font-semibold text-sky">Owner class-launch control →</h2><p className="mt-2 text-sm leading-6 text-cream-dim">Inspect configuration evidence and unresolved launch checks. Built does not mean released, paid or payroll-approved.</p></Link><ClassTemplateForm/><ClassSeriesForm templates={templates.filter(t=>t.visibility==="private").map(t=>({id:t.id,name:t.name}))} trainers={(staffQ.data??[]).map(t=>({id:t.id,name:t.full_name}))}/></>}
 <section className="rounded-3xl border border-divider bg-white p-5"><h2 className="text-xl font-semibold">Class templates and programs</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{templates.map(t=><article key={t.id} className="rounded-2xl bg-surface-soft p-4"><p className="text-xs font-semibold uppercase text-sky">{t.category} · {t.visibility}</p><Link href={`/classes/manage/templates/${t.id}`} className="mt-2 block text-lg font-semibold hover:text-sky">{t.name} →</Link><p className="mt-2 text-xs text-cream-dim">{t.duration_minutes} min · planned capacity {t.capacity}{t.location?` · ${t.location}`:""}</p></article>)}</div>{!templates.length&&<p className="mt-3 text-sm text-cream-dim">No templates yet.</p>}{(templatesQ.data??[]).length>200&&<p role="alert" className="mt-3 text-sm text-status-limited">Only the first 200 templates are shown.</p>}</section>
 <section className="rounded-3xl border border-divider bg-white p-5"><h2 className="text-xl font-semibold">{owner?"Upcoming class operations":"My assigned class dates"}</h2><div className="mt-4 divide-y divide-divider">{dates.map(o=>{const template=names.get(o.template_id),count=counts.get(o.id)??{booked:0,waitlisted:0};return <article key={o.id} className="flex flex-wrap items-start justify-between gap-3 py-4"><div><Link href={`/classes/manage/${o.id}`} className="font-semibold hover:text-sky">{template?.name??"Class template outside loaded catalog"} →</Link><p className="mt-1 text-xs text-cream-dim">{new Date(o.starts_at).toLocaleString("en-US",{timeZone:"America/Los_Angeles",weekday:"short",month:"short",day:"numeric",hour:"numeric",minute:"2-digit"})} · {o.status} · {coaches.get(o.trainer_id)??"Coach unavailable"}</p>{template?.visibility==="private"&&<p className="mt-1 text-xs text-sky">Private class planning—not client registration</p>}</div>{countsUnavailable?<p role="alert" className="text-xs text-status-limited">Roster counts unavailable or incomplete</p>:<p className="text-xs text-cream-dim">{count.booked} booked / {o.capacity} capacity · {count.waitlisted} waitlisted</p>}</article>;})}</div>{!dates.length&&<p className="mt-3 text-sm text-cream-dim">No future class dates in this loaded window.</p>}<p className="mt-3 text-xs text-cream-faint">Up to 80 future class dates and 1,000 enrollment rows. {(occQ.data??[]).length>80?"Additional dates exist beyond this window.":""}</p></section>
 <aside className="rounded-2xl border border-sky/20 bg-sky/5 p-5"><h2 className="font-semibold">Launch boundary</h2><p className="mt-2 text-sm leading-6 text-cream-dim">Building this infrastructure does not announce a class, charge a client, consume a training package, or create trainer payroll. Registration is deliberately held while occurrence publication, shared schedule locks, class entitlement and waitlist consent are verified.</p></aside></div></AppShell>;
}
