import {redirect} from 'next/navigation';
import Link from 'next/link';
import {AppShell} from '@/components/layout/app-shell';
import {createClient} from '@/lib/supabase/server';
import {allCatalogPages} from '@/lib/exercises/catalog';
import {StaffProfileEditor,StaffOperationsForm,CoachingAssignments,type StaffOperations} from '@/components/staff/people-editors';
export const dynamic='force-dynamic';
export default async function StaffControlPage(){const db=await createClient(),{data:{user}}=await db.auth.getUser();if(!user)redirect('/login?next=/staff');const me=await db.from('profiles').select('role,deleted_at').eq('id',user.id).maybeSingle();if(me.error||me.data?.role!=='owner'||me.data.deleted_at)redirect('/dashboard');
 const [people,ops,rules,availability,clients,names]=await Promise.all([
  allCatalogPages<{id:string;full_name:string;email:string|null;phone:string|null;role:string;deleted_at:string|null;updated_at:string}>((a,b)=>db.from('profiles').select('id,full_name,email,phone,role,deleted_at,updated_at',{count:'exact'}).in('role',['owner','trainer']).order('id').range(a,b)),
  allCatalogPages<StaffOperations>((a,b)=>db.from('staff_operations').select('staff_id,staff_status,operational_owner,responsibilities,notes,updated_at',{count:'exact'}).order('staff_id').range(a,b)),
  allCatalogPages<{trainer_id:string;compensation_type:string;provider:string|null;provider_employee_id:string|null;effective_from:string}>((a,b)=>db.from('trainer_compensation_rules').select('id,trainer_id,compensation_type,provider,provider_employee_id,effective_from',{count:'exact'}).eq('active',true).order('id').range(a,b)),
  allCatalogPages<{trainer_id:string;id:string}>((a,b)=>db.from('trainer_availability_rules').select('trainer_id,id',{count:'exact'}).eq('active',true).order('id').range(a,b)),
  allCatalogPages<{id:string;primary_trainer_id:string|null;updated_at:string}>((a,b)=>db.from('clients').select('id,primary_trainer_id,updated_at',{count:'exact'}).order('id').range(a,b)),
  allCatalogPages<{id:string;full_name:string}>((a,b)=>db.from('profiles').select('id,full_name',{count:'exact'}).eq('role','client').is('deleted_at',null).order('id').range(a,b)),
 ]);
 const operations=new Map(ops.map(o=>[o.staff_id,o])),clientNames=new Map(names.map(p=>[p.id,p.full_name]));
 const coaches=people.map(p=>({id:p.id,full_name:p.full_name,eligible:!p.deleted_at&&!['inactive','leave'].includes(operations.get(p.id)?.staff_status??'active')}));
 const assigned=clients.filter(c=>clientNames.has(c.id)).map(c=>({...c,full_name:clientNames.get(c.id)!})).sort((a,b)=>a.full_name.localeCompare(b.full_name));
 return <AppShell expectedRole="owner"><main className="mx-auto w-full max-w-6xl space-y-5 pb-16"><header className="rounded-3xl bg-band p-6 text-white"><p className="text-xs uppercase tracking-widest text-white/60">IMS / People &amp; Coaching</p><h1 className="mt-2 text-4xl font-bold">Staff Control Center</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-white/75">Edit contact details, operating ownership and client coaching assignments. Authentication roles, calendar bookings and compensation stay separate.</p><div className="mt-4 flex flex-wrap gap-4"><a href="#coaching-ownership" className="inline-flex min-h-11 items-center font-semibold">Client coaching ownership →</a><Link href="/settings/staff" className="inline-flex min-h-11 items-center font-semibold">Staff onboarding tools →</Link></div></header>
 <section className="grid gap-4 md:grid-cols-2">{people.sort((a,b)=>a.full_name.localeCompare(b.full_name)).map(person=>{const o=operations.get(person.id),matches=rules.filter(r=>r.trainer_id===person.id),n=availability.filter(a=>a.trainer_id===person.id).length;return <article key={person.id} className="rounded-3xl border border-divider bg-white p-5"><h2 className="text-lg font-semibold">{person.full_name}</h2><p className="mt-1 text-xs text-cream-faint">{person.email??'Login email unavailable'} · {person.role}</p><div className="mt-4 grid grid-cols-2 gap-3">{[['Operating status',person.deleted_at?'Disabled account':o?.staff_status??'Not recorded'],['Operational owner',o?.operational_owner||'Not assigned'],['Availability rules',String(n)],['Provider mapping',matches.length===1?(matches[0].provider_employee_id?'Provider record mapped':'Not verified'):matches.length?'Multiple active rules · review Payroll Center':'Not configured'],['Assigned clients',String(assigned.filter(c=>c.primary_trainer_id===person.id).length)]].map(([label,value])=><div key={label} className="rounded-xl bg-surface-soft p-3"><p className="text-xs text-cream-faint">{label}</p><p className="mt-1 text-sm font-semibold">{value}</p></div>)}</div>{person.deleted_at?<p className="mt-4 text-sm text-cream-dim">Disabled accounts cannot be edited or assigned through this workspace.</p>:<><StaffProfileEditor key={'profile:'+person.updated_at} person={person}/><StaffOperationsForm key={'ops:'+(o?.updated_at??'new')} staffId={person.id} operations={o}/></>}</article>;})}</section>
 <CoachingAssignments clients={assigned} coaches={coaches}/>
 <section className="rounded-2xl border border-sky/20 bg-sky/5 p-5"><h2 className="font-semibold">Control boundaries</h2><p className="mt-2 text-sm leading-6 text-cream-dim">Role controls application access. Staff status and responsibilities describe operations. Compensation rules describe proposed payroll calculations. Provider mapping identifies a future external employee record. None of these states silently changes another.</p><div className="mt-3 flex flex-wrap gap-4"><Link href="/reports/payroll" className="inline-flex min-h-11 items-center text-sm font-semibold text-sky">Payroll Center →</Link><Link href="/capacity" className="inline-flex min-h-11 items-center text-sm font-semibold text-sky">Capacity →</Link><Link href="/schedule/integrity" className="inline-flex min-h-11 items-center text-sm font-semibold text-sky">Schedule integrity →</Link></div></section></main></AppShell>;
}
