import Link from "next/link";
import {redirect} from "next/navigation";
import {AlertTriangle,ArrowRight,CalendarClock,Clock3,Users} from "lucide-react";
import {AppShell} from "@/components/layout/app-shell";
import {createClient} from "@/lib/supabase/server";
import {buildTrainerCapacity} from "@/lib/coaching/capacity";
import {pacificWeek} from "@/lib/time/pacific";

export const dynamic="force-dynamic";
const hours=(minutes:number)=>minutes%60===0?`${minutes/60}h`:`${Math.floor(minutes/60)}h ${minutes%60}m`;

export default async function CapacityPage(){
 const db=await createClient();const {data:{user}}=await db.auth.getUser();if(!user)redirect("/login?next=/capacity");
 const me=await db.from("profiles").select("role,deleted_at").eq("id",user.id).maybeSingle();if(me.error||me.data?.role!=="owner"||me.data.deleted_at)redirect("/dashboard");
 const now=new Date(),week=pacificWeek(now);
 const [staffQ,rulesQ,blocksQ,sessionsQ]=await Promise.all([
  db.from("profiles").select("id,full_name,role").in("role",["owner","trainer"]).is("deleted_at",null).order("full_name"),
  db.from("trainer_availability_rules").select("trainer_id,weekday,start_time,end_time,active").eq("active",true),
  db.from("trainer_time_blocks").select("trainer_id,starts_at,ends_at").lt("starts_at",week.end.toISOString()).gt("ends_at",week.start.toISOString()),
  db.from("sessions").select("trainer_id,scheduled_at,duration_minutes,status").gte("scheduled_at",week.start.toISOString()).lt("scheduled_at",week.end.toISOString()).neq("status","cancelled").neq("status","late_cancelled"),
 ]);
 if([staffQ,rulesQ,blocksQ,sessionsQ].some(q=>q.error))throw new Error("Capacity evidence is unavailable. Coach OS did not infer open hours from partial data.");
 const staff=staffQ.data??[],capacity=buildTrainerCapacity(now,rulesQ.data??[],blocksQ.data??[],sessionsQ.data??[]),byTrainer=new Map(capacity.map(c=>[c.trainer_id,c]));
 const totals=capacity.reduce((a,c)=>({declared:a.declared+c.declared_minutes,blocked:a.blocked+c.blocked_minutes,usable:a.usable+c.usable_minutes,booked:a.booked+c.booked_minutes,open:a.open+c.open_minutes,outside:a.outside+c.outside_declared_sessions}),{declared:0,blocked:0,usable:0,booked:0,open:0,outside:0});
 return <AppShell expectedRole="owner"><main className="mx-auto flex w-full max-w-6xl flex-col gap-5 pb-12">
  <header className="rounded-3xl bg-gradient-to-br from-[#121922] via-[#172536] to-[#225a80] p-6 text-white sm:p-8"><p className="text-[11px] font-semibold uppercase tracking-[.22em] text-white/60">IMS / Capacity & retention</p><h1 className="mt-2 text-4xl font-bold">Declared coaching capacity</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-white/75">This week’s trainer availability, blocked time and booked training—calculated from explicit schedule evidence. It is not a staffing recommendation or revenue forecast.</p></header>
  <section className="grid grid-cols-2 gap-3 sm:grid-cols-5"><div className="rounded-2xl border border-divider bg-white p-4"><Clock3 className="h-5 w-5 text-sky"/><p className="mt-3 text-3xl font-bold text-cream">{hours(totals.declared)}</p><p className="text-xs text-cream-faint">declared availability</p></div><div className="rounded-2xl border border-divider bg-white p-4"><CalendarClock className="h-5 w-5 text-sky"/><p className="mt-3 text-3xl font-bold text-cream">{hours(totals.blocked)}</p><p className="text-xs text-cream-faint">blocked inside availability</p></div><div className="rounded-2xl border border-divider bg-white p-4"><Users className="h-5 w-5 text-sky"/><p className="mt-3 text-3xl font-bold text-cream">{hours(totals.booked)}</p><p className="text-xs text-cream-faint">booked inside availability</p></div><div className="rounded-2xl border border-divider bg-white p-4"><Clock3 className="h-5 w-5 text-sky"/><p className="mt-3 text-3xl font-bold text-cream">{hours(totals.open)}</p><p className="text-xs text-cream-faint">open declared time</p></div><div className="rounded-2xl border border-divider bg-white p-4"><AlertTriangle className="h-5 w-5 text-sky"/><p className="mt-3 text-3xl font-bold text-cream">{totals.outside}</p><p className="text-xs text-cream-faint">sessions outside declared hours</p></div></section>
  <section className="grid gap-4 md:grid-cols-2">{staff.map(person=>{const c=byTrainer.get(person.id);return <article key={person.id} className="rounded-3xl border border-divider bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><h2 className="text-lg font-semibold text-cream">{person.full_name}</h2><p className="mt-1 text-xs capitalize text-cream-faint">{person.role}</p></div><Link href={`/schedule?trainer=${person.id}`} className="inline-flex min-h-11 items-center gap-1 text-sm font-semibold text-sky">Schedule <ArrowRight className="h-4 w-4"/></Link></div>{c?<><div className="mt-4 grid grid-cols-2 gap-2"><div className="rounded-xl bg-surface-soft p-3"><p className="text-xl font-bold text-cream">{hours(c.usable_minutes)}</p><p className="text-[11px] text-cream-faint">usable after blocks</p></div><div className="rounded-xl bg-surface-soft p-3"><p className="text-xl font-bold text-cream">{hours(c.booked_minutes)}</p><p className="text-[11px] text-cream-faint">booked in declared hours</p></div><div className="rounded-xl bg-surface-soft p-3"><p className="text-xl font-bold text-cream">{hours(c.open_minutes)}</p><p className="text-[11px] text-cream-faint">open declared time</p></div><div className="rounded-xl bg-surface-soft p-3"><p className="text-xl font-bold text-cream">{c.booked_sessions}</p><p className="text-[11px] text-cream-faint">booked sessions this week</p></div></div>{c.outside_declared_sessions>0&&<p className="mt-3 rounded-xl border border-status-moderate/30 bg-status-moderate/5 p-3 text-xs text-cream-dim">{c.outside_declared_sessions} scheduled session{c.outside_declared_sessions===1?" is":"s are"} outside this trainer’s declared availability. Review the schedule or availability rules.</p>}</>:<p className="mt-4 rounded-xl bg-surface-soft p-4 text-sm text-cream-dim">No declared availability, blocks or sessions were loaded for this trainer this week.</p>}</article>})}</section>
  <section className="rounded-2xl border border-divider bg-white p-5"><h2 className="font-semibold text-cream">Interpretation boundary</h2><p className="mt-2 text-sm leading-6 text-cream-dim">Open declared time means availability rules minus overlapping time blocks and booked-session overlap. It does not assume every open hour should be sold, and it does not estimate demand, trainer productivity or future revenue.</p><div className="mt-3 flex flex-wrap gap-3"><Link href="/schedule" className="min-h-11 py-3 text-sm font-semibold text-sky">Open schedule →</Link><Link href="/settings/staff" className="min-h-11 py-3 text-sm font-semibold text-sky">Staff & roles →</Link><Link href="/operating-system" className="min-h-11 py-3 text-sm font-semibold text-sky">IMS Operating System →</Link></div></section>
 </main></AppShell>;
}
