"use client";
import Link from "next/link";
import {useState} from "react";
import {assessmentBodPodCandidate,assessmentContext,buildBlocker,composeFuelStrategy,initialBuildInputs,latestBodPod,type BuildEvidence,type BuildInputs,type BuildKind,type BuildMode} from "@/lib/coaching/build";
import {bodyCompWarning} from "@/lib/fuel/model";
import {FuelPlanEditor} from "@/components/fuel/plan-editor";
import {FuelPlanView} from "@/components/fuel/plan-view";
import {FuelBodyCompForm} from "@/components/fuel/coach-forms";
import {Field,fieldClass,primaryClass,secondaryClass} from "@/components/fuel/controls";
import {useTrainingDraft} from "./training-draft";
const panel="min-w-0 space-y-4 rounded-3xl border border-divider bg-white p-5";
const modes=[{id:"quick",title:"Quick Start",detail:"Habits and practical routines. No assessment required."},{id:"bod_pod",title:"Bod Pod Build",detail:"Use a recorded Bod Pod baseline, your goal and coaching context."},{id:"performance",title:"Full Performance",detail:"Review assessment, training demands and recorded performance together."}] as const;
export function CoachingBuilder({evidence,initialKind,initialMode}:{evidence:BuildEvidence;initialKind:BuildKind;initialMode:BuildMode}){
 const [kind,setKind]=useState<BuildKind>(initialKind),[input,setInput]=useState<BuildInputs>(()=>initialBuildInputs(evidence,initialMode)),[confirmed,setConfirmed]=useState(false),[error,setError]=useState<string|null>(null),[candidate,setCandidate]=useState<ReturnType<typeof composeFuelStrategy>|null>(null),[candidateRevision,setCandidateRevision]=useState<number|null>(null);
 const training=useTrainingDraft(),bod=latestBodPod(evidence),bodCandidate=assessmentBodPodCandidate(evidence.assessment,evidence.asOf),context=assessmentContext(evidence.assessment),fuel=kind!=="training",wantsTraining=kind!=="fuel",blocker=fuel?buildBlocker(evidence,input.mode):null;
 const trainingBlocker=!evidence.assessment?"A reviewed assessment is needed for exercise generation. Fuel can still start with habits.":evidence.assessment.status!=="complete"?"Complete and review the assessment before generating exercises.":input.trainingDays===null?"Confirm 1–5 training days per week for the generator.":null;
 const existingDraft=evidence.latest&&evidence.latest.id!==evidence.release?.version_id;
 const locked=training.locked||candidate!==null;
 function change(patch:Partial<BuildInputs>){setInput(previous=>({...previous,...patch}));setConfirmed(false);}
 function prepare(){
  if(locked||!confirmed)return;setError(null);
  try{
   if(fuel){const draft=composeFuelStrategy(evidence,input);setCandidate(draft);setCandidateRevision(evidence.latest?.revision??0);}
   if(wantsTraining&&!trainingBlocker&&evidence.assessment)void training.generate({assessment_id:evidence.assessment.id,client_id:evidence.clientId,expected_assessment_updated_at:evidence.assessment.updated_at,sessions_per_week:input.trainingDays!,goal:input.goal.trim()});
  }catch(cause){setError(cause instanceof Error?cause.message:"Review the build inputs.");}
 }
 const stale=candidate!==null&&candidateRevision!==(evidence.latest?.revision??0);
 return <main className="mx-auto w-full max-w-6xl space-y-5 pb-20">
  <header className="rounded-3xl bg-band p-6 text-white"><p className="text-xs font-semibold uppercase tracking-widest text-white/70">IMS / Client-first coaching</p><h1 className="mt-3 break-words text-3xl font-bold">Build for {evidence.name}</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-white/80">Evidence → Strategy → Meals &amp; habits → Review → Release. No plan selection and no automatic client publication.</p><div className="mt-4 flex flex-wrap gap-4"><Link className="inline-flex min-h-11 items-center text-sm font-semibold text-white" href={`/clients/${evidence.clientId}`}>← Client profile</Link><Link className="inline-flex min-h-11 items-center text-sm font-semibold text-white" href={`/clients/${evidence.clientId}/fuel`}>Current Fuel Strategy →</Link><Link className="inline-flex min-h-11 items-center text-sm font-semibold text-white" href="/fuel/sample">Sample · not assigned →</Link></div></header>
  <nav aria-label="Build steps" className="flex flex-wrap gap-2">{[["evidence","1 · Evidence"],["strategy","2 · Build"],["review","3 · Review & save"]].map(([id,label])=><a key={id} className={secondaryClass} href={`#build-${id}`}>{label}</a>)}</nav>
  <section id="build-evidence" className={panel+" scroll-mt-24"}><h2 className="text-xl font-semibold">Evidence already on this client</h2><p className="text-xs text-cream-faint">Snapshot loaded {evidence.capturedAt}. Refresh for newer records; this is not a live medical monitor.</p>{evidence.unavailable.length>0&&<p role="alert" className="rounded-xl border border-status-moderate/30 p-3 text-sm">Unavailable: {evidence.unavailable.join(", ")}. Missing queries do not mean zero activity or normal health.</p>}
   <div className="grid gap-3 md:grid-cols-3"><article className="rounded-2xl bg-sky/5 p-4"><h3 className="font-semibold">Bod Pod baseline</h3>{bod?<><p className="mt-2 text-sm">{bod.recorded_at}</p><dl className="mt-3 space-y-2 text-sm">{[["Weight",bod.weight_lb,"lb"],["Body fat",bod.body_fat_pct,"%"],["Reported fat-free / lean mass",bod.lean_mass_lb,"lb"]].map(([label,value,unit])=><div key={String(label)}><dt className="text-cream-faint">{label}</dt><dd>{value===null?"Not recorded":`${value} ${unit}`}</dd></div>)}</dl>{bodyCompWarning(bod)&&<p className="mt-3 text-xs leading-5 text-status-moderate">{bodyCompWarning(bod)}</p>}</>:<p className="mt-2 text-sm text-cream-dim">No recorded Bod Pod test. Home BIA is not substituted.</p>}<p className="mt-3 text-xs leading-5 text-cream-dim">No automatic calorie calculation, fat-loss guarantee or muscle-mass claim.</p></article>
    <article className="rounded-2xl bg-surface-soft p-4"><h3 className="font-semibold">Assessment &amp; constraints</h3>{evidence.assessment?<><p className="mt-2 text-sm">{evidence.assessment.assessment_date} · {evidence.assessment.status.replaceAll("_"," ")}</p><p className="mt-2 text-sm">{context.goal||"Goal not recorded"}</p><Link className="mt-2 inline-flex min-h-11 items-center text-sm font-semibold text-sky" href={`/assessments/${evidence.assessment.id}`}>Review full assessment →</Link></>:<Link className="mt-2 inline-flex min-h-11 items-center text-sm font-semibold text-sky" href={`/assessments/new?client_id=${evidence.clientId}`}>Add assessment →</Link>}<p className="mt-2 text-xs leading-5 text-cream-dim">Private restrictions stay on the assessment. They are not copied into client-facing guidance. Missing restrictions are not clearance.</p>{context.restrictions.length>0&&<details className="mt-3"><summary className="min-h-11 cursor-pointer text-sm font-semibold">Private coach context</summary>{context.restrictions.map((value,i)=><p className="mt-2 whitespace-pre-wrap text-sm" key={i}>{value}</p>)}</details>}</article>
    <article className="rounded-2xl bg-surface-soft p-4"><h3 className="font-semibold">Training &amp; performance</h3><p className="mt-2 text-sm">{evidence.unavailable.includes("Upcoming schedule")?"Schedule unavailable":`${evidence.upcoming.length} upcoming bookings in the loaded approximately two-week window (up to 30).`}</p><p className="mt-2 text-xs leading-5 text-cream-dim">Bookings are context, not completed exercise or proof that other days are rest.</p><p className="mt-3 text-sm">{evidence.unavailable.includes("Performed exercise history")?"Performance unavailable":evidence.performance.length?`${evidence.performance.length} recent performed exercise records loaded.`:"No performed exercise evidence in the loaded window."}</p>{evidence.performance.length>0&&<details className="mt-3"><summary className="min-h-11 cursor-pointer text-sm font-semibold">Inspect recorded work</summary><div className="space-y-2">{evidence.performance.map((row,i)=><div key={i} className="rounded-xl border border-divider p-3 text-sm"><p className="font-semibold">{row.exercise_name}</p><p className="text-xs text-cream-faint">{row.performed_at}</p><p>Reps: {row.reps_completed??"not recorded"} · Load: {row.load_performed??"not recorded"} · RPE: {row.rpe_actual??"not recorded"}</p></div>)}</div></details>}<Link className="mt-2 inline-flex min-h-11 items-center text-sm font-semibold text-sky" href={`/clients/${evidence.clientId}#client-performance`}>Review actual performance →</Link></article></div>
   {!bod&&bodCandidate&&<p className="rounded-xl bg-sky/5 p-3 text-sm">The assessment contains Bod Pod fields. Review the prefilled test below to register a verified baseline; nothing was imported automatically.</p>}<details open={input.mode==="bod_pod"&&!bod}><summary className="min-h-12 cursor-pointer font-semibold text-sky">Record Bod Pod / retest, then build from it</summary><div className="mt-3"><FuelBodyCompForm key={evidence.body.map(row=>row.id).join(":")} clientId={evidence.clientId} today={evidence.asOf} initialTest={!bod?bodCandidate:null}/></div></details>
  </section>
  <section id="build-strategy" className={panel+" scroll-mt-24"}><h2 className="text-xl font-semibold">What are we building?</h2><fieldset disabled={locked} className="space-y-4"><legend className="sr-only">Build choices</legend><div className="grid gap-2 sm:grid-cols-3">{([["training","Training Program"],["fuel","Fuel Strategy"],["both","Training + Fuel"]] as const).map(([value,label])=><button key={value} type="button" aria-pressed={kind===value} className={kind===value?primaryClass:secondaryClass} onClick={()=>{setKind(value);setConfirmed(false);}}>{label}</button>)}</div>
   {fuel&&<div className="grid gap-3 sm:grid-cols-3">{modes.map(mode=><button key={mode.id} type="button" aria-pressed={input.mode===mode.id} className={`rounded-2xl border p-4 text-left focus-visible:ring-2 focus-visible:ring-sky ${input.mode===mode.id?"border-sky bg-sky/5":"border-divider"}`} onClick={()=>change({mode:mode.id})}><span className="block font-semibold">{mode.title}</span><span className="mt-2 block text-sm leading-6 text-cream-dim">{mode.detail}</span></button>)}</div>}
   <div className="grid gap-4 sm:grid-cols-2"><Field label="Client goal · confirm or edit"><textarea className={fieldClass} rows={3} maxLength={1000} value={input.goal} onChange={e=>change({goal:e.target.value})} placeholder="Fat loss, recomposition, maintenance, performance support, or the client's own goal"/></Field><Field label="Coach-confirmed training days per week · optional for Fuel"><select className={fieldClass} value={input.trainingDays??""} onChange={e=>change({trainingDays:e.target.value?Number(e.target.value):null})}><option value="">Not assigned</option>{[1,2,3,4,5].map(n=><option key={n} value={n}>{n}</option>)}</select></Field>{fuel&&<><Field label="Strategy starts"><input className={fieldClass} type="date" value={input.start} onChange={e=>change({start:e.target.value})}/></Field><Field label="Suggested coach review / discuss retest date"><input className={fieldClass} type="date" min={input.start} value={input.reviewOn} onChange={e=>change({reviewOn:e.target.value})}/></Field></>}</div>
   {fuel&&<details><summary className="min-h-12 cursor-pointer font-semibold text-sky">Meal ideas, preferences &amp; practical guidance · optional</summary><p className="mt-2 text-xs text-cream-dim">These notes become part of the client-facing strategy after review and release. Keep private clinical or internal notes on the assessment.</p><div className="mt-3 grid gap-4 sm:grid-cols-2">{([["preferences","Food preferences / agreed accommodations"],["meals","Coach-entered meal ideas · one per line"],["grocery","Grocery / prep list · one per line"],["guidance","Client-facing practical guidance"]] as const).map(([key,label])=><Field key={key} label={label}><textarea className={fieldClass} rows={3} maxLength={1500} value={input[key]} onChange={e=>change({[key]:e.target.value})}/></Field>)}</div></details>}
   <p className="text-sm leading-6 text-cream-dim">Fuel starts with an editable habit-led strategy. Numeric targets remain blank; add your reviewed targets in the draft editor. No AI meal or clinical prescription is claimed. Training uses the existing assessment generator and retains its separate review/release gates.</p>
   {existingDraft&&fuel&&<div className="rounded-xl border border-status-moderate/30 p-4"><p className="text-sm">Private Fuel version {evidence.latest!.revision} already exists. Continue it rather than replace it with a new scaffold.</p><Link href={`/clients/${evidence.clientId}/fuel#fuel-plan`} className={secondaryClass}>Continue current private draft →</Link></div>}
   {blocker&&<p role="status" className="text-sm text-status-moderate">{blocker}</p>}{wantsTraining&&trainingBlocker&&<p role="status" className="text-sm text-status-moderate">Training: {trainingBlocker} {fuel?"You can prepare the Fuel portion here; training remains blocked.":""}</p>}
   <label className="flex min-h-12 items-start gap-3 text-sm leading-6"><input className="mt-1 h-5 w-5 shrink-0" type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I reviewed this client&apos;s evidence, goal and training context. This prepares private work, not a client release or medical clearance.</label>
   <button type="button" className={primaryClass} disabled={!confirmed||input.goal.trim().length<3||Boolean(blocker)||fuel&&Boolean(existingDraft)||kind==="training"&&Boolean(trainingBlocker)} onClick={prepare}>{kind==="both"?"Prepare Training + Fuel":kind==="training"?"Build private training draft":"Build Fuel Strategy preview"}</button></fieldset>{error&&<p role="alert" className="text-sm text-status-limited">{error}</p>}
  </section>
  <section id="build-review" className={panel+" scroll-mt-24"}><h2 className="text-xl font-semibold">Review &amp; save</h2><p className="text-sm leading-6 text-cream-dim">Each deliverable has its own status. Training generation saves a private draft. Fuel starts as an unsaved preview; save it below. Neither is released here.</p>
   {wantsTraining&&<article className="rounded-2xl border border-divider p-4"><h3 className="font-semibold">Training Program</h3>{training.busy?<p role="status" className="mt-2 text-sm">Building the assessment-based private draft…</p>:training.result?<><p role="status" className="mt-2 text-sm">{training.result.state==="draft_saved"?"Private training draft saved. Client release is still separate.":"Private draft exists, but its PDF needs recovery/review. It is not ready to release."}</p><Link className={secondaryClass+" mt-3"} href={`/programs/${training.result.id}`}>Review training draft →</Link></>:<p className="mt-2 text-sm text-cream-dim">{trainingBlocker??"Not built yet."}</p>}{training.error&&<p role="alert" className="mt-3 text-sm text-status-limited">{training.error}</p>}{training.uncertain&&<button type="button" disabled={training.busy} className={secondaryClass+" mt-3"} onClick={()=>void training.retry()}>Retry same training request</button>}{training.error&&!training.locked&&evidence.assessment&&!trainingBlocker&&<button className={secondaryClass+" mt-3"} type="button" onClick={()=>void training.generate({assessment_id:evidence.assessment!.id,client_id:evidence.clientId,expected_assessment_updated_at:evidence.assessment!.updated_at,sessions_per_week:input.trainingDays!,goal:input.goal.trim()})}>Retry training portion</button>}</article>}
   {candidate&&!stale?<><div className="rounded-xl bg-sky/5 p-3 text-sm font-semibold">Fuel Strategy · UNSAVED PREVIEW</div><details open><summary className="min-h-12 cursor-pointer font-semibold text-sky">Preview the client-facing strategy</summary><div className="mt-3"><FuelPlanView plan={candidate.content} today={input.start}/></div></details><FuelPlanEditor clientId={evidence.clientId} latest={evidence.latest} release={evidence.release} today={evidence.asOf} initialDraft={candidate} allowRelease={false}/></>:stale?<div role="status" className="rounded-xl bg-sky/5 p-4"><p>A newer Fuel version is now stored. Open the saved strategy to verify its contents and release only after individual review.</p><Link className={secondaryClass+" mt-3"} href={`/clients/${evidence.clientId}/fuel#fuel-plan`}>Review saved Fuel Strategy →</Link></div>:fuel?<p className="text-sm text-cream-dim">Prepare a strategy above, or <Link className="font-semibold text-sky underline" href={`/clients/${evidence.clientId}/fuel#fuel-plan`}>start blank in the coach editor</Link>.</p>:null}
  </section>
 </main>;
}
