import Link from "next/link";
import {redirect} from "next/navigation";
import {Users,CalendarDays,ClipboardList,BadgeDollarSign,ShieldCheck,ArrowRight} from "lucide-react";
import {createClient} from "@/lib/supabase/server";
import {AppShell} from "@/components/layout/app-shell";
import {InviteTrainerPanel} from "@/components/settings/invite-trainer-panel";

export const dynamic="force-dynamic";
const TZ="America/Los_Angeles";
function bounds(){const now=new Date();const date=new Intl.DateTimeFormat("en-CA",{timeZone:TZ}).format(now);const probe=new Date(date+"T12:00:00Z");const off=new Intl.DateTimeFormat("en-US",{timeZone:TZ,timeZoneName:"longOffset"}).formatToParts(probe).find(p=>p.type==="timeZoneName")?.value.replace("GMT","")||"-08:00";const start=new Date(date+"T00:00:00"+off);const monthAgo=new Date(start.getTime()-30*86400000),weekAhead=new Date(start.getTime()+7*86400000);return {start:start.toISOString(),monthAgo:monthAgo.toISOString(),weekAhead:weekAhead.toISOString()};}

export default async function StaffSettingsPage(){
 const db=await createClient();const {data:{user}}=await db.auth.getUser();if(!user)redirect("/login?next=/settings/staff");
 const me=await db.from("profiles").select("role,deleted_at").eq("id",user.id).maybeSingle();if(me.error||me.data?.role!=="owner"||me.data.deleted_at)redirect("/dashboard");
 const b=bounds();
 const [staffQ,clientsQ,sessionsQ,upcomingQ,rulesQ]=await Promise.all([
  db.from("profiles").select("id,full_name,email,phone,role,deleted_at").in("role",["owner","trainer"]).is("deleted_at",null).order("role",{ascending:false}).order("full_name"),
  db.from("clients").select("id,primary_trainer_id,status").eq("status","active"),
  db.from("sessions").select("id,trainer_id,status,scheduled_at").eq("status","completed").gte("scheduled_at",b.monthAgo).lt("scheduled_at",b.start),
  db.from("sessions").select("id,trainer_id,status,scheduled_at").in("status",["scheduled","confirmed","requested"]).gte("scheduled_at",b.start).lt("scheduled_at",b.weekAhead),
  db.from("trainer_compensation_rules").select("trainer_id,compensation_type,provider,provider_employee_id,effective_from,active"),
 ]);
 if([staffQ,clientsQ,sessionsQ,upcomingQ,rulesQ].some(q=>q.error))throw new Error("Staff control data could not be loaded.");
 const staff=staffQ.data??[],clients=clientsQ.data??[],sessions=sessionsQ.data??[],upcoming=upcomingQ.data??[],rules=new Map((rulesQ.data??[]).map(r=>[r.trainer_id,r]));
 return <AppShell expectedRole="owner"><main className="mx-auto flex w-full max-w-6xl flex-col gap-5 py-6">
  <header className="rounded-3xl bg-band p-6 text-white sm:p-8"><p className="text-xs font-semibold uppercase tracking-[.2em] text-white/60">Owner control center</p><h1 className="mt-2 text-4xl font-bold">Staff & Roles</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-white/75">One place to understand who can operate IMS, what they own, their current coaching load and whether payroll mapping is ready.</p></header>
  <InviteTrainerPanel/>
  <section className="grid grid-cols-2 gap-3 sm:grid-cols-4"><div className="rounded-2xl border border-divider bg-white p-4"><Users className="h-5 w-5 text-sky"/><p className="mt-3 text-3xl font-bold">{staff.length}</p><p className="text-xs text-cream-faint">active staff</p></div><div className="rounded-2xl border border-divider bg-white p-4"><ClipboardList className="h-5 w-5 text-sky"/><p className="mt-3 text-3xl font-bold">{clients.length}</p><p className="text-xs text-cream-faint">active clients assigned</p></div><div className="rounded-2xl border border-divider bg-white p-4"><CalendarDays className="h-5 w-5 text-sky"/><p className="mt-3 text-3xl font-bold">{sessions.length}</p><p className="text-xs text-cream-faint">sessions delivered · 30d</p></div><div className="rounded-2xl border border-divider bg-white p-4"><BadgeDollarSign className="h-5 w-5 text-sky"/><p className="mt-3 text-3xl font-bold">{staff.filter(s=>rules.get(s.id)?.active).length}</p><p className="text-xs text-cream-faint">payroll rules configured</p></div></section>
  <section className="grid gap-4 md:grid-cols-2">{staff.map(person=>{const assigned=clients.filter(c=>c.primary_trainer_id===person.id).length,done=sessions.filter(s=>s.trainer_id===person.id).length,next=upcoming.filter(s=>s.trainer_id===person.id).length,rule=rules.get(person.id);const payrollStatus=rule?.provider_employee_id?"Provider employee mapped · effective "+rule.effective_from:rule?.provider?"Provider selected · employee mapping pending":"No provider mapping yet";return <article key={person.id} className="rounded-2xl border border-divider bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2"><h2 className="text-lg font-semibold text-cream">{person.full_name}</h2><span className="rounded-full bg-sky/10 px-2.5 py-1 text-[11px] font-semibold uppercase tracking-wide text-sky">{person.role}</span></div><p className="mt-1 text-sm text-cream-dim">{person.email??"No email"}</p></div><ShieldCheck className="h-5 w-5 text-sky"/></div><div className="mt-5 grid grid-cols-3 gap-2"><div className="rounded-xl bg-surface-soft p-3"><p className="text-2xl font-bold">{assigned}</p><p className="text-[11px] text-cream-faint">active clients</p></div><div className="rounded-xl bg-surface-soft p-3"><p className="text-2xl font-bold">{done}</p><p className="text-[11px] text-cream-faint">delivered 30d</p></div><div className="rounded-xl bg-surface-soft p-3"><p className="text-2xl font-bold">{next}</p><p className="text-[11px] text-cream-faint">next 7d</p></div></div><div className="mt-4 rounded-xl border border-divider p-3"><p className="text-xs font-semibold uppercase tracking-wide text-cream-faint">Payroll mapping</p><p className="mt-1 text-sm font-semibold text-cream">{rule?.active?rule.compensation_type.replaceAll("_"," "):"Not configured"}</p><p className="mt-1 text-xs text-cream-dim">{payrollStatus}</p></div><div className="mt-4 flex flex-wrap gap-2"><Link href={"/schedule?trainer="+person.id} className="inline-flex min-h-11 items-center gap-1 rounded-xl border border-divider px-3 text-sm font-semibold text-cream">View schedule <ArrowRight className="h-3.5 w-3.5"/></Link><Link href="/settings/payroll" className="inline-flex min-h-11 items-center gap-1 rounded-xl border border-divider px-3 text-sm font-semibold text-cream">Payroll settings <ArrowRight className="h-3.5 w-3.5"/></Link></div></article>})}</section>
  <section className="rounded-2xl border border-divider bg-white p-5"><h2 className="font-semibold text-cream">Role boundary</h2><p className="mt-2 text-sm leading-6 text-cream-dim">Owners retain business, finance, payroll and staff controls. Trainers operate their assigned coaching workflow. Role changes and deactivation are intentionally not one-click actions here; those will use explicit confirmation and audit logging when enabled.</p></section>
 </main></AppShell>;
}