"use client";
import {useState} from "react";
import {UserPlus,Loader2,CheckCircle2,Copy} from "lucide-react";

export function InviteTrainerPanel(){
 const [busy,setBusy]=useState(false),[message,setMessage]=useState<string|null>(null),[inviteLink,setInviteLink]=useState<string|null>(null);
 async function submit(formData:FormData){setBusy(true);setMessage(null);setInviteLink(null);try{const body=Object.fromEntries(formData.entries());const res=await fetch("/api/admin/staff",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const data=await res.json();if(!res.ok)throw new Error(data.error||"Could not invite trainer.");setMessage(data.invite_sent?"Trainer account created and invite sent.":"Trainer account created. Email delivery needs attention.");setInviteLink(data.invite_link??null);}catch(e){setMessage(e instanceof Error?e.message:"Could not invite trainer.");}finally{setBusy(false);}}
 const field="mt-1 min-h-11 w-full rounded-xl border border-divider bg-white px-3 text-sm";
 return <section className="rounded-2xl border border-divider bg-white p-5 shadow-sm"><div className="flex items-start gap-3"><span className="rounded-xl bg-sky/10 p-2.5"><UserPlus className="h-5 w-5 text-sky"/></span><div><h2 className="font-semibold text-cream">Invite trainer</h2><p className="mt-1 text-sm leading-6 text-cream-dim">Creates a trainer account, sends the set-password link and records the onboarding action. Owner access cannot be granted from this shortcut.</p></div></div><form action={submit} className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-xs font-semibold text-cream-dim">Full name<input name="full_name" required className={field} placeholder="Trainer name"/></label><label className="text-xs font-semibold text-cream-dim">Email<input name="email" required type="email" className={field} placeholder="trainer@example.com"/></label><label className="text-xs font-semibold text-cream-dim sm:col-span-2">Phone (optional)<input name="phone" inputMode="tel" className={field} placeholder="(555) 555-5555"/></label><div className="sm:col-span-2"><button disabled={busy} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-sky px-4 text-sm font-semibold text-white disabled:opacity-50">{busy?<Loader2 className="h-4 w-4 animate-spin"/>:<UserPlus className="h-4 w-4"/>}Create trainer & send invite</button>{message&&<p role="status" className="mt-3 flex items-center gap-2 text-sm text-cream-dim"><CheckCircle2 className="h-4 w-4 text-sky"/>{message}</p>}{inviteLink&&<button type="button" onClick={()=>navigator.clipboard.writeText(inviteLink)} className="mt-2 inline-flex min-h-11 items-center gap-2 rounded-xl border border-divider px-3 text-sm font-semibold text-cream"><Copy className="h-4 w-4"/>Copy fallback invite link</button>}</div></form></section>;
}
