import Link from "next/link";
import {ArrowRight,TrendingUp} from "lucide-react";
import {createClient} from "@/lib/supabase/server";

type Row={exercise_id:string|null;exercise_name:string;sets_completed:number|null;reps_completed:string;load_performed:string;rpe_actual:number|null;coach_note:string;created_at:string;session_id:string};
export async function ClientPerformanceTrends({clientId}:{clientId:string}){
 const db=await createClient();const rowsQ=await db.from("session_exercise_performance").select("exercise_id,exercise_name,sets_completed,reps_completed,load_performed,rpe_actual,coach_note,created_at,session_id").eq("client_id",clientId).order("created_at",{ascending:false}).limit(300);
 if(rowsQ.error)return <section className="rounded-2xl border border-status-limited/30 bg-white p-5"><h2 className="font-semibold text-cream">Exercise performance</h2><p role="alert" className="mt-2 text-sm text-status-limited">Performed-exercise history is unavailable. No progression state was inferred.</p></section>;
 const groups=new Map<string,Row[]>();for(const row of rowsQ.data??[]){const key=row.exercise_id??"name:"+row.exercise_name.toLowerCase();groups.set(key,[...(groups.get(key)??[]),row]);}
 const repeated=[...groups.values()].filter(rows=>rows.length>=2).sort((a,b)=>b.length-a.length||Date.parse(b[0].created_at)-Date.parse(a[0].created_at)).slice(0,12);
 if(!repeated.length)return null;
 return <section className="rounded-3xl border border-divider bg-white p-5 shadow-sm"><div className="flex items-start gap-3"><div className="rounded-xl bg-sky/10 p-2.5"><TrendingUp className="h-5 w-5 text-sky"/></div><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-sky">Longitudinal coaching</p><h2 className="mt-1 text-lg font-semibold text-cream">Repeated exercise evidence</h2><p className="mt-1 text-sm leading-6 text-cream-dim">Recent performed records for exercises seen in multiple coached sessions. Coach OS shows the evidence; it does not declare automatic progression.</p></div></div><div className="mt-4 grid gap-3 md:grid-cols-2">{repeated.map(rows=>{const current=rows[0],prior=rows[1];const summary=(row:Row)=>[row.sets_completed!=null?`${row.sets_completed} sets`:"",row.reps_completed,row.load_performed,row.rpe_actual!=null?`RPE ${row.rpe_actual}`:""].filter(Boolean).join(" · ")||"Performed record";return <article key={current.exercise_id??current.exercise_name} className="rounded-2xl bg-surface-soft p-4"><div className="flex items-start justify-between gap-3"><h3 className="text-sm font-semibold text-cream">{current.exercise_name}</h3><span className="text-[11px] text-cream-faint">{rows.length} records</span></div><div className="mt-3 grid grid-cols-[52px_1fr] gap-x-2 gap-y-2 text-xs"><span className="font-semibold text-sky">Latest</span><div><p className="text-cream">{summary(current)}</p><p className="mt-0.5 text-cream-faint">{new Date(current.created_at).toLocaleDateString("en-US",{timeZone:"America/Los_Angeles",month:"short",day:"numeric"})}</p></div><span className="font-semibold text-cream-faint">Prior</span><div><p className="text-cream-dim">{summary(prior)}</p><p className="mt-0.5 text-cream-faint">{new Date(prior.created_at).toLocaleDateString("en-US",{timeZone:"America/Los_Angeles",month:"short",day:"numeric"})}</p></div></div>{current.coach_note&&<p className="mt-3 border-t border-divider pt-2 text-xs leading-5 text-cream-dim">{current.coach_note}</p>}<Link href={`/sessions/${current.session_id}`} className="mt-2 inline-flex min-h-11 items-center gap-1 text-xs font-semibold text-sky">Latest session <ArrowRight className="h-3.5 w-3.5"/></Link></article>})}</div></section>;
}
