import Link from "next/link";
import { ClipboardCheck, Dumbbell, FileCheck2 } from "lucide-react";
import { createClient } from "@/lib/supabase/server";
import { isExerciseSet } from "@/lib/exercises/catalog";
export async function ClientProgrammingStatus({clientId}:{clientId:string}){
 const db=await createClient(); const {data:{user}}=await db.auth.getUser(); if(!user)return null;
 const viewer=await db.from("profiles").select("role,deleted_at").eq("id",user.id).maybeSingle(); if(viewer.error||!viewer.data||viewer.data.deleted_at||!["owner","trainer"].includes(viewer.data.role))return null;
 const [assessments,programs]=await Promise.all([db.from("assessments").select("id,status,assessment_date").eq("client_id",clientId).order("assessment_date",{ascending:false}).limit(1),db.from("programs").select("id,status,data").eq("client_id",clientId).order("updated_at",{ascending:false}).limit(100)]);
 if(assessments.error||programs.error)return <p role="alert" className="rounded-2xl border border-status-limited/30 bg-white p-4 text-sm text-status-limited">Programming status could not be loaded.</p>;
 const rows=programs.data??[]; const sets=rows.filter(p=>isExerciseSet(p.data)); const finished=rows.filter(p=>!isExerciseSet(p.data)); const active=finished.filter(p=>["published","active"].includes(p.status)); const assessment=assessments.data?.[0]; const mode=assessment?.status==="complete"?"Assessed":assessment?"Assessment in progress":sets.length||finished.length?"Quick programming":"Not started";
 return <section className="rounded-2xl border border-divider bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wider text-sky">Programming status</p><h2 className="mt-1 text-xl font-semibold text-cream">{mode}</h2></div><span className="rounded-full bg-surface-soft px-3 py-1.5 text-xs font-semibold text-cream-dim">{active.length ? active.length+" client-visible program"+(active.length===1?"":"s") : "Coach workspace"}</span></div>
<div className="mt-4 grid grid-cols-3 gap-3"><div className="rounded-xl bg-surface-soft p-3"><ClipboardCheck className="h-4 w-4 text-sky"/><p className="mt-2 text-xl font-bold">{assessment?1:0}</p><p className="text-xs text-cream-faint">current assessment</p></div><div className="rounded-xl bg-surface-soft p-3"><Dumbbell className="h-4 w-4 text-sky"/><p className="mt-2 text-xl font-bold">{sets.length}</p><p className="text-xs text-cream-faint">exercise sets</p></div><div className="rounded-xl bg-surface-soft p-3"><FileCheck2 className="h-4 w-4 text-sky"/><p className="mt-2 text-xl font-bold">{finished.length}</p><p className="text-xs text-cream-faint">programs</p></div></div>
<p className="mt-4 text-xs leading-5 text-cream-dim">{assessment?.status==="complete"?"Current assessment evidence is available for programming.":assessment?"Assessment is underway; quick exercise work can still be saved privately.":"No current in-gym assessment is required for quick/remote programming. Use one when you want current findings to drive decisions."}</p><div className="mt-3 flex flex-wrap gap-3"><Link href={"/library?client_id="+clientId} className="min-h-11 py-3 text-sm font-semibold text-sky">Quick program →</Link><Link href={"/assessments/new?client_id="+clientId} className="min-h-11 py-3 text-sm font-semibold text-sky">Assessment-led →</Link></div></section>;
}