import Link from "next/link";
import {createClient} from "@/lib/supabase/server";
import {repeatedPerformance,type PerformanceEvidence} from "@/lib/coaching/performance-evidence";
export async function ClientPerformanceTrends({clientId}:{clientId:string}){
 const db=await createClient();const {data:{user}}=await db.auth.getUser();if(!user)return null;
 const me=await db.from("profiles").select("role,deleted_at").eq("id",user.id).maybeSingle();if(me.error)throw new Error("Performance authorization unavailable.");if(!me.data||me.data.deleted_at||!["owner","trainer"].includes(me.data.role))return null;
 const sessionsQ=await db.from("sessions").select("id").eq("client_id",clientId).eq("status","completed").lte("scheduled_at",new Date().toISOString()).order("scheduled_at",{ascending:false}).limit(100);
 const unavailable=<section className="rounded-2xl border border-status-limited/30 bg-white p-5"><h2 className="font-semibold">Exercise performance</h2><p role="alert" className="mt-2 text-sm text-status-limited">Performed-exercise history is unavailable. No progression state was inferred.</p></section>;
 if(sessionsQ.error)return unavailable;const ids=(sessionsQ.data??[]).map(s=>s.id);
 const result=ids.length?await db.from("session_exercise_performance").select("id,session_id,exercise_id,exercise_name,sets_completed,reps_completed,load_performed,rpe_actual,performed_at").eq("client_id",clientId).in("session_id",ids).order("performed_at",{ascending:false}).limit(300):{data:[],error:null};
 if(result.error)return unavailable;const comparisons=repeatedPerformance(result.data as PerformanceEvidence[]);
 return <section className="rounded-3xl border border-divider bg-white p-5"><p className="text-xs font-semibold uppercase tracking-wider text-sky">Longitudinal coaching</p><h2 className="mt-1 text-xl font-semibold">Repeated exercise evidence</h2><p className="mt-2 text-sm leading-6 text-cream-dim">Compare actual work across different completed sessions. Coach OS does not declare automatic progression, combine different units or match exercises by name alone.</p>
 <div className="mt-4 grid gap-3 sm:grid-cols-2">{comparisons.groups.slice(0,12).map(item=><article key={item.exerciseId} className="rounded-2xl bg-surface-soft p-4"><h3 className="font-semibold">{item.latest.exercise_name}</h3><p className="mt-2 text-xs text-cream-faint">{item.records.length} distinct sessions in loaded evidence</p><p className="mt-3 text-xs font-semibold text-sky">Latest · {new Date(item.latest.performed_at).toLocaleDateString("en-US",{timeZone:"America/Los_Angeles",month:"short",day:"numeric"})}</p><p className="mt-1 text-sm">{item.latestText}</p><p className="mt-3 text-xs text-cream-faint">Previous · {new Date(item.prior.performed_at).toLocaleDateString("en-US",{timeZone:"America/Los_Angeles",month:"short",day:"numeric"})}</p><p className="mt-1 text-sm text-cream-dim">{item.priorText}</p><Link className="mt-3 inline-flex min-h-11 items-center text-sm font-semibold text-sky" href={`/sessions/${item.latest.session_id}`}>Open evidence and coaching context →</Link></article>)}</div>
 {!comparisons.groups.length&&<p className="mt-3 rounded-xl bg-surface-soft p-4 text-sm">No comparable repeated exercise yet. Two distinct completed sessions with the same exercise identity are needed.</p>}<p className="mt-3 text-xs text-cream-faint">Loaded window: 100 completed sessions and 300 exercise records. {comparisons.excluded>0?`${comparisons.excluded} records excluded for missing identity or invalid/future performed date.`:""}</p></section>;
}
