"use client";
import Link from "next/link";
import { useMemo, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { Search, Target, Users, ArrowRight, AlertTriangle } from "lucide-react";
import { CAMPAIGN_STARTERS, CHANNEL_LABELS, GROWTH_CHANNELS, duplicateCandidateIds, opportunityState, type GrowthCampaign, type GrowthLead, type OpportunityReview, type GrowthAttribution } from "@/lib/growth/model";
import type { GrowthCommand } from "@/lib/growth/commands";
import type { GrowthCenterData } from "@/lib/growth/server";
const field="mt-1 min-h-11 w-full rounded-xl border border-divider bg-white px-3 py-2 text-base text-cream focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-sky";
const button="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-sky px-4 py-2 text-sm font-semibold text-white disabled:opacity-50";
const panel="rounded-2xl border border-divider bg-white p-5 shadow-sm";
const money=(cents:number|null)=>cents===null?"Not recorded":new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(cents/100);
const dollars=(value:string):number|null=>{
  if(!value.trim())return null;
  if(!/^\d+(\.\d{1,2})?$/.test(value))throw new Error("Enter a dollar amount with up to two decimal places.");
  const [whole,fraction=""]=value.split("."); const cents=Number(whole)*100+Number(fraction.padEnd(2,"0"));
  if(!Number.isSafeInteger(cents)||cents>10000000)throw new Error("Amount is outside the supported range.");
  return cents;
};
type WithoutRequest<T> = T extends unknown ? Omit<T,"request_id"> : never;
type CommandInput = WithoutRequest<GrowthCommand>;
function useGrowthCommand(){
  const router=useRouter(), lock=useRef(false), pending=useRef<{signature:string;id:string}|null>(null);
  const [busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[saved,setSaved]=useState(false);
  async function run(make:()=>CommandInput){
    if(lock.current)return false; lock.current=true; setBusy(true);setError(null);setSaved(false);
    try{
      const input=make(),signature=JSON.stringify(input);
      if(pending.current?.signature!==signature)pending.current={signature,id:crypto.randomUUID()};
      const response=await fetch("/api/growth",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...input,request_id:pending.current.id})});
      const result=await response.json().catch(()=>null);
      if(!response.ok || result?.ok!==true || !result.id)throw new Error(result?.error||"Save was not confirmed. Your inputs are still here.");
      setSaved(true);router.refresh();return true;
    }catch(cause){setError(cause instanceof Error?cause.message:"Could not save growth record.");return false;}
    finally{lock.current=false;setBusy(false);}
  }
  return {busy,error,saved,run};
}
function Feedback({mutation}:{mutation:ReturnType<typeof useGrowthCommand>}){
  return <>{mutation.error&&<p role="alert" className="mt-3 rounded-xl border border-status-limited/30 p-3 text-sm text-status-limited">{mutation.error}</p>}{mutation.saved&&<p role="status" className="mt-3 text-sm text-sky">Record saved with audit history. No external action was taken.</p>}</>;
}
function CampaignEditor({campaign,seed}:{campaign?:GrowthCampaign;seed?:Partial<GrowthCampaign>}){
  const mutation=useGrowthCommand();
  const [name,setName]=useState(campaign?.name??seed?.name??""),[channel,setChannel]=useState(campaign?.channel??seed?.channel??"local_search");
  const [audience,setAudience]=useState(campaign?.audience??seed?.audience??"both"),[area,setArea]=useState(campaign?.area??"Scripps Ranch and nearby San Diego communities");
  const [offer,setOffer]=useState(campaign?.offer??seed?.offer??""),[budget,setBudget]=useState(campaign?.budget_cents==null?"":(campaign.budget_cents/100).toFixed(2)),[status,setStatus]=useState(campaign?.status??"draft");
  return <form onSubmit={e=>{e.preventDefault();void mutation.run(()=>({action:"save_campaign",campaign_id:campaign?.id??null,expected_updated_at:campaign?.updated_at??null,name,channel,audience,area,offer,budget_cents:dollars(budget),status}));}}>
    <fieldset disabled={mutation.busy} className="grid gap-3 sm:grid-cols-2"><legend className="sr-only">Campaign plan</legend>
      <label className="text-sm font-medium">Campaign name<input required minLength={2} maxLength={160} className={field} value={name} onChange={e=>setName(e.target.value)}/></label>
      <label className="text-sm font-medium">Channel<select className={field} value={channel} onChange={e=>setChannel(e.target.value as GrowthCampaign["channel"])}>{GROWTH_CHANNELS.map(key=><option key={key} value={key}>{CHANNEL_LABELS[key]}</option>)}</select></label>
      <label className="text-sm font-medium">Coaching offer<select className={field} value={audience} onChange={e=>setAudience(e.target.value as GrowthCampaign["audience"])}><option value="both">General population + private coaching</option><option value="general_population">General-population training</option><option value="private_coaching">Higher-touch private coaching</option></select></label>
      <label className="text-sm font-medium">Target area<input required minLength={2} maxLength={160} className={field} value={area} onChange={e=>setArea(e.target.value)}/></label>
      <label className="text-sm font-medium sm:col-span-2">Offer / acquisition hypothesis<textarea required minLength={10} maxLength={1000} rows={3} className={field} value={offer} onChange={e=>setOffer(e.target.value)}/></label>
      <label className="text-sm font-medium">Planned budget · USD<input inputMode="decimal" placeholder="Not set" className={field} value={budget} onChange={e=>setBudget(e.target.value)}/></label>
      <label className="text-sm font-medium">Internal tracking status<select className={field} value={status} onChange={e=>setStatus(e.target.value as GrowthCampaign["status"])}><option value="draft">Draft plan</option><option value="tracking">Tracking activity</option><option value="paused">Paused</option></select></label>
      <p className="text-xs leading-5 text-cream-dim sm:col-span-2">This is a plan, not authorization to charge a card, activate ads or execute paid research. Blank budget remains unknown, not $0.</p>
      <button className={button} disabled={mutation.busy}>{mutation.busy?"Saving…":campaign?"Save campaign plan":"Create campaign plan"}</button>
    </fieldset><Feedback mutation={mutation}/>
  </form>;
}
function SpendForm({campaignId,today}:{campaignId:string;today:string}){
  const mutation=useGrowthCommand(),[amount,setAmount]=useState(""),[category,setCategory]=useState<"research"|"advertising"|"creative"|"other">("research"),[date,setDate]=useState(today),[reference,setReference]=useState("");
  return <form className="mt-3" onSubmit={e=>{e.preventDefault();void mutation.run(()=>{const amount_cents=dollars(amount);if(amount_cents===null||amount_cents===0)throw new Error("Enter an actual positive expense amount.");return {action:"record_spend",campaign_id:campaignId,amount_cents,category,incurred_on:date,evidence_reference:reference};});}}>
    <fieldset disabled={mutation.busy} className="grid gap-3 sm:grid-cols-2"><legend className="sr-only">Record incurred expense</legend>
      <label className="text-sm">Actual amount · USD<input required inputMode="decimal" className={field} value={amount} onChange={e=>setAmount(e.target.value)}/></label>
      <label className="text-sm">Category<select className={field} value={category} onChange={e=>setCategory(e.target.value as typeof category)}>{["research","advertising","creative","other"].map(value=><option key={value}>{value}</option>)}</select></label>
      <label className="text-sm">Date incurred · UTC<input required type="date" max={today} className={field} value={date} onChange={e=>setDate(e.target.value)}/></label>
      <label className="text-sm">Receipt / invoice reference<input required minLength={5} maxLength={500} className={field} value={reference} onChange={e=>setReference(e.target.value)} placeholder="Provider invoice or receipt reference"/></label>
      <p className="text-xs leading-5 text-cream-dim sm:col-span-2">Records an expense that already occurred. This does not purchase anything. Use a reference, never card details or API keys.</p>
      <button className={button} disabled={mutation.busy}>{mutation.busy?"Saving…":"Record expense"}</button>
    </fieldset><Feedback mutation={mutation}/>
  </form>;
}
function OpportunityCard({lead,review,campaigns,today,duplicate}:{lead:GrowthLead;review?:OpportunityReview;campaigns:GrowthCampaign[];today:string;duplicate:boolean}){
  const state=opportunityState(lead,review,today),mutation=useGrowthCommand();
  const [decision,setDecision]=useState<OpportunityReview["decision"]>(review?.decision??"hold"),[campaign,setCampaign]=useState(review?.campaign_id??"");
  const [rationale,setRationale]=useState(review?.rationale??""),[next,setNext]=useState(review?.next_action??state.evidence?.next_step??""),[due,setDue]=useState(review?.due_on??""),[draft,setDraft]=useState(review?.outreach_draft??""),[copyMessage,setCopyMessage]=useState("");
  return <article className={panel}>
    <div className="flex flex-wrap items-start justify-between gap-2"><div><h3 className="text-lg font-semibold text-cream">{lead.full_name}</h3><p className="mt-1 text-xs text-cream-dim">{state.decision.replaceAll("_"," ")} · research candidate, not an inquiry</p></div>{state.overdue&&<span className="rounded-full bg-status-moderate/10 px-3 py-1 text-xs text-status-moderate">Follow-up due {review?.due_on}</span>}</div>
    {(state.stale||duplicate||state.sourceInvalid)&&<p className="mt-3 rounded-xl bg-status-moderate/10 p-3 text-xs leading-5 text-cream">{state.stale?"Source changed since review. Review again before treating this as approved. ":""}{duplicate?"Possible duplicate organization/domain. Compare existing research before outreach. ":""}{state.sourceInvalid?"Dated source evidence is missing or invalid; approval is blocked.":""}</p>}
    {state.evidence&&<div className="mt-3 space-y-2 text-sm leading-6 text-cream-dim"><p>{state.evidence.fit_reason}</p><div className="flex flex-wrap gap-4 text-xs font-semibold"><a href={state.evidence.website_url} target="_blank" rel="noopener noreferrer" className="inline-flex min-h-11 items-center text-sky">Official website ↗</a><a href={state.evidence.evidence_url} target="_blank" rel="noopener noreferrer" className="inline-flex min-h-11 items-center text-sky">Evidence · checked {state.evidence.checked_on} ↗</a></div></div>}
    <details className="mt-3 border-t border-divider"><summary className="min-h-11 cursor-pointer py-3 text-sm font-semibold text-sky">Review, assign and draft follow-up</summary>
      <form onSubmit={e=>{e.preventDefault();void mutation.run(()=>({action:"review_opportunity",candidate_id:lead.id,campaign_id:campaign||null,expected_source_updated_at:lead.updated_at,expected_updated_at:review?.updated_at??null,decision,rationale,next_action:next,due_on:due||null,outreach_draft:draft}));}}>
        <fieldset disabled={mutation.busy} className="grid gap-3 sm:grid-cols-2"><legend className="sr-only">Review {lead.full_name}</legend>
          <label className="text-sm">Owner decision<select className={field} value={decision} onChange={e=>setDecision(e.target.value as typeof decision)}><option value="hold">Hold for more evidence</option><option value="approve" disabled={state.sourceInvalid}>Approve opportunity — not a lead</option><option value="dismiss">Dismiss opportunity</option></select></label>
          <label className="text-sm">Campaign<select className={field} value={campaign} onChange={e=>setCampaign(e.target.value)}><option value="">Unassigned</option>{campaigns.map(row=><option key={row.id} value={row.id}>{row.name}</option>)}</select></label>
          <label className="text-sm sm:col-span-2">Decision rationale<textarea required minLength={10} maxLength={2000} rows={2} className={field} value={rationale} onChange={e=>setRationale(e.target.value)}/></label>
          <label className="text-sm">Next action<input required={decision==="approve"} minLength={decision==="approve"?5:undefined} maxLength={500} className={field} value={next} onChange={e=>setNext(e.target.value)}/></label>
          <label className="text-sm">Follow-up date · UTC<input type="date" required={decision==="approve"} className={field} value={due} onChange={e=>setDue(e.target.value)}/></label>
          <label className="text-sm sm:col-span-2">Outreach draft · nothing is sent<textarea maxLength={5000} rows={4} className={field} value={draft} onChange={e=>{setDraft(e.target.value);setCopyMessage("");}} placeholder="Write a source-grounded introduction. Do not imply an existing relationship or consent."/></label>
          <div className="flex flex-wrap gap-3 sm:col-span-2"><button type="button" className="min-h-11 text-sm font-semibold text-sky" onClick={()=>{setDraft(`Hello ${lead.full_name} team,\n\nI'm reaching out from Innovative Movement Solutions in Scripps Ranch. We offer individualized strength and mobility coaching. Would your team be open to a brief conversation about whether a referral or community partnership would be a fit?\n\nThank you,\nIMS Fitness`);setCopyMessage("");}}>Use editable introduction</button><button type="button" disabled={!draft} className="min-h-11 text-sm font-semibold text-sky disabled:opacity-50" onClick={async()=>{try{await navigator.clipboard.writeText(draft);setCopyMessage("Draft copied. Nothing was sent.");}catch{setCopyMessage("Clipboard unavailable. Select the draft and copy it manually.");}}}>Copy draft</button></div>
          {copyMessage&&<p role="status" className="text-xs text-cream-dim sm:col-span-2">{copyMessage}</p>}
          <p className="text-xs leading-5 text-cream-dim sm:col-span-2">Approval means this public opportunity is worth pursuing. It does not qualify a consumer, establish consent, send a message or add anyone to a marketing list.</p>
          <button className={button} disabled={mutation.busy||(decision==="approve"&&state.sourceInvalid)}>{mutation.busy?"Saving…":"Save owner review"}</button>
        </fieldset><Feedback mutation={mutation}/>
      </form>
    </details>
  </article>;
}
function AttributionForm({lead,existing,data,today}:{lead:GrowthLead;existing?:GrowthAttribution;data:GrowthCenterData;today:string}){
  const mutation=useGrowthCommand(),[campaign,setCampaign]=useState(existing?.campaign_id??data.campaigns[0]?.id??""),[candidate,setCandidate]=useState(existing?.candidate_id??""),[evidence,setEvidence]=useState(existing?.evidence??""),[client,setClient]=useState(existing?.client_id??""),[date,setDate]=useState(existing?.revenue_from??"");
  const approved=data.research.filter(row=>{const r=data.reviews.find(review=>review.candidate_id===row.id);return r?.campaign_id===campaign&&opportunityState(row,r,today).decision==="approve";});
  return <form className="mt-4" onSubmit={e=>{e.preventDefault();void mutation.run(()=>({action:"link_inquiry",lead_id:lead.id,campaign_id:campaign,candidate_id:candidate||null,expected_source_updated_at:lead.updated_at,expected_updated_at:existing?.updated_at??null,evidence,client_id:lead.stage==="converted"&&client?client:null,revenue_from:lead.stage==="converted"&&client?date||null:null}));}}>
    <fieldset disabled={mutation.busy} className="grid gap-3 sm:grid-cols-2"><legend className="sr-only">Source attribution for {lead.full_name}</legend>
      <label className="text-sm">Campaign<select required className={field} value={campaign} onChange={e=>{setCampaign(e.target.value);setCandidate("");}}><option value="">Choose campaign</option>{data.campaigns.map(row=><option key={row.id} value={row.id}>{row.name}</option>)}</select></label>
      <label className="text-sm">Approved source opportunity · optional<select className={field} value={candidate} onChange={e=>setCandidate(e.target.value)}><option value="">No organization-level source</option>{approved.map(row=><option key={row.id} value={row.id}>{row.full_name}</option>)}</select></label>
      <label className="text-sm sm:col-span-2">How is this source confirmed?<textarea required minLength={10} maxLength={2000} rows={2} className={field} value={evidence} onChange={e=>setEvidence(e.target.value)} placeholder="e.g. Inquiry supplied this referral source; include a dated operational reference."/></label>
      {lead.stage==="converted"&&<><label className="text-sm">Confirmed existing client · optional<select className={field} value={client} onChange={e=>{setClient(e.target.value);if(!e.target.value)setDate("");}}><option value="">Not mapped; revenue remains unlinked</option>{data.clients.map(row=><option key={row.id} value={row.id}>{row.full_name}</option>)}</select></label><label className="text-sm">Payment attribution starts · UTC<input type="date" required={!!client} disabled={!client} max={today} className={field} value={date} onChange={e=>setDate(e.target.value)}/></label></>}
      <p className="text-xs leading-5 text-cream-dim sm:col-span-2">Links an existing real inquiry without changing its original source or stage. Map revenue only after you confirm the converted client identity. A client can have only one acquisition attribution.</p>
      <button className={button} disabled={mutation.busy||!campaign}>{mutation.busy?"Saving…":"Save confirmed attribution"}</button>
    </fieldset><Feedback mutation={mutation}/>
  </form>;
}
export function GrowthCenter({data,today}:{data:GrowthCenterData;today:string}){
  const [starter,setStarter]=useState(0),[queue,setQueue]=useState("needs_review"),[shown,setShown]=useState(20),[leadId,setLeadId]=useState("");
  const reviewMap=useMemo(()=>new Map(data.reviews.map(row=>[row.candidate_id,row])),[data.reviews]);
  const duplicates=useMemo(()=>duplicateCandidateIds(data.research),[data.research]);
  const states=data.research.map(lead=>({lead,...opportunityState(lead,reviewMap.get(lead.id),today)}));
  const candidates=states.filter(row=>queue==="all"||queue==="due"&&row.overdue||queue===row.decision).sort((a,b)=>Number(b.overdue)-Number(a.overdue)||a.lead.full_name.localeCompare(b.lead.full_name));
  const chosen=data.pipeline.find(row=>row.id===leadId);
  return <main className="mx-auto flex w-full max-w-6xl flex-col gap-5 py-6 pb-24">
    <header className="rounded-3xl bg-band p-6 text-white sm:p-8"><p className="text-xs font-semibold uppercase tracking-[.2em] text-white/65">IMS / Acquisition & evidence</p><h1 className="mt-2 text-4xl font-bold">Growth Center</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-white/80">General-population training and higher-touch private coaching. Build repeatable channels, review the evidence, and connect real inquiries to consultations, clients and successful payments.</p><div className="mt-5 flex flex-wrap gap-3"><Link href="/leads/research" className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-white px-4 text-sm font-semibold text-sky-deep"><Search className="h-4 w-4"/>Research Desk</Link><Link href="/leads" className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-white/25 px-4 text-sm font-semibold">Real inquiry pipeline<ArrowRight className="h-4 w-4"/></Link><a href="#opportunities" className="inline-flex min-h-11 items-center rounded-xl border border-white/25 px-4 text-sm font-semibold">Review opportunities</a></div></header>
    <section className="grid grid-cols-2 gap-3 lg:grid-cols-4" aria-label="Separate acquisition stages">{[{label:"Research candidates",value:data.research.length,icon:Search},{label:"Approved opportunities",value:states.filter(row=>row.decision==="approve").length,icon:Target},{label:"Real current inquiries",value:data.pipeline.filter(row=>!["converted","not_interested"].includes(row.stage)).length,icon:Users},{label:"Research follow-ups due",value:states.filter(row=>row.overdue).length,icon:ArrowRight}].map(item=><div key={item.label} className={panel}><item.icon className="h-5 w-5 text-sky"/><p className="mt-3 text-3xl font-bold text-cream">{item.value}</p><p className="text-xs text-cream-dim">{item.label}</p></div>)}</section>
    <section className={panel}><h2 className="text-xl font-semibold">Acquisition campaign plans</h2><p className="mt-2 text-sm leading-6 text-cream-dim">Start with an editable channel hypothesis, not a purchased list. Audience language describes the offer; the system does not infer anyone&apos;s income, age or health.</p><details className="mt-4 border-t border-divider"><summary className="min-h-11 cursor-pointer py-3 font-semibold text-sky">Create a campaign plan</summary><label className="mb-4 block text-sm">Starting point<select className={field} value={starter} onChange={e=>setStarter(Number(e.target.value))}>{CAMPAIGN_STARTERS.map((row,index)=><option key={row.name} value={index}>{row.name}</option>)}</select></label><CampaignEditor key={starter} seed={CAMPAIGN_STARTERS[starter]}/></details></section>
    {data.campaigns.length===0&&<p className="rounded-2xl border border-dashed border-divider p-5 text-sm text-cream-dim">No campaign plans recorded yet. Create one above; no budget, results or spend will be invented.</p>}
    {data.campaigns.map(campaign=>{const metrics=data.metrics.find(row=>row.campaign_id===campaign.id)!;const expenses=data.spend.filter(row=>row.campaign_id===campaign.id);return <section key={campaign.id} className={panel}><div className="flex flex-wrap justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wide text-sky">{CHANNEL_LABELS[campaign.channel]} · {campaign.status}</p><h2 className="mt-1 text-xl font-semibold">{campaign.name}</h2><p className="mt-1 text-xs text-cream-dim">{campaign.area}</p></div><div className="text-sm"><p className="text-xs text-cream-faint">Planned budget</p><p className="font-semibold">{campaign.budget_cents===null?"Not set":money(campaign.budget_cents)}</p></div></div><p className="mt-3 text-sm leading-6 text-cream-dim">{campaign.offer}</p><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-3">{[["Attributed inquiries",metrics.inquiries],["Consultations recorded",metrics.consultations],["Converted inquiries",metrics.converted],["Recorded spend",money(metrics.recordedSpend)],["Attributed successful payments",money(metrics.successfulPayments)],["Confirmed client mappings",metrics.mappedClients]].map(([label,value])=><div key={label} className="rounded-xl bg-surface-soft p-3"><p className="text-xs text-cream-dim">{label}</p><p className="mt-1 text-xl font-semibold">{value}</p></div>)}</div><p className="mt-3 text-xs leading-5 text-cream-faint">Only explicitly linked inquiries count here. Payment totals read succeeded USD records after the confirmed attribution date; they are not net revenue or profit and do not reconcile fees, taxes or unrepresented partial refunds. Spend is recorded evidence, not a complete provider bill.</p>{(metrics.overBudget||metrics.excludedCurrency>0)&&<p className="mt-3 flex gap-2 rounded-xl bg-status-moderate/10 p-3 text-sm"><AlertTriangle className="h-4 w-4 shrink-0"/>{metrics.overBudget?"Recorded spend exceeds this plan. ":""}{metrics.excludedCurrency>0?`${metrics.excludedCurrency} non-USD payment records need separate reconciliation.`:""}</p>}<details className="mt-4 border-t border-divider"><summary className="min-h-11 cursor-pointer py-3 text-sm font-semibold text-sky">Edit plan</summary><CampaignEditor key={campaign.updated_at} campaign={campaign}/></details><details className="border-t border-divider"><summary className="min-h-11 cursor-pointer py-3 text-sm font-semibold text-sky">Expense evidence · {expenses.length} records</summary>{expenses.map(row=><p key={row.id} className="border-b border-divider py-2 text-xs leading-5 text-cream-dim">{row.incurred_on} · {row.category} · {money(row.amount_cents)} · {row.evidence_reference}{row.voided_at?" · voided":""}</p>)}<SpendForm campaignId={campaign.id} today={today}/></details></section>;})}
    <section id="opportunities" className="scroll-mt-24 space-y-4"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-2xl font-semibold">Opportunity review queue</h2><p className="mt-1 text-sm text-cream-dim">Approve / Hold / Dismiss, with reasons and a dated next action.</p></div><label className="text-xs font-semibold">Show<select className={field} value={queue} onChange={e=>{setQueue(e.target.value);setShown(20);}}>{[["needs_review","Needs review"],["approve","Approved opportunities"],["hold","On hold"],["dismiss","Dismissed"],["due","Follow-up due"],["all","All research"]].map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label></div><p className="text-xs text-cream-faint">Showing {Math.min(shown,candidates.length)} of {candidates.length} matching candidates.</p>{candidates.slice(0,shown).map(({lead})=><OpportunityCard key={`${lead.id}:${lead.updated_at}:${reviewMap.get(lead.id)?.updated_at??"new"}`} lead={lead} review={reviewMap.get(lead.id)} campaigns={data.campaigns} today={today} duplicate={duplicates.has(lead.id)}/>)}{candidates.length===0&&<p className={panel+" text-sm text-cream-dim"}>No candidates in this queue. Import source-backed research in Research Desk; it will not become sales activity automatically.</p>}{shown<candidates.length&&<button className={button} type="button" onClick={()=>setShown(value=>value+20)}>Show more opportunities</button>}</section>
    <section className={panel}><h2 className="text-xl font-semibold">Connect a real inquiry to its source</h2><p className="mt-2 text-sm leading-6 text-cream-dim">After someone actually inquires, record where they came from. Do not promote a research organization or an old contact simply to increase lead counts.</p><label className="mt-4 block text-sm font-medium">Existing inquiry<select className={field} value={leadId} onChange={e=>setLeadId(e.target.value)}><option value="">Choose a real inquiry</option>{data.pipeline.map(row=><option key={row.id} value={row.id}>{row.full_name} · {row.stage.replaceAll("_"," ")}</option>)}</select></label>{chosen&&<AttributionForm key={`${chosen.id}:${chosen.updated_at}:${data.attributions.find(row=>row.lead_id===chosen.id)?.updated_at??"new"}`} lead={chosen} existing={data.attributions.find(row=>row.lead_id===chosen.id)} data={data} today={today}/>}</section>
    <aside className="rounded-2xl border border-sky/20 bg-sky/5 p-5 text-sm leading-6 text-cream-dim"><h2 className="font-semibold text-cream">Paid execution remains separate</h2><p className="mt-2">You can plan budgets and record real research or advertising costs here. Automated paid research and ad activation are not connected in this release. No messages, charges, purchased lists or provider submissions are triggered by these forms.</p></aside>
  </main>;
}
