"use client";
import {useState} from 'react';
import {opportunityState,duplicateCandidateIds,publicSourceUrl,type GrowthLead,type OpportunityReview,type GrowthCampaign} from '@/lib/growth/model';
import {LANE_LABELS,RESEARCH_RULES} from '@/lib/growth/research-engine';
import {useGrowthCommand} from './use-growth-command';
import {Field,fieldClass,primaryClass,secondaryClass} from '@/components/fuel/controls';
export function GrowthFeedback({mutation}:{mutation:ReturnType<typeof useGrowthCommand>}){return <>{mutation.error&&<p role="alert" className="mt-3 rounded-xl border border-status-moderate/40 p-3 text-sm">{mutation.error}</p>}{mutation.uncertain&&<button type="button" className={secondaryClass+' mt-3'} disabled={mutation.busy} onClick={()=>void mutation.retry()}>Retry preserved growth request</button>}{mutation.saved&&<p role="status" className="mt-3 text-sm text-sky">Saved with audit evidence. No external action was taken.</p>}</>;}
export function aiOpportunityDetails(notes:string|null){try{const v=JSON.parse(notes??'null');if(v?.type!=='research_opportunity'||v.rules!==RESEARCH_RULES||v.qualification!=='unverified'||v.outreach_sent!==false||!Number.isInteger(v.score)||v.score<0||v.score>100||!Object.hasOwn(LANE_LABELS,v.lane)||!Array.isArray(v.signals)||!Array.isArray(v.unknowns))return null;return {score:v.score as number,lane:v.lane as keyof typeof LANE_LABELS,location:typeof v.location_label==='string'?v.location_label:'Unverified location',contact:publicSourceUrl(v.contact_url),draft:typeof v.outreach_draft==='string'?v.outreach_draft.slice(0,4000):'',signals:v.signals.filter((s:any)=>typeof s.claim==='string'&&publicSourceUrl(s.url)).slice(0,6) as {kind:string;claim:string;url:string}[],unknowns:v.unknowns.filter((s:unknown):s is string=>typeof s==='string').slice(0,5)};}catch{return null;}}
export function OpportunityCard({lead,review,campaigns,today,duplicate=false}:{lead:GrowthLead;review?:OpportunityReview;campaigns:GrowthCampaign[];today:string;duplicate?:boolean}){
 const state=opportunityState(lead,review,today),ai=aiOpportunityDetails(lead.notes),m=useGrowthCommand();const [decision,setDecision]=useState(review?.decision??'hold'),[campaign,setCampaign]=useState(review?.campaign_id??''),[why,setWhy]=useState(review?.rationale??''),[next,setNext]=useState(review?.next_action??state.evidence?.next_step??''),[due,setDue]=useState(review?.due_on??''),[draft,setDraft]=useState(review?.outreach_draft??ai?.draft??''),[copied,setCopied]=useState('');
 const oldEvidence=Boolean(state.evidence&&(Date.parse(today+'T00:00:00Z')-Date.parse(state.evidence.checked_on+'T00:00:00Z'))/86400000>30);
 return <article id={'opportunity-'+lead.id} className="scroll-mt-24 rounded-2xl border border-divider bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="text-xl font-semibold">{lead.full_name}</h3><p className="mt-1 text-xs capitalize text-cream-dim">{state.decision.replaceAll('_',' ')} · prospect, not an inquiry</p></div>{ai&&<span className="rounded-full bg-sky/5 px-3 py-2 text-sm font-semibold text-sky">{ai.score}/100 evidence fit</span>}</div>
 {(state.stale||state.sourceInvalid||duplicate||oldEvidence)&&<p role="status" className="mt-3 rounded-xl bg-status-moderate/10 p-3 text-sm leading-6">{state.stale?'Source changed since the last review. ':''}{state.sourceInvalid?'The dated source evidence is invalid. ':''}{duplicate?'Possible duplicate organization/domain; compare before outreach. ':''}{oldEvidence?'Evidence is over 30 days old; revisit its source before using it. ':''}No approval or outreach is inferred.</p>}
 {state.evidence&&<div className="mt-4 space-y-3"><p className="text-sm leading-6">{state.evidence.fit_reason}</p><p className="text-xs text-cream-faint">Checked {state.evidence.checked_on}{ai?' · '+LANE_LABELS[ai.lane]+' · '+ai.location:''}. AI interpretation still requires review.</p><div className="flex flex-wrap gap-3"><a href={publicSourceUrl(state.evidence.website_url)!} target="_blank" rel="noreferrer" className="inline-flex min-h-11 items-center text-sm font-semibold text-sky">Official website ↗</a><a href={publicSourceUrl(state.evidence.evidence_url)!} target="_blank" rel="noreferrer" className="inline-flex min-h-11 items-center text-sm font-semibold text-sky">Source evidence ↗</a>{ai?.contact&&<a href={ai.contact} target="_blank" rel="noreferrer" className="inline-flex min-h-11 items-center text-sm font-semibold text-sky">Public organization contact page ↗</a>}</div></div>}
 {ai&&<details className="mt-3"><summary className="min-h-11 cursor-pointer text-sm font-semibold">Why it surfaced · sources &amp; unknowns</summary><div className="space-y-3">{ai.signals.map((s,i)=><div key={i} className="rounded-xl bg-surface-soft p-3"><p className="text-xs font-semibold uppercase text-cream-faint">{s.kind}</p><p className="mt-1 text-sm">{s.claim}</p><a href={publicSourceUrl(s.url)!} target="_blank" rel="noreferrer" className="mt-2 inline-flex min-h-11 max-w-full break-all text-xs text-sky">{s.url} ↗</a></div>)}<p className="text-xs text-cream-dim">Unknown: {ai.unknowns.join(' · ')}. Fit score is not a probability of buying and does not infer any person's income or health.</p></div></details>}
 <details className="mt-4 border-t border-divider" open={state.overdue}><summary className="min-h-12 cursor-pointer py-3 font-semibold text-sky">Review / next action{state.overdue?' · follow-up due '+review?.due_on:''}</summary><form className="space-y-3" onSubmit={e=>{e.preventDefault();void m.run(()=>({action:'review_opportunity',candidate_id:lead.id,campaign_id:campaign||null,expected_source_updated_at:lead.updated_at,expected_updated_at:review?.updated_at??null,decision:decision as OpportunityReview['decision'],rationale:why,next_action:next,due_on:due||null,outreach_draft:draft}));}}><fieldset disabled={m.locked} className="space-y-3"><legend className="sr-only">Opportunity review</legend><div className="grid gap-3 sm:grid-cols-2"><Field label="Decision"><select className={fieldClass} value={decision} onChange={e=>setDecision(e.target.value as OpportunityReview['decision'])}><option value="approve">Approve opportunity — not a lead</option><option value="hold">Hold</option><option value="dismiss">Dismiss / do not pursue</option></select></Field><Field label="Campaign plan · optional"><select className={fieldClass} value={campaign} onChange={e=>setCampaign(e.target.value)}><option value="">Not assigned</option>{campaigns.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="Next action"><input maxLength={500} className={fieldClass} value={next} onChange={e=>setNext(e.target.value)}/></Field><Field label="Follow-up date"><input type="date" className={fieldClass} value={due} onChange={e=>setDue(e.target.value)}/></Field></div><Field label="Owner rationale / source review"><textarea required minLength={10} maxLength={2000} rows={3} className={fieldClass} value={why} onChange={e=>setWhy(e.target.value)}/></Field><Field label="Draft introduction · not sent"><textarea rows={5} maxLength={5000} className={fieldClass} value={draft} onChange={e=>setDraft(e.target.value)}/></Field><p className="text-xs leading-5 text-cream-dim">Approve records a prospecting decision only. The organization remains in research, not the consumer sales pipeline. Public contact details are not marketing consent. Review contact permissions and platform rules before external outreach.</p><button className={primaryClass} disabled={state.sourceInvalid}>Save owner review</button></fieldset><GrowthFeedback mutation={m}/></form></details>
 {review?.outreach_draft&&state.decision==='approve'&&<div className="mt-3"><button className={secondaryClass} type="button" onClick={()=>void navigator.clipboard.writeText(review.outreach_draft).then(()=>setCopied('Approved draft copied. No message was sent or contact recorded.')).catch(()=>setCopied('Clipboard unavailable. Open the saved draft above.'))}>Copy saved, approved draft</button>{copied&&<p role="status" className="mt-2 text-xs text-cream-dim">{copied}</p>}</div>}
 </article>;
}
export function ResearchOpportunities({rows,reviews,campaigns,today}:{rows:GrowthLead[];reviews:OpportunityReview[];campaigns:GrowthCampaign[];today:string}){const [filter,setFilter]=useState('needs_review'),[shown,setShown]=useState(20),[query,setQuery]=useState('');const maps=new Map(reviews.map(r=>[r.candidate_id,r])),duplicates=duplicateCandidateIds(rows);const found=rows.map(lead=>({lead,state:opportunityState(lead,maps.get(lead.id),today),score:aiOpportunityDetails(lead.notes)?.score??0})).filter(x=>x.lead.full_name.toLowerCase().includes(query.toLowerCase())&&(filter==='all'||filter==='due'&&x.state.overdue||filter===x.state.decision)).sort((a,b)=>Number(b.state.overdue)-Number(a.state.overdue)||b.score-a.score||b.lead.updated_at.localeCompare(a.lead.updated_at));return <section id="opportunities" className="scroll-mt-24 space-y-4"><h2 className="text-2xl font-semibold">Opportunity review queue</h2><div className="grid gap-3 sm:grid-cols-2"><Field label="Find an organization"><input className={fieldClass} type="search" value={query} onChange={e=>{setQuery(e.target.value);setShown(20);}}/></Field><Field label="Review status"><select className={fieldClass} value={filter} onChange={e=>{setFilter(e.target.value);setShown(20);}}>{[['needs_review','Needs review'],['approve','Approved opportunities'],['hold','On hold'],['dismiss','Dismissed'],['due','Follow-up due'],['all','All research']].map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></Field></div><p className="text-xs text-cream-faint">Showing {Math.min(shown,found.length)} of {found.length} matches. Source-backed does not mean consented or interested.</p>{found.slice(0,shown).map(({lead})=><OpportunityCard key={lead.id+':'+lead.updated_at+':'+(maps.get(lead.id)?.updated_at??'new')} lead={lead} review={maps.get(lead.id)} campaigns={campaigns} today={today} duplicate={duplicates.has(lead.id)}/>)}{!found.length&&<p className="rounded-xl border border-divider bg-white p-5 text-sm text-cream-dim">No prospects in this view. Run research above or change the filter. Nothing is auto-qualified to fill a quota.</p>}{shown<found.length&&<button className={secondaryClass} onClick={()=>setShown(shown+20)}>Show more opportunities</button>}</section>;}
