import {emptyTargets,shiftDate,type FuelPlan,type Targets} from "./model";
export const NUTRITION_GOALS=["fat_loss","recomposition","maintenance","performance","lean_gain"] as const;
export type NutritionGoal=typeof NUTRITION_GOALS[number];
export type DietStyle="omnivore"|"vegetarian"|"vegan"|"flexible";
export type NutritionInput={clientName:string;start:string;weightLb:number;leanMassLb:number;bodyFatPct:number|null;goal:NutritionGoal;activityFactor:number;trainingDays:number|null;dietStyle:DietStyle;allergies:string;preferences:string;mealsPerDay:3|4|5;clinicalReferral:boolean;sourceReference:string;};
export type NutritionEstimate={rmrKcal:number;tdeeKcal:number;averageKcal:number;proteinG:number;carbsG:number;fatG:number;formula:string;assumptions:string[]};
const round=(n:number,step:number)=>Math.round(n/step)*step;
export function estimateNutrition(input:NutritionInput):NutritionEstimate|null{
 if(input.clinicalReferral)return null;
 if(!Number.isFinite(input.weightLb)||input.weightLb<=0||input.weightLb>999||!Number.isFinite(input.leanMassLb)||input.leanMassLb<=0||input.leanMassLb>input.weightLb||input.activityFactor<1.2||input.activityFactor>2)return null;
 const leanKg=input.leanMassLb/2.2046226218,rmr=370+21.6*leanKg,tdee=rmr*input.activityFactor;
 const factor:Record<NutritionGoal,number>={fat_loss:.85,recomposition:.95,maintenance:1,performance:1,lean_gain:1.05};
 const kcal=round(Math.max(rmr,tdee*factor[input.goal]),50),protein=round(leanKg*2.2,5),fat=round(kcal*.25/9,5),carbs=round(Math.max(0,(kcal-protein*4-fat*9)/4),5);
 return {rmrKcal:round(rmr,10),tdeeKcal:round(tdee,10),averageKcal:kcal,proteinG:protein,carbsG:carbs,fatG:fat,formula:"Katch-McArdle estimate: 370 + 21.6 × confirmed fat-free mass (kg)",assumptions:["Activity multiplier: "+input.activityFactor.toFixed(2),"Goal adjustment: "+Math.round((factor[input.goal]-1)*100)+"% from estimated maintenance","Estimated intake is floored at estimated RMR in this coaching draft.","Protein starts at 2.2 g/kg confirmed fat-free mass; fat starts near 25% of estimated energy; carbohydrate fills the remaining estimate.","These are starting coaching estimates, not measured metabolic rate or medical nutrition therapy."]};
}
function target(e:NutritionEstimate):Targets{return {kcal:e.averageKcal,protein_g:e.proteinG,carbs_g:e.carbsG,fat_g:e.fatG};}
const meals:Record<DietStyle,string[]>={
 omnivore:["Eggs / egg whites + oats + fruit","Lean-protein grain bowl + vegetables","Greek yogurt + fruit or another reviewed training snack","Fish or lean meat + potato/rice + vegetables","Protein-forward snack chosen for the client"],
 vegetarian:["Eggs or Greek yogurt + oats + fruit","Tofu/tempeh or bean grain bowl + vegetables","Greek yogurt/cottage cheese or another reviewed training snack","Egg/tofu/legume plate + potato/rice + vegetables","Protein-forward vegetarian snack chosen for the client"],
 vegan:["Tofu scramble + oats + fruit","Tofu/tempeh or lentil grain bowl + vegetables","Soy yogurt or reviewed plant-protein training snack","Tempeh/tofu/legume plate + potato/rice + vegetables","Plant-protein snack chosen for the client"],
 flexible:["Protein-forward breakfast + high-fiber carbohydrate + fruit","Protein + grain/starch + vegetables","Easy pre-training carbohydrate + tolerated protein","Protein + starch + vegetables","Protein-forward snack chosen for the client"]
};
export function createNutritionDraft(input:NutritionInput):{content:FuelPlan;sourceReference:string;estimate:NutritionEstimate|null}{
 const estimate=estimateNutrition(input),end=shiftDate(input.start,27),review=shiftDate(input.start,14);
 const content:FuelPlan={schema_version:1,title:"Nutrition Strategy · "+input.clientName.slice(0,90),goal:input.goal.replaceAll("_"," "),start:input.start,end,event_date:null,mode:estimate?"targets":"habits",habits:["protein","fuel","water","sleep"],phases:[{name:"Foundation",start:input.start,end,focus:estimate?"Use the coach-reviewed starting targets as an estimate, prioritize repeatable meals, and review actual training, hunger, energy and body-composition evidence before changing them.":"Use a habit-led strategy while clinical nutrition needs are referred or numeric targets remain unassigned.",training:estimate?target(estimate):emptyTargets(),rest:estimate?target(estimate):emptyTargets()}],meals:[],grocery:[],guidance:"",review_on:review};
 const allergy=input.allergies.trim(),base=allergy?Array.from({length:input.mealsPerDay},(_,i)=>"Meal "+(i+1)+": choose allergy-safe foods with a reviewed protein source, produce, and appropriate carbohydrate/fat portions"):meals[input.dietStyle].slice(0,input.mealsPerDay);
 content.meals=base.map((name,i)=>({name,day:i===2&&input.trainingDays?"training":"either",serving:"Coach-reviewed meal framework. Confirm brands, portions, ingredients and substitutions before client release.",ingredients:[],swaps:allergy?"Allergy/restriction review required before selecting foods.":"Use a comparable protein/carbohydrate/fat option that fits the reviewed strategy.",targets:emptyTargets()}));
 content.grocery=allergy?["Allergy-safe protein choices","Produce selected with the client","Carbohydrate staples selected with the client","Cooking fats / flavorings reviewed for restrictions"]:["Primary protein choices","Greek yogurt / dairy or chosen alternative","Rice, oats, potatoes or other preferred starches","Fruit","Vegetables","Cooking fats and flavorings","Convenient training-day food options"];
 content.guidance=[estimate?"Starting estimate: "+estimate.averageKcal+" kcal · "+estimate.proteinG+" g protein · "+estimate.carbsG+" g carbohydrate · "+estimate.fatG+" g fat. Training and rest targets begin the same; adjust only after coach review of actual response.":"Numeric nutrition targets are intentionally unassigned pending appropriate clinical review or additional evidence.",estimate?estimate.formula:"",input.trainingDays===null?"Training frequency not confirmed. Calendar gaps are not rest days.":"Coach-confirmed training context: "+input.trainingDays+" day"+(input.trainingDays===1?"":"s")+" per week.",allergy?"Reported allergies/restrictions: "+allergy+". Food selections require individual review before release.":"No allergy/restriction text was entered in this draft; absence of text is not proof of no allergy.",input.preferences.trim()?"Preferences/context: "+input.preferences.trim():"",estimate?estimate.assumptions.join(" "):"This workflow does not diagnose or treat a medical condition."].filter(Boolean).join("\n\n");
 return {content,sourceReference:"ims_bod_pod_nutrition_v1; "+input.sourceReference+"; goal:"+input.goal+"; activity:"+input.activityFactor,estimate};
}
